import type { FaultEntry } from '../types';

export const poolFaults: FaultEntry[] = [
  {
    id: 'pool-pump-no-prime',
    packId: 'pool',
    category: 'pumps',
    title: 'Pump won’t prime / loses prime',
    aliases: ['no prime', 'losing prime', 'air in pump', 'pump sucking air'],
    symptoms: ['Basket empty after run', 'Air bubbles in lid', 'Weak returns', 'Pump runs dry sound'],
    likelyCauses: [
      'Suction-side air leak (lid o-ring, unions, valves)',
      'Low water level / skim too low',
      'Clogged impeller or skimmer basket',
      'Cracked pump lid or worn lid o-ring',
      'Check valve stuck or missing on suction',
    ],
    steps: [
      'Fill pump basket with water, seat lid firmly with clean lubricated o-ring.',
      'Open suction valves fully; close returns briefly to help pull prime (if safe for equipment).',
      'Watch lid for continuous air bubbles — bubbles = suction leak.',
      'Inspect/replace lid o-ring; check unions and valve stems with soapy water while running.',
      'Clear skimmer/pump baskets and feel impeller for debris.',
      'Verify pool water covers skimmer mouth; adjust water level.',
    ],
    safety: ['Never run pump dry for long — seal damage.', 'Kill power before opening strainer if unsure.'],
    tools: ['Spare lid o-ring', 'Magic lube / silicone lube', 'Flashlight', 'Shop vac (optional)'],
    parts: ['Pump lid o-ring', 'Union gaskets', 'Shaft seal (if leaking at seal plate)'],
    severity: 'medium',
    proTips: ['A wet finger around the lid while running often finds the hiss of an air leak.'],
  },
  {
    id: 'pool-pump-hum-no-spin',
    packId: 'pool',
    category: 'pumps',
    title: 'Pump hums but impeller doesn’t spin',
    aliases: ['humming pump', 'locked rotor', 'capacitor', 'won’t start'],
    symptoms: ['Hum then thermal trip', 'No water movement', 'Hot motor end bell'],
    likelyCauses: [
      'Failed start/run capacitor (single-speed)',
      'Seized shaft / bad bearings',
      'Debris locked impeller',
      'Failed VS drive / programming',
      'Low voltage at motor',
    ],
    steps: [
      'Kill power at breaker. Try hand-spin impeller through basket (power OFF).',
      'If locked, remove debris; if seized, plan motor/seal service.',
      'Single-speed: test/replace start capacitor with correct µF rating.',
      'Measure voltage under load at motor terminals.',
      'VS pumps: check drive error codes and bonding/ground.',
    ],
    safety: ['Capacitors can hold charge — discharge safely.', 'LOTO before opening motor wiring.'],
    tools: ['Multimeter', 'Capacitor tester', 'Insulated screwdriver'],
    parts: ['Start capacitor', 'Shaft seal kit', 'Motor or wet end'],
    severity: 'high',
    proTips: ['If it free-spins by hand and still only hums, capacitor or start circuit is prime suspect.'],
  },
  {
    id: 'pool-vs-error',
    packId: 'pool',
    category: 'pumps',
    title: 'Variable-speed pump error / fault code',
    aliases: ['intelliflo', 'tristar vs', 'vs drive fault', 'pump error code'],
    symptoms: ['Drive display fault', 'Pump won’t run scheduled speeds', 'Repeated resets'],
    likelyCauses: ['Overheat', 'Undervoltage', 'Drive failure', 'Bad priming detection', 'Communication loss with automation'],
    steps: [
      'Photograph the exact code on the drive.',
      'Power-cycle at breaker 60 seconds; note if code returns immediately.',
      'Verify supply voltage and tight lugs at disconnect.',
      'Clear debris from fan/heat sink; ensure shade/ventilation.',
      'Reseat automation comms cable; check address/settings.',
      'If persistent drive faults, replace drive per brand procedure.',
    ],
    safety: ['Wait for drive capacitors to discharge before service.'],
    tools: ['Phone for code photo', 'Multimeter', 'Brand service manual'],
    parts: ['VS drive', 'Comm cable', 'Thrust bearing kit (brand-specific)'],
    severity: 'high',
    proTips: ['Always match the code to brand chart — same number means different things across brands.'],
  },
  {
    id: 'pool-filter-high-pressure',
    packId: 'pool',
    category: 'filters',
    title: 'Filter pressure high / weak flow',
    aliases: ['high psi', 'needs backwash', 'dirty filter', 'low returns'],
    symptoms: ['Gauge 8–10+ psi over clean', 'Weak jets', 'Pump louder'],
    likelyCauses: ['Dirty media/cartridge', 'Partially closed valve', 'Channeling DE', 'Obstructed returns', 'Wrong gauge'],
    steps: [
      'Note clean vs dirty baseline for this system.',
      'Backwash sand/DE or clean/replace cartridges.',
      'Verify multiport on FILTER (not recirculate/waste accidentally).',
      'Check return valves and cleaner lines for restrictions.',
      'Replace cracked/stuck pressure gauge if reading nonsense.',
    ],
    safety: ['Relieve pressure before opening filter clamp/band.'],
    tools: ['Filter cleaner', 'Pressure gauge', 'DE scoop / cartridge stand'],
    parts: ['Cartridges', 'DE grids/manifolds', 'Multiport spider gasket'],
    severity: 'medium',
    proTips: ['Write clean PSI on the tank with a paint pen — techs love you later.'],
  },
  {
    id: 'pool-multiport-leak',
    packId: 'pool',
    category: 'filters',
    title: 'Multiport leaking from waste or handle',
    aliases: ['spider gasket', 'waste leaking', 'multiport leak'],
    symptoms: ['Water from waste port on FILTER', 'Sand in pool after backwash', 'Hard handle'],
    likelyCauses: ['Worn spider gasket', 'Misaligned key', 'Cracked valve body', 'Bad washers'],
    steps: [
      'Kill pump. Inspect key and spider gasket for flat spots/tears.',
      'Replace spider gasket; lubricate lightly with silicone lube only.',
      'Ensure handle seats fully in each position before starting pump.',
      'If body cracked, replace multiport assembly.',
    ],
    safety: ['Never force handle with pump running.'],
    tools: ['Silicone lube', 'Gasket pick'],
    parts: ['Spider gasket', 'Multiport key', 'Complete multiport'],
    severity: 'medium',
    proTips: ['Sand returning to pool after backwash almost always points to gasket or laterals.'],
  },
  {
    id: 'pool-salt-low-false',
    packId: 'pool',
    category: 'salt',
    title: 'Low salt alarm but chemistry looks fine',
    aliases: ['low salt', 'check salt', 'salt cell dirty', 'false low salt'],
    symptoms: ['Low salt LED', 'No Cl generation', 'Cell scaled'],
    likelyCauses: ['Scaled cell', 'Cold water', 'Failing cell', 'Bad flow switch', 'Actual low salt'],
    steps: [
      'Test salt with reliable meter (not just display).',
      'Inspect cell plates for white scale; acid-wash per manufacturer.',
      'Verify flow switch / filter pressure adequate.',
      'Check water temp — many cells reduce output when cold.',
      'If salt is correct and cell clean, test cell amp draw; replace if weak.',
    ],
    safety: ['Use diluted muriatic carefully; never mix with other chemicals.', 'Power off cell before removing.'],
    tools: ['Salt meter', 'Cell cleaning kit', 'PPE'],
    parts: ['Salt cell', 'Flow switch', 'Control board'],
    severity: 'medium',
    proTips: ['A dirty cell lies. Clean before you condemn.'],
  },
  {
    id: 'pool-no-chlorine',
    packId: 'pool',
    category: 'salt',
    title: 'Salt system running but no chlorine residual',
    aliases: ['no chlorine', 'fc zero', 'swg no output'],
    symptoms: ['FC = 0', 'Algae starting', 'Cell status OK'],
    likelyCauses: ['Output % too low', 'High stabilizer (CYA)', 'Phosphates/algae demand', 'Failing cell', 'Short runtime'],
    steps: [
      'Test FC, CC, pH, TA, CYA, salt.',
      'Shock to breakpoint; brush; run pump longer.',
      'Raise SWG output % and confirm cell generating (bubbles/amps).',
      'If CYA very high, partial drain/dilute.',
      'Replace cell if amp draw far below spec.',
    ],
    safety: ['Never mix shock types casually; follow label.', 'Ventilate when acid washing.'],
    tools: ['Test kit (Taylor preferred)', 'Brush', 'Shock'],
    parts: ['Salt cell', 'Cyanuric acid (only if low)'],
    severity: 'high',
    proTips: ['High CYA is the silent killer of SWG performance.'],
  },
  {
    id: 'pool-heater-ignition',
    packId: 'pool',
    category: 'heaters',
    title: 'Heater ignites then shuts down',
    aliases: ['heater lockout', 'ignition failure', 'heater tries then dies'],
    symptoms: ['Trial for ignition', 'Fault after flame', 'Cold outlet'],
    likelyCauses: ['Dirty flame sensor', 'Gas pressure', 'Airflow/vent', 'Bypass/flow', 'Board/igniter'],
    steps: [
      'Record fault code from heater display.',
      'Verify adequate flow and clean filter; check bypass valve.',
      'Clean flame sensor; inspect igniter.',
      'Confirm gas supply and vent clearances.',
      'Check intake/exhaust for nests or water.',
    ],
    safety: ['Gas work — if unsure, stop and call qualified tech.', 'Carbon monoxide hazard with bad venting.'],
    tools: ['Manometer', 'Emery cloth', 'Combustion analyzer (pro)'],
    parts: ['Flame sensor', 'Hot surface igniter', 'Pressure switch', 'Control board'],
    severity: 'high',
    proTips: ['Many “bad boards” are dirty sensors and flow issues.'],
  },
  {
    id: 'pool-automation-relay',
    packId: 'pool',
    category: 'automation',
    title: 'Automation relay stuck / wrong mode',
    aliases: ['stuck on spa', 'relay welded', 'intellicenter', 'iaqualink'],
    symptoms: ['Spa mode won’t clear', 'Aux always on', 'Schedules ignored'],
    likelyCauses: ['Welded relay', 'Bad UI board', 'Config mismatch', 'App/cloud desync', 'Low voltage transformer'],
    steps: [
      'Note which circuit is wrong in the UI vs actual voltage at load.',
      'Manually toggle relay; listen/feel for actuation.',
      'Power-cycle load center; reseat ribbon cables.',
      'Check 24VAC transformer output under load.',
      'Replace relay pack or board if stuck closed.',
    ],
    safety: ['High voltage in load center — LOTO.', 'Label circuits before pulling relays.'],
    tools: ['Multimeter', 'Label maker', 'Board puller'],
    parts: ['Relay', 'Transformer', 'Personality board'],
    severity: 'high',
    proTips: ['Verify with a meter at the lug — UI lies when relays weld.'],
  },
  {
    id: 'pool-cloudy-water',
    packId: 'pool',
    category: 'chemistry',
    title: 'Cloudy water',
    aliases: ['cloudy', 'milky', 'dull water'],
    symptoms: ['Poor clarity', 'Filter working overtime'],
    likelyCauses: ['Low FC', 'High pH', 'Poor filtration', 'Dead algae', 'Calcium haze'],
    steps: [
      'Test full panel: FC/CC/pH/TA/CH/CYA.',
      'Balance pH 7.2–7.6; raise FC appropriately for CYA.',
      'Run filter 24 hrs; clean if pressure high.',
      'Clarifier or floc as appropriate; vacuum to waste if floccing.',
    ],
    safety: ['PPE with chemicals; add chem to water, not water to chem.'],
    tools: ['Test kit', 'Clarifier', 'Brush'],
    parts: ['Filter media', 'Pump basket o-ring if priming issues contribute'],
    severity: 'medium',
    proTips: ['If you can’t see the main drain, treat filtration + sanitizer first.'],
  },
  {
    id: 'pool-green-algae',
    packId: 'pool',
    category: 'chemistry',
    title: 'Green algae bloom',
    aliases: ['green pool', 'algae', 'mustard algae'],
    symptoms: ['Green tint', 'Slippery walls', 'FC disappears'],
    likelyCauses: ['Sanitizer failure', 'Poor circulation', 'Phosphates', 'Dead spots'],
    steps: [
      'Brush thoroughly; clean filter; balance pH.',
      'Shock to SLAM / breakpoint for CYA level.',
      'Keep FC elevated until water clears and overnight FC loss is normal.',
      'Backwash/clean often during treatment.',
    ],
    safety: ['Don’t mix algaecides carelessly with shock.', 'Avoid swimming until FC safe.'],
    tools: ['Brush', 'Shock', 'Test kit'],
    parts: ['Salt cell if SWG failed', 'Filter cartridges'],
    severity: 'high',
    proTips: ['Brushing is not optional — chemicals can’t reach what you don’t knock loose.'],
  },
  {
    id: 'pool-leak-suspected',
    packId: 'pool',
    category: 'structure',
    title: 'Suspected leak / water loss',
    aliases: ['losing water', 'leak', 'bucket test'],
    symptoms: ['Water drops daily', 'Wet spots', 'High bill'],
    likelyCauses: ['Evaporation', 'Plumbing leak', 'Fitting crack', 'Light niche', 'Suction leak'],
    steps: [
      'Do bucket test (pool vs bucket) over 24–48 hrs.',
      'Dye test returns/suction fittings and lights.',
      'Isolate spa vs pool with valves if applicable.',
      'Pressure/vacuum test lines as equipped.',
    ],
    safety: ['Electrical bonding around wet equipment pads.'],
    tools: ['Bucket', 'Dye bottle', 'Pressure test kit'],
    parts: ['Unions', 'Gaskets', 'Pipe repair couplings'],
    severity: 'medium',
    proTips: ['Windy hot days fake leaks — always bucket test before digging.'],
  },
  {
    id: 'pool-heater-no-heat',
    packId: 'pool',
    category: 'heaters',
    title: 'Heater runs but water stays cold',
    aliases: ['no heat', 'heater not heating', 'cold water heater'],
    symptoms: ['Burner/compressor on', 'Outlet not warming', 'Short cycles'],
    likelyCauses: ['Bypass open too far', 'Low flow', 'Scaled exchanger', 'Wrong thermostat/remote settings', 'Heat pump low ambient'],
    steps: [
      'Confirm call for heat from automation and local setpoint.',
      'Measure inlet vs outlet delta-T after 5+ minutes.',
      'Verify filter clean and pump speed adequate for heater.',
      'Check bypass valve position.',
      'Inspect for scale / schedule acid flush if appropriate.',
    ],
    safety: ['Gas/electrical hazards — LOTO as needed.'],
    tools: ['Thermometer', 'Manometer'],
    parts: ['Bypass valve', 'Thermistor', 'Heat exchanger'],
    severity: 'medium',
    proTips: ['No delta-T with flame/compressor on usually means bypass or no flow through exchanger.'],
  },
  {
    id: 'pool-valve-actuator',
    packId: 'pool',
    category: 'automation',
    title: 'Valve actuator not rotating / wrong port',
    aliases: ['actuator', 'diverter valve', 'valve stuck'],
    symptoms: ['Spa/pool mode wrong', 'Actuator hums', 'Cam not switching'],
    likelyCauses: ['Failed actuator motor', 'Bad 24VAC', 'Cam switches mis-set', 'Seized diverter'],
    steps: [
      'Listen for hum; check 24VAC at actuator.',
      'Toggle spa/pool at automation and watch cam.',
      'Manually override valve; feel for mechanical bind.',
      'Replace actuator or rebuild diverter as needed.',
    ],
    safety: ['Power off before disconnecting actuator leads.'],
    tools: ['Multimeter', 'Allen keys'],
    parts: ['Valve actuator', 'Diverter valve'],
    severity: 'medium',
    proTips: ['Mark valve body ports with paint pen before you pull the actuator.'],
  },
  {
    id: 'pool-suction-leak-whine',
    packId: 'pool',
    category: 'pumps',
    title: 'Cavitation / suction-side restriction whine',
    aliases: ['cavitation', 'pump screaming', 'starved pump'],
    symptoms: ['High-pitched whine', 'Rattling', 'Weak flow with low filter pressure'],
    likelyCauses: ['Closed suction valve', 'Clogged skimmer', 'Collapsed flex', 'Main drain blocked'],
    steps: [
      'Compare filter pressure — low pressure + noise = suction side.',
      'Open all suction valves; clear baskets.',
      'Check for collapsed above-ground flex or clogged leaf canister.',
      'Inspect main drain cover legality/obstruction.',
    ],
    safety: ['Entrapment hazard — never run with missing drain covers.'],
    tools: ['Flashlight', 'Shop vac'],
    parts: ['Skimmer basket', 'Drain cover (compliant)'],
    severity: 'high',
    proTips: ['Low filter PSI + loud pump is suction. High PSI + weak returns is filter/returns.'],
  },
];

