import type { FaultEntry } from '../types';

export const hvacFaults: FaultEntry[] = [
  {
    id: 'hvac-ac-warm-air',
    packId: 'hvac',
    category: 'cooling',
    title: 'AC running but supply air is warm',
    aliases: ['ac warm', 'not cooling', 'blower runs no cold air', 'outside unit on but warm'],
    symptoms: ['Thermostat calling for cool but room temp climbs', 'Supply air only 2-8F below return', 'Outdoor unit may run continuously'],
    likelyCauses: ['Low refrigerant charge', 'Outdoor condenser coil plugged', 'Indoor airflow too low', 'Compressor not pumping properly', 'Reversing valve stuck mid-position'],
    steps: [
      'Confirm thermostat mode COOL and setpoint at least 3F below room temperature.',
      'Measure return vs supply dry-bulb at air handler; target roughly 16-22F split on a healthy system.',
      'Check condenser coil and fan operation; wash coil if matted and verify fan is pulling full airflow.',
      'Attach gauges and temperature clamps; compare suction, head, superheat, and subcooling to equipment chart.',
      'If charge/airflow checks out but split stays low, verify compressor amp draw against nameplate and evaluate valve/compressor efficiency.',
    ],
    safety: ['Use lockout/tagout before opening electrical compartments.', 'Keep hands/tools clear of condenser fan and high-voltage lugs.'],
    tools: ['Digital manifold gauges', 'Clamp meter', 'Dual temperature probes', 'Coil cleaning sprayer'],
    parts: ['Run capacitor', 'Contactor', 'Condenser fan motor', 'Refrigerant (after leak check)'],
    severity: 'high',
    proTips: ['Start with airflow and clean coils before touching charge. Bad airflow can mimic low refrigerant every time.'],
  },
  {
    id: 'hvac-frozen-evaporator-coil',
    packId: 'hvac',
    category: 'airflow',
    title: 'Evaporator coil frozen / suction line icing',
    aliases: ['frozen coil', 'ice on lines', 'a-coil iced up', 'airflow freeze'],
    symptoms: ['Ice on suction line or indoor coil panel', 'Weak airflow at registers', 'Water around furnace after thaw'],
    likelyCauses: ['Dirty filter or plugged blower wheel', 'Low blower speed', 'Low refrigerant from leak', 'Restricted metering device', 'Return duct restrictions'],
    steps: [
      'Turn cooling OFF and run FAN-ON to thaw completely before diagnostics.',
      'Replace/filter check and inspect blower wheel, evaporator face, and return grilles for blockage.',
      'Measure external static pressure and compare to blower chart for actual CFM.',
      'After thaw, run cooling and verify superheat/subcooling to rule in charge or metering restrictions.',
      'If icing repeats with good airflow and proper charge, inspect TXV bulb mounting and liquid line restrictions.',
    ],
    safety: ['Do not chip ice with tools; coil damage is expensive.', 'Watch for water spill near electrical components during thaw.'],
    tools: ['Manometer', 'Digital manifold gauges', 'Temperature probes', 'Inspection mirror/light'],
    parts: ['Air filter', 'Blower motor capacitor', 'TXV', 'Evaporator coil (if oil-stained leak found)'],
    severity: 'high',
    proTips: ['Always thaw first. Gauges on an iced coil will send you in the wrong direction.'],
  },
  {
    id: 'hvac-high-head-pressure',
    packId: 'hvac',
    category: 'refrigeration',
    title: 'High head pressure trip / elevated discharge pressure',
    aliases: ['high head', 'head pressure lockout', 'discharge pressure high', 'hp switch open'],
    symptoms: ['Outdoor unit short trips on pressure safety', 'Compressor amp draw elevated', 'Hot discharge line and noisy condenser'],
    likelyCauses: ['Dirty condenser coil', 'Condenser fan weak or rotating wrong direction', 'Overcharge or non-condensables', 'Restricted airflow around unit', 'Liquid line restriction'],
    steps: [
      'Confirm condenser fan operation, rotation direction, and full speed under load.',
      'Clean coil thoroughly and verify at least 18-24 inches of clearance around condenser.',
      'Read head pressure and compare condensing temperature to outdoor ambient (split too high points to heat rejection issue).',
      'Check subcooling vs manufacturer target; high subcooling with high head suggests overcharge/restriction.',
      'If pressures remain abnormal after airflow correction, recover/evacuate/recharge by weighed charge and verify system performance.',
    ],
    safety: ['High pressure refrigerant can cause severe injury; use rated hoses and eye protection.', 'Do not bypass high-pressure safeties to keep unit running.'],
    tools: ['Digital manifold set', 'Temperature clamps', 'Anemometer', 'Fin comb'],
    parts: ['Condenser fan motor', 'Fan capacitor', 'Pressure switch', 'Filter-drier'],
    severity: 'high',
    proTips: ['Head pressure diagnosis starts at the condenser coil and fan, not the refrigerant jug.'],
  },
  {
    id: 'hvac-low-suction-undercharge-signs',
    packId: 'hvac',
    category: 'refrigeration',
    title: 'Low suction pressure / undercharge indicators',
    aliases: ['low suction', 'undercharged', 'starved evap', 'low refrigerant symptoms'],
    symptoms: ['Low suction with high superheat', 'Poor cooling and long run times', 'Suction line barely cool or sweating only at coil'],
    likelyCauses: ['Refrigerant leak', 'Metering device restriction', 'Liquid line drier restriction', 'Low indoor load/airflow skewing readings', 'Incorrect prior charge'],
    steps: [
      'Verify airflow first (filter, blower speed, static pressure) so gauge readings are meaningful.',
      'Measure superheat and subcooling; undercharge typically shows high superheat and low subcooling.',
      'Inspect for oil residue at braze joints, coil bends, Schrader cores, and service valves.',
      'Leak check with electronic detector and confirm with bubble solution at suspect points.',
      'Repair leak, pressure test, evacuate below 500 microns, then weigh in charge and fine-tune per chart.',
    ],
    safety: ['Never top off repeatedly without finding and repairing leaks.', 'Use nitrogen regulator for pressure tests; do not use oxygen.'],
    tools: ['Electronic leak detector', 'Nitrogen regulator', 'Micron gauge', 'Refrigerant scale'],
    parts: ['Schrader cores', 'Filter-drier', 'Evaporator coil', 'Service valve caps with seals'],
    severity: 'high',
    proTips: ['If superheat is high and subcool is low, leak search before charge adjustment.'],
  },
  {
    id: 'hvac-condensate-overflow',
    packId: 'hvac',
    category: 'cooling',
    title: 'Condensate overflow / drain pan filling',
    aliases: ['ac leaking water', 'float switch trip', 'drain clogged', 'secondary pan full'],
    symptoms: ['Water around furnace or ceiling stain below attic unit', 'System shuts off on float switch', 'Drain line gurgling or no discharge'],
    likelyCauses: ['Clogged primary drain line', 'No trap or wrong trap on negative pressure coil', 'Algae/slime buildup', 'Cracked drain pan', 'Improper unit pitch'],
    steps: [
      'Shut equipment down and verify float switch operation to prevent property damage.',
      'Clear drain line from cleanout using wet vac and flush with water until free flow is confirmed.',
      'Verify proper trap configuration and slope from coil to termination.',
      'Pour water into pan to prove drainage and check for pan cracks/leaks at fittings.',
      'Add pan treatment and document regular maintenance interval.',
    ],
    safety: ['Water near line voltage is shock risk; de-energize before service.', 'Use caution in attic spaces around insulation and ceiling drywall.'],
    tools: ['Wet/dry vacuum', 'CO2 drain gun', 'PVC hand tools', 'Flashlight'],
    parts: ['Float switch', 'PVC trap fittings', 'Drain pan treatment tabs', 'Auxiliary pan'],
    severity: 'medium',
    proTips: ['Always water-test the drain before leaving, not just a quick vacuum pull.'],
  },
  {
    id: 'hvac-furnace-no-heat',
    packId: 'hvac',
    category: 'heating',
    title: 'Gas furnace no heat call',
    aliases: ['furnace not heating', 'no ignition sequence', 'burners never light', 'heat call no fire'],
    symptoms: ['Thermostat calling but burners stay off', 'Inducer may run then stop', 'Lockout code flashing'],
    likelyCauses: ['No 24V call at W', 'Open pressure switch circuit', 'Ignition failure', 'Gas valve not opening', 'Limit switch open from airflow issue'],
    steps: [
      'Read and record board fault code before cycling power.',
      'Verify 24VAC from R to W at board during call for heat.',
      'Check inducer operation and pressure switch proving with manometer/continuity.',
      'Confirm ignitor operation and gas valve voltage during ignition trial.',
      'Inspect filter, blower, and high-limit circuit if furnace briefly fires then drops out.',
    ],
    safety: ['Gas and combustion work requires proper venting checks and CO awareness.', 'Do not jumper safeties except brief diagnostic checks per manufacturer procedure.'],
    tools: ['Multimeter', 'Manometer', 'Combustion analyzer', 'Inspection mirror'],
    parts: ['Pressure switch', 'Control board fuse', 'Gas valve', 'Limit switch'],
    severity: 'critical',
    proTips: ['Fault code first, power cycle second. You lose the best clue when you reset too early.'],
  },
  {
    id: 'hvac-ignitor-failure',
    packId: 'hvac',
    category: 'heating',
    title: 'Hot surface ignitor failed',
    aliases: ['bad ignitor', 'glow plug cracked', 'furnace click no light', 'hsi open'],
    symptoms: ['Inducer runs but no glow at ignitor', 'Ignition retries then lockout', 'Ignitor reads open ohms'],
    likelyCauses: ['Cracked/weak hot surface ignitor', 'No voltage from board during trial', 'Dirty burner ground path', 'Improper replacement part rating'],
    steps: [
      'Inspect ignitor for hairline crack and test resistance against manufacturer range.',
      'During ignition trial, verify line voltage to ignitor connector (or specified output type).',
      'If voltage present and ignitor open/weak, replace with exact OEM equivalent.',
      'Clean burner crossovers and verify good cabinet ground to board.',
      'Run at least three complete heat cycles to confirm reliable light-off.',
    ],
    safety: ['Ignitors are fragile and oils from bare fingers shorten life; handle by ceramic base.', 'Kill power before unplugging ignitor harness.'],
    tools: ['Multimeter', 'Nut driver', 'Soft brush'],
    parts: ['Hot surface ignitor', 'Burner screws', 'Ignitor harness plug'],
    severity: 'high',
    proTips: ['Carry universal brackets, but match ignitor style and amp draw to avoid repeat failures.'],
  },
  {
    id: 'hvac-flame-sensor-fault',
    packId: 'hvac',
    category: 'heating',
    title: 'Flame sensor proving failure',
    aliases: ['flame sensor dirty', 'lights then shuts off', 'flame rectification fault', 'burner dropout'],
    symptoms: ['Burners ignite for 1-3 seconds then drop out', 'Multiple retries then lockout', 'Intermittent heat complaints'],
    likelyCauses: ['Oxidized flame sensor rod', 'Poor furnace grounding', 'Low flame carryover', 'Cracked sensor porcelain', 'Weak board flame signal circuit'],
    steps: [
      'Clean flame sensor rod with fine abrasive pad and reinstall firmly.',
      'Measure flame signal in microamps in series; compare to board minimum spec.',
      'Check burner flame carryover and crossover ports for rust/debris.',
      'Verify equipment ground continuity from burner rack to control board neutral.',
      'Replace sensor or board if microamp signal remains below spec after cleaning/ground corrections.',
    ],
    safety: ['Shut off gas and power before pulling burner/sensor assembly.', 'Never sand sensor aggressively; remove oxidation only.'],
    tools: ['Meter with microamp capability', 'Abrasive pad', 'Nut driver'],
    parts: ['Flame sensor', 'Ground strap', 'Control board'],
    severity: 'high',
    proTips: ['A clean sensor that still reads low microamps usually points to grounding or flame quality, not the rod itself.'],
  },
  {
    id: 'hvac-heat-pump-wont-heat',
    packId: 'hvac',
    category: 'heating',
    title: 'Heat pump runs but will not heat',
    aliases: ['heat pump cold air', 'no heat in heat mode', 'reversing valve issue', 'outdoor unit runs no warmth'],
    symptoms: ['Supply air barely warm or cool in HEAT mode', 'Outdoor unit runs continuously', 'Aux heat may eventually pick up load'],
    likelyCauses: ['Reversing valve not shifting', 'Low refrigerant charge', 'Defrost control fault', 'Outdoor coil icing', 'Incorrect thermostat setup for heat pump'],
    steps: [
      'Confirm thermostat equipment type and O/B setting match unit manufacturer.',
      'Measure return/supply delta-T in heat mode; typically expect a clear rise above room temperature.',
      'Verify reversing valve coil energization and listen/feel for valve shift when mode changes.',
      'Check refrigerant pressures/temperatures for low charge or restriction indicators.',
      'Force and verify defrost operation if outdoor coil is iced over and heating output is poor.',
    ],
    safety: ['Keep clear of moving fan blades and energized defrost components.', 'Use insulated probes when measuring control voltage outdoors.'],
    tools: ['Digital gauges', 'Thermometer probes', 'Multimeter', 'Service manual'],
    parts: ['Reversing valve solenoid', 'Defrost board', 'Outdoor sensor', 'Refrigerant after leak repair'],
    severity: 'high',
    proTips: ['Wrong O/B setup can make a perfect system blow cold in heat mode. Verify setup before teardown.'],
  },
  {
    id: 'hvac-aux-heat-stuck-on',
    packId: 'hvac',
    category: 'controls',
    title: 'Aux/emergency heat stuck on',
    aliases: ['heat strips always on', 'aux heat lock-in', 'high electric bill heat pump', 'w2 stuck'],
    symptoms: ['High amp draw continuously', 'Very hot supply air even mild weather', 'Thermostat showing AUX most of the time'],
    likelyCauses: ['Thermostat staging misconfiguration', 'Stuck heat-strip relay/contactor', 'Shorted W2 circuit', 'Defrost board keeping strips energized', 'Outdoor temperature sensor fault'],
    steps: [
      'Check thermostat call outputs at air handler: confirm whether W2 is being commanded continuously.',
      'If no W2 call but strips energized, test strip relay/contactor for welded contacts.',
      'Inspect low-voltage wiring for shorts between R and W2.',
      'Verify defrost board logic and sensor readings if strips only stick after defrost events.',
      'Correct staging setup and lockout temperatures based on manufacturer guidance.',
    ],
    safety: ['Heat strips are high amperage; de-energize all breakers before opening strip section.', 'Use meter to verify both low and high voltage are dead.'],
    tools: ['Clamp meter', 'Multimeter', 'Wiring diagram', 'Thermostat installer menu access'],
    parts: ['Heat strip sequencer/relay', 'Defrost board', 'Outdoor sensor', 'Thermostat'],
    severity: 'high',
    proTips: ['Confirm thermostat logic before replacing relays. Bad setup can look exactly like a welded sequencer.'],
  },
  {
    id: 'hvac-blower-wont-run',
    packId: 'hvac',
    category: 'airflow',
    title: 'Indoor blower will not run',
    aliases: ['no indoor fan', 'blower dead', 'fan on no airflow', 'air handler silent'],
    symptoms: ['Outdoor unit may run but no indoor airflow', 'No airflow in FAN-ON mode', 'High limit or freeze trips follow'],
    likelyCauses: ['Failed blower capacitor', 'Open blower motor winding', 'No 24V G signal', 'Board relay failure', 'Door switch or breaker open'],
    steps: [
      'Force FAN-ON at thermostat and check for 24VAC from G to C at board.',
      'Verify line voltage into air handler and that door interlock switch is closed.',
      'Test blower capacitor against rated microfarads and replace if out of tolerance.',
      'Measure motor amp draw and winding continuity; compare against nameplate.',
      'If motor and capacitor are good, verify board fan relay output to motor speed tap/ECM command.',
    ],
    safety: ['Disconnect power before spinning/testing blower wheel.', 'Capacitors hold charge; discharge safely before handling.'],
    tools: ['Multimeter', 'Capacitance meter', 'Clamp meter', 'Insulated jumper leads'],
    parts: ['Blower capacitor', 'Blower motor', 'Fan relay/control board', 'Door switch'],
    severity: 'high',
    proTips: ['Always test in FAN-ON first. It isolates fan controls from heating/cooling call logic.'],
  },
  {
    id: 'hvac-dirty-filter-high-delta-t',
    packId: 'hvac',
    category: 'airflow',
    title: 'Dirty filter causing high temperature split',
    aliases: ['dirty filter', 'high delta t', 'airflow restricted', 'hot supply low airflow'],
    symptoms: ['Filter heavily loaded', 'Cooling split excessively high with weak airflow', 'Furnace high-limit trips in heat mode'],
    likelyCauses: ['Neglected filter replacement', 'Filter too restrictive for system static', 'Undersized return duct', 'Closed supply/return grilles'],
    steps: [
      'Measure return/supply temperatures and total external static pressure before replacing filter.',
      'Replace with correct size and approved MERV rating; avoid over-restrictive media unless ductwork supports it.',
      'Recheck static pressure and temperature split after 10-15 minutes of run time.',
      'Inspect all return paths and supply registers to confirm they are open and unobstructed.',
      'If static remains above blower rating, document duct modifications needed.',
    ],
    safety: ['Power down before accessing blower compartment near moving parts.', 'Use respiratory protection if filter is moldy or heavily contaminated.'],
    tools: ['Manometer', 'Thermometer probes', 'Static pressure tips', 'Replacement filter'],
    parts: ['Air filter', 'Filter rack door', 'Return grille'],
    severity: 'medium',
    proTips: ['Record clean-filter static on the service sticker. It makes future callbacks faster to solve.'],
  },
  {
    id: 'hvac-thermostat-blank',
    packId: 'hvac',
    category: 'controls',
    title: 'Thermostat display blank / no power',
    aliases: ['dead thermostat', 'blank stat', 'no 24v at thermostat', 'thermostat offline'],
    symptoms: ['Screen dark or rebooting', 'No system response to calls', 'Wi-Fi thermostat disconnected'],
    likelyCauses: ['Tripped furnace/air handler breaker', 'Blown low-voltage board fuse', 'Failed 24V transformer', 'Float switch open on condensate backup', 'Broken R or C conductor'],
    steps: [
      'Verify equipment power at breaker/service switch and blower door interlock.',
      'Measure 24VAC at control board R to C, then at thermostat R to C.',
      'If board has 24V but stat does not, isolate/open-check low-voltage conductors.',
      'Check and replace board fuse only after locating cause of short.',
      'If no 24V at board, test transformer primary/secondary and replace as needed.',
    ],
    safety: ['Even low-voltage troubleshooting is near line voltage in equipment cabinet; isolate power when moving wires.', 'Replace blown fuse with exact rating only.'],
    tools: ['Multimeter', 'Spare 3A/5A blade fuses', 'Screwdriver set'],
    parts: ['24V transformer', 'Low-voltage fuse', 'Thermostat', 'Wire nuts/splices'],
    severity: 'medium',
    proTips: ['Float switch in series with R can blank the stat and save the ceiling. Check condensate before replacing electronics.'],
  },
  {
    id: 'hvac-zoning-damper-fault',
    packId: 'hvac',
    category: 'controls',
    title: 'Zoning damper not opening/closing correctly',
    aliases: ['zone not cooling', 'damper stuck', 'zone control board fault', 'one room no airflow'],
    symptoms: ['One zone never reaches setpoint', 'Bypass noise or high static', 'Damper actuator not moving on command'],
    likelyCauses: ['Failed damper motor/actuator', 'No 24V output from zone board', 'Damper blade mechanically bound', 'Miswired thermostat to zone panel', 'Failed end switch feedback'],
    steps: [
      'Command each zone individually and verify board outputs and damper movement.',
      'Measure 24VAC at damper motor during open/close call.',
      'Manually move damper shaft (if serviceable) to check for mechanical binding.',
      'Confirm thermostat-to-zone panel wiring and addressing are correct.',
      'Set bypass and blower speed to maintain acceptable static pressure when fewer zones call.',
    ],
    safety: ['Power down air handler before reaching into damper sections.', 'Secure ladders and attic footing when accessing branch dampers.'],
    tools: ['Multimeter', 'Manometer', 'Small hand tools', 'Wiring diagram'],
    parts: ['Zone damper actuator', 'Zone control board', 'Damper blade assembly', 'Thermostat wire'],
    severity: 'medium',
    proTips: ['A stuck closed damper can look like a refrigerant issue from the room side. Confirm airflow path early.'],
  },
  {
    id: 'hvac-refrigerant-leak-signs',
    packId: 'hvac',
    category: 'refrigeration',
    title: 'Refrigerant leak indicators present',
    aliases: ['suspected refrigerant leak', 'oil spots on coil', 'charge keeps dropping', 'leaky schrader'],
    symptoms: ['Cooling capacity drops over weeks/months', 'Repeated need for refrigerant top-off', 'Oil staining on coil or line set joints'],
    likelyCauses: ['Evaporator coil corrosion', 'Vibration crack at braze joints', 'Leaking Schrader core/cap', 'Service valve seepage', 'Rub-through on line set'],
    steps: [
      'Document baseline pressures/superheat/subcooling to confirm charge deficiency trend.',
      'Perform complete electronic leak survey with system off and running modes.',
      'Use bubble solution on all accessible joints, valves, and Schrader cores.',
      'Isolate/pressure test suspect sections with dry nitrogen when leak is not obvious.',
      'Repair confirmed leak, replace filter-drier, evacuate to deep vacuum, and weigh in factory charge.',
    ],
    safety: ['Recover refrigerant before opening system; do not vent to atmosphere.', 'Nitrogen pressure testing requires regulator and rated hoses.'],
    tools: ['Heated diode leak detector', 'Bubble solution', 'Nitrogen kit', 'Refrigerant scale'],
    parts: ['Schrader cores/caps', 'Evaporator coil', 'Line set section', 'Filter-drier'],
    severity: 'high',
    proTips: ['If the same system needs refrigerant every season, stop topping off and start leak proving.'],
  },
  {
    id: 'hvac-compressor-hard-start',
    packId: 'hvac',
    category: 'refrigeration',
    title: 'Compressor hard start / locked rotor behavior',
    aliases: ['compressor hums then trips', 'hard starting compressor', 'locked rotor amps', 'contactor chatters on start'],
    symptoms: ['Compressor pulls high inrush then trips', 'Outdoor fan may run while compressor stalls', 'Breaker or internal overload opens'],
    likelyCauses: ['Weak run capacitor', 'High starting load from pressure imbalance', 'Low line voltage under load', 'Aging compressor mechanical wear', 'Failed start assist components'],
    steps: [
      'Measure line voltage at contactor during start attempt and verify acceptable sag.',
      'Test run capacitor microfarads and replace if out of tolerance.',
      'Record compressor inrush and running amps; compare to RLA/LRA nameplate.',
      'Install manufacturer-approved hard start kit if voltage is stable and compressor is mechanically borderline.',
      'If locked rotor persists with proper voltage/capacitors/start kit, quote compressor or condenser replacement.',
    ],
    safety: ['Stand clear during restart attempts; components can fail violently under high current.', 'Isolate power before capacitor replacement.'],
    tools: ['Clamp meter with inrush', 'Capacitance meter', 'Multimeter', 'Hard start selection chart'],
    parts: ['Run capacitor', 'Potential relay/PTC hard start kit', 'Contactor', 'Compressor'],
    severity: 'high',
    proTips: ['Do voltage and capacitor checks before condemning the compressor. Many “bad compressors” are bad capacitors.'],
  },
  {
    id: 'hvac-duct-leak-weak-room',
    packId: 'hvac',
    category: 'airflow',
    title: 'Weak airflow in one room / suspected duct leakage',
    aliases: ['one room hot', 'weak register', 'duct leak', 'poor balancing'],
    symptoms: ['Single room consistently off setpoint', 'Low register velocity', 'Attic whistle or visible disconnected duct'],
    likelyCauses: ['Disconnected/fallen flex duct', 'Crushed or kinked flex run', 'Major leakage at plenum boot', 'Damper closed or misadjusted', 'Insufficient return path'],
    steps: [
      'Measure supply temperature and airflow at affected register versus a nearby healthy room.',
      'Inspect branch run from plenum to boot for disconnections, kinks, and compression.',
      'Seal joints/boots with mastic and proper tape, then support flex to full diameter.',
      'Check balancing dampers and adjust only after leakage/mechanical issues are fixed.',
      'Verify door undercut/return path so the room can circulate air when door is closed.',
    ],
    safety: ['Use attic PPE and watch footing to avoid ceiling damage.', 'Avoid disturbing insulation around recessed lights or electrical junctions.'],
    tools: ['Anemometer', 'Thermometer', 'Duct mastic', 'Zip ties and hanging strap'],
    parts: ['Flex duct', 'Start collar', 'Register boot', 'Balancing damper'],
    severity: 'medium',
    proTips: ['Balancing won’t fix a disconnected run. Physical duct inspection beats guessing every time.'],
  },
  {
    id: 'hvac-short-cycling',
    packId: 'hvac',
    category: 'controls',
    title: 'System short cycling (rapid on/off)',
    aliases: ['short cycling ac', 'furnace short cycle', 'unit starts stops quickly', 'rapid cycling'],
    symptoms: ['Runtime under 5 minutes repeatedly', 'Poor comfort and humidity control', 'Frequent compressor or burner starts'],
    likelyCauses: ['Oversized equipment', 'Thermostat location or anticipator/staging issue', 'Dirty coil causing safety trips', 'Low/high pressure safety opening', 'Limit switch opening from airflow problems'],
    steps: [
      'Log cycle times and identify whether shutdown is thermostat satisfied or safety/device controlled.',
      'Read control board fault history for pressure, limit, or lockout events.',
      'Verify thermostat placement away from supply drafts/sunload and confirm cycle rate settings.',
      'Check airflow, coil cleanliness, and refrigerant conditions for pressure-related trips.',
      'Correct root cause and verify stable runtimes that allow proper temperature and humidity control.',
    ],
    safety: ['Do not bypass limits or pressure switches for normal operation.', 'Repeated hard starts can damage compressors and blowers quickly.'],
    tools: ['Data logging thermometer', 'Multimeter', 'Manometer', 'Refrigeration gauges'],
    parts: ['Thermostat', 'Pressure switch', 'High-limit switch', 'Contactor'],
    severity: 'high',
    proTips: ['Ask what turns it off: thermostat click or fault code. That answer cuts diagnosis time in half.'],
  },
  {
    id: 'hvac-gas-smell-at-furnace',
    packId: 'hvac',
    category: 'heating',
    title: 'Gas smell reported at furnace',
    aliases: ['furnace gas odor', 'smell gas near unit', 'possible gas leak', 'raw gas smell'],
    symptoms: ['Noticeable gas odor in mechanical room', 'Odor stronger during ignition attempts', 'Possible headaches/nausea complaints'],
    likelyCauses: ['Gas valve/manifold leak', 'Loose union or drip leg fitting', 'Delayed ignition causing brief gas puff', 'Cracked burner or crossover issue', 'Upstream utility leak'],
    steps: [
      'If strong active odor: stop operation, shut gas supply, ventilate area, and follow emergency protocol.',
      'Use calibrated gas detector and bubble solution on valve, unions, manifold, and test ports.',
      'Check ignition sequence for delayed ignition and inspect burner crossover condition.',
      'Verify inlet and manifold gas pressures are within manufacturer range.',
      'Repair leaks, replace defective gas train components, and perform full combustion/safety verification before return to service.',
    ],
    safety: ['Treat any sustained gas odor as an immediate hazard; no sparks/open flames.', 'Follow local code and utility notification requirements for confirmed leaks.'],
    tools: ['Combustible gas detector', 'Manometer', 'Bubble solution', 'Combustion analyzer'],
    parts: ['Gas valve', 'Manifold gaskets', 'Burner assembly', 'Gas cock/union fittings'],
    severity: 'critical',
    proTips: ['Never normalize “small gas smell.” Find it, prove it, fix it, document it.'],
  },
  {
    id: 'hvac-communicating-stat-fault',
    packId: 'hvac',
    category: 'controls',
    title: 'Communicating thermostat/bus fault',
    aliases: ['comm stat error', 'abc bus fault', 'indoor outdoor communication lost', 'smart stat no equipment found'],
    symptoms: ['Thermostat displays communication error', 'Outdoor or indoor unit missing from menu', 'System drops into backup/default operation'],
    likelyCauses: ['Open/short on communication bus', 'Reversed polarity on ABCD terminals', 'Addressing mismatch after board replacement', 'Firmware incompatibility', 'Noise/interference from damaged cable'],
    steps: [
      'Document exact error code and equipment model numbers before power cycling.',
      'Verify bus wiring continuity, polarity, and tight terminations at every device in chain.',
      'Disconnect non-essential accessories and reintroduce one at a time to isolate bad node.',
      'Confirm board addresses and run manufacturer setup/discovery sequence.',
      'Update compatible firmware and replace faulty communicating board/stat if bus integrity is confirmed.',
    ],
    safety: ['Power down equipment before moving communication conductors near line voltage sections.', 'Use manufacturer procedures when flashing firmware to avoid bricking controls.'],
    tools: ['Multimeter', 'Manufacturer service app/tool', 'Wiring diagram', 'Spare comm cable'],
    parts: ['Communicating thermostat', 'Indoor control board', 'Outdoor control board', 'Communication harness'],
    severity: 'medium',
    proTips: ['Take pictures of every comm terminal before touching wiring. One swapped pair can waste hours.'],
  },
];
