/** Auto-generated by scripts/resolve-plant-wiki-images.mjs — do not edit by hand. */
import type { PlantImage } from './types';

export type PlantImageSet = {
  imageUrl: string;
  imageCredit: string;
  additionalImages: PlantImage[];
};

export const PLANT_IMAGE_MANIFEST: Record<string, PlantImageSet> = {
  "blackcap-raspberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Rubusleucodermis.jpg/960px-Rubusleucodermis.jpg",
    "imageCredit": "Wikimedia Commons — Rubus leucodermis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rubus%20leucodermis.jpg?width=960",
        "credit": "Wikimedia Commons — Rubus leucodermis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rubus%20leucodermis%201.jpg?width=960",
        "credit": "Wikimedia Commons — Rubus leucodermis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "evergreen-blackberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Rubus_laciniatus.jpg/960px-Rubus_laciniatus.jpg",
    "imageCredit": "Wikimedia Commons — Rubus laciniatus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rubus%20laciniatus.jpg?width=960",
        "credit": "Wikimedia Commons — Rubus laciniatus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Rubus_laciniatus_07.jpg/960px-Rubus_laciniatus_07.jpg",
        "credit": "Wikimedia Commons — Rubus laciniatus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "red-flowering-currant-berry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Pink_Flowering_Currant_closeup%2C_Ribes_sanguineum.jpg/960px-Pink_Flowering_Currant_closeup%2C_Ribes_sanguineum.jpg",
    "imageCredit": "Wikimedia Commons — Ribes sanguineum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Fruit%20de%20Ribes%20sanguineum.jpg?width=960",
        "credit": "Wikimedia Commons — Ribes sanguineum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Gewone%20aardhommel%20koningin%20op%20Ribes%20sanguineum%20(Bombus%20terrestris)%204.jpg?width=960",
        "credit": "Wikimedia Commons — Ribes sanguineum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "stink-currant": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Ribes_bracteosum_9295.JPG/960px-Ribes_bracteosum_9295.JPG",
    "imageCredit": "Wikimedia Commons — Ribes bracteosum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Myriophyllum%20matogrossense.jpg?width=960",
        "credit": "Wikimedia Commons — Ribes bracteosum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ribes%20bracteosum%2010366.JPG?width=960",
        "credit": "Wikimedia Commons — Ribes bracteosum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sierra-gooseberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ribes_roezlii.jpg/960px-Ribes_roezlii.jpg",
    "imageCredit": "Wikimedia Commons — Ribes roezlii",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ribes%20roezlii.jpg?width=960",
        "credit": "Wikimedia Commons — Ribes roezlii",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ribes%20roezlii%20spiny%20fruit.jpg?width=960",
        "credit": "Wikimedia Commons — Ribes roezlii",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "chokecherry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Prunus_virginiana_flowers.jpg/960px-Prunus_virginiana_flowers.jpg",
    "imageCredit": "Wikimedia Commons — Prunus virginiana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2014-10-03%2015%2015%2035%20Chokecherry%20showing%20autumn%20foliage%20coloration%20along%20the%20main%20ridge%20of%20the%20Diamond%20Mountains%20south%20of%20Diamond%20Peak%2C%20Nevada.JPG?width=960",
        "credit": "Wikimedia Commons — Prunus virginiana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Chokecherries%20being%20prepared%20for%20wojapi%202023.09.08.jpg?width=960",
        "credit": "Wikimedia Commons — Prunus virginiana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bitter-cherry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Prunus_emarginata_15419.JPG/960px-Prunus_emarginata_15419.JPG",
    "imageCredit": "Wikimedia Commons — Prunus emarginata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bitter%20cherry%20Prunus%20emarginata%20close.jpg?width=960",
        "credit": "Wikimedia Commons — Prunus emarginata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/PrunusEmarginata%20pits.jpg?width=960",
        "credit": "Wikimedia Commons — Prunus emarginata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "madrone-berry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Arbutus_menziesii_5822.JPG/960px-Arbutus_menziesii_5822.JPG",
    "imageCredit": "Wikimedia Commons — Arbutus menziesii",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arbutus%20Tree%20(7743626674).jpg?width=960",
        "credit": "Wikimedia Commons — Arbutus menziesii",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arbutus%20menziesii-5.jpg?width=960",
        "credit": "Wikimedia Commons — Arbutus menziesii",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "manzanita-berry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Arctostaphylos_patula_08399.JPG/960px-Arctostaphylos_patula_08399.JPG",
    "imageCredit": "Wikimedia Commons — Arctostaphylos patula",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arctostaphylos%20patula%20(Green%20leaf%20Manzanita).jpg?width=960",
        "credit": "Wikimedia Commons — Arctostaphylos patula",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arctostaphylos%20patula%2008399.JPG?width=960",
        "credit": "Wikimedia Commons — Arctostaphylos patula",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "toyon": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Heteromeles_arbutifolia_1.jpg/960px-Heteromeles_arbutifolia_1.jpg",
    "imageCredit": "Wikimedia Commons — Heteromeles arbutifolia",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Heteromeles_arbutifolia_03.jpg/960px-Heteromeles_arbutifolia_03.jpg",
        "credit": "Wikimedia Commons — Heteromeles arbutifolia",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Heteromeles_arbutifolia_range_map.jpg",
        "credit": "Wikimedia Commons — Heteromeles arbutifolia",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wild-grape": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Vitis_californica_with_grapes.jpg/960px-Vitis_californica_with_grapes.jpg",
    "imageCredit": "Wikimedia Commons — Vitis californica",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vitis%20californica%20Roger%E2%80%99s%20Red%20ripe%20grapes.jpg?width=960",
        "credit": "Wikimedia Commons — Vitis californica",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vitis%20californica%20at%20Caswell%20Memorial%20State%20Park%20spring%20leaves.jpg?width=960",
        "credit": "Wikimedia Commons — Vitis californica",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "woodland-strawberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Illustration_Fragaria_vesca0.jpg/960px-Illustration_Fragaria_vesca0.jpg",
    "imageCredit": "Wikimedia Commons — Fragaria vesca",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Fragaria%20vesca%20-%20metsmaasikas.jpg?width=960",
        "credit": "Wikimedia Commons — Fragaria vesca",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Fragaria%20vesca%205044.JPG?width=960",
        "credit": "Wikimedia Commons — Fragaria vesca",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "cascade-huckleberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Vaccinium_deliciosum_Full_Plant.jpg/960px-Vaccinium_deliciosum_Full_Plant.jpg",
    "imageCredit": "Wikimedia Commons — Vaccinium deliciosum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vaccinium%20deliciosum.jpg?width=960",
        "credit": "Wikimedia Commons — Vaccinium deliciosum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vaccinium%20deliciosum%20Full%20Plant.jpg?width=960",
        "credit": "Wikimedia Commons — Vaccinium deliciosum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "dwarf-huckleberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Vaccinium_cespitosum_0806025.jpg/960px-Vaccinium_cespitosum_0806025.jpg",
    "imageCredit": "Wikimedia Commons — Vaccinium caespitosum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Sierra_bilberry_Vaccinium_caespitosum.jpg/960px-Sierra_bilberry_Vaccinium_caespitosum.jpg",
        "credit": "Wikimedia Commons — Vaccinium caespitosum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Vaccinium_caespitosum_3-eheep_%285097507665%29.jpg/960px-Vaccinium_caespitosum_3-eheep_%285097507665%29.jpg",
        "credit": "Wikimedia Commons — Vaccinium caespitosum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "osoberry": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Oemleria_cerasiformis_07.jpg/960px-Oemleria_cerasiformis_07.jpg",
    "imageCredit": "Wikimedia Commons — Oemleria cerasiformis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Indian%20Plum.JPG?width=960",
        "credit": "Wikimedia Commons — Oemleria cerasiformis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Oemleria%20cerasiformis%2007.jpg?width=960",
        "credit": "Wikimedia Commons — Oemleria cerasiformis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "western-dock": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Rumexoccidentalis.jpg/960px-Rumexoccidentalis.jpg",
    "imageCredit": "Wikimedia Commons — Rumex occidentalis",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/9/91/Rumexoccidentalis.jpg",
        "credit": "Wikimedia Commons — Rumex occidentalis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rumexoccidentalis.jpg?width=960",
        "credit": "Wikimedia Commons — Rumex occidentalis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "common-mallow": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Malva_neglecta-flower.jpg/960px-Malva_neglecta-flower.jpg",
    "imageCredit": "Wikimedia Commons — Malva neglecta",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Frosted%20Common%20Mallow%20in%20Port%20Edward.jpg?width=960",
        "credit": "Wikimedia Commons — Malva neglecta",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Malva%20neglecta-flower.jpg?width=960",
        "credit": "Wikimedia Commons — Malva neglecta",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sow-thistle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sonchus_February_2008-1.jpg/960px-Sonchus_February_2008-1.jpg",
    "imageCredit": "Wikimedia Commons — Sonchus oleraceus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Amanida%20de%20lletsons9.JPG?width=960",
        "credit": "Wikimedia Commons — Sonchus oleraceus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flower%20of%20Sonchus%20oleraceus.jpg?width=960",
        "credit": "Wikimedia Commons — Sonchus oleraceus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "prickly-lettuce": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Lactucaserriola2web.jpg/960px-Lactucaserriola2web.jpg",
    "imageCredit": "Wikimedia Commons — Lactuca serriola",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Lactucaserriola2web.jpg",
        "credit": "Wikimedia Commons — Lactuca serriola",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Kompassla%2008-07-2006%209.39.08.JPG?width=960",
        "credit": "Wikimedia Commons — Lactuca serriola",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "watercress": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Watercress_%282%29.JPG/960px-Watercress_%282%29.JPG",
    "imageCredit": "Wikimedia Commons — Nasturtium officinale",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Illustration_Nasturtium_officinale0.jpg/960px-Illustration_Nasturtium_officinale0.jpg",
        "credit": "Wikimedia Commons — Nasturtium officinale",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Nasturtium_officinale_154629037.jpg/960px-Nasturtium_officinale_154629037.jpg",
        "credit": "Wikimedia Commons — Nasturtium officinale",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "spring-beauty": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Claytonia_lanceolata_at_Leavenworth_Ski_Hill_2.jpg/960px-Claytonia_lanceolata_at_Leavenworth_Ski_Hill_2.jpg",
    "imageCredit": "Wikimedia Commons — Claytonia lanceolata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Claytonia%20lanceolata%20at%20Leavenworth%20Ski%20Hill%202.jpg?width=960",
        "credit": "Wikimedia Commons — Claytonia lanceolata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Starr%20030418-0059%20Bougainvillea%20spectabilis.jpg?width=960",
        "credit": "Wikimedia Commons — Claytonia lanceolata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "nodding-onion": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Allium_cernuum_1.jpg/960px-Allium_cernuum_1.jpg",
    "imageCredit": "Wikimedia Commons — Allium cernuum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Allium_cernuum_1.jpg",
        "credit": "Wikimedia Commons — Allium cernuum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Allium%20cernuum%20(3287845832).jpg?width=960",
        "credit": "Wikimedia Commons — Allium cernuum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wild-onion": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Alliumacuminatum.JPG/960px-Alliumacuminatum.JPG",
    "imageCredit": "Wikimedia Commons — Allium acuminatum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/02%20Allium%20sp.%2002.jpg?width=960",
        "credit": "Wikimedia Commons — Allium acuminatum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Alliumacuminatum.JPG?width=960",
        "credit": "Wikimedia Commons — Allium acuminatum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "fat-hen": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Melganzenvoet_bloeiwijze_Chenopodium_album.jpg/960px-Melganzenvoet_bloeiwijze_Chenopodium_album.jpg",
    "imageCredit": "Wikimedia Commons — Chenopodium album",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/6H-Lambs-quarter.jpg?width=960",
        "credit": "Wikimedia Commons — Chenopodium album",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Chenopodium%20albium%20(wild%20spinach)%2C%20wild%20field%2C%20Warsaw%2C%20Poland.jpg?width=960",
        "credit": "Wikimedia Commons — Chenopodium album",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wild-amaranth": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Amaranthus_retroflexus_flower1.jpg/960px-Amaranthus_retroflexus_flower1.jpg",
    "imageCredit": "Wikimedia Commons — Amaranthus retroflexus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Amaranthus%20retroflexus%2C%20Thom%C3%A9%201885-1.png?width=960",
        "credit": "Wikimedia Commons — Amaranthus retroflexus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Amaranthus%20retroflexus%20flower1.jpg?width=960",
        "credit": "Wikimedia Commons — Amaranthus retroflexus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "orache": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Atriplex_hortensis_MHNT.BOT.2013.22.60.jpg/960px-Atriplex_hortensis_MHNT.BOT.2013.22.60.jpg",
    "imageCredit": "Wikimedia Commons — Atriplex hortensis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Atriplex%20hortensis%20MHNT.BOT.2013.22.60.jpg?width=960",
        "credit": "Wikimedia Commons — Atriplex hortensis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Atriplex%20hortensis%20cleaned%20Sturm.png?width=960",
        "credit": "Wikimedia Commons — Atriplex hortensis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "winter-cress": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/%28MHNT%29_Barbarea_vulgaris_-_Habit.jpg/960px-%28MHNT%29_Barbarea_vulgaris_-_Habit.jpg",
    "imageCredit": "Wikimedia Commons — Barbarea vulgaris",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/(MHNT)%20Barbarea%20vulgaris%20-%20Habit.jpg?width=960",
        "credit": "Wikimedia Commons — Barbarea vulgaris",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/31%20Barbarea%20vulgaris%20R.Br.jpg?width=960",
        "credit": "Wikimedia Commons — Barbarea vulgaris",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bittercress": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Cardamine_oligosperma_6649.JPG/960px-Cardamine_oligosperma_6649.JPG",
    "imageCredit": "Wikimedia Commons — Cardamine oligosperma",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Barbarea%20vulgaris%20002.JPG?width=960",
        "credit": "Wikimedia Commons — Cardamine oligosperma",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cardamine%20oligosperma%201840.JPG?width=960",
        "credit": "Wikimedia Commons — Cardamine oligosperma",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wild-radish-greens": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Raphanus_raphanistrum_-_Deutschlands_flora_in_abbildungen_nach_der_natur_-_vol._6_-_t._40_-_clean.jpg/960px-Raphanus_raphanistrum_-_Deutschlands_flora_in_abbildungen_nach_der_natur_-_vol._6_-_t._40_-_clean.jpg",
    "imageCredit": "Wikimedia Commons — Raphanus raphanistrum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Raphanus_raphanistrum_-_Deutschlands_flora_in_abbildungen_nach_der_natur_-_vol._6_-_t._40_-_clean.jpg",
        "credit": "Wikimedia Commons — Raphanus raphanistrum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/(MHNT)%20Raphanus%20raphanistrum%20-%20Habitus.jpg?width=960",
        "credit": "Wikimedia Commons — Raphanus raphanistrum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "camas": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Camassia_quamash_%28Pursh%29_Greene.jpg/960px-Camassia_quamash_%28Pursh%29_Greene.jpg",
    "imageCredit": "Wikimedia Commons — Camassia quamash",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Camassia%20quamash%20(Pursh)%20Greene.jpg?width=960",
        "credit": "Wikimedia Commons — Camassia quamash",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Camassia%20quamash%2007017.JPG?width=960",
        "credit": "Wikimedia Commons — Camassia quamash",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wapato": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Sagittaria_latifolia_%28flowers%29.jpg/960px-Sagittaria_latifolia_%28flowers%29.jpg",
    "imageCredit": "Wikimedia Commons — Sagittaria latifolia",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sagittaria%20latifolia%20(flowers).jpg?width=960",
        "credit": "Wikimedia Commons — Sagittaria latifolia",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sagittaria%20latifolia%20027.jpg?width=960",
        "credit": "Wikimedia Commons — Sagittaria latifolia",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "balsamroot": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Balsamorhiza_sagittata_10.jpg/960px-Balsamorhiza_sagittata_10.jpg",
    "imageCredit": "Wikimedia Commons — Balsamorhiza sagittata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arrowleaf%20Balsamroot%20009.jpg?width=960",
        "credit": "Wikimedia Commons — Balsamorhiza sagittata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Balsamorhiza%20sagittata%20(3625593445).jpg?width=960",
        "credit": "Wikimedia Commons — Balsamorhiza sagittata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "biscuitroot": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Lomatium_californicum.jpeg/960px-Lomatium_californicum.jpeg",
    "imageCredit": "Wikimedia Commons — Lomatium californicum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/8/87/Lomatium_californicum.jpeg",
        "credit": "Wikimedia Commons — Lomatium californicum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Lomatium%20californicum.jpeg?width=960",
        "credit": "Wikimedia Commons — Lomatium californicum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "cow-parsnip": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Heracleum_lanatum_from_High_Trail.jpg/960px-Heracleum_lanatum_from_High_Trail.jpg",
    "imageCredit": "Wikimedia Commons — Heracleum maximum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Big%20pushki.jpg?width=960",
        "credit": "Wikimedia Commons — Heracleum maximum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Big%20pushki%20in%20winter.jpg?width=960",
        "credit": "Wikimedia Commons — Heracleum maximum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "silverweed": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Argentina_egedii_2818.JPG/960px-Argentina_egedii_2818.JPG",
    "imageCredit": "Wikimedia Commons — Argentina pacifica",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Addisonia%20-%20colored%20illustrations%20and%20popular%20descriptions%20of%20plants%20(1916-(1964))%20(16585422840).jpg?width=960",
        "credit": "Wikimedia Commons — Argentina pacifica",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Argentina%20egedii%202818.JPG?width=960",
        "credit": "Wikimedia Commons — Argentina pacifica",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "lady-fern-fiddleheads": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Athyrium_filix-femina0.jpg/960px-Athyrium_filix-femina0.jpg",
    "imageCredit": "Wikimedia Commons — Athyrium filix-femina",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Athyrium%20filix-femina0.jpg?width=960",
        "credit": "Wikimedia Commons — Athyrium filix-femina",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Athyrium%20filix-femina%20Sori%20Tannwald1.jpg?width=960",
        "credit": "Wikimedia Commons — Athyrium filix-femina",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "deer-fern": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Blechnum_spicant_%28fertile_and_sterile_fronts%29.jpg/960px-Blechnum_spicant_%28fertile_and_sterile_fronts%29.jpg",
    "imageCredit": "Wikimedia Commons — Blechnum spicant",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Blechnum_spicant.jpg/960px-Blechnum_spicant.jpg",
        "credit": "Wikimedia Commons — Blechnum spicant",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Blechnum_spicant_%287184638950%29.jpg",
        "credit": "Wikimedia Commons — Blechnum spicant",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bracken-fiddleheads": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Adelaarsvaren_planten_Pteridium_aquilinum.jpg/960px-Adelaarsvaren_planten_Pteridium_aquilinum.jpg",
    "imageCredit": "Wikimedia Commons — Pteridium aquilinum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Adelaarsvaren%20planten%20Pteridium%20aquilinum.jpg?width=960",
        "credit": "Wikimedia Commons — Pteridium aquilinum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Dried%20Eastern%20brakenfern.jpg?width=960",
        "credit": "Wikimedia Commons — Pteridium aquilinum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wild-hazelnut": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Corylus_cornuta.jpg/960px-Corylus_cornuta.jpg",
    "imageCredit": "Wikimedia Commons — Corylus cornuta",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Corylus_cornuta.jpg",
        "credit": "Wikimedia Commons — Corylus cornuta",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Corylus%20cornuta%2C%20nut.jpg?width=960",
        "credit": "Wikimedia Commons — Corylus cornuta",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "garry-oak-acorn": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/52/Lone_oak_%28cropped%29.jpg",
    "imageCredit": "Wikimedia Commons — Quercus garryana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Gallrazorback.jpg?width=960",
        "credit": "Wikimedia Commons — Quercus garryana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Lone%20oak%20(cropped).jpg?width=960",
        "credit": "Wikimedia Commons — Quercus garryana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "golden-chinquapin": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Chrysolepis_chrysophylla_foliage_and_fruit_Big_Basin_State_Park.jpg/960px-Chrysolepis_chrysophylla_foliage_and_fruit_Big_Basin_State_Park.jpg",
    "imageCredit": "Wikimedia Commons — Chrysolepis chrysophylla",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysolepis%20chrysophylla%20foliage%20and%20fruit%20Big%20Basin%20State%20Park.jpg?width=960",
        "credit": "Wikimedia Commons — Chrysolepis chrysophylla",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Chrysolepis_chrysophylla_Huckleberry_BRP_1.jpg/960px-Chrysolepis_chrysophylla_Huckleberry_BRP_1.jpg",
        "credit": "Wikimedia Commons — Chrysolepis chrysophylla",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "gray-pine-nut": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Pinus_sabiniana.jpg/960px-Pinus_sabiniana.jpg",
    "imageCredit": "Wikimedia Commons — Pinus sabiniana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/FoothillPineCone.jpg?width=960",
        "credit": "Wikimedia Commons — Pinus sabiniana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/J20161101-0079%E2%80%94Gray%20pine%20cone%2C%20pine%20nuts%2C%20and%20resin%E2%80%94RPBG%20(30547385050).jpg?width=960",
        "credit": "Wikimedia Commons — Pinus sabiniana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "chia": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Salvia_columbariae_7922.JPG/960px-Salvia_columbariae_7922.JPG",
    "imageCredit": "Wikimedia Commons — Salvia columbariae",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Salvia%20columbariae%201.jpg?width=960",
        "credit": "Wikimedia Commons — Salvia columbariae",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Salvia%20columbariae%207922.JPG?width=960",
        "credit": "Wikimedia Commons — Salvia columbariae",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "spruce-tips": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Sitka_01.JPG/960px-Sitka_01.JPG",
    "imageCredit": "Wikimedia Commons — Picea sitchensis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Kiidk'yaas%20in%201984.jpg?width=960",
        "credit": "Wikimedia Commons — Picea sitchensis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Picea%20sitchensis1.jpg?width=960",
        "credit": "Wikimedia Commons — Picea sitchensis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "grand-fir-tips": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Abies_grandis_Rog%C3%B3w_6.jpg/960px-Abies_grandis_Rog%C3%B3w_6.jpg",
    "imageCredit": "Wikimedia Commons — Abies grandis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Abies%20grandis%205357.JPG?width=960",
        "credit": "Wikimedia Commons — Abies grandis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Abies%20grandis%205359.JPG?width=960",
        "credit": "Wikimedia Commons — Abies grandis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bigleaf-maple-sap": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Acer_macrophyllum_1199.jpg/960px-Acer_macrophyllum_1199.jpg",
    "imageCredit": "Wikimedia Commons — Acer macrophyllum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Acer%20macrophyllum%201.jpg?width=960",
        "credit": "Wikimedia Commons — Acer macrophyllum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Acer%20macrophyllum%201199.jpg?width=960",
        "credit": "Wikimedia Commons — Acer macrophyllum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "yerba-buena": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Yerba_Buena_-_Clinopodium_douglasii.jpg/960px-Yerba_Buena_-_Clinopodium_douglasii.jpg",
    "imageCredit": "Wikimedia Commons — Clinopodium douglasii",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Micromeria%20douglasii%20type%20specimen%20sheet.jpg?width=960",
        "credit": "Wikimedia Commons — Clinopodium douglasii",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/YERBA%20BUENA%20(satureja%20douglasii)%20(6-19-08)%20canet%20(2593333894).jpg?width=960",
        "credit": "Wikimedia Commons — Clinopodium douglasii",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "mugwort": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Artemisia_douglasiana_1.jpg/960px-Artemisia_douglasiana_1.jpg",
    "imageCredit": "Wikimedia Commons — Artemisia douglasiana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aceria%20abalis%201.jpg?width=960",
        "credit": "Wikimedia Commons — Artemisia douglasiana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Artemisia%20douglasiana%201.jpg?width=960",
        "credit": "Wikimedia Commons — Artemisia douglasiana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sweet-cicely": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Osmorhiza_occidentalis_15382.JPG/960px-Osmorhiza_occidentalis_15382.JPG",
    "imageCredit": "Wikimedia Commons — Osmorhiza occidentalis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Osmorhiza%20occidentalis%2015382.JPG?width=960",
        "credit": "Wikimedia Commons — Osmorhiza occidentalis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Osmorhiza_occidentalis_15380.JPG/960px-Osmorhiza_occidentalis_15380.JPG",
        "credit": "Wikimedia Commons — Osmorhiza occidentalis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "california-bay-laurel": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Umbellularia_californica_02.jpg/960px-Umbellularia_californica_02.jpg",
    "imageCredit": "Wikimedia Commons — Umbellularia californica",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Umbellularia_californica_02.jpg",
        "credit": "Wikimedia Commons — Umbellularia californica",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Umbellularia_californica_03.jpg/960px-Umbellularia_californica_03.jpg",
        "credit": "Wikimedia Commons — Umbellularia californica",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bull-kelp": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Nereocystis_luetkeana1.jpg/960px-Nereocystis_luetkeana1.jpg",
    "imageCredit": "Wikimedia Commons — Nereocystis luetkeana",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Algae_bladder_4290.jpg/960px-Algae_bladder_4290.jpg",
        "credit": "Wikimedia Commons — Nereocystis luetkeana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/CAS_Nereocystis_1.JPG/960px-CAS_Nereocystis_1.JPG",
        "credit": "Wikimedia Commons — Nereocystis luetkeana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sea-palm": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Postelsia_palmaeformis_Salt_Point.jpg/960px-Postelsia_palmaeformis_Salt_Point.jpg",
    "imageCredit": "Wikimedia Commons — Postelsia palmaeformis",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Postelsia_palmaeformis-1.jpg/960px-Postelsia_palmaeformis-1.jpg",
        "credit": "Wikimedia Commons — Postelsia palmaeformis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Postelsia_palmaeformis_2.jpg/960px-Postelsia_palmaeformis_2.jpg",
        "credit": "Wikimedia Commons — Postelsia palmaeformis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sea-lettuce": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sea_lettuce_in_Brofjorden_1_-_cropped.jpg/960px-Sea_lettuce_in_Brofjorden_1_-_cropped.jpg",
    "imageCredit": "Wikimedia Commons — Ulva lactuca",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sea%20lettuce%20in%20Brofjorden%201%20-%20cropped.jpg?width=960",
        "credit": "Wikimedia Commons — Ulva lactuca",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ulva%20lactuca%20-%20Sowerby.jpg?width=960",
        "credit": "Wikimedia Commons — Ulva lactuca",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bladderwrack": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Fucus_gardneri_rockweed.jpg/960px-Fucus_gardneri_rockweed.jpg",
    "imageCredit": "Wikimedia Commons — Fucus gardneri",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bladderwrack%20(Fucus%20gardneri).jpg?width=960",
        "credit": "Wikimedia Commons — Fucus gardneri",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Fucus%20gardneri%20rockweed.jpg?width=960",
        "credit": "Wikimedia Commons — Fucus gardneri",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "rockweed": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pelvetiopsislimitata.jpg/960px-Pelvetiopsislimitata.jpg",
    "imageCredit": "Wikimedia Commons — Pelvetiopsis limitata",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Dwarf_rockweed%2C_north_Moonstone.jpg/960px-Dwarf_rockweed%2C_north_Moonstone.jpg",
        "credit": "Wikimedia Commons — Pelvetiopsis limitata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Dwarf_rockweed%2C_north_Moonstone.jpg/960px-Dwarf_rockweed%2C_north_Moonstone.jpg",
        "credit": "Wikimedia Commons — Pelvetiopsis limitata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "pickleweed": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Sarcocorniapacifica.jpg/960px-Sarcocorniapacifica.jpg",
    "imageCredit": "Wikimedia Commons — Salicornia pacifica",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Salt%20Pond%20Restoration%20Project%20natural%20plant%20recruits!%20(6967964400).jpg?width=960",
        "credit": "Wikimedia Commons — Salicornia pacifica",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sarcocornia%20pacificaP5458.JPG?width=960",
        "credit": "Wikimedia Commons — Salicornia pacifica",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "sea-rocket": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/C_edentula.jpg/960px-C_edentula.jpg",
    "imageCredit": "Wikimedia Commons — Cakile edentula",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/C%20edentula.jpg?width=960",
        "credit": "Wikimedia Commons — Cakile edentula",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/C%20edentula%20fleurs%2001.jpg?width=960",
        "credit": "Wikimedia Commons — Cakile edentula",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "elderflower": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Sambucus_caerulea_8012.jpg/960px-Sambucus_caerulea_8012.jpg",
    "imageCredit": "Wikimedia Commons — Sambucus cerulea",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Sambucus_caerulea_8012.jpg",
        "credit": "Wikimedia Commons — Sambucus cerulea",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sambucus%20caerulea%207997.jpg?width=960",
        "credit": "Wikimedia Commons — Sambucus cerulea",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "nootka-rose-hips": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Rosa_nutkana_07513.JPG/960px-Rosa_nutkana_07513.JPG",
    "imageCredit": "Wikimedia Commons — Rosa nutkana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Diplolepis-rosae.jpg?width=960",
        "credit": "Wikimedia Commons — Rosa nutkana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa%20nutkana%2007513.JPG?width=960",
        "credit": "Wikimedia Commons — Rosa nutkana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "white-chanterelle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Cantharellus_subalbidus_130252.jpg/960px-Cantharellus_subalbidus_130252.jpg",
    "imageCredit": "Wikimedia Commons — Cantharellus subalbidus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletopsis%20nothofagi%20fruitbodies.jpg?width=960",
        "credit": "Wikimedia Commons — Cantharellus subalbidus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cantharellus%20subalbidus%20130252.jpg?width=960",
        "credit": "Wikimedia Commons — Cantharellus subalbidus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "yellowfoot-chanterelle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Craterellus_tubaeformis_1345904803_69350246bb_o.jpg/960px-Craterellus_tubaeformis_1345904803_69350246bb_o.jpg",
    "imageCredit": "Wikimedia Commons — Craterellus tubaeformis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Craterellus%20tubaeformis%201345904803%2069350246bb%20o.jpg?width=960",
        "credit": "Wikimedia Commons — Craterellus tubaeformis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Craterellus tubaeformis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "black-trumpet": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Craterellus_cornucopioides_JPG1.jpg/960px-Craterellus_cornucopioides_JPG1.jpg",
    "imageCredit": "Wikimedia Commons — Craterellus cornucopioides",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2010-08-24%20Craterellus%20cinereus%20(Pers.)%20Qu%C3%A9l%20100703%20cropped.jpg?width=960",
        "credit": "Wikimedia Commons — Craterellus cornucopioides",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Craterellus.cornucopioides.1000x.DIC.jpg?width=960",
        "credit": "Wikimedia Commons — Craterellus cornucopioides",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "king-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Boletus_edulis_IT.jpg/960px-Boletus_edulis_IT.jpg",
    "imageCredit": "Wikimedia Commons — Boletus edulis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita%20muscaria%203%20vliegenzwammen%20op%20rij.jpg?width=960",
        "credit": "Wikimedia Commons — Boletus edulis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus%20edulis%20(7).jpg?width=960",
        "credit": "Wikimedia Commons — Boletus edulis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "spring-king-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rexveris.jpg/960px-Rexveris.jpg",
    "imageCredit": "Wikimedia Commons — Boletus rex-veris",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus.rex-veris.ar.jpg?width=960",
        "credit": "Wikimedia Commons — Boletus rex-veris",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Boletus rex-veris",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "admirable-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Aureoboletus_mirabilis_%28Murrill%29_Halling_681855.jpg/960px-Aureoboletus_mirabilis_%28Murrill%29_Halling_681855.jpg",
    "imageCredit": "Wikimedia Commons — Aureoboletus mirabilis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aureoboletus%20mirabilis%20(Murrill)%20Halling%20681855.jpg?width=960",
        "credit": "Wikimedia Commons — Aureoboletus mirabilis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aureoboletus%20mirabilis%20Mt%20Baker%20Snoqualmie%20NF.jpg?width=960",
        "credit": "Wikimedia Commons — Aureoboletus mirabilis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "zellers-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Xerocomellus_zelleri_10114_crop.jpg/960px-Xerocomellus_zelleri_10114_crop.jpg",
    "imageCredit": "Wikimedia Commons — Xerocomellus zelleri",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Xerocomellus_zelleri_10114_crop.jpg",
        "credit": "Wikimedia Commons — Xerocomellus zelleri",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus%20zelleri.JPG?width=960",
        "credit": "Wikimedia Commons — Xerocomellus zelleri",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "chicken-of-the-woods": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Laetiporus_gilbertsonii_19346.jpg/960px-Laetiporus_gilbertsonii_19346.jpg",
    "imageCredit": "Wikimedia Commons — Laetiporus gilbertsonii",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ganoderma%20applanatum%204977.jpg?width=960",
        "credit": "Wikimedia Commons — Laetiporus gilbertsonii",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Laetiporus%20gilbertsonii%2019346.jpg?width=960",
        "credit": "Wikimedia Commons — Laetiporus gilbertsonii",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "lobster-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Hypomyces_lactifluorum.JPG/960px-Hypomyces_lactifluorum.JPG",
    "imageCredit": "Wikimedia Commons — Hypomyces lactifluorum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hypomyces%20lactifluorum.JPG?width=960",
        "credit": "Wikimedia Commons — Hypomyces lactifluorum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hypomyces%20lactifluorum%20(Lobster%20mushroom).jpg?width=960",
        "credit": "Wikimedia Commons — Hypomyces lactifluorum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "hedgehog-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Hedgehog_fungi2.jpg/960px-Hedgehog_fungi2.jpg",
    "imageCredit": "Wikimedia Commons — Hydnum repandum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Hedgehog_fungi2.jpg",
        "credit": "Wikimedia Commons — Hydnum repandum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hedgehog%20fungi2.jpg?width=960",
        "credit": "Wikimedia Commons — Hydnum repandum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "lions-mane": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Lion%27s-mane_mushroom_imported_from_iNaturalist_photo_29576097_on_21_March_2024.jpg/960px-Lion%27s-mane_mushroom_imported_from_iNaturalist_photo_29576097_on_21_March_2024.jpg",
    "imageCredit": "Wikimedia Commons — Hericium erinaceus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Beholder%20-%20June%202022%20-%20Sarah%20Stierch%2005.jpg?width=960",
        "credit": "Wikimedia Commons — Hericium erinaceus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Karl%20Johanssvamp%2C%20Iduns%20kokbok.png?width=960",
        "credit": "Wikimedia Commons — Hericium erinaceus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bears-head-hericium": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Hericium_abietis_109093.jpg/960px-Hericium_abietis_109093.jpg",
    "imageCredit": "Wikimedia Commons — Hericium abietis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hericium%20abietis%20109093.jpg?width=960",
        "credit": "Wikimedia Commons — Hericium abietis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hericium%20abietis%20mushroom%202018.jpg?width=960",
        "credit": "Wikimedia Commons — Hericium abietis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "oyster-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Pleurotus_pulmonarius_LC0228.jpg/960px-Pleurotus_pulmonarius_LC0228.jpg",
    "imageCredit": "Wikimedia Commons — Pleurotus pulmonarius",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Pleurotus pulmonarius",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pleurotus%20pulmonarius%20LC0228.jpg?width=960",
        "credit": "Wikimedia Commons — Pleurotus pulmonarius",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "western-giant-puffball": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Calvatia_booniana.jpg/960px-Calvatia_booniana.jpg",
    "imageCredit": "Wikimedia Commons — Calvatia booniana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Calvatia%20booniana.jpg?width=960",
        "credit": "Wikimedia Commons — Calvatia booniana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Calvatia booniana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "gem-studded-puffball": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Single_lycoperdon_perlatum.jpg/960px-Single_lycoperdon_perlatum.jpg",
    "imageCredit": "Wikimedia Commons — Lycoperdon perlatum",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flaschen-St%C3%A4ubling_%28Lycoperdon_perlatum%2C_syn._L._gemmatum%29-RM-20191014-01.jpg/960px-Flaschen-St%C3%A4ubling_%28Lycoperdon_perlatum%2C_syn._L._gemmatum%29-RM-20191014-01.jpg",
        "credit": "Wikimedia Commons — Lycoperdon perlatum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Lycoperdon_perlatum_97777217.jpg/960px-Lycoperdon_perlatum_97777217.jpg",
        "credit": "Wikimedia Commons — Lycoperdon perlatum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "shaggy-mane": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Coprinus_comatus%2C_the_shaggy_ink_cap%2C_lawyer%27s_wig%2C_or_shaggy_mane_mushroom.jpg/960px-Coprinus_comatus%2C_the_shaggy_ink_cap%2C_lawyer%27s_wig%2C_or_shaggy_mane_mushroom.jpg",
    "imageCredit": "Wikimedia Commons — Coprinus comatus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Coprinus%20comatus%2C%20the%20shaggy%20ink%20cap%2C%20lawyer's%20wig%2C%20or%20shaggy%20mane%20mushroom.jpg?width=960",
        "credit": "Wikimedia Commons — Coprinus comatus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Coprinus%20comatus-3%20hg.jpg?width=960",
        "credit": "Wikimedia Commons — Coprinus comatus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "matsutake": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/2018-11-10_Tricholoma_murrillianum_Singer_959693.jpg/960px-2018-11-10_Tricholoma_murrillianum_Singer_959693.jpg",
    "imageCredit": "Wikimedia Commons — Tricholoma murrillianum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2018-11-10%20Tricholoma%20murrillianum%20Singer%20959693.jpg?width=960",
        "credit": "Wikimedia Commons — Tricholoma murrillianum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Tricholoma murrillianum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "cauliflower-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Sparassis_crispa_JPG1.jpg/960px-Sparassis_crispa_JPG1.jpg",
    "imageCredit": "Wikimedia Commons — Sparassis radicata",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Penicilum_Spongia_Forma_Curalium1.jpg/960px-Penicilum_Spongia_Forma_Curalium1.jpg",
        "credit": "Wikimedia Commons — Sparassis radicata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Sparassis_spec._-_Lindsey.jpg",
        "credit": "Wikimedia Commons — Sparassis radicata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "candy-cap": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Lactarius_camphoratus_-_Lindsey.jpg/960px-Lactarius_camphoratus_-_Lindsey.jpg",
    "imageCredit": "Wikimedia Commons — Lactarius rubidus",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Lactarius_rubidus.jpg/960px-Lactarius_rubidus.jpg",
        "credit": "Wikimedia Commons — Lactarius rubidus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Lactarius_camphoratus_-_Lindsey.jpg",
        "credit": "Wikimedia Commons — Lactarius rubidus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "saffron-milk-cap": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Lactarius_deliciosus.jpg/960px-Lactarius_deliciosus.jpg",
    "imageCredit": "Wikimedia Commons — Lactarius deliciosus",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Lactarius_deliciosus.jpg",
        "credit": "Wikimedia Commons — Lactarius deliciosus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Lactarius%20deliciosus.jpg?width=960",
        "credit": "Wikimedia Commons — Lactarius deliciosus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "shrimp-russula": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/2011-11-08_Russula_xerampelina_%28Schaeff.%29_Fr_180998_mod.jpg/960px-2011-11-08_Russula_xerampelina_%28Schaeff.%29_Fr_180998_mod.jpg",
    "imageCredit": "Wikimedia Commons — Russula xerampelina",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2011-11-08%20Russula%20xerampelina%20(Schaeff.)%20Fr%20180998%20mod.jpg?width=960",
        "credit": "Wikimedia Commons — Russula xerampelina",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Russula xerampelina",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "prince-agaricus": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Agaricus_augustus_2011_G1.jpg/960px-Agaricus_augustus_2011_G1.jpg",
    "imageCredit": "Wikimedia Commons — Agaricus augustus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus.augustus.spores.1000x.jpg?width=960",
        "credit": "Wikimedia Commons — Agaricus augustus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus%20augustus%202011%20G1.jpg?width=960",
        "credit": "Wikimedia Commons — Agaricus augustus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "meadow-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Agaricus_campestris.jpg/960px-Agaricus_campestris.jpg",
    "imageCredit": "Wikimedia Commons — Agaricus campestris",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus%20campestris.jpg?width=960",
        "credit": "Wikimedia Commons — Agaricus campestris",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus%20campestris%20IMG%2020200912%20170142.jpg?width=960",
        "credit": "Wikimedia Commons — Agaricus campestris",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "pheasants-back": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Polyporus_squamosus_Molter.jpg/960px-Polyporus_squamosus_Molter.jpg",
    "imageCredit": "Wikimedia Commons — Cerioporus squamosus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Dryad's%20Saddle%20-%20pores.jpg?width=960",
        "credit": "Wikimedia Commons — Cerioporus squamosus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Edible.png?width=960",
        "credit": "Wikimedia Commons — Cerioporus squamosus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "honey-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Armillaria_ostoyae.jpg/960px-Armillaria_ostoyae.jpg",
    "imageCredit": "Wikimedia Commons — Armillaria ostoyae",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Armillaria_ostoyae.jpg",
        "credit": "Wikimedia Commons — Armillaria ostoyae",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Armillaria%20ostoyae.jpg?width=960",
        "credit": "Wikimedia Commons — Armillaria ostoyae",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "blewit": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Clitocybe_nuda_%28Fr.%29_H.E._Bigelow_%26_A.H._Sm_267650.jpg/960px-Clitocybe_nuda_%28Fr.%29_H.E._Bigelow_%26_A.H._Sm_267650.jpg",
    "imageCredit": "Wikimedia Commons — Lepista nuda",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Lepista_nuda.jpg",
        "credit": "Wikimedia Commons — Lepista nuda",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/9/91/Lepista.nuda2.-.lindsey.jpg",
        "credit": "Wikimedia Commons — Lepista nuda",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wood-ear": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Auricularia_americana_Parmasto_%26_I._Parmasto_ex_Audet%2C_Boulet_%26_Sirard_633121.jpg/960px-Auricularia_americana_Parmasto_%26_I._Parmasto_ex_Audet%2C_Boulet_%26_Sirard_633121.jpg",
    "imageCredit": "Wikimedia Commons — Auricularia americana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Auricularia%20americana%20Parmasto%20%26%20I.%20Parmasto%20ex%20Audet%2C%20Boulet%20%26%20Sirard%20633121.jpg?width=960",
        "credit": "Wikimedia Commons — Auricularia americana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Auricularia_americana_Parmasto_%26_I._Parmasto_ex_Audet%2C_Boulet_%26_Sirard_207208.jpg/960px-Auricularia_americana_Parmasto_%26_I._Parmasto_ex_Audet%2C_Boulet_%26_Sirard_207208.jpg",
        "credit": "Wikimedia Commons — Auricularia americana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "enoki": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/2009-11-19_Flammulina_velutipes_agg_biolib.cz_crop.jpg/960px-2009-11-19_Flammulina_velutipes_agg_biolib.cz_crop.jpg",
    "imageCredit": "Wikimedia Commons — Flammulina velutipes",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/f3/2009-11-19_Flammulina_velutipes_agg_biolib.cz_crop.jpg",
        "credit": "Wikimedia Commons — Flammulina velutipes",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2009-11-19%20Flammulina%20velutipes%20agg%20biolib.cz%20crop.jpg?width=960",
        "credit": "Wikimedia Commons — Flammulina velutipes",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "slippery-jack": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Suillus_luteus_475376.jpg/960px-Suillus_luteus_475376.jpg",
    "imageCredit": "Wikimedia Commons — Suillus luteus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2012-10-12%20Suillus%20luteus%20(L.)%20Roussel%20271431.jpg?width=960",
        "credit": "Wikimedia Commons — Suillus luteus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus%20luteus%20%E2%80%94%20Flora%20Batava%20%E2%80%94%20Volume%20v13.jpg?width=960",
        "credit": "Wikimedia Commons — Suillus luteus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "wine-cap": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/2011-05-19_Stropharia_rugosoannulata_Farl._ex_Murrill_183478.jpg/960px-2011-05-19_Stropharia_rugosoannulata_Farl._ex_Murrill_183478.jpg",
    "imageCredit": "Wikimedia Commons — Stropharia rugosoannulata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2011-05-19%20Stropharia%20rugosoannulata%20Farl.%20ex%20Murrill%20183478.jpg?width=960",
        "credit": "Wikimedia Commons — Stropharia rugosoannulata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Stropharia rugosoannulata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "pig-ear-gomphus": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Gomphus_clavatus_II_Totes_Gebirge.jpg/960px-Gomphus_clavatus_II_Totes_Gebirge.jpg",
    "imageCredit": "Wikimedia Commons — Gomphus clavatus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Gomphus%20clavatus%20Fairy%20ring.jpg?width=960",
        "credit": "Wikimedia Commons — Gomphus clavatus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Gomphus%20clavatus%20II%20Totes%20Gebirge.jpg?width=960",
        "credit": "Wikimedia Commons — Gomphus clavatus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "pine-spike": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Chroogomphus_vinicolor_116581.jpg/960px-Chroogomphus_vinicolor_116581.jpg",
    "imageCredit": "Wikimedia Commons — Chroogomphus vinicolor",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/5/54/Chroogomphus_vinicolor_116581.jpg",
        "credit": "Wikimedia Commons — Chroogomphus vinicolor",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Chroogomphus%20pseudovinicolor%20182522.jpg?width=960",
        "credit": "Wikimedia Commons — Chroogomphus vinicolor",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "combtooth": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Hericium_americanum_59312.jpg/960px-Hericium_americanum_59312.jpg",
    "imageCredit": "Wikimedia Commons — Hericium americanum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hericium%20americanum%2059312.jpg?width=960",
        "credit": "Wikimedia Commons — Hericium americanum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mushroom-IMG%203304.JPG?width=960",
        "credit": "Wikimedia Commons — Hericium americanum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "charcoal-burner": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Russula_cyanoxantha.JPG/960px-Russula_cyanoxantha.JPG",
    "imageCredit": "Wikimedia Commons — Russula cyanoxantha",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Russula_cyanoxantha.JPG",
        "credit": "Wikimedia Commons — Russula cyanoxantha",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Russula cyanoxantha",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "black-morel": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Morchella_elata_Spitzmorchel_Morchella_conica.jpg/960px-Morchella_elata_Spitzmorchel_Morchella_conica.jpg",
    "imageCredit": "Wikimedia Commons — Morchella elata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella%20elata%20Spitzmorchel%20Morchella%20conica.jpg?width=960",
        "credit": "Wikimedia Commons — Morchella elata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morelasci.jpg?width=960",
        "credit": "Wikimedia Commons — Morchella elata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "california-chanterelle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Cantharellus_californicus_81770.jpg/960px-Cantharellus_californicus_81770.jpg",
    "imageCredit": "Wikimedia Commons — Cantharellus californicus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cantharellus%20californicus%2080866.jpg?width=960",
        "credit": "Wikimedia Commons — Cantharellus californicus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cantharellus%20californicus%2081770.jpg?width=960",
        "credit": "Wikimedia Commons — Cantharellus californicus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "blue-chanterelle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Polyozellus_multiplex_-Haida_Guaii.jpg/960px-Polyozellus_multiplex_-Haida_Guaii.jpg",
    "imageCredit": "Wikimedia Commons — Polyozellus multiplex",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Abies%20lasiocarpa%207458.jpg?width=960",
        "credit": "Wikimedia Commons — Polyozellus multiplex",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Craterellus%20cornucopiodes%2012457.jpg?width=960",
        "credit": "Wikimedia Commons — Polyozellus multiplex",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "butter-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Butyriboletus_persolidus_69469.jpg/960px-Butyriboletus_persolidus_69469.jpg",
    "imageCredit": "Wikimedia Commons — Butyriboletus persolidus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Butyriboletus%20persolidus%2069469.jpg?width=960",
        "credit": "Wikimedia Commons — Butyriboletus persolidus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Maronenr%C3%B6hrling-1.jpg?width=960",
        "credit": "Wikimedia Commons — Butyriboletus persolidus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "bay-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Boletus_badius_JPG1.jpg/960px-Boletus_badius_JPG1.jpg",
    "imageCredit": "Wikimedia Commons — Imleria badia",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2007-07-14%20Imleria%20badia%202.jpg?width=960",
        "credit": "Wikimedia Commons — Imleria badia",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus%20badius%205052175998%20df099ccc79%20b%20cropped.jpg?width=960",
        "credit": "Wikimedia Commons — Imleria badia",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "cracked-cap-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Xerocomellus_chrysenteron28.jpg/960px-Xerocomellus_chrysenteron28.jpg",
    "imageCredit": "Wikimedia Commons — Xerocomellus chrysenteron",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bol.chrys.jpg?width=960",
        "credit": "Wikimedia Commons — Xerocomellus chrysenteron",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus%20chrysenteron%20(Red%20Cracking%20Bolete).JPG?width=960",
        "credit": "Wikimedia Commons — Xerocomellus chrysenteron",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "aspen-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Leccinum_insigne_98865.jpg/960px-Leccinum_insigne_98865.jpg",
    "imageCredit": "Wikimedia Commons — Leccinum insigne",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum%20insigne%2098865.jpg?width=960",
        "credit": "Wikimedia Commons — Leccinum insigne",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Maronenr%C3%B6hrling-1.jpg?width=960",
        "credit": "Wikimedia Commons — Leccinum insigne",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "manzanita-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Leccinum_manzanitae_29496_crop.jpg/960px-Leccinum_manzanitae_29496_crop.jpg",
    "imageCredit": "Wikimedia Commons — Leccinum manzanitae",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Leccinum_manzanitae_29496_crop.jpg",
        "credit": "Wikimedia Commons — Leccinum manzanitae",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum%20manzanitae%20126166.jpg?width=960",
        "credit": "Wikimedia Commons — Leccinum manzanitae",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "conifer-chicken": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Laetiporus_conifericola_306.jpg/960px-Laetiporus_conifericola_306.jpg",
    "imageCredit": "Wikimedia Commons — Laetiporus conifericola",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Laetiporus%20conifericola%20306.jpg?width=960",
        "credit": "Wikimedia Commons — Laetiporus conifericola",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Laetiporus_conifericola_6037.JPG/960px-Laetiporus_conifericola_6037.JPG",
        "credit": "Wikimedia Commons — Laetiporus conifericola",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "early-morel": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Morchella_rufobrunnea_154543.jpg/960px-Morchella_rufobrunnea_154543.jpg",
    "imageCredit": "Wikimedia Commons — Morchella rufobrunnea",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella%20rufobrunnea%2011174.jpg?width=960",
        "credit": "Wikimedia Commons — Morchella rufobrunnea",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella%20rufobrunnea%20154543.jpg?width=960",
        "credit": "Wikimedia Commons — Morchella rufobrunnea",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "half-free-morel": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Morchella_punctipes_205457.jpg/960px-Morchella_punctipes_205457.jpg",
    "imageCredit": "Wikimedia Commons — Morchella punctipes",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella%20punctipes%20205457.jpg?width=960",
        "credit": "Wikimedia Commons — Morchella punctipes",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Caution.png?width=960",
        "credit": "Wikimedia Commons — Morchella punctipes",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "yellow-morel": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Morchella_americana_closer.JPG/960px-Morchella_americana_closer.JPG",
    "imageCredit": "Wikimedia Commons — Morchella americana",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella%20americana%20closer.JPG?width=960",
        "credit": "Wikimedia Commons — Morchella americana",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Morchella_americana_76797711.jpg/960px-Morchella_americana_76797711.jpg",
        "credit": "Wikimedia Commons — Morchella americana",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "crown-coral": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Artomyces_pyxidatus.jpg/960px-Artomyces_pyxidatus.jpg",
    "imageCredit": "Wikimedia Commons — Artomyces pyxidatus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Artomyces%20pyxidatus.jpg?width=960",
        "credit": "Wikimedia Commons — Artomyces pyxidatus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mushroom-IMG%203304.JPG?width=960",
        "credit": "Wikimedia Commons — Artomyces pyxidatus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "golden-coral": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/2012-09-03_Ramaria_aurea_crop.jpg/960px-2012-09-03_Ramaria_aurea_crop.jpg",
    "imageCredit": "Wikimedia Commons — Ramaria aurea",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2012-09-03%20Ramaria%20aurea%20crop.jpg?width=960",
        "credit": "Wikimedia Commons — Ramaria aurea",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Schweinsohr-1.jpg?width=960",
        "credit": "Wikimedia Commons — Ramaria aurea",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "orange-peel-fungus": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Aleuria_aurantia_%28Orange_Peel_Fungus%29.JPG/960px-Aleuria_aurantia_%28Orange_Peel_Fungus%29.JPG",
    "imageCredit": "Wikimedia Commons — Aleuria aurantia",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1865%20Disciotis%20venosa.jpg?width=960",
        "credit": "Wikimedia Commons — Aleuria aurantia",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aleuria%20aurantia%201.jpg?width=960",
        "credit": "Wikimedia Commons — Aleuria aurantia",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "fried-chicken-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Lyophyllum_decastes_071012.jpg/960px-Lyophyllum_decastes_071012.jpg",
    "imageCredit": "Wikimedia Commons — Lyophyllum decastes",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Lyophyllum%20decastes%20071012.jpg?width=960",
        "credit": "Wikimedia Commons — Lyophyllum decastes",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mushroom%20(PSF).png?width=960",
        "credit": "Wikimedia Commons — Lyophyllum decastes",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "brick-cap": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/HypholomaSublateritium.jpg/960px-HypholomaSublateritium.jpg",
    "imageCredit": "Wikimedia Commons — Hypholoma lateritium",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/HypholomaSublateritium.jpg?width=960",
        "credit": "Wikimedia Commons — Hypholoma lateritium",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hypholoma%20Lateritium%20Growing%20on%20Fallen%20Tree%20Stump.jpg?width=960",
        "credit": "Wikimedia Commons — Hypholoma lateritium",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "shingled-hedgehog": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Habichtspilz-Sarcodon-imbricatus.jpg/960px-Habichtspilz-Sarcodon-imbricatus.jpg",
    "imageCredit": "Wikimedia Commons — Sarcodon imbricatus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20short%20day%20trip%20to%20the%20near%20alpine%20(2200m)%20area%20of%20Mt%20Baldy%20E%20of%20Little%20Fort%2C%20BC...here%20be%20a%20large%20assortment%20of%20things%20fungii%20and%20smaller%3F%3F...%20(28757770376).jpg?width=960",
        "credit": "Wikimedia Commons — Sarcodon imbricatus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Habichtspilz-Sarcodon-imbricatus.jpg?width=960",
        "credit": "Wikimedia Commons — Sarcodon imbricatus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "terracotta-hedgehog": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Hydnum_rufescens_20070927w.JPG/960px-Hydnum_rufescens_20070927w.JPG",
    "imageCredit": "Wikimedia Commons — Hydnum rufescens",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Hydnum_rufescens.jpg/960px-Hydnum_rufescens.jpg",
        "credit": "Wikimedia Commons — Hydnum rufescens",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Hydnum_rufescens_2.jpg/960px-Hydnum_rufescens_2.jpg",
        "credit": "Wikimedia Commons — Hydnum rufescens",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "pear-shaped-puffball": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Lycoperdon_pyriforme_Sasata_scale.jpg/960px-Lycoperdon_pyriforme_Sasata_scale.jpg",
    "imageCredit": "Wikimedia Commons — Apioperdon pyriforme",
    "additionalImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Apioperdon_pyriforme_103323376.jpg/960px-Apioperdon_pyriforme_103323376.jpg",
        "credit": "Wikimedia Commons — Apioperdon pyriforme",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Apioperdon_pyriforme_103323405.jpg/960px-Apioperdon_pyriforme_103323405.jpg",
        "credit": "Wikimedia Commons — Apioperdon pyriforme",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "horse-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Pieczarka_polowa_vongrzanka.JPG/960px-Pieczarka_polowa_vongrzanka.JPG",
    "imageCredit": "Wikimedia Commons — Agaricus arvensis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/A.%20arvensis%20showing%20cogwheel.jpg?width=960",
        "credit": "Wikimedia Commons — Agaricus arvensis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Agaricus arvensis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "poplar-mushroom": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Agrocybe_aegerita.jpg/960px-Agrocybe_aegerita.jpg",
    "imageCredit": "Wikimedia Commons — Cyclocybe aegerita",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agrocybe%20aegerita.jpg?width=960",
        "credit": "Wikimedia Commons — Cyclocybe aegerita",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Agrocybe%20aegerita%2022.jpg?width=960",
        "credit": "Wikimedia Commons — Cyclocybe aegerita",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "elm-oyster": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Hypsizygus_ulmarius_%28Bull.%29_Redhead_383230.jpg/960px-Hypsizygus_ulmarius_%28Bull.%29_Redhead_383230.jpg",
    "imageCredit": "Wikimedia Commons — Hypsizygus ulmarius",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Annual%20report%20of%20the%20State%20Botanist%20of%20the%20State%20of%20New%20York%22%20(1889-1897.)%20(19179965158).jpg?width=960",
        "credit": "Wikimedia Commons — Hypsizygus ulmarius",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bresadola%20-%20Pleurotus%20ulmarius%20und%20porrigens.png?width=960",
        "credit": "Wikimedia Commons — Hypsizygus ulmarius",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "man-on-horseback": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/2018-11-10_Tricholoma_murrillianum_Singer_959693.jpg/960px-2018-11-10_Tricholoma_murrillianum_Singer_959693.jpg",
    "imageCredit": "Wikimedia Commons — Tricholoma murrillianum",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2018-11-10%20Tricholoma%20murrillianum%20Singer%20959693.jpg?width=960",
        "credit": "Wikimedia Commons — Tricholoma murrillianum",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Choice.png?width=960",
        "credit": "Wikimedia Commons — Tricholoma murrillianum",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "painted-suillus": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Suillus_lakei_50606.jpg/960px-Suillus_lakei_50606.jpg",
    "imageCredit": "Wikimedia Commons — Suillus lakei",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Boletinus%20cavipes.JPG?width=960",
        "credit": "Wikimedia Commons — Suillus lakei",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Edible.png?width=960",
        "credit": "Wikimedia Commons — Suillus lakei",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "larch-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Suill.grev.jpg/960px-Suill.grev.jpg",
    "imageCredit": "Wikimedia Commons — Suillus grevillei",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mycomorphbox%20Edible.png?width=960",
        "credit": "Wikimedia Commons — Suillus grevillei",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Suillus_grevillei.jpg/960px-Suillus_grevillei.jpg",
        "credit": "Wikimedia Commons — Suillus grevillei",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "amethyst-deceiver": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Laccaria_amethysteo-occidentalis_%2832942930552%29.jpg/960px-Laccaria_amethysteo-occidentalis_%2832942930552%29.jpg",
    "imageCredit": "Wikimedia Commons — Laccaria amethysteo-occidentalis",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Laccaria%20amethysteo-occidentalis%20(32942930552).jpg?width=960",
        "credit": "Wikimedia Commons — Laccaria amethysteo-occidentalis",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mushroom%20(PSF).png?width=960",
        "credit": "Wikimedia Commons — Laccaria amethysteo-occidentalis",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "common-deceiver": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Lacc.lacc.jpg/960px-Lacc.lacc.jpg",
    "imageCredit": "Wikimedia Commons — Laccaria laccata",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Gewone%20fopzwam%20(Laccaria%20laccata).%20Locatie%2C%20Paddenstoelenreservaat.%2014-10-2025.%20(d.j.b).jpg?width=960",
        "credit": "Wikimedia Commons — Laccaria laccata",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustrations%20of%20British%20Fungi%20(Hymenomycetes)%2C%20to%20serve%20as%20an%20atlas%20to%20the%20%22Handbook%20of%20British%20Fungi%22%20(Pl.%20139)%20(6055652565).jpg?width=960",
        "credit": "Wikimedia Commons — Laccaria laccata",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "white-elfin-saddle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/0_Helvella_crispa_-_Havr%C3%A9_%281%29.JPG/960px-0_Helvella_crispa_-_Havr%C3%A9_%281%29.JPG",
    "imageCredit": "Wikimedia Commons — Helvella crispa",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/0%20Helvella%20crispa%20-%20Havr%C3%A9%20(1).JPG?width=960",
        "credit": "Wikimedia Commons — Helvella crispa",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bresadola%20-%20Helvella%20crispa.png?width=960",
        "credit": "Wikimedia Commons — Helvella crispa",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "western-elfin-saddle": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Helvella_vespertina_316605.jpg/960px-Helvella_vespertina_316605.jpg",
    "imageCredit": "Wikimedia Commons — Helvella vespertina",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1865%20Disciotis%20venosa.jpg?width=960",
        "credit": "Wikimedia Commons — Helvella vespertina",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Helvella%20vespertina%20316605.jpg?width=960",
        "credit": "Wikimedia Commons — Helvella vespertina",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  },
  "ruby-bolete": {
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Hortiboletus_rubellus_2016_G1.jpg/960px-Hortiboletus_rubellus_2016_G1.jpg",
    "imageCredit": "Wikimedia Commons — Hortiboletus rubellus",
    "additionalImages": [
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Hortiboletus%20rubellus%202016%20G1.jpg?width=960",
        "credit": "Wikimedia Commons — Hortiboletus rubellus",
        "caption": "Habitat & growth habit"
      },
      {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Karl%20Johanssvamp%2C%20Iduns%20kokbok.png?width=960",
        "credit": "Wikimedia Commons — Hortiboletus rubellus",
        "caption": "Flowers, fruit, or ID detail"
      }
    ]
  }
};
