import type { PlantEntry } from './types';
import { wikiGallery } from './plantGallery';

/** Edible wild mushrooms of Oregon and Northern California — full ID + safety entries. */
export const EDIBLE_MUSHROOM_LIBRARY: PlantEntry[] = [
  {
    id: 'white-chanterelle',
    commonName: 'White Chanterelle',
    scientificName: 'Cantharellus subalbidus',
    alsoKnownAs: ['White gold chanterelle'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'ca-sierra-foothills', 'or-cascades', 'or-rogue'],
    habitat:
      'Mature conifer forests — Douglas-fir and hemlock from Oregon Cascades through the Klamath-Siskiyou and north-coast California.',
    identification:
      'Pale cream to buff funnel cap with false forked ridges (not true gills). Fruity apricot scent. Stems often stocky and off-center.',
    lookalikes: [
      'Golden chanterelle — more orange; same false gill rule.',
      'Jack-o-lantern (Omphalotus) — true gills, grows on wood in clusters, bioluminescent — TOXIC.',
      'False chanterelle (Hygrophoropsis) — thin true gills, no apricot smell.',
    ],
    edibleNotes: 'Choice edible — firmer and nuttier than golden chanterelle. Dries and sautés beautifully.',
    preparation: 'Cook thoroughly. Brush clean; avoid waterlogging.',
    harvestSeason: 'Fall after first heavy rains — October–December.',
    safetyWarnings: ['Confirm false gills vs. true gills every time.', 'Never eat raw.'],
    ...wikiGallery(
      ['Cantharellus subalbidus 47469.jpg', 'Cantharellus subalbidus.jpg', 'Cantharellus subalbidus 2.jpg'],
      'Wikimedia Commons — Cantharellus subalbidus',
    ),
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cantharellus_subalbidus' },
      { label: 'PSMS', url: 'https://www.psms.org/' },
    ],
  },
  {
    id: 'yellowfoot-chanterelle',
    commonName: 'Yellowfoot / Winter Chanterelle',
    scientificName: 'Craterellus tubaeformis',
    alsoKnownAs: ['Funnel chanterelle', 'Yellow leg'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Mossy conifer logs and wet needle litter — late-season coast and valley forests.',
    identification:
      'Small brownish funnel cap with yellow-orange hollow stem. False gills on cap underside. Often in large troops on rotting wood.',
    lookalikes: [
      'False chanterelle — brighter orange, not hollow stem.',
      'Toxic small brown gilled mushrooms on wood — always verify hollow stem + false ridges.',
    ],
    edibleNotes: 'Excellent in soups and stews — holds texture when simmered. Less fruity than golden chanterelle.',
    preparation: 'Simmer in broth or sauté; pairs with cream and potatoes.',
    harvestSeason: 'Late fall through winter — November–February on wet coast.',
    safetyWarnings: ['Small size makes ID harder — use magnifier on gill structure.'],
    ...wikiGallery(
      ['Craterellus tubaeformis 584995.jpg', 'Craterellus tubaeformis.jpg', 'Craterellus tubaeformis (8358645676).jpg'],
      'Wikimedia Commons — Craterellus tubaeformis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Craterellus_tubaeformis' }],
  },
  {
    id: 'black-trumpet',
    commonName: 'Black Trumpet',
    scientificName: 'Craterellus cornucopioides',
    alsoKnownAs: ['Horn of plenty', 'Trumpet of death (misnomer — edible)'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-coast', 'or-willamette'],
    habitat: 'Mossy hardwood and mixed forest floors — often near oak and madrone in northerly California foothills.',
    identification:
      'Thin blackish-gray vase- or trumpet-shaped cap with smooth underside (no gills). Fragile, papery flesh.',
    lookalikes: [
      'Very few lookalikes when trumpet shape confirmed — avoid any with true gills.',
      'Urnula craterium (devil’s urn) — spring cup fungus on wood; inedible but different season/habitat.',
    ],
    edibleNotes: 'Intense earthy flavor — prized dried. Excellent in sauces and risotto.',
    preparation: 'Dry whole or sauté; rehydrate dried trumpets in warm water.',
    harvestSeason: 'Fall and winter rains — October–January.',
    safetyWarnings: ['Hard to spot against leaf litter — go slow and use basket.'],
    ...wikiGallery(
      ['Craterellus cornucopioides 1.jpg', 'Craterellus cornucopioides.jpg', 'Craterellus cornucopioides (8358645676).jpg'],
      'Wikimedia Commons — Craterellus cornucopioides',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Craterellus_cornucopioides' }],
  },
  {
    id: 'king-bolete',
    commonName: 'King Bolete / Porcini',
    scientificName: 'Boletus edulis',
    alsoKnownAs: ['Cep', 'Penny bun'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake', 'or-cascades', 'or-klamath', 'or-rogue'],
    habitat:
      'Under pine and fir — eastern Oregon Cascades, Klamath-Silver Lake country, Mt. Shasta, and Sierra pine belts near Placerville.',
    identification:
      'Large brown bun cap, thick white stem with fine reticulation (net pattern). Pores under cap white then yellow-green — NOT red/blue staining badly.',
    lookalikes: [
      'Bitter bolete (Caloboletus) — intensely bitter; blue-staining pores.',
      'Satan’s bolete (Rubroboletus) — red pores on mature cap — TOXIC.',
      'False king bolete — learn pore color and reticulation with a mentor.',
    ],
    edibleNotes: 'Premier gourmet mushroom — nutty when young, best dried for year-round use.',
    preparation: 'Slice and dry, or grill thick slices. Remove wormy sections.',
    harvestSeason: 'Early fall — September–November after rain under pines.',
    safetyWarnings: [
      'Bolete rule: avoid red-pored or rapid blue-bruising species unless expert ID.',
      'Cut every cap to check for maggots.',
    ],
    ...wikiGallery(
      ['Boletus edulis Edible.jpg', 'Boletus edulis 1.jpg', 'Boletus edulis mushroom.jpg'],
      'Wikimedia Commons — Boletus edulis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Boletus_edulis' }],
  },
  {
    id: 'spring-king-bolete',
    commonName: 'Spring King Bolete',
    scientificName: 'Boletus rex-veris',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake', 'or-klamath', 'or-rogue'],
    habitat: 'Ponderosa pine and mixed conifer — spring snowmelt zones from Rogue Valley to Modoc and Sierra foothills.',
    identification:
      'Large brown cap, stout stem with reticulation. Spring fruiting. Pores yellow. Similar to king bolete but earlier season.',
    lookalikes: ['Bitter boletes — taste test tiny raw nibble at tip of cap (spit out) only if experienced.', 'Satan’s bolete — red pores.'],
    edibleNotes: 'Excellent spring porcini relative — firmer texture than fall king.',
    preparation: 'Grill or dry. Check for larvae when cutting.',
    harvestSeason: 'April–June at elevation after snowmelt.',
    safetyWarnings: ['Spring boletes still require full pore and staining checks.'],
    ...wikiGallery(
      ['Boletus rex-veris 1.jpg', 'Boletus rex-veris.jpg', 'Boletus rex-veris mushroom.jpg'],
      'Wikimedia Commons — Boletus rex-veris',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Boletus_rex-veris' }],
  },
  {
    id: 'admirable-bolete',
    commonName: 'Admirable Bolete',
    scientificName: 'Aureoboletus mirabilis',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On rotting conifer logs and stumps — classic Pacific Northwest log bolete.',
    identification:
      'Velvety brown cap. Yellow pores bruise blue. Grows directly from wood (not soil). Stem often curved.',
    lookalikes: [
      'Other blue-staining boletes on wood — some bitter; admirable is considered good when young.',
      'Conifer chicken of the woods grows on same logs — bright orange shelves.',
    ],
    edibleNotes: 'Oregon coast specialty on old-growth logs — nutty when young and firm.',
    preparation: 'Sauté young specimens; discard soft or wormy flesh.',
    harvestSeason: 'Fall — September–November.',
    safetyWarnings: ['Only young firm caps — becomes buggy and soft quickly.'],
    ...wikiGallery(
      ['Aureoboletus mirabilis.jpg', 'Boletus mirabilis.jpg', 'Aureoboletus mirabilis 2.jpg'],
      'Wikimedia Commons — Aureoboletus mirabilis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Aureoboletus_mirabilis' }],
  },
  {
    id: 'zellers-bolete',
    commonName: "Zeller's Bolete",
    scientificName: 'Xerocomellus zelleri',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Mixed conifer-hardwood forest floor — common in Douglas-fir and hemlock woods.',
    identification:
      'Dark brown cracked cap, yellow pores that bruise blue, red-stained base of stem. Medium-sized bolete.',
    lookalikes: ['Other small boletes — use field guides for pore color and cap cracking pattern.'],
    edibleNotes: 'Solid table mushroom when young — earthy and mild.',
    preparation: 'Cook thoroughly; remove slimy cap cuticle if preferred.',
    harvestSeason: 'Fall rains — October–December.',
    safetyWarnings: ['Blue bruising is normal for this species — do not confuse with red-pored toxic boletes.'],
    ...wikiGallery(
      ['Xerocomellus zelleri.jpg', 'Boletus zelleri 1.jpg', 'Xerocomellus zelleri 2.jpg'],
      'Wikimedia Commons — Xerocomellus zelleri',
    ),
    externalLinks: [{ label: 'Mushroom Observer', url: 'https://mushroomobserver.org/' }],
  },
  {
    id: 'chicken-of-the-woods',
    commonName: 'Chicken of the Woods',
    scientificName: 'Laetiporus gilbertsonii',
    alsoKnownAs: ['Sulfur shelf'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On living or dead hardwoods and conifers — oak, eucalyptus, and fir stumps.',
    identification:
      'Bright orange-yellow overlapping shelf brackets. Soft suede-like surface when young. No gills — porous yellow underside.',
    lookalikes: [
      'Jack-o-lantern (Omphalotus) — grows on wood but has GILLS and bioluminescence — TOXIC.',
      'Dryad’s saddle — scaly brown cap, different texture.',
    ],
    edibleNotes: 'Meaty texture — shreds like chicken. Only eat young tender margins.',
    preparation: 'Sauté, bread and fry, or simmer in curry. Avoid alcohol with some individuals (rare sensitivity).',
    harvestSeason: 'Spring through fall on fresh growth — May–October.',
    safetyWarnings: [
      'Never eat growing on eucalyptus or locust without caution — some report reactions.',
      'Only young soft orange edges — woody older parts cause GI upset.',
    ],
    ...wikiGallery(
      ['Laetiporus sulphureus USDA.jpg', 'Laetiporus gilbertsonii.jpg', 'Chicken of the woods.jpg'],
      'Wikimedia Commons — Laetiporus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Laetiporus_gilbertsonii' }],
  },
  {
    id: 'lobster-mushroom',
    commonName: 'Lobster Mushroom',
    scientificName: 'Hypomyces lactifluorum',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Parasite on russulas and lactarius — forest floor and trails in mixed woods.',
    identification:
      'Bright orange-red bumpy crust completely covering host mushroom. No visible gills — looks like sculpted seafood.',
    lookalikes: [
      'Any orange mushroom without confirmed parasite crust on a host — must be Hypomyces over white mushroom host.',
      'Do not confuse with unrelated orange gilled species.',
    ],
    edibleNotes: 'Dense seafood-like texture — excellent in chowder and pasta.',
    preparation: 'Cook thoroughly; dice and sauté. Host identity obscured — only collect pristine specimens.',
    harvestSeason: 'Summer through fall — July–October.',
    safetyWarnings: ['If parasite not complete or host unknown, skip.', 'Cook well.'],
    ...wikiGallery(
      ['Hypomyces lactifluorum 1.jpg', 'Hypomyces lactifluorum.jpg', 'Lobster mushroom.jpg'],
      'Wikimedia Commons — Hypomyces lactifluorum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hypomyces_lactifluorum' }],
  },
  {
    id: 'hedgehog-mushroom',
    commonName: 'Hedgehog Mushroom',
    scientificName: 'Hydnum repandum',
    alsoKnownAs: ['Sweet tooth'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Mossy conifer and mixed woods — often near chanterelle habitat.',
    identification:
      'Pale orange-tan cap with TEETH (spines) underneath instead of gills or pores. Fruity smell when fresh.',
    lookalikes: [
      'Toothed hedgehog relatives — Hydnum umbilicatum smaller with central depression.',
      'No deadly lookalikes with teeth under cap in PNW — still verify every collection.',
    ],
    edibleNotes: 'Mild sweet flavor — excellent sautéed with butter.',
    preparation: 'Brush clean; cook until golden. Holds shape well.',
    harvestSeason: 'Fall — October–December.',
    safetyWarnings: ['Teeth, not gills — key ID feature.'],
    ...wikiGallery(
      ['Hydnum repandum G4.jpg', 'Hydnum repandum 1.jpg', 'Hydnum repandum.jpg'],
      'Wikimedia Commons — Hydnum repandum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hydnum_repandum' }],
  },
  {
    id: 'lions-mane',
    commonName: "Lion's Mane",
    scientificName: 'Hericium erinaceus',
    alsoKnownAs: ['Bearded tooth', 'Pom pom mushroom'],
    uses: 'both',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On hardwood logs and wounds — bigleaf maple, oak, and beech in northerly California.',
    identification:
      'White cascading icicle-like teeth hanging from a single attachment point. No cap. Looks like a frozen waterfall.',
    lookalikes: [
      'Other Hericium species — all considered edible in PNW when fresh and white.',
      'Do not confuse with polypore brackets — Hericium is tooth-bearing soft mass.',
    ],
    edibleNotes: 'Crab-like texture when sautéed — gourmet and medicinal (nerve support studies).',
    medicinalNotes: 'Traditional use for cognitive and nerve support — lion’s mane widely studied.',
    preparation: 'Slice steaks and pan-fry until edges crisp. Also dual-extract for tincture.',
    harvestSeason: 'Fall on hardwood logs — September–November.',
    safetyWarnings: ['Only fresh white specimens — yellow/brown indicates decay.'],
    ...wikiGallery(
      ['Hericium erinaceus 1.jpg', 'Hericium erinaceus.jpg', 'Lions mane mushroom.jpg'],
      'Wikimedia Commons — Hericium erinaceus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hericium_erinaceus' }],
  },
  {
    id: 'bears-head-hericium',
    commonName: "Bear's Head Tooth",
    scientificName: 'Hericium abietis',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast'],
    habitat: 'On conifer logs and stumps — fir and hemlock in coastal and montane forests.',
    identification:
      'Branching white coral-like teeth — more branched than lion’s mane. Grows on conifers.',
    lookalikes: ['Other Hericium — generally edible group in our region.'],
    edibleNotes: 'Similar to lion’s mane — excellent texture. PNW conifer specialist.',
    preparation: 'Sauté or simmer in soup. Harvest young white clusters.',
    harvestSeason: 'Late summer through fall on logs.',
    safetyWarnings: ['Confirm growth on wood and tooth structure.'],
    ...wikiGallery(
      ['Hericium abietis 1.jpg', 'Hericium abietis.jpg', 'Hericium americanum.jpg'],
      'Wikimedia Commons — Hericium abietis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hericium_abietis' }],
  },
  {
    id: 'oyster-mushroom',
    commonName: 'Oyster Mushroom',
    scientificName: 'Pleurotus pulmonarius',
    alsoKnownAs: ['Phoenix oyster', 'Indian oyster'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On dead hardwood and cottonwood — logs, stumps, and standing snags.',
    identification:
      'Shelf-like caps growing in overlapping clusters. White gills running down short stem. Lilac-gray spore print.',
    lookalikes: [
      'Angel wings (Pleurocybella porrigens) on conifer — historically eaten but linked to fatalities in Japan — AVOID on hemlock.',
      'Omphalotus — bright orange, grows on wood, bioluminescent — TOXIC.',
    ],
    edibleNotes: 'Mild anise-like flavor — farmed and wild. Great stir-fried.',
    preparation: 'Cook on high heat until edges crisp. Discard tough stems if desired.',
    harvestSeason: 'Year-round on logs; peak fall and spring flushes.',
    safetyWarnings: [
      'NEVER collect white gilled mushrooms on conifer as “oysters” — angel wings risk.',
      'Stick to hardwood-hosted clusters with lilac spore print.',
    ],
    ...wikiGallery(
      ['Pleurotus pulmonarius 1.jpg', 'Pleurotus pulmonarius.jpg', 'Oyster mushroom.jpg'],
      'Wikimedia Commons — Pleurotus pulmonarius',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Pleurotus_pulmonarius' }],
  },
  {
    id: 'western-giant-puffball',
    commonName: 'Western Giant Puffball',
    scientificName: 'Calvatia booniana',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-shasta', 'ca-silver-lake', 'or-east', 'or-klamath'],
    habitat: 'Open sagebrush-steppe and dry grassland — eastern Oregon, Modoc, and Great Basin fringes of northerly California.',
    identification:
      'Huge white ball on ground — soccer-ball size possible. Interior solid white when young. No stem or gills.',
    lookalikes: [
      'Death cap button stage (Amanita) — MUST slice vertically — amanita has forming cap inside.',
      'Earthball (Scleroderma) — dark interior when young — TOXIC.',
    ],
    edibleNotes: 'Only edible when interior pure white like marshmallow. Earthy slices fried like eggplant.',
    preparation: 'Peel skin; slice and fry breaded cutlets. Never eat if interior yellowing.',
    harvestSeason: 'Late summer after thunderstorms — August–September in high desert.',
    safetyWarnings: [
      'ALWAYS cut in half — if any silhouette of cap/stem inside, discard (Amanita button).',
      'Yellow-green interior = too mature — do not eat.',
    ],
    ...wikiGallery(
      ['Calvatia booniana 1.jpg', 'Calvatia booniana.jpg', 'Giant puffball.jpg'],
      'Wikimedia Commons — Calvatia booniana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Calvatia_booniana' }],
  },
  {
    id: 'gem-studded-puffball',
    commonName: 'Gem-Studded Puffball',
    scientificName: 'Lycoperdon perlatum',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Wood chip trails, forest edges, and disturbed soil — very common.',
    identification:
      'Small white pear-shaped puffball with conical spines that rub off. Interior white when young. Grows on ground.',
    lookalikes: [
      'Young earthballs — interior turns dark early; cut every puffball in half.',
      'Amanita egg stage — shows cap forming inside when sliced.',
    ],
    edibleNotes: 'Snack-sized — sauté whole young specimens or add to breakfast scrambles.',
    preparation: 'Only pure white interior. Peel optional.',
    harvestSeason: 'Summer through fall — widespread.',
    safetyWarnings: ['Slice vertically before eating any puffball.'],
    ...wikiGallery(
      ['Lycoperdon perlatum 1.jpg', 'Lycoperdon perlatum.jpg', 'Common puffball.jpg'],
      'Wikimedia Commons — Lycoperdon perlatum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lycoperdon_perlatum' }],
  },
  {
    id: 'shaggy-mane',
    commonName: 'Shaggy Mane',
    scientificName: 'Coprinus comatus',
    alsoKnownAs: ['Lawyer’s wig', 'Inky cap'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Disturbed ground — gravel roads, lawns, compost, and trail edges after rain.',
    identification:
      'Tall cylindrical white cap with shaggy scales. Deliquesces to black ink when old. Free white gills. Bulbous base.',
    lookalikes: [
      'Other inky caps — some with alcohol interaction; shaggy mane is the safest well-known species.',
      'Green-spored parasol (Chlorophyllum) — much larger, green spores — TOXIC.',
    ],
    edibleNotes: 'Delicate flavor — must cook same day while caps still white.',
    preparation: 'Sauté quickly after harvest. Do not combine with alcohol (related species issue — caution).',
    harvestSeason: 'Spring and fall flushes after rain.',
    safetyWarnings: [
      'Harvest only fresh white specimens — black inky stage is past prime.',
      'Some people avoid all inky caps with alcohol.',
    ],
    ...wikiGallery(
      ['Coprinus comatus 1.jpg', 'Coprinus comatus.jpg', 'Shaggy mane mushroom.jpg'],
      'Wikimedia Commons — Coprinus comatus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Coprinus_comatus' }],
  },
  {
    id: 'matsutake',
    commonName: 'Matsutake',
    scientificName: 'Tricholoma murrillianum',
    alsoKnownAs: ['Pine mushroom'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake', 'or-cascades', 'or-klamath'],
    habitat: 'Under ponderosa pine and Douglas-fir — duff buried under needle litter. Eastern Oregon to Sierra.',
    identification:
      'White to brown cap with cottony veil remnants. Spicy cinnamon-cedar aroma when fresh. White gills. Stains brown when handled.',
    lookalikes: [
      'Deadly galerina — small brown on wood — TOXIC.',
      'Catathelasma — larger, bitter, no matsutake aroma.',
      'Amanita species — always excavate base and check for volva.',
    ],
    edibleNotes: 'Highly prized in Japanese cuisine — aroma is the delicacy. Rice and clear broth showcase flavor.',
    preparation: 'Gently clean — do not overwash aroma away. Slice and simmer in rice or soup.',
    harvestSeason: 'Fall after first cools — September–November under pines.',
    safetyWarnings: [
      'High-stakes ID — go with experienced matsutake forager first seasons.',
      'Never rake duff excessively — ecological and legal concerns on public land.',
    ],
    ...wikiGallery(
      ['Tricholoma matsutake 1.jpg', 'Tricholoma murrillianum.jpg', 'Matsutake mushroom.jpg'],
      'Wikimedia Commons — Tricholoma murrillianum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Tricholoma_murrillianum' }],
  },
  {
    id: 'cauliflower-mushroom',
    commonName: 'Cauliflower Mushroom',
    scientificName: 'Sparassis radicata',
    alsoKnownAs: ['Western cauliflower fungus'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Base of conifers — pine and fir roots. Often partially buried.',
    identification:
      'Large brain-like or noodle-like white-yellow mass of flattened branches. No cap. Grows from ground at tree base.',
    lookalikes: [
      'Rarely confused when full size — unique cauliflower form.',
      'Some polypores at base — Sparassis is soft and fleshy.',
    ],
    edibleNotes: 'Firm noodle texture — holds up in soups and stir-fries. Can weigh several pounds.',
    preparation: 'Separate branches and wash out needles. Simmer or sauté until tender.',
    harvestSeason: 'Fall — October–November.',
    safetyWarnings: ['Clean thoroughly — traps forest debris.'],
    ...wikiGallery(
      ['Sparassis radicata 1.jpg', 'Sparassis crispa.jpg', 'Cauliflower mushroom.jpg'],
      'Wikimedia Commons — Sparassis radicata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sparassis_radicata' }],
  },
  {
    id: 'candy-cap',
    commonName: 'Candy Cap',
    scientificName: 'Lactarius rubidus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-coast'],
    habitat: 'Coastal oak-madrone and mixed hardwood duff — northern California specialty extending to Oregon coast.',
    identification:
      'Small orange-brown lactarius with brittle flesh. Milky latex when cut. Dries to maple-syrup scent.',
    lookalikes: [
      'Other small orange lactarius — candy cap aroma when dried is definitive test.',
      'Some russulas — no latex when cut.',
    ],
    edibleNotes: 'Famous for maple flavor when dried — cookies, ice cream, and syrup infusions.',
    preparation: 'Dry thoroughly to develop aroma. Grind into sugar for baking.',
    harvestSeason: 'Fall and winter — November–January on coast.',
    safetyWarnings: ['Confirm latex and maple scent when dried before culinary use.'],
    ...wikiGallery(
      ['Lactarius rubidus 1.jpg', 'Lactarius rubidus.jpg', 'Candy cap mushroom.jpg'],
      'Wikimedia Commons — Lactarius rubidus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lactarius_rubidus' }],
  },
  {
    id: 'saffron-milk-cap',
    commonName: 'Saffron Milk Cap',
    scientificName: 'Lactarius deliciosus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'or-rogue'],
    habitat: 'Under pine — especially Monterey and ponderosa pine belts in southern Oregon and California mountains.',
    identification:
      'Orange cap with darker concentric zones. Orange latex when cut. Brittle flesh. Green staining after handling.',
    lookalikes: [
      'Other orange lactarius — many require expert ID; saffron milk cap has carrot-orange latex.',
      'False saffron milk caps — learn with mentor.',
    ],
    edibleNotes: 'Popular in Mediterranean cooking — grilled or pickled. Carrot-orange latex is key.',
    preparation: 'Cook thoroughly; traditional grilling over coals.',
    harvestSeason: 'Fall under pines — October–December.',
    safetyWarnings: ['Lactarius ID is advanced — confirm latex color and pine association.'],
    ...wikiGallery(
      ['Lactarius deliciosus 1.jpg', 'Lactarius deliciosus.jpg', 'Saffron milk cap.jpg'],
      'Wikimedia Commons — Lactarius deliciosus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lactarius_deliciosus' }],
  },
  {
    id: 'shrimp-russula',
    commonName: 'Shrimp Russula',
    scientificName: 'Russula xerampelina',
    alsoKnownAs: ['Crab brittlegill'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Conifer and mixed woods — often with hemlock and fir.',
    identification:
      'Purple to wine-red cap fading with age. White gills. Stem bruises brown. Distinctive fish/shrimp odor when cooked.',
    lookalikes: [
      'Other russulas — many are toxic or acrid; shrimp russula is mild and fish-scented when cooked.',
      'Never eat raw russula — taste test acridity only with expert guidance.',
    ],
    edibleNotes: 'One of the few reliably mild russulas when cooked — shrimp aroma develops in pan.',
    preparation: 'Cook thoroughly — never raw. Discard acrid specimens.',
    harvestSeason: 'Fall — September–November.',
    safetyWarnings: [
      'Russula group is for advanced foragers — learn shrimp russula with an expert.',
      'Spit-test acridity only if trained.',
    ],
    ...wikiGallery(
      ['Russula xerampelina 1.jpg', 'Russula xerampelina.jpg', 'Shrimp russula.jpg'],
      'Wikimedia Commons — Russula xerampelina',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Russula_xerampelina' }],
  },
  {
    id: 'prince-agaricus',
    commonName: 'The Prince',
    scientificName: 'Agaricus augustus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Wood chip beds, roadsides, and forest edges — often near cedar and fir.',
    identification:
      'Large brown-scaled cap, thick stem with skirt ring. Almond or anise scent. Gills pink then brown. Not yellow-staining.',
    lookalikes: [
      'Yellow-staining agaricus (A. xanthodermus) — phenolic smell, yellow bruising — GI illness.',
      'Death angel (Amanita) — white gills when young, volva at base — DEADLY.',
    ],
    edibleNotes: 'Large meaty caps — almond aroma. Excellent grilled.',
    preparation: 'Cook until gills brown. Discard if yellow staining or phenolic smell.',
    harvestSeason: 'Summer through fall — July–October.',
    safetyWarnings: [
      'Always check for yellow bruising at stem base and amanita volva when excavating.',
      'Pink-then-brown gills, not white gills in mature specimen.',
    ],
    ...wikiGallery(
      ['Agaricus augustus 1.jpg', 'Agaricus augustus.jpg', 'The prince mushroom.jpg'],
      'Wikimedia Commons — Agaricus augustus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Agaricus_augustus' }],
  },
  {
    id: 'meadow-mushroom',
    commonName: 'Meadow Mushroom',
    scientificName: 'Agaricus campestris',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-silver-lake', 'or-cascades', 'or-coast', 'or-east', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Pastures, lawns, and grasslands after rain — not on wood.',
    identification:
      'White to brown cap, pink gills turning brown. Ring on stem. No yellow staining. Found in grass.',
    lookalikes: [
      'Destroying angel (Amanita) — white gills, volva, white cap — DEADLY in same habitat.',
      'Yellow stainer — yellow bruising and phenolic odor.',
    ],
    edibleNotes: 'Classic wild field mushroom — must be distinguished from amanita every time.',
    preparation: 'Cook thoroughly. Only from grasslands with confirmed pink-brown gill progression.',
    harvestSeason: 'Fall rains on open grass — September–November.',
    safetyWarnings: [
      'DEADLY amanita species grow in same lawns — dig entire base and check for volva.',
      'Never eat with white gills.',
    ],
    ...wikiGallery(
      ['Agaricus campestris 1.jpg', 'Agaricus campestris.jpg', 'Meadow mushroom.jpg'],
      'Wikimedia Commons — Agaricus campestris',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Agaricus_campestris' }],
  },
  {
    id: 'pheasants-back',
    commonName: "Pheasant's Back / Dryad's Saddle",
    scientificName: 'Cerioporus squamosus',
    alsoKnownAs: ['Hawk’s wing'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On dead hardwood logs and stumps — elm, maple, and cottonwood.',
    identification:
      'Large brown scaly cap resembling pheasant feathers. White porous underside. Grows on wood in spring.',
    lookalikes: [
      'Other polypores on wood — pheasant’s back has distinctive scaly cap pattern.',
      'Not a gilled mushroom.',
    ],
    edibleNotes: 'Only tender young margins edible — older tough. Watermelon-rind scent when fresh.',
    preparation: 'Slice off soft outer inch and sauté. Make broth from older parts.',
    harvestSeason: 'Spring — April–June.',
    safetyWarnings: ['Older specimens are leathery — only eat young edges.'],
    ...wikiGallery(
      ['Polyporus squamosus 1.jpg', 'Cerioporus squamosus.jpg', 'Dryads saddle.jpg'],
      'Wikimedia Commons — Cerioporus squamosus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cerioporus_squamosus' }],
  },
  {
    id: 'honey-mushroom',
    commonName: 'Honey Mushroom',
    scientificName: 'Armillaria ostoyae',
    alsoKnownAs: ['Honey fungus'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On wood and clustered at tree bases — pathogenic root rot fungus. Very common.',
    identification:
      'Honey-brown cap in dense clusters on wood. Stem with black rhizomorphs. White spore print. Partial ring on stem.',
    lookalikes: [
      'Deadly galerina — smaller brown on wood — TOXIC — learn spore print and ring differences.',
      'Jack-o-lantern — orange, gilled, bioluminescent.',
    ],
    edibleNotes: 'Edible when well-cooked — some people have sensitivity. Bulky harvests possible.',
    preparation: 'Boil or parboil 10+ minutes then sauté — never undercooked. Try small amount first time.',
    harvestSeason: 'Fall clusters — October–November.',
    safetyWarnings: [
      'Must be well-cooked — raw or undercooked causes GI upset.',
      'Some individuals allergic — first taste small portion.',
      'Confirm not Galerina — deadly on same substrate.',
    ],
    ...wikiGallery(
      ['Armillaria ostoyae 1.jpg', 'Armillaria mellea.jpg', 'Honey mushroom cluster.jpg'],
      'Wikimedia Commons — Armillaria',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Armillaria_ostoyae' }],
  },
  {
    id: 'blewit',
    commonName: 'Wood Blewit',
    scientificName: 'Lepista nuda',
    alsoKnownAs: ['Clitocybe nuda'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Compost piles, leaf litter, and woody debris — often in rings.',
    identification:
      'Lilac-purple cap and gills fading to tan. Spore print pinkish-buff. No ring on stem. Fruity floral smell.',
    lookalikes: [
      'Purple cortinarius — rusty spores and cortina web on young gills — TOXIC.',
      'Other purple mushrooms — spore print and lack of cortina critical.',
    ],
    edibleNotes: 'Choice edible when purple — excellent flavor after cooking.',
    preparation: 'Cook thoroughly — do not eat raw. Beautiful in cream sauces.',
    harvestSeason: 'Late fall after first frosts — October–December.',
    safetyWarnings: ['Always spore print and rule out Cortinarius before eating.'],
    ...wikiGallery(
      ['Lepista nuda 1.jpg', 'Lepista nuda.jpg', 'Wood blewit.jpg'],
      'Wikimedia Commons — Lepista nuda',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lepista_nuda' }],
  },
  {
    id: 'wood-ear',
    commonName: 'Wood Ear',
    scientificName: 'Auricularia americana',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On dead hardwood branches and logs — especially elder and maple.',
    identification:
      'Rubbery ear-shaped brown translucent fruiting bodies. No gills. Cartilage texture.',
    lookalikes: ['Other jelly fungi — generally edible group; wood ear is most common culinary species.'],
    edibleNotes: 'Classic Asian stir-fry ingredient — crunchy texture when rehydrated.',
    preparation: 'Dry and rehydrate, or simmer fresh in soup. Adds texture not flavor.',
    harvestSeason: 'Year-round on wood; peak after rains.',
    safetyWarnings: ['Only collect from clean wood away from roadside pollution.'],
    ...wikiGallery(
      ['Auricularia americana 1.jpg', 'Auricularia auricula-judae.jpg', 'Wood ear mushroom.jpg'],
      'Wikimedia Commons — Auricularia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Auricularia_americana' }],
  },
  {
    id: 'enoki',
    commonName: 'Wild Enoki',
    scientificName: 'Flammulina velutipes',
    alsoKnownAs: ['Velvet foot', 'Winter mushroom'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'On hardwood logs and stumps — especially elm and cottonwood in cool weather.',
    identification:
      'Small orange caps with dark velvety stem base. Grows in cold weather on wood. Gilled.',
    lookalikes: [
      'Galerina on wood — DEADLY — always confirm spore print brown (enoki) vs. rusty brown (galerina) with expert.',
      'Sulphur tuft — greenish gills, different season.',
    ],
    edibleNotes: 'Same species as cultivated enoki — wild form is shorter and more flavorful.',
    preparation: 'Cook in soups and hot pot. Harvest cool-season clusters.',
    harvestSeason: 'Late fall through winter on logs.',
    safetyWarnings: ['Wood-growing gilled mushrooms demand expert ID — high fatality risk if confused with Galerina.'],
    ...wikiGallery(
      ['Flammulina velutipes 1.jpg', 'Flammulina velutipes.jpg', 'Enoki mushroom wild.jpg'],
      'Wikimedia Commons — Flammulina velutipes',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Flammulina_velutipes' }],
  },
  {
    id: 'slippery-jack',
    commonName: 'Slippery Jack',
    scientificName: 'Suillus luteus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Under planted and wild pine — especially Scots and ponderosa pine plantations.',
    identification:
      'Brown cap with sticky slimy coating when wet. Yellow pores. Ring on stem. Grows with pines.',
    lookalikes: [
      'Other suillus — most edible when cap skin peeled; some bitter species.',
      'Boletes — no ring typically; different pore attachment.',
    ],
    edibleNotes: 'Edible after peeling slimy cap cuticle — mild flavor. Popular in Eastern Europe.',
    preparation: 'Peel cap skin off before cooking. Pickle or sauté.',
    harvestSeason: 'Fall under pines — October–November.',
    safetyWarnings: ['Always peel slimy cap — cuticle can cause GI upset for some.'],
    ...wikiGallery(
      ['Suillus luteus 1.jpg', 'Suillus luteus.jpg', 'Slippery jack mushroom.jpg'],
      'Wikimedia Commons — Suillus luteus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Suillus_luteus' }],
  },
  {
    id: 'wine-cap',
    commonName: 'Wine Cap / Garden Giant',
    scientificName: 'Stropharia rugosoannulata',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Wood chip mulch, garden paths, and compost — urban and rural.',
    identification:
      'Large burgundy wine-red cap fading to tan. Purple-gray gills. Thick ring on stem. Chips and compost habitat.',
    lookalikes: [
      'Other stropharia — wine cap is largest in mulch.',
      'Agrocybe — different habitat and spore color.',
    ],
    edibleNotes: 'Excellent cultivated and wild mulch mushroom — asparagus-like when young.',
    preparation: 'Harvest before gills dark purple-black. Grill caps or sauté.',
    harvestSeason: 'Spring through fall on fresh wood chips.',
    safetyWarnings: ['Only from clean mulch — avoid treated or contaminated chips.'],
    ...wikiGallery(
      ['Stropharia rugosoannulata 1.jpg', 'Stropharia rugosoannulata.jpg', 'Wine cap mushroom.jpg'],
      'Wikimedia Commons — Stropharia rugosoannulata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Stropharia_rugosoannulata' }],
  },
  {
    id: 'pig-ear-gomphus',
    commonName: "Pig's Ear Gomphus",
    scientificName: 'Gomphus clavatus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'or-cascades', 'or-rogue'],
    habitat: 'Old-growth conifer duff — mountain hemlock and fir zones.',
    identification:
      'Clustered vase-shaped purple-brown caps with wrinkled undersurface (not gills). Fleshy.',
    lookalikes: [
      'Black trumpet — thinner, black, individual trumpets.',
      'Some polypores — gomphus is fleshy violet-brown.',
    ],
    edibleNotes: 'Historically eaten in PNW — some people report mild GI upset; try small portion first.',
    preparation: 'Cook thoroughly. Used in traditional mountain foraging.',
    harvestSeason: 'Fall in high-elevation conifer forests.',
    safetyWarnings: ['Can cause GI upset in sensitive individuals — taste small amount first.'],
    ...wikiGallery(
      ['Gomphus clavatus 1.jpg', 'Gomphus clavatus.jpg', 'Pigs ear mushroom.jpg'],
      'Wikimedia Commons — Gomphus clavatus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Gomphus_clavatus' }],
  },
  {
    id: 'pine-spike',
    commonName: 'Pine Spike',
    scientificName: 'Chroogomphus vinicolor',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-silver-lake', 'or-cascades', 'or-klamath'],
    habitat: 'Under pine — often near slippery jacks and boletes. Sandy pine duff.',
    identification:
      'Orange-brown slimy cap, long slender stem. Grows with pines. Gilled (unusual for suillus associates).',
    lookalikes: ['Other chroogomphus — generally edible group under pine.'],
    edibleNotes: 'Mild edible often collected alongside boletes — improves when dried.',
    preparation: 'Cook thoroughly; often added to mixed mushroom dishes.',
    harvestSeason: 'Fall under pines.',
    safetyWarnings: ['Confirm pine habitat and gill structure.'],
    ...wikiGallery(
      ['Chroogomphus vinicolor 1.jpg', 'Chroogomphus vinicolor.jpg', 'Pine spike mushroom.jpg'],
      'Wikimedia Commons — Chroogomphus vinicolor',
    ),
    externalLinks: [{ label: 'Mushroom Observer', url: 'https://mushroomobserver.org/' }],
  },
  {
    id: 'combtooth',
    commonName: 'Comb Tooth',
    scientificName: 'Hericium americanum',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Hardwood logs — maple and oak wounds in valley and foothill forests.',
    identification:
      'Branched white icicle teeth — more coral-like than single lion’s mane. On hardwood.',
    lookalikes: ['Other Hericium — edible group.'],
    edibleNotes: 'Similar to lion’s mane — choice edible on hardwood.',
    preparation: 'Sauté young white clusters.',
    harvestSeason: 'Fall on hardwood logs.',
    safetyWarnings: ['Fresh white only.'],
    ...wikiGallery(
      ['Hericium americanum 1.jpg', 'Hericium coralloides.jpg', 'Comb tooth mushroom.jpg'],
      'Wikimedia Commons — Hericium americanum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hericium_americanum' }],
  },
  {
    id: 'charcoal-burner',
    commonName: 'Charcoal Burner',
    scientificName: 'Russula cyanoxantha',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Mixed conifer-hardwood forest floor.',
    identification:
      'Green to purple cap. White gills that do not shatter when rolled between fingers (flexible gills — key trait).',
    lookalikes: [
      'Other russulas — most have brittle gills; flexible gills distinguish this edible species.',
      'Acidic russulas — taste acrid raw (spit test only if trained).',
    ],
    edibleNotes: 'One of the few non-acrid russulas — flexible gill test is diagnostic.',
    preparation: 'Cook thoroughly. Popular in European foraging tradition.',
    harvestSeason: 'Summer through fall.',
    safetyWarnings: ['Russula group — confirm flexible gills and mild taste with expert.'],
    ...wikiGallery(
      ['Russula cyanoxantha 1.jpg', 'Russula cyanoxantha.jpg', 'Charcoal burner mushroom.jpg'],
      'Wikimedia Commons — Russula cyanoxantha',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Russula_cyanoxantha' }],
  },
  {
    id: 'black-morel',
    commonName: 'Black Morel',
    scientificName: 'Morchella elata group',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Burn scars, riparian cottonwoods, and disturbed ground in mountains — spring.',
    identification:
      'Dark brown elongated honeycombed cap. Completely hollow stem and cap. Pits and ridges (not wrinkled brain-like).',
    lookalikes: [
      'False morel (Gyromitra) — brain-like RED-BROWN cap, NOT fully hollow — TOXIC.',
      'Verpa — cap attached only at apex of stem.',
    ],
    edibleNotes: 'Mountain burn morel — highly prized spring harvest in Sierra and Cascades.',
    preparation: 'Cook thoroughly. Split and wash. Never raw.',
    harvestSeason: 'Spring — April–June at elevation, especially year after fire.',
    safetyWarnings: ['Must be completely hollow inside — false morels are solid or chambered.'],
    ...wikiGallery(
      ['Morchella elata 1.jpg', 'Morchella angusticeps.jpg', 'Black morel mushroom.jpg'],
      'Wikimedia Commons — Morchella elata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Morchella_elata' }],
  },
  {
    id: 'california-chanterelle',
    commonName: 'California Oak Chanterelle',
    scientificName: 'Cantharellus californicus',
    alsoKnownAs: ['Oak chanterelle', 'Large chanterelle'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sacramento', 'ca-sierra-foothills', 'or-rogue'],
    habitat: 'Under oaks in Sierra foothills and interior valleys — large golden clusters in leaf litter.',
    identification:
      'Very large golden chanterelle with false forked ridges. Strong apricot scent. Often grows in massive clumps under live oak.',
    lookalikes: [
      'Pacific golden chanterelle — smaller, more conifer-associated.',
      'Jack-o-lantern (Omphalotus) — true gills, grows on wood — TOXIC.',
    ],
    edibleNotes: 'One of the largest chanterelles in North America — excellent dried or sautéed.',
    preparation: 'Cook thoroughly. Slice thick caps; dry excess.',
    harvestSeason: 'Fall through early winter after rains — October–December.',
    safetyWarnings: ['Confirm false gills and apricot scent.'],
    ...wikiGallery(
      ['Cantharellus californicus.jpg', 'Cantharellus californicus 2.jpg', 'Oak chanterelle.jpg'],
      'Wikimedia Commons — Cantharellus californicus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cantharellus_californicus' }],
  },
  {
    id: 'blue-chanterelle',
    commonName: 'Blue Chanterelle',
    scientificName: 'Polyozellus multiplex',
    alsoKnownAs: ['Clustered blue chanterelle', 'Fan fungus'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath'],
    habitat: 'Old-growth conifer forests — mossy ground under spruce and fir at higher elevation.',
    identification:
      'Dark blue-black to purple clustered fan-shaped caps with wrinkled undersides (not true gills). Grows in tight groups.',
    lookalikes: [
      'Black trumpet — single trumpet shape, not clustered fans.',
      'Any gilled mushroom — blue chanterelle has ridges/wrinkles only.',
    ],
    edibleNotes: 'Choice edible with earthy flavor — popular in PNW high-country foraging.',
    preparation: 'Sauté young clusters; dries well.',
    harvestSeason: 'Late summer through fall at elevation.',
    safetyWarnings: ['Verify wrinkled underside — no true gills.'],
    ...wikiGallery(
      ['Polyozellus multiplex.jpg', 'Polyozellus multiplex 2.jpg', 'Blue chanterelle mushroom.jpg'],
      'Wikimedia Commons — Polyozellus multiplex',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Polyozellus_multiplex' }],
  },
  {
    id: 'queen-bolete',
    commonName: 'Queen Bolete',
    scientificName: 'Butyriboletus regineus',
    alsoKnownAs: ['Royal bolete', 'Oak porcini'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sacramento', 'ca-sierra-foothills', 'or-rogue', 'or-willamette'],
    habitat: 'Under oaks and mixed hardwoods — Sierra foothills and coastal oak woodlands.',
    identification:
      'Large brown cap, thick reticulated stem, white pores that age yellow-green. Nutty aroma. Does not stain blue.',
    lookalikes: [
      'King bolete — more conifer-associated; both choice edibles.',
      'Bitter bolete (Caloboletus) — stains blue, bitter taste.',
    ],
    edibleNotes: 'Premier NorCal oak bolete — often called the queen to the king porcini.',
    preparation: 'Grill caps, dry slices, or sauté in butter.',
    harvestSeason: 'Fall — September through November.',
    safetyWarnings: ['Spore print olive-brown. No blue staining.'],
    ...wikiGallery(
      ['Butyriboletus regineus.jpg', 'Boletus regineus.jpg', 'Queen bolete mushroom.jpg'],
      'Wikimedia Commons — Butyriboletus regineus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Butyriboletus_regineus' }],
  },
  {
    id: 'butter-bolete',
    commonName: 'Butter Bolete',
    scientificName: 'Butyriboletus persolidus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-sierra-foothills', 'or-cascades', 'or-rogue'],
    habitat: 'Under ponderosa pine and mixed conifers in mountains and east-side forests.',
    identification:
      'Red-brown cap, yellow pores, stout yellow stem often with red mesh. Buttery aroma when young.',
    lookalikes: ['King bolete — similar; both edible. Bitter bolete — blue stains.'],
    edibleNotes: 'Excellent pine-associated bolete in eastern Cascades and Sierra.',
    preparation: 'Young firm specimens sautéed; remove spongy pores if desired.',
    harvestSeason: 'Late summer through fall.',
    safetyWarnings: ['Confirm non-bitter taste and no blue staining.'],
    ...wikiGallery(
      ['Butyriboletus persolidus.jpg', 'Butter bolete.jpg', 'Boletus persolidus.jpg'],
      'Wikimedia Commons — Butyriboletus persolidus',
    ),
    externalLinks: [{ label: 'Mushroom Observer', url: 'https://mushroomobserver.org/' }],
  },
  {
    id: 'bay-bolete',
    commonName: 'Bay Bolete',
    scientificName: 'Imleria badia',
    alsoKnownAs: ['Chestnut bolete'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Conifer and mixed woods — often with spruce and fir on coast.',
    identification:
      'Bay-brown cap, yellow pores that bruise blue-green, yellow stem with brown reticulation. Flesh may blue slightly.',
    lookalikes: [
      'Bitter bolete — intensely bitter; bay bolete is mild.',
      'King bolete — larger, paler pore surface when young.',
    ],
    edibleNotes: 'Good edible — peel slimy cap cuticle before cooking. Mild flavor.',
    preparation: 'Peel cap skin; cook thoroughly. Remove blue-stained pore layer if desired.',
    harvestSeason: 'Fall rains through early winter.',
    safetyWarnings: ['Blue bruising is normal — do not confuse with toxic boletes.'],
    ...wikiGallery(
      ['Imleria badia.jpg', 'Boletus badius.jpg', 'Bay bolete mushroom.jpg'],
      'Wikimedia Commons — Imleria badia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Imleria_badia' }],
  },
  {
    id: 'cracked-cap-bolete',
    commonName: 'Cracked Cap Bolete',
    scientificName: 'Xerocomellus chrysenteron',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Urban parks, lawns, and mixed woods — very common small bolete.',
    identification:
      'Small brown cap cracking to show red flesh underneath. Yellow pores age reddish. Stem often reddish at base.',
    lookalikes: ['Other small boletes — generally edible if mild taste.'],
    edibleNotes: 'Common edible — best when young and firm. Can be buggy at maturity.',
    preparation: 'Cook young specimens; discard soft or wormy ones.',
    harvestSeason: 'Summer through fall.',
    safetyWarnings: ['Small size — verify pore surface not gills.'],
    ...wikiGallery(
      ['Xerocomellus chrysenteron.jpg', 'Boletus chrysenteron.jpg', 'Cracked cap bolete.jpg'],
      'Wikimedia Commons — Xerocomellus chrysenteron',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Xerocomellus_chrysenteron' }],
  },
  {
    id: 'aspen-bolete',
    commonName: 'Aspen Bolete',
    scientificName: 'Leccinum insigne',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-silver-lake', 'or-east', 'or-klamath'],
    habitat: 'Under aspen and cottonwood in eastern Oregon and Modoc Plateau.',
    identification:
      'Brown cap with dark scabers (dots) on white to gray stem. White flesh. Grows with poplar relatives.',
    lookalikes: [
      'Other Leccinum — most require thorough cooking; some cause GI upset if undercooked.',
      'Orange-capped scaber stalk — different cap color.',
    ],
    edibleNotes: 'Edible when well-cooked — leccinums need longer cooking than other boletes.',
    preparation: 'Cook at least 15–20 minutes. Do not eat raw or lightly sautéed.',
    harvestSeason: 'Summer through early fall.',
    safetyWarnings: ['ALWAYS cook leccinums thoroughly — undercooking causes nausea for some people.'],
    ...wikiGallery(
      ['Leccinum insigne.jpg', 'Aspen bolete.jpg', 'Leccinum scabrum.jpg'],
      'Wikimedia Commons — Leccinum insigne',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Leccinum' }],
  },
  {
    id: 'manzanita-bolete',
    commonName: 'Manzanita Bolete',
    scientificName: 'Leccinum manzanitae',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-rogue'],
    habitat: 'Under manzanita and madrone in chaparral-woodland edges.',
    identification:
      'Brown to gray cap, stem with dark scabers, often stocky. Found only near manzanita hosts.',
    lookalikes: ['Other Leccinum — cook thoroughly.'],
    edibleNotes: 'Regional specialty — good when thoroughly cooked.',
    preparation: 'Extended cooking required — soups or stews ideal.',
    harvestSeason: 'Fall after first rains.',
    safetyWarnings: ['Cook leccinums thoroughly — never raw.'],
    ...wikiGallery(
      ['Leccinum manzanitae.jpg', 'Manzanita bolete.jpg', 'Leccinum aurantiacum.jpg'],
      'Wikimedia Commons — Leccinum manzanitae',
    ),
    externalLinks: [{ label: 'Mushroom Observer', url: 'https://mushroomobserver.org/' }],
  },
  {
    id: 'conifer-chicken',
    commonName: 'Conifer Chicken of the Woods',
    scientificName: 'Laetiporus conifericola',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Parasitic on living and dead conifers — shelf clusters on trunks.',
    identification:
      'Bright orange to salmon shelving brackets with yellow pore underside. Soft when young. On conifers (not hardwood).',
    lookalikes: [
      'Hardwood chicken (Laetiporus gilbertsonii) — on oak/madrone in California.',
      'Jack-o-lantern — gilled, grows in clusters on wood — TOXIC.',
    ],
    edibleNotes: 'Choice when young and tender — some people react to conifer species; try small amount first.',
    preparation: 'Harvest outer 2 inches only. Cook thoroughly. Not everyone tolerates conifer chicken.',
    harvestSeason: 'Late spring through fall.',
    safetyWarnings: [
      'Eat a small cooked portion first time — rare allergic reactions reported.',
      'Never eat raw.',
    ],
    ...wikiGallery(
      ['Laetiporus conifericola.jpg', 'Chicken of the woods conifer.jpg', 'Laetiporus sulphureus.jpg'],
      'Wikimedia Commons — Laetiporus conifericola',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Laetiporus_conifericola' }],
  },
  {
    id: 'early-morel',
    commonName: 'Early Landscape Morel',
    scientificName: 'Morchella rufobrunnea',
    alsoKnownAs: ['Blushing morel', 'Landscape morel'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-portland', 'or-willamette'],
    habitat: 'Mulched landscaping, disturbed soil, wood chips — urban and suburban spring flushes.',
    identification:
      'Small tan to brown conical morel. Bruises reddish-brown. Honeycombed cap fully attached to stem. Hollow inside.',
    lookalikes: [
      'False morel (Gyromitra) — brain-like, not fully hollow — TOXIC.',
      'Verpa — cap hangs free from stem apex.',
    ],
    edibleNotes: 'First morel of the season in cities — reliable in wood-chip beds.',
    preparation: 'Cook thoroughly. Wash grit from honeycomb.',
    harvestSeason: 'Late winter through spring — February–April.',
    safetyWarnings: ['Must be completely hollow. Avoid contaminated urban sites.'],
    ...wikiGallery(
      ['Morchella rufobrunnea.jpg', 'Landscape morel.jpg', 'Morchella rufobrunnea 2.jpg'],
      'Wikimedia Commons — Morchella rufobrunnea',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Morchella_rufobrunnea' }],
  },
  {
    id: 'half-free-morel',
    commonName: 'Half-Free Morel',
    scientificName: 'Morchella punctipes',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Hardwood edges, riparian zones, and disturbed ground in spring.',
    identification:
      'Cap attached only at apex of stem (half-free). Honeycombed brown cap. Completely hollow stem and cap.',
    lookalikes: [
      'Verpa bohemica — cap hangs like a thimble; stem stuffed with cottony tissue — not recommended.',
      'False morel — not hollow.',
    ],
    edibleNotes: 'Good edible — less prized than yellow or black morels but abundant.',
    preparation: 'Cook thoroughly. Split and clean hollow stem.',
    harvestSeason: 'Spring — March through May.',
    safetyWarnings: ['Confirm hollow interior and honeycomb (not brain-like) cap.'],
    ...wikiGallery(
      ['Morchella punctipes.jpg', 'Half-free morel.jpg', 'Morchella semilibera.jpg'],
      'Wikimedia Commons — Morchella punctipes',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Morchella_punctipes' }],
  },
  {
    id: 'yellow-morel',
    commonName: 'Yellow Morel',
    scientificName: 'Morchella americana',
    alsoKnownAs: ['Common morel', 'Blonde morel'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Cottonwood riparian zones, old orchards, ash and elm associations in valleys.',
    identification:
      'Tan to yellow honeycombed cap fully attached to white hollow stem. Entire mushroom hollow when cut.',
    lookalikes: ['False morel — solid or chambered interior — TOXIC.'],
    edibleNotes: 'Classic spring delicacy — among the most sought-after wild mushrooms.',
    preparation: 'Sauté in butter; stuff; never eat raw.',
    harvestSeason: 'Spring — March through May in valleys.',
    safetyWarnings: ['Must be completely hollow inside.'],
    ...wikiGallery(
      ['Morchella americana.jpg', 'Yellow morel mushroom.jpg', 'Morchella esculenta.jpg'],
      'Wikimedia Commons — Morchella americana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Morchella_americana' }],
  },
  {
    id: 'crown-coral',
    commonName: 'Crown-Tipped Coral',
    scientificName: 'Artomyces pyxidatus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Dead hardwood logs and stumps — common on alder and maple.',
    identification:
      'White to cream branching coral with crown-like depressed tips. Grows on wood. No gelatinous base.',
    lookalikes: [
      'Other corals — some Ramaria; verify crown-shaped tips.',
      'White spindle coral on ground — different growth habit.',
    ],
    edibleNotes: 'Tender when young — mild flavor. Harvest before tips brown.',
    preparation: 'Sauté young white clusters; bitter when old.',
    harvestSeason: 'Summer through fall on rotting hardwood.',
    safetyWarnings: ['Only on wood. Avoid any coral you cannot ID to species.'],
    ...wikiGallery(
      ['Artomyces pyxidatus.jpg', 'Crown tipped coral fungus.jpg', 'Clavicorona pyxidata.jpg'],
      'Wikimedia Commons — Artomyces pyxidatus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Artomyces_pyxidatus' }],
  },
  {
    id: 'golden-coral',
    commonName: 'Golden Coral',
    scientificName: 'Ramaria aurea',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast'],
    habitat: 'Conifer forest floor — often near spruce and fir.',
    identification:
      'Bright golden-yellow branching coral, tips often pointed. White spore print. Grows from soil not wood.',
    lookalikes: [
      'Other Ramaria — some cause GI upset; golden coral is a safe edible group when identified correctly.',
      'Yellow-tipped coral — similar; expert ID recommended.',
    ],
    edibleNotes: 'Choice coral mushroom — breaks easily, cooks like cauliflower.',
    preparation: 'Cook thoroughly. Discard any with bitter taste.',
    harvestSeason: 'Late summer through fall.',
    safetyWarnings: ['Coral mushrooms require careful ID — start with known golden coral.'],
    ...wikiGallery(
      ['Ramaria aurea.jpg', 'Golden coral mushroom.jpg', 'Ramaria flava.jpg'],
      'Wikimedia Commons — Ramaria aurea',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ramaria_aurea' }],
  },
  {
    id: 'orange-peel-fungus',
    commonName: 'Orange Peel Fungus',
    scientificName: 'Aleuria aurantia',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'ca-silver-lake', 'or-east', 'or-klamath'],
    habitat: 'Compacted soil, gravel roadsides, trail edges — often in groups.',
    identification:
      'Bright orange cup-shaped fungus that looks like scattered orange peels. No stem. Smooth outer surface.',
    lookalikes: [
      'Scarlet cup — brighter red, on wood.',
      'Any cup fungus — orange peel is distinctive on bare soil.',
    ],
    edibleNotes: 'Edible but bland — more a curiosity than a meal.',
    preparation: 'Cook in mixed mushroom dishes.',
    harvestSeason: 'Fall through winter after rains.',
    safetyWarnings: ['Avoid roadside specimens with contamination.'],
    ...wikiGallery(
      ['Aleuria aurantia.jpg', 'Orange peel fungus.jpg', 'Aleuria aurantia 2.jpg'],
      'Wikimedia Commons — Aleuria aurantia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Aleuria_aurantia' }],
  },
  {
    id: 'fried-chicken-mushroom',
    commonName: 'Fried Chicken Mushroom',
    scientificName: 'Lyophyllum decastes',
    alsoKnownAs: ['Clustered domecap'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'or-portland', 'or-willamette'],
    habitat: 'Grass, mulch, and compacted soil — urban parks and landscaped areas.',
    identification:
      'Tan-brown caps in tight clusters, white gills, white spore print. Smooth cap without scales.',
    lookalikes: [
      'Deadly Galerina — brown spore print, ring on stem — TOXIC.',
      'Honey mushroom — ring and spore print differ.',
    ],
    edibleNotes: 'Good urban edible when spore print confirmed white.',
    preparation: 'Cook thoroughly. Confirm white spore print.',
    harvestSeason: 'Fall through spring in mild climates.',
    safetyWarnings: ['WHITE spore print essential — deadly lookalikes have brown spores.'],
    ...wikiGallery(
      ['Lyophyllum decastes.jpg', 'Fried chicken mushroom.jpg', 'Lyophyllum decastes 2.jpg'],
      'Wikimedia Commons — Lyophyllum decastes',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lyophyllum_decastes' }],
  },
  {
    id: 'brick-cap',
    commonName: 'Brick Cap',
    scientificName: 'Hypholoma lateritium',
    alsoKnownAs: ['Chestnut mushroom', 'Red bricktop'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Clusters on dead hardwood logs and stumps — especially maple and alder.',
    identification:
      'Brick-red cap with yellowish margin when young. Grows in overlapping clusters on wood. Purple-brown spore print.',
    lookalikes: [
      'Sulfur tuft (Hypholoma fasciculare) — greenish-yellow gills, bitter — TOXIC.',
      'Must compare gill color — brick cap has gray-brown gills.',
    ],
    edibleNotes: 'Edible when young — sulfur tuft is the dangerous lookalike on same substrate.',
    preparation: 'Harvest young caps; cook thoroughly. Avoid sulfur-tuft lookalikes.',
    harvestSeason: 'Fall through winter on rotting logs.',
    safetyWarnings: ['NEVER confuse with sulfur tuft — verify gray-brown gills not green-yellow.'],
    ...wikiGallery(
      ['Hypholoma lateritium.jpg', 'Brick cap mushroom.jpg', 'Hypholoma sublateritium.jpg'],
      'Wikimedia Commons — Hypholoma lateritium',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hypholoma_lateritium' }],
  },
  {
    id: 'shingled-hedgehog',
    commonName: 'Shingled Hedgehog',
    scientificName: 'Sarcodon imbricatus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'ca-silver-lake', 'or-cascades', 'or-klamath'],
    habitat: 'Under conifers — especially pine and spruce in mountains.',
    identification:
      'Large brown cap with dark scaly shingles. Underside has teeth (spines) not gills. Often bitter when old.',
    lookalikes: [
      'Hedgehog mushroom — smoother cap, not scaly.',
      'Old specimens become too bitter to eat.',
    ],
    edibleNotes: 'Edible when young — choose firm specimens with mild flavor.',
    preparation: 'Young caps only; older ones are bitter. Long cooking helps.',
    harvestSeason: 'Late summer through fall at elevation.',
    safetyWarnings: ['Spines not gills — verify tooth underside.'],
    ...wikiGallery(
      ['Sarcodon imbricatus.jpg', 'Shingled hedgehog mushroom.jpg', 'Sarcodon imbricatus 2.jpg'],
      'Wikimedia Commons — Sarcodon imbricatus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sarcodon_imbricatus' }],
  },
  {
    id: 'terracotta-hedgehog',
    commonName: 'Terracotta Hedgehog',
    scientificName: 'Hydnum rufescens',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Conifer and mixed forest floor — often near moss and spruce.',
    identification:
      'Small orange-tan cap with white to pale spines underneath. Compact stature. Spines descend stem slightly.',
    lookalikes: ['Sweet tooth hedgehog — larger, paler; both edible.'],
    edibleNotes: 'Choice small hedgehog — excellent flavor relative to size.',
    preparation: 'Sauté whole small caps.',
    harvestSeason: 'Fall.',
    safetyWarnings: ['Confirm spines — not gills.'],
    ...wikiGallery(
      ['Hydnum rufescens.jpg', 'Terracotta hedgehog.jpg', 'Hydnum repandum.jpg'],
      'Wikimedia Commons — Hydnum rufescens',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hydnum_rufescens' }],
  },
  {
    id: 'pear-shaped-puffball',
    commonName: 'Pear-Shaped Puffball',
    scientificName: 'Apioperdon pyriforme',
    alsoKnownAs: ['Stump puffball'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Clusters on rotting logs and stumps — extremely common.',
    identification:
      'Small pear-shaped brownish puffballs growing in dense clusters on wood. White interior when young.',
    lookalikes: [
      'Earthballs (Scleroderma) — interior dark from youth — TOXIC.',
      'Must be pure white inside.',
    ],
    edibleNotes: 'Good when young and white throughout — peel outer skin.',
    preparation: 'Slice and sauté only pure white interior.',
    harvestSeason: 'Fall through winter.',
    safetyWarnings: ['Cut every puffball in half — pure white only.'],
    ...wikiGallery(
      ['Apioperdon pyriforme.jpg', 'Lycoperdon pyriforme.jpg', 'Pear shaped puffball.jpg'],
      'Wikimedia Commons — Apioperdon pyriforme',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Apioperdon_pyriforme' }],
  },
  {
    id: 'horse-mushroom',
    commonName: 'Horse Mushroom',
    scientificName: 'Agaricus arvensis',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-east', 'or-willamette'],
    habitat: 'Pastures, meadows, and grassy areas — often in fairy rings.',
    identification:
      'Large white cap staining yellow. Ring on stem. Pink gills aging brown. Anise or almond scent.',
    lookalikes: [
      'Destroying angel (Amanita) — volva at base, white gills — DEADLY.',
      'Yellow stainer — intense yellow stain, phenolic smell — causes GI illness.',
    ],
    edibleNotes: 'Excellent meadow mushroom when Amanita ruled out (no volva, brown spores).',
    preparation: 'Cook thoroughly. Dig stem base to check for volva.',
    harvestSeason: 'Late summer through fall.',
    safetyWarnings: ['Check for volva at stem base — Amanita is deadly.'],
    ...wikiGallery(
      ['Agaricus arvensis.jpg', 'Horse mushroom.jpg', 'Agaricus arvensis 2.jpg'],
      'Wikimedia Commons — Agaricus arvensis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Agaricus_arvensis' }],
  },
  {
    id: 'poplar-mushroom',
    commonName: 'Poplar Mushroom',
    scientificName: 'Cyclocybe aegerita',
    alsoKnownAs: ['Black poplar mushroom', 'Pioppino'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'ca-sierra-foothills', 'or-willamette'],
    habitat: 'Cottonwood and poplar stumps and buried wood in riparian zones.',
    identification:
      'Brown cap, white stem with ring, gills aging brown. Grows in clusters on poplar wood.',
    lookalikes: ['Galerina — brown spores on wood; always take spore print.'],
    edibleNotes: 'Cultivated worldwide — wild on cottonwood in valley riparian zones.',
    preparation: 'Sauté stems and caps — stems are tender.',
    harvestSeason: 'Spring and fall.',
    safetyWarnings: ['On wood — rule out Galerina with spore print.'],
    ...wikiGallery(
      ['Cyclocybe aegerita.jpg', 'Agrocybe aegerita.jpg', 'Poplar mushroom.jpg'],
      'Wikimedia Commons — Cyclocybe aegerita',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cyclocybe_aegerita' }],
  },
  {
    id: 'elm-oyster',
    commonName: 'Elm Oyster',
    scientificName: 'Hypsizygus ulmarius',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'or-portland', 'or-willamette'],
    habitat: 'Wounds on living hardwoods — elm, cottonwood, and maple in riparian areas.',
    identification:
      'Tan cap, white gills, stem attached to wood. Often high on tree trunks. White spore print.',
    lookalikes: ['Oyster mushroom — grows from stumps lower; both edible.'],
    edibleNotes: 'Mild firm texture — good stir-fry mushroom.',
    preparation: 'Harvest young firm caps.',
    harvestSeason: 'Fall.',
    safetyWarnings: ['On hardwood wounds — white spore print.'],
    ...wikiGallery(
      ['Hypsizygus ulmarius.jpg', 'Elm oyster mushroom.jpg', 'Hypsizygus ulmarius 2.jpg'],
      'Wikimedia Commons — Hypsizygus ulmarius',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hypsizygus_ulmarius' }],
  },
  {
    id: 'man-on-horseback',
    commonName: 'Man on Horseback',
    scientificName: 'Tricholoma murrillianum',
    alsoKnownAs: ['American matsutake', 'Pine mushroom'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Under pine and fir — sandy duff in coastal and montane forests.',
    identification:
      'White to brown cap, white gills, thick white stem with cottony ring. Strong cinnamon-spice aroma.',
    lookalikes: [
      'Matsutake (Tricholoma magnivelare) — closely related; both prized.',
      'Amanita — volva at base; matsutake has no volva.',
    ],
    edibleNotes: 'Prized for aroma — used in rice and soups. Related to Japanese matsutake.',
    preparation: 'Brush clean; do not wash. Cook in rice or clear soup.',
    harvestSeason: 'Fall — September through November.',
    safetyWarnings: ['Dig base to confirm no volva (Amanita).'],
    ...wikiGallery(
      ['Tricholoma murrillianum.jpg', 'Matsutake mushroom.jpg', 'Tricholoma magnivelare.jpg'],
      'Wikimedia Commons — Tricholoma murrillianum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Tricholoma_murrillianum' }],
  },
  {
    id: 'painted-suillus',
    commonName: 'Painted Suillus',
    scientificName: 'Suillus lakei',
    alsoKnownAs: ['Western painted bolete'],
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-shasta', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Under Douglas-fir — common PNW associate.',
    identification:
      'Brown cap with reddish pattern, yellow pores, ring on stem. Slimy cap when wet.',
    lookalikes: ['Other Suillus — generally edible with peeling cap cuticle.'],
    edibleNotes: 'Edible when cap skin peeled — mucilaginous cap is unpalatable otherwise.',
    preparation: 'Peel slimy cap cuticle; cook thoroughly.',
    harvestSeason: 'Fall.',
    safetyWarnings: ['Always peel cap skin on suillus species.'],
    ...wikiGallery(
      ['Suillus lakei.jpg', 'Painted suillus.jpg', 'Suillus lakei 2.jpg'],
      'Wikimedia Commons — Suillus lakei',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Suillus_lakei' }],
  },
  {
    id: 'larch-bolete',
    commonName: 'Larch Bolete',
    scientificName: 'Suillus grevillei',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-shasta', 'or-cascades', 'or-klamath'],
    habitat: 'Exclusively under larch (tamarack) in subalpine zones.',
    identification:
      'Yellow to orange slimy cap, yellow pores, yellow stem with dark dots. Grows only with larch.',
    lookalikes: ['Other Suillus — peel cap; host tree is diagnostic.'],
    edibleNotes: 'Good when young with peeled cap — larch host is key ID feature.',
    preparation: 'Peel cap cuticle; cook well.',
    harvestSeason: 'Late summer through fall at elevation.',
    safetyWarnings: ['Confirm larch host tree present.'],
    ...wikiGallery(
      ['Suillus grevillei.jpg', 'Larch bolete.jpg', 'Suillus grevillei 2.jpg'],
      'Wikimedia Commons — Suillus grevillei',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Suillus_grevillei' }],
  },
  {
    id: 'amethyst-deceiver',
    commonName: 'Amethyst Deceiver',
    scientificName: 'Laccaria amethysteo-occidentalis',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Mossy conifer forest floor — common and widespread.',
    identification:
      'Small purple to amethyst cap fading with age. Thick purple gills. White spore print. Fibrous stem.',
    lookalikes: [
      'Other Laccaria — generally edible group.',
      'Purple cortinarius — rusty spore print; spore print essential.',
    ],
    edibleNotes: 'Small but abundant — good in mixed mushroom medleys.',
    preparation: 'Cook thoroughly. White spore print.',
    harvestSeason: 'Fall through winter.',
    safetyWarnings: ['Take spore print — Cortinarius has rusty brown spores.'],
    ...wikiGallery(
      ['Laccaria amethystina.jpg', 'Amethyst deceiver.jpg', 'Laccaria amethysteo-occidentalis.jpg'],
      'Wikimedia Commons — Laccaria amethysteo-occidentalis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Laccaria_amethystina' }],
  },
  {
    id: 'common-deceiver',
    commonName: 'Common Deceiver',
    scientificName: 'Laccaria laccata',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Virtually all forest types — one of the most common forest floor mushrooms.',
    identification:
      'Small tawny to orange-brown cap, thick widely spaced gills, fibrous stem. White spore print.',
    lookalikes: ['Other small brown mushrooms — spore print white for Laccaria.'],
    edibleNotes: 'Abundant and edible — small size makes it best in mixes.',
    preparation: 'Cook in stews or mixed sauté.',
    harvestSeason: 'Year-round in mild coastal forests; peak fall.',
    safetyWarnings: ['White spore print — rule out Cortinarius.'],
    ...wikiGallery(
      ['Laccaria laccata.jpg', 'Common deceiver mushroom.jpg', 'Laccaria laccata 2.jpg'],
      'Wikimedia Commons — Laccaria laccata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Laccaria_laccata' }],
  },
  {
    id: 'white-elfin-saddle',
    commonName: 'White Elfin Saddle',
    scientificName: 'Helvella crispa',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Hardwood and mixed forest edges — often near paths in sandy soil.',
    identification:
      'White convoluted saddle-shaped cap on white ribbed stem. No gills — cap is folded and brain-like.',
    lookalikes: [
      'Other Helvella — most edible cooked; H. vespertina is darker.',
      'False morel — different shape and season.',
    ],
    edibleNotes: 'Edible when cooked — contains heat-labile toxins; never raw.',
    preparation: 'MUST be cooked thoroughly — parboil then sauté. Never eat raw.',
    harvestSeason: 'Spring and fall.',
    safetyWarnings: ['RAW HELVELLA IS TOXIC — cook thoroughly every time.'],
    ...wikiGallery(
      ['Helvella crispa.jpg', 'White elfin saddle.jpg', 'Helvella crispa 2.jpg'],
      'Wikimedia Commons — Helvella crispa',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Helvella_crispa' }],
  },
  {
    id: 'western-elfin-saddle',
    commonName: 'Western Elfin Saddle',
    scientificName: 'Helvella vespertina',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'or-cascades', 'or-coast', 'or-klamath', 'or-portland', 'or-rogue', 'or-willamette'],
    habitat: 'Under conifers — especially pine and fir on NorCal coast.',
    identification:
      'Dark gray-brown convoluted saddle cap on pale ribbed stem. Larger than white elfin saddle.',
    lookalikes: ['False morel — different cap attachment and interior.'],
    edibleNotes: 'Edible cooked — popular NorCal spring mushroom when prepared correctly.',
    preparation: 'Parboil 5 minutes, discard water, then sauté. Never raw.',
    harvestSeason: 'Spring — March through May.',
    safetyWarnings: ['Must be parboiled and cooked — raw helvellas are toxic.'],
    ...wikiGallery(
      ['Helvella vespertina.jpg', 'Western elfin saddle.jpg', 'Helvella lacunosa.jpg'],
      'Wikimedia Commons — Helvella vespertina',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Helvella_vespertina' }],
  },
  {
    id: 'ruby-bolete',
    commonName: 'Ruby Bolete',
    scientificName: 'Hortiboletus rubellus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['ca-sacramento', 'or-portland', 'or-willamette'],
    habitat: 'Urban parks, lawns, and oak woodlands — often in groups.',
    identification:
      'Small red cap, yellow pores, slender red stem. Blue stains quickly when cut. Mild taste.',
    lookalikes: [
      'Red-pored bolete — red pores indicate bitter/toxic; ruby has yellow pores.',
      'Small size distinguishes from larger boletes.',
    ],
    edibleNotes: 'Small but good — mild flavor when young.',
    preparation: 'Cook young firm specimens.',
    harvestSeason: 'Summer through fall.',
    safetyWarnings: ['Yellow pores only — red pores mean do not eat.'],
    ...wikiGallery(
      ['Hortiboletus rubellus.jpg', 'Boletus rubellus.jpg', 'Ruby bolete mushroom.jpg'],
      'Wikimedia Commons — Hortiboletus rubellus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Hortiboletus_rubellus' }],
  },
];
