import type { PlantEntry, ResourceCategory } from './types';

/** Curated Pacific Northwest plants — Eugene (Willamette Valley) & Florence (Oregon Coast). Private reference library. */
export const PLANT_LIBRARY: PlantEntry[] = [
  {
    id: 'stinging-nettle',
    commonName: 'Stinging Nettle',
    scientificName: 'Urtica dioica',
    alsoKnownAs: ['Common nettle'],
    uses: 'both',
    category: 'herb',
    regions: ['both'],
    habitat: 'Rich moist soil along streams, ditches, forest edges, and disturbed ground. Very common near Eugene waterways and coast range valleys toward Florence.',
    identification: 'Opposite serrated leaves with stinging hairs on stems and undersides. Square stems. Can reach 3–6 ft when flowering. Crushing or drying removes the sting.',
    edibleNotes: 'One of the most nutritious wild greens in the PNW. Young tops in spring taste like spinach. High in iron, calcium, and protein.',
    medicinalNotes: 'Traditional support for seasonal allergies, joint comfort, and nourishing tonics. Often used as dried leaf tea or tincture.',
    holisticNotes: 'A cornerstone “food as medicine” plant in Pacific Northwest herbalism — nutrient-dense and broadly tonifying.',
    preparation: 'Blanch or dry to neutralize sting. Tea, soup, pesto (blanched), or capsules from dried leaf.',
    harvestSeason: 'Young shoots: March–May. Handle with gloves.',
    safetyWarnings: [
      'Fresh stingers cause welts — always wear gloves when harvesting.',
      'Avoid during pregnancy unless guided by a qualified herbalist.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Urtica_dioica.jpg/640px-Urtica_dioica.jpg',
    imageCredit: 'Wikimedia Commons — Urtica dioica',
    externalLinks: [
      { label: 'USDA Plant Profile', url: 'https://plants.usda.gov/plant-profile/URDI' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Urtica_dioica' },
      { label: 'OSU Extension — Wild harvesting', url: 'https://extension.oregonstate.edu/' },
    ],
  },
  {
    id: 'oregon-grape',
    commonName: 'Oregon Grape',
    scientificName: 'Mahonia aquifolium',
    alsoKnownAs: ['Tall Oregon grape'],
    uses: 'both',
    category: 'shrub',
    regions: ['eugene', 'both'],
    habitat: 'Dry to moist woodland understory throughout the Willamette Valley and coast range foothills.',
    identification: 'Spiny holly-like evergreen leaflets in groups. Bright yellow flower clusters in early spring. Blue berries with whitish bloom in summer.',
    edibleNotes: 'Berries are very tart — best as jelly, syrup, or mixed with sweeter fruit. Not a snacking berry.',
    medicinalNotes: 'Root and bark traditionally used as a bitter liver and digestive tonic. Contains berberine (similar action to goldenseal).',
    holisticNotes: 'Oregon’s state flower and a signature “bitter tonic” in Western herbal practice.',
    preparation: 'Berry: cook with sugar. Root: tincture or decoction (sustainably harvest only from abundant stands).',
    harvestSeason: 'Flowers: Feb–Apr. Berries: Jul–Aug. Root: late fall.',
    safetyWarnings: [
      'Do not confuse with invasive English holly.',
      'Berberine-containing plants may interact with medications — consult a practitioner.',
      'Never strip roots from wild populations.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mahonia_aquifolium_002.jpg/640px-Mahonia_aquifolium_002.jpg',
    imageCredit: 'Wikimedia Commons — Mahonia aquifolium',
    externalLinks: [
      { label: 'USDA Plant Profile', url: 'https://plants.usda.gov/plant-profile/MAAQ' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Mahonia_aquifolium' },
    ],
  },
  {
    id: 'salmonberry',
    commonName: 'Salmonberry',
    scientificName: 'Rubus spectabilis',
    uses: 'edible',
    category: 'berry',
    regions: ['both'],
    habitat: 'Stream banks, wetlands, and shady forest edges — abundant on the coast near Florence and in wet Willamette Valley corridors.',
    identification: 'Magenta flowers in spring. Compound leaves with three leaflets. Orange to red raspberry-like fruit.',
    edibleNotes: 'Mild, slightly sweet-tart berries. Young shoots also peeled and eaten traditionally in spring.',
    medicinalNotes: 'Primarily food; berry antioxidants and seasonal nutrition.',
    holisticNotes: 'A reliable coast-range wild food — often one of the first berries of the season.',
    preparation: 'Eat fresh, jam, or dry. Young peeled shoots in spring.',
    harvestSeason: 'Berries: May–July depending on elevation.',
    safetyWarnings: ['Identify carefully vs. other Rubus species.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Rubus_spectabilis_flower.jpg/640px-Rubus_spectabilis_flower.jpg',
    imageCredit: 'Wikimedia Commons — Rubus spectabilis',
    externalLinks: [
      { label: 'USDA Plant Profile', url: 'https://plants.usda.gov/plant-profile/RUSP' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rubus_spectabilis' },
    ],
  },
  {
    id: 'salal',
    commonName: 'Salal',
    scientificName: 'Gaultheria shallon',
    uses: 'both',
    category: 'shrub',
    regions: ['florence', 'both'],
    habitat: 'Coastal conifer forest understory — dominant groundcover from Florence dunes inland and common in coast-range woods toward Eugene.',
    identification: 'Leathery evergreen oval leaves. Urn-shaped pink-white flowers. Dark blue-purple mealy berries.',
    edibleNotes: 'Berries are sweet when fully ripe. Used in jams and pemmican traditionally.',
    medicinalNotes: 'Leaf tea used as an astringent mouth rinse and mild anti-inflammatory wash.',
    holisticNotes: 'Ubiquitous coast plant — berries are a staple wild food where salal thickets are dense.',
    preparation: 'Berries fresh or dried. Leaf tea for topical or gargle use.',
    harvestSeason: 'Berries: late summer–fall.',
    safetyWarnings: ['Leaves very astringent — don’t overconsume as tea.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Gaultheria_shallon_2.jpg/640px-Gaultheria_shallon_2.jpg',
    imageCredit: 'Wikimedia Commons — Gaultheria shallon',
    externalLinks: [
      { label: 'USDA Plant Profile', url: 'https://plants.usda.gov/plant-profile/GASH' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Gaultheria_shallon' },
    ],
  },
  {
    id: 'miners-lettuce',
    commonName: "Miner's Lettuce",
    scientificName: 'Claytonia perfoliata',
    alsoKnownAs: ['Winter purslane'],
    uses: 'edible',
    category: 'herb',
    regions: ['eugene', 'both'],
    habitat: 'Cool moist shady spots, woodland edges, and spring gardens throughout the valley.',
    identification: 'Succulent leaves with a cup-like leaf bracketing the flower stem. Small white or pink flowers.',
    edibleNotes: 'Mild, crunchy salad green — entire aerial parts edible. Excellent source of vitamin C.',
    medicinalNotes: 'Historically used by miners to prevent scurvy.',
    holisticNotes: 'One of the easiest beginner wild foods in Western Oregon spring.',
    preparation: 'Raw in salads or lightly wilted.',
    harvestSeason: 'Feb–May peak; fades in heat.',
    safetyWarnings: ['Avoid areas sprayed with herbicides (roadsides).'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Claytonia_perfoliata_2.jpg/640px-Claytonia_perfoliata_2.jpg',
    imageCredit: 'Wikimedia Commons — Claytonia perfoliata',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Claytonia_perfoliata' },
    ],
  },
  {
    id: 'yarrow',
    commonName: 'Yarrow',
    scientificName: 'Achillea millefolium',
    uses: 'medicinal',
    category: 'herb',
    regions: ['both'],
    habitat: 'Meadows, roadsides, dry fields, and disturbed sunny ground valley-wide and along the coast highway corridor.',
    identification: 'Feathery aromatic leaves. Flat-topped clusters of tiny white (sometimes pink) flowers. Distinct sage-like scent when crushed.',
    medicinalNotes: 'Classic first-aid herb — styptic powder from dried leaves for minor cuts. Tea for fever support and digestion.',
    holisticNotes: '“Soldier’s woundwort” — one of the most widely used medicinal herbs in European and Indigenous traditions.',
    preparation: 'Dried leaf and flower tea, poultice, or infused oil for topical use.',
    harvestSeason: 'Flower: Jun–Sep.',
    safetyWarnings: [
      'May cause contact dermatitis in sensitive people.',
      'Avoid internal use in pregnancy.',
      'Can potentiate sedatives in large doses.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Achillea_millefolium_2.jpg/640px-Achillea_millefolium_2.jpg',
    imageCredit: 'Wikimedia Commons — Achillea millefolium',
    externalLinks: [
      { label: 'USDA Plant Profile', url: 'https://plants.usda.gov/plant-profile/ACMI2' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Achillea_millefolium' },
    ],
  },
  {
    id: 'plantain',
    commonName: 'Broadleaf Plantain',
    scientificName: 'Plantago major',
    uses: 'medicinal',
    category: 'herb',
    regions: ['both'],
    habitat: 'Lawns, trails, compacted soil — everywhere in Eugene and Florence.',
    identification: 'Low rosette of ribbed oval leaves with parallel veins. Slender seed spikes rise from center.',
    medicinalNotes: 'Fresh leaf poultice for bee stings, bites, and splinters. Mucilage soothes skin and mucous membranes.',
    holisticNotes: 'A “footpath medicine” — often right underfoot on hikes near Spencer Butte or coastal trails.',
    preparation: 'Chew fresh leaf for poultice or dry for tea.',
    harvestSeason: 'Spring through fall; best before seed stalk hardens.',
    safetyWarnings: ['Ensure correct ID — not lily or other lookalikes.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Plantago_major_flower.jpg/640px-Plantago_major_flower.jpg',
    imageCredit: 'Wikimedia Commons — Plantago major',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Plantago_major' },
    ],
  },
  {
    id: 'dandelion',
    commonName: 'Dandelion',
    scientificName: 'Taraxacum officinale',
    uses: 'both',
    category: 'herb',
    regions: ['both'],
    habitat: 'Lawns, fields, roadsides — ubiquitous.',
    identification: 'Toothed basal leaves, hollow stem, yellow composite flower, white puffball seed head.',
    edibleNotes: 'Young leaves in salad (bitter). Flowers for fritters. Roasted root as coffee substitute.',
    medicinalNotes: 'Bitter root and leaf support digestion and liver function. Gentle diuretic (“piss-a-bed”).',
    holisticNotes: 'Classic liver/spring tonic in Western herbalism.',
    preparation: 'Salad greens, root decoction, flower wine.',
    harvestSeason: 'Leaves: early spring. Roots: fall.',
    safetyWarnings: ['Only harvest from unsprayed areas.', 'Latex may irritate skin.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Taraxacum_officinale_flower.jpg/640px-Taraxacum_officinale_flower.jpg',
    imageCredit: 'Wikimedia Commons — Taraxacum officinale',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Taraxacum_officinale' },
    ],
  },
  {
    id: 'red-clover',
    commonName: 'Red Clover',
    scientificName: 'Trifolium pratense',
    uses: 'both',
    category: 'herb',
    regions: ['eugene', 'both'],
    habitat: 'Meadows, pastures, and sunny fields in the Willamette Valley.',
    identification: 'Three leaflets with pale chevron. Round pink-purple flower heads.',
    edibleNotes: 'Flower heads and young leaves in salads or tea.',
    medicinalNotes: 'Traditional support for skin health and menopausal comfort. Contains isoflavones.',
    holisticNotes: 'Gentle lymphatic and nutritive herb.',
    preparation: 'Dried blossom tea or fresh in salads.',
    harvestSeason: 'Late spring–summer flowers.',
    safetyWarnings: ['May affect hormone-sensitive conditions — consult practitioner.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Trifolium_pratense_flower.jpg/640px-Trifolium_pratense_flower.jpg',
    imageCredit: 'Wikimedia Commons — Trifolium pratense',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Trifolium_pratense' },
    ],
  },
  {
    id: 'elderberry',
    commonName: 'Blue Elderberry',
    scientificName: 'Sambucus cerulea',
    alsoKnownAs: ['Mexican elderberry'],
    uses: 'both',
    category: 'shrub',
    regions: ['eugene', 'both'],
    habitat: 'Stream banks, open woods, and disturbed sunny edges in the valley.',
    identification: 'Opposite compound leaves. Large flat cream flower clusters. Powdery blue berries on reddish stems.',
    edibleNotes: 'Berries must be cooked — used for syrup, jam, and wine.',
    medicinalNotes: 'Cooked berry syrup traditionally used for immune support during cold season.',
    holisticNotes: 'One of the most popular home herbal preparations in North America.',
    preparation: 'Cook berries at least 20 minutes. Strain seeds. Syrup with honey.',
    harvestSeason: 'Flowers: May–Jun. Berries: Aug–Sep.',
    safetyWarnings: [
      'NEVER eat raw berries — nausea and worse.',
      'Red elderberry (S. racemosa) on coast is toxic — learn the difference.',
      'Leaves, bark, and seeds are toxic.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sambucus_cerulea.jpg/640px-Sambucus_cerulea.jpg',
    imageCredit: 'Wikimedia Commons — Sambucus cerulea',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sambucus_cerulea' },
    ],
  },
  {
    id: 'fireweed',
    commonName: 'Fireweed',
    scientificName: 'Chamerion angustifolium',
    alsoKnownAs: ['Willowherb'],
    uses: 'both',
    category: 'herb',
    regions: ['both'],
    habitat: 'Burn sites, roadsides, clearcuts, and open meadows — common coast to cascades.',
    identification: 'Tall spikes of magenta four-petaled flowers. Long narrow leaves. Fluffy seed parachutes.',
    edibleNotes: 'Young shoots peeled like asparagus. Leaves as cooked green. Honey from fireweed is prized.',
    medicinalNotes: 'Mucilaginous — soothing for irritated GI tract. Traditional anti-inflammatory.',
    holisticNotes: 'Pioneer species that heals disturbed land — symbolic in PNW ecology.',
    preparation: 'Peel young shoots; leaf tea; flower blossom garnish.',
    harvestSeason: 'Shoots: spring. Flowers: Jul–Aug.',
    safetyWarnings: ['Positive ID vs. other tall magenta spikes.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chamerion_angustifolium_flower.jpg/640px-Chamerion_angustifolium_flower.jpg',
    imageCredit: 'Wikimedia Commons — Chamerion angustifolium',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Chamerion_angustifolium' },
    ],
  },
  {
    id: 'licorice-fern',
    commonName: 'Licorice Fern',
    scientificName: 'Polypodium glycyrrhiza',
    uses: 'medicinal',
    category: 'fern',
    regions: ['florence', 'both'],
    habitat: 'Mossy tree trunks, rocks, and wet forest — very common in coast range and valley forests.',
    identification: 'Fronds from creeping rhizome on mossy maples and logs. Sweet licorice-scented rhizome when chewed.',
    medicinalNotes: 'Rhizome traditionally chewed for sore throat and cough — demulcent and sweet.',
    holisticNotes: 'Look up on big leaf maple trunks on hikes between Eugene and the coast.',
    preparation: 'Fresh or dried rhizome tea; chew small piece for throat.',
    harvestSeason: 'Year-round rhizome; take only small portions sustainably.',
    safetyWarnings: ['Overharvest damages host ecosystem — take sparingly.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Polypodium_glycyrrhiza_1.jpg/640px-Polypodium_glycyrrhiza_1.jpg',
    imageCredit: 'Wikimedia Commons — Polypodium glycyrrhiza',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Polypodium_glycyrrhiza' },
    ],
  },
  {
    id: 'redwood-sorrel',
    commonName: 'Redwood Sorrel',
    scientificName: 'Oxalis oregana',
    uses: 'edible',
    category: 'herb',
    regions: ['florence', 'both'],
    habitat: 'Shady moist conifer forest floor — coast range and old growth near Florence.',
    identification: 'Three heart-shaped leaflets often folded. White to pink five-petaled flowers. Sour lemon taste.',
    edibleNotes: 'Small amounts as trail nibble — oxalic acid gives sour flavor.',
    holisticNotes: 'Beautiful forest floor indicator species in coast range hikes.',
    preparation: 'Few leaves fresh — not large quantities.',
    harvestSeason: 'Spring–early summer.',
    safetyWarnings: [
      'High oxalates — avoid large amounts; kidney stone risk.',
      'Do not confuse with clover.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Oxalis_oregana.jpg/640px-Oxalis_oregana.jpg',
    imageCredit: 'Wikimedia Commons — Oxalis oregana',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Oxalis_oregana' },
    ],
  },
  {
    id: 'huckleberry',
    commonName: 'Evergreen Huckleberry',
    scientificName: 'Vaccinium ovatum',
    uses: 'edible',
    category: 'berry',
    regions: ['florence', 'both'],
    habitat: 'Coastal and low-elevation forest understory — Florence dunes forest and coast range.',
    identification: 'Leathery serrated evergreen leaves. Pink urn flowers. Dark purple-black sweet berries.',
    edibleNotes: 'Excellent wild berry — fresh, jam, pancakes. Ripen further after picking.',
    holisticNotes: 'Coast range counterpart to valley black huckleberry species.',
    preparation: 'Fresh or cooked; freeze well.',
    harvestSeason: 'Late summer–fall.',
    safetyWarnings: ['Positive berry ID essential.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Vaccinium_ovatum_2.jpg/640px-Vaccinium_ovatum_2.jpg',
    imageCredit: 'Wikimedia Commons — Vaccinium ovatum',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Vaccinium_ovatum' },
    ],
  },
  {
    id: 'cottonwood',
    commonName: 'Black Cottonwood',
    scientificName: 'Populus trichocarpa',
    uses: 'medicinal',
    category: 'tree',
    regions: ['eugene', 'both'],
    habitat: 'River bottoms and wet lowland — Willamette River corridor and coastal river valleys.',
    identification: 'Large cottonwood with balsam-scented sticky buds in late winter. Heart-shaped toothed leaves.',
    medicinalNotes: 'Balm of Gilead — cottonwood buds infused in oil for salves on sore muscles and skin irritation.',
    holisticNotes: 'Late winter bud harvest is a traditional PNW herbalist ritual along the Willamette.',
    preparation: 'Collect fuzzy buds before leaf-out. Infuse in olive oil 4–6 weeks. Strain for salve.',
    harvestSeason: 'Buds: Feb–Mar before leaves open.',
    safetyWarnings: ['Tree identification only — do not girdle trees.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Populus_trichocarpa_1.jpg/640px-Populus_trichocarpa_1.jpg',
    imageCredit: 'Wikimedia Commons — Populus trichocarpa',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Populus_trichocarpa' },
    ],
  },
  {
    id: 'willow',
    commonName: 'Pacific Willow',
    scientificName: 'Salix lucida ssp. lasiandra',
    alsoKnownAs: ['Shining willow'],
    uses: 'medicinal',
    category: 'tree',
    regions: ['both'],
    habitat: 'Wetlands, stream banks, and lakeshores — common in Eugene wetlands and coastal estuaries near Florence.',
    identification: 'Flexible branches. Long narrow leaves often with silky undersides. Catkins in early spring.',
    medicinalNotes: 'Bark contains salicin (aspirin precursor). Traditional tea for pain and fever — bitter.',
    holisticNotes: 'The original “aspirin plant” — use with respect and medical awareness.',
    preparation: 'Bark tea from pruned twigs only — never ring-bark living trees.',
    harvestSeason: 'Bark: early spring on pruned material.',
    safetyWarnings: [
      'Avoid if allergic to aspirin.',
      'Not for children with viral illness (Reye syndrome risk with salicylates).',
      'Can interact with blood thinners.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Salix_lucida.jpg/640px-Salix_lucida.jpg',
    imageCredit: 'Wikimedia Commons — Salix lucida',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Salix_lucida' },
    ],
  },
  {
    id: 'self-heal',
    commonName: 'Self-Heal',
    scientificName: 'Prunella vulgaris',
    uses: 'medicinal',
    category: 'herb',
    regions: ['both'],
    habitat: 'Lawns, meadows, and trail edges.',
    identification: 'Low plant with square stem. Purple tubular flowers in dense head. Lance-shaped leaves.',
    medicinalNotes: 'Traditional wound herb and throat-soothing tea. Mild antimicrobial reputation.',
    holisticNotes: 'Name says it all — common “lawyer’s woundwort” of European herbalism, naturalized in Oregon.',
    preparation: 'Tea from flowering tops; poultice.',
    harvestSeason: 'Summer flowering tops.',
    safetyWarnings: ['Generally mild — verify ID.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Prunella_vulgaris_flower.jpg/640px-Prunella_vulgaris_flower.jpg',
    imageCredit: 'Wikimedia Commons — Prunella vulgaris',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Prunella_vulgaris' },
    ],
  },
  {
    id: 'cleavers',
    commonName: 'Cleavers',
    scientificName: 'Galium aparine',
    alsoKnownAs: ['Bedstraw', 'Goosegrass'],
    uses: 'medicinal',
    category: 'herb',
    regions: ['both'],
    habitat: 'Moist shady edges, gardens, and stream banks.',
    identification: 'Square stem with whorled narrow leaves that cling (hooked hairs). Tiny white flowers.',
    medicinalNotes: 'Spring lymphatic tonic — fresh juice or tea. Traditional diuretic and skin support.',
    holisticNotes: 'Best used fresh in spring cleanse protocols in Western herbal tradition.',
    preparation: 'Cold infusion of fresh plant or juiced tops.',
    harvestSeason: 'Before flowering: Mar–May.',
    safetyWarnings: ['Diuretic — hydrate well. Avoid if pregnant.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Galium_aparine_002.jpg/640px-Galium_aparine_002.jpg',
    imageCredit: 'Wikimedia Commons — Galium aparine',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Galium_aparine' },
    ],
  },
  {
    id: 'usnea',
    commonName: 'Usnea Lichen',
    scientificName: 'Usnea spp.',
    alsoKnownAs: ['Old man’s beard'],
    uses: 'medicinal',
    category: 'lichen',
    regions: ['florence', 'both'],
    habitat: 'Hanging from tree branches in moist clean air — coast range and valley forests after rain.',
    identification: 'Gray-green branched lichen with white elastic cord inside main stem when pulled apart.',
    medicinalNotes: 'Traditional antimicrobial for respiratory and urinary support. Usnic acid content.',
    holisticNotes: 'Harvest only from fallen branches after storms — sustainable practice.',
    preparation: 'Alcohol tincture or hot water decoction (strain well).',
    harvestSeason: 'Year-round on windfall after storms.',
    safetyWarnings: [
      'Liver toxicity possible with prolonged high-dose usnic acid — short-term use only.',
      'Never harvest from polluted areas.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Usnea.jpg/640px-Usnea.jpg',
    imageCredit: 'Wikimedia Commons — Usnea',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Usnea' },
    ],
  },
  {
    id: 'turkey-tail',
    commonName: 'Turkey Tail',
    scientificName: 'Trametes versicolor',
    uses: 'medicinal',
    category: 'mushroom',
    regions: ['both'],
    habitat: 'Dead hardwood and conifer logs — everywhere in Oregon forests.',
    identification: 'Bracket fungus with concentric color bands. Underside white with tiny pores (not gills).',
    medicinalNotes: 'Immune-modulating polysaccharides (PSK/PSP) — studied extensively in Asia. Long decoction.',
    holisticNotes: 'One of the safest and most researched medicinal mushrooms for daily broth.',
    preparation: 'Slow simmer 1–4 hours for broth or dual-extract tincture.',
    harvestSeason: 'Year-round on logs.',
    safetyWarnings: [
      'Must be pore surface — not gilled mushrooms.',
      'Wild mushroom ID confidence required.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Trametes_versicolor_G4.jpg/640px-Trametes_versicolor_G4.jpg',
    imageCredit: 'Wikimedia Commons — Trametes versicolor',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Trametes_versicolor' },
    ],
  },
  {
    id: 'chanterelle',
    commonName: 'Pacific Golden Chanterelle',
    scientificName: 'Cantharellus formosus',
    uses: 'edible',
    category: 'mushroom',
    regions: ['florence', 'both'],
    habitat: 'Mossy conifer forest floor — coast range and valley foothills after fall rains.',
    identification: 'Golden funnel-shaped cap with false gills (forked ridges). Fruity apricot smell. No true gills.',
    edibleNotes: 'Oregon state mushroom. Premier wild edible — sauté, dry, freeze.',
    holisticNotes: 'Fall mushroom hunting is a PNW tradition from Eugene foothills to coast range near Florence.',
    preparation: 'Cook thoroughly. Never eat raw wild mushrooms.',
    harvestSeason: 'Oct–Dec after rains.',
    safetyWarnings: [
      'DEADLY lookalike: Jack-o-lantern (Omphalotus) — learn false gills vs. true gills.',
      'Always confirm with experienced forager first season.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Cantharellus_formosus_1.jpg/640px-Cantharellus_formosus_1.jpg',
    imageCredit: 'Wikimedia Commons — Cantharellus formosus',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cantharellus_formosus' },
      { label: 'Oregon State Mushroom', url: 'https://en.wikipedia.org/wiki/Cantharellus_formosus' },
    ],
  },
  {
    id: 'beach-strawberry',
    commonName: 'Beach Strawberry',
    scientificName: 'Fragaria chiloensis',
    uses: 'edible',
    category: 'herb',
    regions: ['florence'],
    habitat: 'Coastal sand dunes and bluffs — Florence to Oregon Dunes National Recreation Area.',
    identification: 'Three toothed leaflets, runners on sand. Small sweet white-flowered berries close to ground.',
    edibleNotes: 'Tiny intense strawberries — best trail snack on dune walks.',
    holisticNotes: 'Coast-specific wild food not found inland in Eugene.',
    preparation: 'Eat fresh.',
    harvestSeason: 'Late spring–summer.',
    safetyWarnings: ['Stay on trails in dune habitat — fragile ecosystem.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Fragaria_chiloensis_2.jpg/640px-Fragaria_chiloensis_2.jpg',
    imageCredit: 'Wikimedia Commons — Fragaria chiloensis',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Fragaria_chiloensis' },
    ],
  },
  {
    id: 'douglas-fir-tip',
    commonName: 'Douglas Fir Spring Tips',
    scientificName: 'Pseudotsuga menziesii',
    uses: 'both',
    category: 'tree',
    regions: ['both'],
    habitat: 'Dominant conifer from valley floor to coast — everywhere.',
    identification: 'Soft bright green new growth tips in spring. Distinct bracts on cones (“mouse tail and legs”).',
    edibleNotes: 'Citrus-pine flavored tips for tea, syrup, and seasoning. High vitamin C.',
    medicinalNotes: 'Resinous tea for congestion. Traditional respiratory support.',
    holisticNotes: 'Signature tree of the PNW — spring tip harvest connects you to forest seasonality.',
    preparation: 'Tea, infused honey, or dried for winter.',
    harvestSeason: 'Soft tips: Apr–May only.',
    safetyWarnings: ['Avoid yew (toxic) — flat needles, red cup on berry.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pseudotsuga_menziesii_2.jpg/640px-Pseudotsuga_menziesii_2.jpg',
    imageCredit: 'Wikimedia Commons — Pseudotsuga menziesii',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Pseudotsuga_menziesii' },
    ],
  },
  {
    id: 'nootka-rose',
    commonName: 'Nootka Rose',
    scientificName: 'Rosa nutkana',
    uses: 'both',
    category: 'shrub',
    regions: ['both'],
    habitat: 'Stream banks, roadsides, and open sunny areas valley and coast.',
    identification: 'Pink five-petaled flowers. Thorns on stems. Large red rose hips in fall.',
    edibleNotes: 'Rose hips extremely high in vitamin C — tea and jelly. Petals for garnish.',
    medicinalNotes: 'Astringent hip tea for digestive and skin support.',
    holisticNotes: 'Fall hip harvest along Willamette paths and coastal trails.',
    preparation: 'Remove seeds/hairs from hips before eating. Tea or syrup.',
    harvestSeason: 'Flowers: May–Jun. Hips: after first frost.',
    safetyWarnings: ['Irritating hairs inside hips — strain well.'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Rosa_nutkana_2.jpg/640px-Rosa_nutkana_2.jpg',
    imageCredit: 'Wikimedia Commons — Rosa nutkana',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rosa_nutkana' },
    ],
  },
  {
    id: 'horsetail',
    commonName: 'Horsetail',
    scientificName: 'Equisetum arvense',
    uses: 'medicinal',
    category: 'herb',
    regions: ['both'],
    habitat: 'Sandy wet soils, roadsides, and disturbed ground.',
    identification: 'Jointed hollow stems with whorled branches. Silica-rich. Two stages: fertile brown cone stage and green vegetative.',
    medicinalNotes: 'High silica — traditional use for hair, skin, nails, and connective tissue support.',
    holisticNotes: 'Ancient plant lineage — use short-term only in modern herbal practice.',
    preparation: 'Long decoction of dried sterile stems. Never raw.',
    harvestSeason: 'Summer green stems.',
    safetyWarnings: [
      'Contains thiaminase — long-term use may deplete B1.',
      'Avoid in pregnancy and with alcoholism.',
      'Contains nicotine — not for children.',
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Equisetum_arvense.jpg/640px-Equisetum_arvense.jpg',
    imageCredit: 'Wikimedia Commons — Equisetum arvense',
    externalLinks: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Equisetum_arvense' },
    ],
  },
];

export const EXTERNAL_RESOURCE_LIBRARY: ResourceCategory[] = [
  {
    id: 'pnw-field-guides',
    title: 'Pacific Northwest Field Guides & ID',
    description: 'Authoritative identification resources for Oregon plants and mushrooms.',
    links: [
      {
        label: 'Oregon Flora Project',
        url: 'https://www.oregonflora.org/',
        description: 'Complete Oregon plant atlas with photos and range maps.',
      },
      {
        label: 'USDA PLANTS Database',
        url: 'https://plants.usda.gov/',
        description: 'Scientific profiles for every native and naturalized species.',
      },
      {
        label: 'iNaturalist — Lane County, OR',
        url: 'https://www.inaturalist.org/places/lane-county-us-or',
        description: 'Community observations with photos near Eugene.',
      },
      {
        label: 'iNaturalist — Florence area',
        url: 'https://www.inaturalist.org/places/siuslaw-national-forest',
        description: 'Coast range and Siuslaw NF plant observations near Florence.',
      },
      {
        label: 'PNW Mushroom ID (PSMS)',
        url: 'https://www.psms.org/',
        description: 'Puget Sound Mycological Society resources applicable to Oregon fungi.',
      },
    ],
  },
  {
    id: 'eugene-local',
    title: 'Eugene & Willamette Valley',
    description: 'Local ecology, foraging ethics, and extension education.',
    links: [
      {
        label: 'OSU Extension — Lane County',
        url: 'https://extension.oregonstate.edu/county/lane',
        description: 'Workshops, Master Gardener, and natural resources programs.',
      },
      {
        label: 'Mount Pisgah Arboretum',
        url: 'https://www.mountpisgaharboretum.org/',
        description: 'Living native plant collection in the southern Willamette Valley.',
      },
      {
        label: 'Friends of Buford Park',
        url: 'https://www.bufordpark.org/',
        description: 'Meadows oak savanna and native plant habitat near Eugene.',
      },
      {
        label: 'Willamette River natural history',
        url: 'https://www.oregon.gov/owrd/programs/Pages/Willamette.aspx',
        description: 'Riparian corridor ecology along the valley.',
      },
    ],
  },
  {
    id: 'florence-coast',
    title: 'Florence & Oregon Coast',
    description: 'Coastal dunes, estuary, and shore-zone plants.',
    links: [
      {
        label: 'Oregon Dunes NRA',
        url: 'https://www.fs.usda.gov/recarea/siuslaw/recarea/?recid=42470',
        description: 'Dune forest, shore pine, and coastal wildflower habitat.',
      },
      {
        label: 'Siuslaw National Forest',
        url: 'https://www.fs.usda.gov/siuslaw',
        description: 'Coast range forest from Florence to Yachats.',
      },
      {
        label: 'Oregon Shores — coastal ecology',
        url: 'https://oregonshores.org/',
        description: 'Shoreline conservation and coastal natural history.',
      },
      {
        label: 'Seaweed foraging — Oregon (reference)',
        url: 'https://en.wikipedia.org/wiki/Edible_seaweed',
        description: 'Overview of edible seaweeds — tidepool ethics and species basics.',
      },
    ],
  },
  {
    id: 'holistic-herbal',
    title: 'Holistic & Herbal Medicine References',
    description: 'Educational resources on Western herbalism and plant energetics (private study).',
    links: [
      {
        label: 'American Herbalists Guild',
        url: 'https://www.americanherbalistsguild.com/',
        description: 'Professional herbalist standards and education.',
      },
      {
        label: 'Henriette’s Herbal Homepage',
        url: 'https://www.henriettes-herb.com/',
        description: 'Classic eclectic herbal texts and materia medica.',
      },
      {
        label: 'Southwest School of Botanical Medicine',
        url: 'http://www.swsbm.com/',
        description: 'Michael Moore’s free PNW-relevant herbal manuscripts.',
      },
      {
        label: 'Dr. Duke’s Phytochemical Database',
        url: 'https://phytochem.nal.usda.gov/phytochem/search',
        description: 'USDA phytochemical and ethnobotanical search.',
      },
    ],
  },
  {
    id: 'safety-ethics',
    title: 'Foraging Safety & Ethics',
    description: 'Read before harvesting — legal, ecological, and health considerations.',
    links: [
      {
        label: 'OSU — Wild harvesting guidelines',
        url: 'https://extension.oregonstate.edu/',
        description: 'Extension guidance on sustainable wildcrafting.',
      },
      {
        label: 'Oregon poisonous plants (OSU)',
        url: 'https://extension.oregonstate.edu/gardening/techniques/poisonous-plants',
        description: 'Know toxic lookalikes before you forage.',
      },
      {
        label: 'Leave No Trace — foraging ethics',
        url: 'https://lnt.org/',
        description: 'Minimum impact principles on public lands.',
      },
    ],
  },
];

export function regionLabel(r: PlantEntry['regions'][number]): string {
  if (r === 'eugene') return 'Eugene / Willamette Valley';
  if (r === 'florence') return 'Florence / Oregon Coast';
  return 'Both regions';
}

export function matchesRegion(plant: PlantEntry, filter: 'all' | 'eugene' | 'florence'): boolean {
  if (filter === 'all') return true;
  return plant.regions.includes(filter) || plant.regions.includes('both');
}
