import type { PlantEntry } from './types';
import { wikiGallery } from './plantGallery';

/** Edible wild plants of Oregon and Northern California — full ID + safety entries. */
export const EDIBLE_PLANT_LIBRARY: PlantEntry[] = [
  // ——— Berries & fruit ———
  {
    id: 'blackcap-raspberry',
    commonName: 'Blackcap Raspberry',
    scientificName: 'Rubus leucodermis',
    alsoKnownAs: ['Whitebark raspberry', 'Western black raspberry'],
    uses: 'edible',
    category: 'berry',
    regions: ['or-rogue', 'or-klamath', 'or-east', 'ca-shasta', 'ca-sierra-foothills', 'ca-north-coast'],
    habitat:
      'Dry open slopes, forest edges, and disturbed ground from eastern Oregon through Klamath-Siskiyou and Sierra foothills.',
    identification:
      'Arching canes with whitish bloom (glaucous) when young, turning dark purple-black. Compound leaves with 3–5 leaflets. Berries hollow when picked like black raspberry — not solid like blackberry.',
    lookalikes: [
      'Evergreen blackberry — solid aggregate fruit, persistent green leaves through winter.',
      'Trailing blackberry — already in main library; smaller trailing canes.',
      'Baneberry — white or red toxic berries on thick stalk; no cane structure.',
    ],
    edibleNotes: 'Intense sweet-tart flavor — excellent fresh, jam, or vinegar. Hollow core distinguishes from blackberries.',
    preparation: 'Eat fresh, freeze, or cook into jam. Wear gloves — canes have fine prickles.',
    harvestSeason: 'Mid-summer — July–August.',
    safetyWarnings: ['Verify hollow berry core vs. solid blackberry aggregate.', 'Avoid berries near roads or sprayed areas.'],
    ...wikiGallery(
      ['Rubus leucodermis 1.jpg', 'Rubus leucodermis fruit.jpg', 'Rubus leucodermis plant.jpg'],
      'Wikimedia Commons — Rubus leucodermis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rubus_leucodermis' }],
  },
  {
    id: 'evergreen-blackberry',
    commonName: 'Evergreen Blackberry',
    scientificName: 'Rubus laciniatus',
    alsoKnownAs: ['Cut-leaf blackberry'],
    uses: 'edible',
    category: 'berry',
    regions: ['or-willamette', 'or-portland', 'or-coast', 'ca-sacramento', 'ca-north-coast', 'both', 'eugene'],
    habitat:
      'Disturbed roadsides, fencerows, and open woods — widespread invasive in Willamette Valley and north-coast California.',
    identification:
      'Deeply incised (laciniate) leaflets on vigorous thorny canes. White to pink flowers. Large aggregate black berries that stay solid when picked.',
    lookalikes: [
      'Himalayan blackberry (R. armeniacus) — larger rounded leaflets, not deeply cut.',
      'Trailing blackberry — native, smaller, trailing habit.',
      'Blackcap raspberry — hollow berry, whitish young canes.',
    ],
    edibleNotes: 'Abundant late-summer fruit — tart when underripe, sweet when fully black and soft.',
    preparation: 'Jam, pie, or freeze. Cook to soften seeds if desired.',
    harvestSeason: 'Late summer — August–September.',
    safetyWarnings: ['Invasive species — harvest freely but do not spread canes.', 'Thorns are fierce — use thick gloves.'],
    ...wikiGallery(
      ['Rubus laciniatus 1.jpg', 'Rubus laciniatus fruit.jpg', 'Rubus laciniatus leaves.jpg'],
      'Wikimedia Commons — Rubus laciniatus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rubus_laciniatus' }],
  },
  {
    id: 'red-flowering-currant-berry',
    commonName: 'Red-flowering Currant',
    scientificName: 'Ribes sanguineum',
    alsoKnownAs: ['Blood currant'],
    uses: 'both',
    category: 'shrub',
    regions: ['or-coast', 'or-willamette', 'or-portland', 'ca-north-coast', 'both', 'florence'],
    habitat: 'Open woods, bluffs, and forest edges — signature early-spring shrub of the coast and western valleys.',
    identification:
      'Drooping clusters of pink to red tubular flowers in early spring. Maple-like lobed leaves with sticky glands. Dark blue-black berries with whitish bloom in summer.',
    lookalikes: [
      'Stink currant (R. bracteosum) — larger sticky flowers, skunky odor on bruised leaves.',
      'Sierra gooseberry — spiny stems and prickly berries.',
      'Any Ribes — learn leaf shape and flower timing.',
    ],
    edibleNotes: 'Berries are tart and seedy — best cooked into jelly or mixed with sweeter fruit. Flowers edible as garnish.',
    medicinalNotes: 'Traditional coastal peoples used bark and berries as tonics — consult experienced sources.',
    preparation: 'Cook berries with sugar for jelly. Flowers in salads (sparingly).',
    harvestSeason: 'Flowers: March–April. Berries: July–August.',
    safetyWarnings: ['Raw berries are very tart — some people find them laxative in quantity.', 'Do not confuse with unrelated toxic shrubs.'],
    ...wikiGallery(
      ['Ribes sanguineum flowers.jpg', 'Ribes sanguineum fruit.jpg', 'Ribes sanguineum shrub.jpg'],
      'Wikimedia Commons — Ribes sanguineum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ribes_sanguineum' }],
  },
  {
    id: 'stink-currant',
    commonName: 'Stink Currant',
    scientificName: 'Ribes bracteosum',
    alsoKnownAs: ['Skunk currant'],
    uses: 'edible',
    category: 'shrub',
    regions: ['or-coast', 'or-cascades', 'ca-north-coast', 'ca-shasta', 'both', 'florence'],
    habitat: 'Moist shady forest — coast range and Cascades understory.',
    identification:
      'Large sticky-glandular greenish-white flower clusters. Strong skunky odor when leaves bruised. Dark purple-black berries.',
    lookalikes: [
      'Red-flowering currant — pink/red flowers, no skunk smell.',
      'Sierra gooseberry — spiny stems.',
      'Blue elderberry — flat flower cluster, not currant-like leaves.',
    ],
    edibleNotes: 'Berries edible cooked despite the name — flavor improves with heat and sugar. Not a fresh-eating berry.',
    preparation: 'Jelly or sauce only — always cook.',
    harvestSeason: 'Berries: August–September.',
    safetyWarnings: ['Skunky smell is normal — not a sign of spoilage.', 'Cook before eating — raw flavor is harsh.'],
    ...wikiGallery(
      ['Ribes bracteosum.jpg', 'Ribes bracteosum fruit.jpg', 'Ribes bracteosum flowers.jpg'],
      'Wikimedia Commons — Ribes bracteosum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ribes_bracteosum' }],
  },
  {
    id: 'sierra-gooseberry',
    commonName: 'Sierra Gooseberry',
    scientificName: 'Ribes roezlii',
    alsoKnownAs: ['Roezl\'s gooseberry'],
    uses: 'edible',
    category: 'berry',
    regions: ['or-rogue', 'or-klamath', 'ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake'],
    habitat: 'Dry open pine and oak woodland — Klamath-Siskiyou and Sierra foothills.',
    identification:
      'Spiny stems. Small lobed leaves. Purple-black berries covered in sharp spines — handle with care. Small greenish flowers.',
    lookalikes: [
      'Other gooseberries (Ribes) — all have spiny fruit; verify regional species.',
      'Barberry — different leaf and spine pattern on branches.',
    ],
    edibleNotes: 'Tart spiny berries — classic gooseberry flavor once spines are removed by cooking and straining.',
    preparation: 'Cook and strain for jelly or pie filling. Never eat raw spiny fruit whole.',
    harvestSeason: 'Summer — July–August.',
    safetyWarnings: ['Spines on fruit can lodge in throat — always cook and strain.', 'Spiny stems — wear gloves.'],
    ...wikiGallery(
      ['Ribes roezlii.jpg', 'Ribes roezlii fruit.jpg', 'Ribes roezlii plant.jpg'],
      'Wikimedia Commons — Ribes roezlii',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ribes_roezlii' }],
  },
  {
    id: 'chokecherry',
    commonName: 'Chokecherry',
    scientificName: 'Prunus virginiana',
    uses: 'both',
    category: 'shrub',
    regions: ['or-east', 'or-klamath', 'ca-silver-lake', 'ca-shasta', 'ca-sierra-foothills'],
    habitat: 'Stream banks, canyon edges, and open slopes in eastern Oregon and Modoc/Sierra country.',
    identification:
      'Oval serrated leaves. White fragrant flower racemes in spring. Dark purple-black cherries in hanging clusters. Bark often marked with lenticels.',
    lookalikes: [
      'Bitter cherry (P. emarginata) — larger, more bitter fruit; similar but different range.',
      'Buckthorn — different leaf venation; berries not in cherry clusters.',
      'Wild cherry pits contain cyanogenic compounds — never eat pits.',
    ],
    edibleNotes: 'Extremely astringent raw — name says it all. Excellent jelly, syrup, and pemmican ingredient when cooked.',
    medicinalNotes: 'Traditional bark tea — use only with expert guidance; bark contains compounds requiring careful preparation.',
    preparation: 'Cook fruit thoroughly. Strain out pits — NEVER crush or eat seeds (cyanide risk).',
    harvestSeason: 'Late summer — August–September.',
    safetyWarnings: [
      'PITS CONTAIN CYANIDE — never eat, crush, or blend pits.',
      'Raw fruit causes nausea — always cook.',
      'Wilted leaves toxic to livestock — not for forage.',
    ],
    ...wikiGallery(
      ['Prunus virginiana fruit.jpg', 'Prunus virginiana flowers.jpg', 'Prunus virginiana shrub.jpg'],
      'Wikimedia Commons — Prunus virginiana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Prunus_virginiana' }],
  },
  {
    id: 'bitter-cherry',
    commonName: 'Bitter Cherry',
    scientificName: 'Prunus emarginata',
    uses: 'edible',
    category: 'tree',
    regions: ['or-cascades', 'or-rogue', 'or-coast', 'ca-north-coast', 'ca-shasta', 'both'],
    habitat: 'Forest edges and moist slopes from coast range through Cascades and into northern California.',
    identification:
      'Small tree or large shrub. Oval leaves with rounded tips. White spring flowers. Bright red to dark red cherries — very bitter raw.',
    lookalikes: [
      'Chokecherry — darker purple fruit, more eastern distribution.',
      'Oregon cherry relatives — all Prunus pits are toxic.',
      'Holly — not a cherry; red berries on waxy leaves.',
    ],
    edibleNotes: 'Historically used cooked or dried by Indigenous peoples — extremely bitter raw. Mostly a survival or traditional food.',
    preparation: 'Cook thoroughly and strain. Discard all pits.',
    harvestSeason: 'Summer — July–August.',
    safetyWarnings: ['Pits contain cyanogenic glycosides — never eat or crush seeds.', 'Raw fruit is intensely bitter and may cause stomach upset.'],
    ...wikiGallery(
      ['Prunus emarginata.jpg', 'Prunus emarginata fruit.jpg', 'Prunus emarginata flowers.jpg'],
      'Wikimedia Commons — Prunus emarginata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Prunus_emarginata' }],
  },
  {
    id: 'madrone-berry',
    commonName: 'Madrone Berry',
    scientificName: 'Arbutus menziesii',
    alsoKnownAs: ['Pacific madrone'],
    uses: 'both',
    category: 'tree',
    regions: ['or-coast', 'or-rogue', 'ca-north-coast', 'ca-shasta'],
    habitat: 'Dry open conifer and oak woodland — iconic peeling orange-red bark on coast and southwest Oregon.',
    identification:
      'Leathery evergreen leaves. Smooth peeling cinnamon bark. Clusters of small white urn-shaped flowers. Orange-red warty berries in fall.',
    lookalikes: [
      'Manzanita — similar flowers and berries but shrub form with smooth red bark, not peeling.',
      'Toyon — serrated leaves, different bark.',
    ],
    edibleNotes: 'Berries are mealy and bland-sweet — traditionally dried or made into cider-like drinks. High tannin when unripe.',
    medicinalNotes: 'Traditional uses for leaves and berries — consult cultural and herbal sources.',
    preparation: 'Wait until fully ripe (soft and red). Dry, ferment, or cook into jelly.',
    harvestSeason: 'Fall — October–November when berries soften.',
    safetyWarnings: ['Unripe berries are astringent and high in tannins.', 'Eat in moderation — can be laxative.'],
    ...wikiGallery(
      ['Arbutus menziesii.jpg', 'Arbutus menziesii fruit.jpg', 'Arbutus menziesii bark.jpg'],
      'Wikimedia Commons — Arbutus menziesii',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Arbutus_menziesii' }],
  },
  {
    id: 'manzanita-berry',
    commonName: 'Manzanita Berry',
    scientificName: 'Arctostaphylos patula',
    alsoKnownAs: ['Greenleaf manzanita', 'Hairy manzanita (A. columbiana in OR)'],
    uses: 'both',
    category: 'shrub',
    regions: ['or-east', 'or-klamath', 'ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake'],
    habitat: 'Dry open pine and oak forest — eastern Cascades, Klamath, and Sierra foothills.',
    identification:
      'Smooth red or brown bark on twisted stems. Leathery oval leaves. Pink-white urn flowers. Small red-brown apple-like berries.',
    lookalikes: [
      'Madrone — tree with peeling bark, larger berries.',
      'Bearberry — ground-hugging, smaller range.',
      'Toyon — tree/shrub with serrated leaves.',
    ],
    edibleNotes: 'Dry mealy "little apples" — traditionally ground into meal for mush or cider. Pleasant dry sweetness when ripe.',
    medicinalNotes: 'Leaves traditionally used as urinary antiseptic tea — strong tannin.',
    preparation: 'Dry berries and grind into flour, or soak for cider. Remove stones if grinding.',
    harvestSeason: 'Late summer–fall when deep red-brown and dry.',
    safetyWarnings: ['High tannin in unripe berries — wait until fully ripe.', 'Seeds are hard — grind or strain.'],
    ...wikiGallery(
      ['Arctostaphylos patula.jpg', 'Arctostaphylos manzanita berries.jpg', 'Arctostaphylos columbiana.jpg'],
      'Wikimedia Commons — Arctostaphylos',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Arctostaphylos' }],
  },
  {
    id: 'toyon',
    commonName: 'Toyon',
    scientificName: 'Heteromeles arbutifolia',
    alsoKnownAs: ['California holly', 'Christmas berry'],
    uses: 'both',
    category: 'shrub',
    regions: ['ca-north-coast', 'ca-sierra-foothills', 'ca-sacramento'],
    habitat: 'Chaparral, oak woodland, and coastal scrub in northern California — Sacramento Valley foothills to north coast.',
    identification:
      'Evergreen shrub to small tree. Serrated holly-like leaf edges (not spiny). Clusters of small white flowers. Bright red berries in winter.',
    lookalikes: [
      'Holly — invasive; spiny leaves.',
      'Manzanita — urn flowers, different leaf.',
      'Pyracantha — thorny, non-native.',
    ],
    edibleNotes: 'Berries edible cooked — traditional cider and jelly. Raw berries cause GI upset for some.',
    medicinalNotes: 'Historical Native California uses — leaves and bark are astringent.',
    preparation: 'Cook berries for jelly or roast. Strain seeds.',
    harvestSeason: 'Winter — December–January when bright red.',
    safetyWarnings: ['Do not eat large quantities raw — can cause nausea.', 'Protected on some lands — check local rules.'],
    ...wikiGallery(
      ['Heteromeles arbutifolia.jpg', 'Heteromeles arbutifolia fruit.jpg', 'Heteromeles arbutifolia flowers.jpg'],
      'Wikimedia Commons — Heteromeles arbutifolia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Heteromeles_arbutifolia' }],
  },
  {
    id: 'wild-grape',
    commonName: 'Wild Grape',
    scientificName: 'Vitis californica',
    alsoKnownAs: ['California wild grape'],
    uses: 'edible',
    category: 'shrub',
    regions: ['ca-north-coast', 'ca-sacramento', 'ca-sierra-foothills', 'or-rogue'],
    habitat: 'Stream banks, riparian corridors, and forest edges — Rogue Valley and throughout northern California.',
    identification:
      'Climbing vine with tendrils. Large lobed grape leaves. Small purple-black grapes in loose clusters. Shredding bark on older vines.',
    lookalikes: [
      'Virginia creeper — 5 leaflets, blue berries; oxalate crystals — toxic.',
      'Poison ivy — "leaves of three" — no grape clusters.',
      'Moonseed — single crescent seed — TOXIC.',
    ],
    edibleNotes: 'Small tart grapes — excellent wild wine, juice, and jelly. Seeds and skin add tannin.',
    preparation: 'Crush for juice/wine, or cook into jelly. Strain seeds.',
    harvestSeason: 'Late summer–fall — September–October.',
    safetyWarnings: ['CRITICAL: Check seeds — moonseed has a single crescent seed and is toxic.', 'Verify tendrils and grape leaf shape.'],
    ...wikiGallery(
      ['Vitis californica.jpg', 'Vitis californica fruit.jpg', 'Vitis californica leaves.jpg'],
      'Wikimedia Commons — Vitis californica',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Vitis_californica' }],
  },
  {
    id: 'woodland-strawberry',
    commonName: 'Woodland Strawberry',
    scientificName: 'Fragaria vesca',
    alsoKnownAs: ['Wild strawberry'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-cascades', 'or-coast', 'ca-shasta', 'ca-north-coast', 'both', 'eugene'],
    habitat: 'Partial shade in forests, meadows, and trail edges — distinct from coastal beach strawberry.',
    identification:
      'Trifoliate toothed leaflets on thin runners. White five-petaled flowers. Small elongated red berries with seeds on surface — intense flavor.',
    lookalikes: [
      'Beach strawberry (F. chiloensis) — coastal dunes; in main library.',
      'Mock strawberry (Potentilla indica) — yellow flowers, bland hollow berry.',
      'Cinquefoil — five leaflets, no sweet berry.',
    ],
    edibleNotes: 'Tiny but explosively flavorful — among the best wild strawberries in the world.',
    preparation: 'Eat fresh, or add to salads and desserts.',
    harvestSeason: 'Spring through early summer — May–July.',
    safetyWarnings: ['Yellow-flowered mock strawberry is not sweet — verify white flowers.'],
    ...wikiGallery(
      ['Fragaria vesca fruit.jpg', 'Fragaria vesca plant.jpg', 'Fragaria vesca flower.jpg'],
      'Wikimedia Commons — Fragaria vesca',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Fragaria_vesca' }],
  },
  {
    id: 'cascade-huckleberry',
    commonName: 'Cascade Huckleberry',
    scientificName: 'Vaccinium deliciosum',
    alsoKnownAs: ['Cascade bilberry', 'Blueleaf huckleberry'],
    uses: 'edible',
    category: 'berry',
    regions: ['or-cascades', 'or-klamath', 'ca-shasta', 'ca-silver-lake'],
    habitat: 'Subalpine meadows and open conifer forest — high Cascades and Mt. Shasta country.',
    identification:
      'Deciduous shrub with bright green oval leaves turning red in fall. Pink-tinged bell flowers. Dark blue-purple berries with bloom.',
    lookalikes: [
      'Evergreen huckleberry (in main library) — evergreen leaves, lower elevation.',
      'Dwarf huckleberry — smaller, often lower growing.',
      'Red huckleberry (in main library) — grows on stumps, red stems.',
    ],
    edibleNotes: 'Choice subalpine berry — sweet-tart, excellent fresh or in pancakes.',
    preparation: 'Eat fresh, dry, or freeze. No cooking needed.',
    harvestSeason: 'Mid to late summer at elevation — August–September.',
    safetyWarnings: ['Harvest at legal elevations and permits on public land.', 'Bear country — make noise while picking.'],
    ...wikiGallery(
      ['Vaccinium deliciosum.jpg', 'Vaccinium deliciosum fruit.jpg', 'Vaccinium deliciosum leaves.jpg'],
      'Wikimedia Commons — Vaccinium deliciosum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Vaccinium_deliciosum' }],
  },
  {
    id: 'dwarf-huckleberry',
    commonName: 'Dwarf Huckleberry',
    scientificName: 'Vaccinium caespitosum',
    alsoKnownAs: ['Dwarf bilberry', 'Cascade huckleberry (regional name overlap)'],
    uses: 'edible',
    category: 'berry',
    regions: ['or-cascades', 'or-klamath', 'ca-shasta', 'ca-sierra-foothills'],
    habitat: 'Alpine and subalpine meadows, rocky slopes — low mat-forming shrub.',
    identification:
      'Low mat-forming shrub only a few inches to a foot tall. Small oval leaves. Tiny blue-black berries with intense flavor.',
    lookalikes: [
      'Cascade huckleberry — taller shrub, larger berries.',
      'Blueberries — cultivated or wild; similar but different growth habit.',
    ],
    edibleNotes: 'Tiny powerhouse berries — labor-intensive to pick but exceptional flavor.',
    preparation: 'Eat fresh or add to granola. Freeze for winter.',
    harvestSeason: 'Short alpine window — August.',
    safetyWarnings: ['Alpine environment — weather changes fast.', 'Pick sustainably in fragile meadows.'],
    ...wikiGallery(
      ['Vaccinium caespitosum.jpg', 'Vaccinium caespitosum fruit.jpg', 'Vaccinium caespitosum habitat.jpg'],
      'Wikimedia Commons — Vaccinium caespitosum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Vaccinium_caespitosum' }],
  },
  {
    id: 'osoberry',
    commonName: 'Osoberry',
    scientificName: 'Oemleria cerasiformis',
    alsoKnownAs: ['Indian plum', 'Oregon plum'],
    uses: 'both',
    category: 'shrub',
    regions: ['or-willamette', 'or-portland', 'or-coast', 'ca-north-coast', 'both', 'eugene', 'florence'],
    habitat: 'Earliest-blooming native shrub — moist forest edges and riparian zones valley to coast.',
    identification:
      'First white flower clusters in late winter. Slender leaves. Pea-sized peach-colored berries turning dark blue-black. Bitter almond scent when twigs scratched.',
    lookalikes: [
      'Cherry relatives — osoberry has dangling clusters and almond scent on twig.',
      'Non-fruiting lookalikes in winter — learn twig and leaf shape.',
    ],
    edibleNotes: 'Berries are mostly pit with thin flesh — bland to bitter. Historically eaten but not a choice fruit. First fresh berry of the season.',
    medicinalNotes: 'Bark and bark tea used traditionally — expert knowledge required.',
    preparation: 'Eat sparingly fresh when fully dark. Most foragers prefer later-season berries.',
    harvestSeason: 'Very early — March–May.',
    safetyWarnings: ['Pits should not be crushed — cyanogenic compounds like other Prunus relatives.', 'Flavor disappoints many — manage expectations.'],
    ...wikiGallery(
      ['Oemleria cerasiformis.jpg', 'Oemleria cerasiformis fruit.jpg', 'Oemleria cerasiformis flowers.jpg'],
      'Wikimedia Commons — Oemleria cerasiformis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Oemleria_cerasiformis' }],
  },

  // ——— Greens & weeds ———
  {
    id: 'western-dock',
    commonName: 'Western Dock',
    scientificName: 'Rumex occidentalis',
    alsoKnownAs: ['Western sorrel dock'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-east', 'or-klamath', 'ca-silver-lake', 'ca-shasta', 'both', 'eugene'],
    habitat: 'Moist meadows, stream banks, and spring wetlands — valley and eastern Oregon.',
    identification:
      'Basal rosette of large lance-shaped leaves. Tall seed stalks with rust-brown triangular seeds (tumbling). Sour taste from oxalic acid.',
    lookalikes: [
      'Curly dock (R. crispus) — wavy leaf margins; also edible.',
      'Sheep sorrel (in main library) — smaller arrow-shaped leaves.',
      'Lily-of-the-valley — TOXIC; not sour when chewed.',
    ],
    edibleNotes: 'Young leaves add lemony tang to salads and soups. Seeds can be ground as flour substitute.',
    preparation: 'Use young spring leaves. Cook to reduce oxalates for large servings.',
    harvestSeason: 'Early spring leaves — March–April. Seeds: summer.',
    safetyWarnings: ['High oxalic acid — avoid large raw quantities if prone to kidney stones.', 'Do not confuse with non-sour toxic plants.'],
    ...wikiGallery(
      ['Rumex occidentalis.jpg', 'Rumex occidentalis leaves.jpg', 'Rumex occidentalis seeds.jpg'],
      'Wikimedia Commons — Rumex occidentalis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rumex' }],
  },
  {
    id: 'common-mallow',
    commonName: 'Common Mallow',
    scientificName: 'Malva neglecta',
    alsoKnownAs: ['Cheeses', 'Buttonweed'],
    uses: 'both',
    category: 'herb',
    regions: ['or-willamette', 'or-portland', 'or-east', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Disturbed soil, gardens, and roadsides — cosmopolitan weed in valley and California lowlands.',
    identification:
      'Roundish lobed leaves on long petioles. Pink to white striped flowers. Disc-shaped "cheese" seed pods.',
    lookalikes: [
      'Other mallows — all generally edible in the Malva group.',
      'Ground ivy — different square-stem mint smell.',
    ],
    edibleNotes: 'Mild mucilaginous leaves and young seed pods ("cheeses") — good in soups and as thickener.',
    medicinalNotes: 'Mucilage soothes throat and digestive tract — traditional demulcent.',
    preparation: 'Young leaves raw or cooked. Seed pods when still green and soft.',
    harvestSeason: 'Spring through fall — tender growth in spring best.',
    safetyWarnings: ['Forage away from contaminated urban soils.'],
    ...wikiGallery(
      ['Malva neglecta.jpg', 'Malva neglecta flower.jpg', 'Malva neglecta fruit.jpg'],
      'Wikimedia Commons — Malva neglecta',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Malva_neglecta' }],
  },
  {
    id: 'sow-thistle',
    commonName: 'Sow Thistle',
    scientificName: 'Sonchus oleraceus',
    alsoKnownAs: ['Common sow thistle'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-portland', 'or-coast', 'ca-sacramento', 'ca-north-coast', 'both', 'eugene'],
    habitat: 'Disturbed ground, gardens, and field edges everywhere.',
    identification:
      'Milky sap when stem broken. Dandelion-like yellow flowers. Prickly-edged clasping stem leaves. Not a true thistle (no spines on stem).',
    lookalikes: [
      'Prickly lettuce — more spiny; also has milky sap.',
      'True thistles — spiny all over; many edible after peeling.',
      'Wild lettuce (in main library) — sedative sap; different uses.',
    ],
    edibleNotes: 'Young leaves mild and good cooked like spinach — traditional Mediterranean pot herb.',
    preparation: 'Boil or sauté young leaves. Change water if bitterness bothers you.',
    harvestSeason: 'Spring and fall tender growth.',
    safetyWarnings: ['Milky sap — normal; not the same as wild lettuce sedative species.'],
    ...wikiGallery(
      ['Sonchus oleraceus.jpg', 'Sonchus oleraceus flower.jpg', 'Sonchus oleraceus leaves.jpg'],
      'Wikimedia Commons — Sonchus oleraceus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sonchus_oleraceus' }],
  },
  {
    id: 'prickly-lettuce',
    commonName: 'Prickly Lettuce',
    scientificName: 'Lactuca serriola',
    alsoKnownAs: ['Wild lettuce', 'Compass plant'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-east', 'ca-sacramento', 'ca-sierra-foothills', 'both', 'eugene'],
    habitat: 'Dry disturbed roadsides, fields, and waste ground.',
    identification:
      'Tall upright plant with spiny midrib on underside of leaves. Milky white latex. Yellow dandelion-like flowers. Leaves often twist to orient vertically.',
    lookalikes: [
      'Wild lettuce (L. virosa / L. canadensis in main library) — stronger sedative latex.',
      'Sow thistle — less prickly midrib.',
      'True lettuce relatives — all have milky sap.',
    ],
    edibleNotes: 'Young leaves before flowering — bitter but edible as cooked green. Older plants very bitter.',
    preparation: 'Cook young leaves; blanch to reduce bitterness.',
    harvestSeason: 'Early spring rosettes — before tall flowering stalk.',
    safetyWarnings: ['Bitter latex increases as plant ages — avoid large amounts of mature plant.', 'Not the same as recreational wild lettuce species.'],
    ...wikiGallery(
      ['Lactuca serriola.jpg', 'Lactuca serriola leaves.jpg', 'Lactuca serriola flower.jpg'],
      'Wikimedia Commons — Lactuca serriola',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lactuca_serriola' }],
  },
  {
    id: 'watercress',
    commonName: 'Watercress',
    scientificName: 'Nasturtium officinale',
    uses: 'both',
    category: 'herb',
    regions: ['or-willamette', 'or-coast', 'or-portland', 'ca-north-coast', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Clean cold spring-fed streams and slow-moving water — must verify water quality.',
    identification:
      'Low growing in water. Pinnately compound leaves with oval leaflets. White four-petaled flowers. Peppery taste when chewed.',
    lookalikes: [
      'Poison hemlock — TOXIC; musty smell, purple blotched stem, NOT peppery.',
      'Water hemlock (Cicuta) — DEADLY; grows in same habitat.',
      'Penny-cress and other cresses — peppery but different leaf shape.',
    ],
    edibleNotes: 'Classic peppery salad green — rich in vitamins and minerals.',
    medicinalNotes: 'Traditional spring tonic and digestive stimulant.',
    preparation: 'Raw in salads or briefly wilted in soup. Wash thoroughly.',
    harvestSeason: 'Year-round in mild springs — best spring growth.',
    safetyWarnings: [
      'NEVER harvest from polluted water — risk of liver fluke and bacteria.',
      'Positive ID essential — hemlock grows in similar wet places and is DEADLY.',
      'If in doubt, do not eat.',
    ],
    ...wikiGallery(
      ['Nasturtium officinale.jpg', 'Nasturtium officinale habitat.jpg', 'Nasturtium officinale flowers.jpg'],
      'Wikimedia Commons — Nasturtium officinale',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Nasturtium_officinale' }],
  },
  {
    id: 'spring-beauty',
    commonName: 'Spring Beauty',
    scientificName: 'Claytonia lanceolata',
    alsoKnownAs: ['Western spring beauty', 'Indian potato'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-cascades', 'or-klamath', 'ca-shasta', 'ca-sierra-foothills', 'ca-silver-lake'],
    habitat: 'Moist open forest and meadows — spring ephemerals in mountains and foothills.',
    identification:
      'Pair of narrow lance-shaped leaves. Delicate pink-striped white flowers. Small round corm (Indian potato) underground.',
    lookalikes: [
      'Other Claytonia species — generally edible.',
      'False hellebore — TOXIC; much larger, different flower — know before digging.',
    ],
    edibleNotes: 'Corms nutty and sweet raw or cooked — traditional Indigenous root food. Leaves also edible.',
    preparation: 'Dig corms sustainably (small portion of patch). Roast or boil like mini potatoes.',
    harvestSeason: 'Spring — March–May when flowering.',
    safetyWarnings: ['Dig only where legal and sustainable — corms are slow to recover.', 'Verify not false hellebore before any root harvest.'],
    ...wikiGallery(
      ['Claytonia lanceolata.jpg', 'Claytonia lanceolata flower.jpg', 'Claytonia lanceolata corm.jpg'],
      'Wikimedia Commons — Claytonia lanceolata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Claytonia_lanceolata' }],
  },
  {
    id: 'nodding-onion',
    commonName: 'Nodding Onion',
    scientificName: 'Allium cernuum',
    uses: 'both',
    category: 'herb',
    regions: ['or-east', 'or-klamath', 'ca-shasta', 'ca-silver-lake', 'ca-sierra-foothills'],
    habitat: 'Dry open slopes and rocky outcrops — eastern Oregon and northern California.',
    identification:
      'Grass-like onion smell when crushed. Nodding pink flower umbels. Bulbs small and clustered.',
    lookalikes: [
      'Death camas (Zigadenus) — NO onion smell — TOXIC; grows in same areas as camas.',
      'Other Allium — if it smells like onion/garlic, generally edible.',
      'Grass — no onion odor when crushed.',
    ],
    edibleNotes: 'Bulbs and leaves add mild onion flavor — smaller than cultivated onion.',
    medicinalNotes: 'Same antimicrobial sulfur compounds as garlic/onion family.',
    preparation: 'Use bulbs and leaves raw or cooked. Dried bulbs store well.',
    harvestSeason: 'Spring–summer — after flowering for bulb size.',
    safetyWarnings: ['MUST smell onion/garlic — if no smell, do not eat (death camas rule).', 'Harvest sustainably — small bulbs.'],
    ...wikiGallery(
      ['Allium cernuum.jpg', 'Allium cernuum flowers.jpg', 'Allium cernuum bulb.jpg'],
      'Wikimedia Commons — Allium cernuum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Allium_cernuum' }],
  },
  {
    id: 'wild-onion',
    commonName: 'Wild Onion',
    scientificName: 'Allium acuminatum',
    alsoKnownAs: ['Tapertip onion', 'Hooker\'s onion'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-east', 'or-klamath', 'ca-shasta', 'ca-silver-lake', 'ca-sierra-foothills'],
    habitat: 'Dry open grassland and sagebrush — east-side Oregon and Modoc/Sierra.',
    identification:
      'Strong onion odor. Pink to purple flower umbel on short stem. Bulb with fibrous coat.',
    lookalikes: [
      'Death camas — NO onion smell — potentially FATAL.',
      'Nodding onion — similar; both edible if onion-scented.',
    ],
    edibleNotes: 'Pungent wild onion bulbs — flavor punch in small packages.',
    preparation: 'Roast, pickle, or use fresh. Leaves also edible.',
    harvestSeason: 'Spring bulbs before flowering, or after seed set.',
    safetyWarnings: ['Onion smell test is mandatory every time.', 'Never harvest bulbs without confirming Allium identity.'],
    ...wikiGallery(
      ['Allium acuminatum.jpg', 'Allium acuminatum flowers.jpg', 'Allium acuminatum habitat.jpg'],
      'Wikimedia Commons — Allium acuminatum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Allium_acuminatum' }],
  },
  {
    id: 'fat-hen',
    commonName: 'Fat Hen',
    scientificName: 'Chenopodium album',
    alsoKnownAs: ['Lamb\'s quarters (related)', 'Goosefoot'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-east', 'ca-sacramento', 'ca-sierra-foothills', 'both', 'eugene'],
    habitat: 'Disturbed soil, gardens, and agricultural edges worldwide.',
    identification:
      'Mealy white powder on young growing tips. Diamond-shaped toothed leaves with goosefoot shape. No red sap (unlike amaranth).',
    lookalikes: [
      'Lamb\'s quarters (in main library) — closely related; similar uses.',
      'Orache — often reddish or arrow-shaped.',
      'Nightshades — do not have mealy white coating.',
    ],
    edibleNotes: 'Top wild spinach — nutritious and mild when cooked.',
    preparation: 'Cook like spinach. Use only young tender tops.',
    harvestSeason: 'Spring through early summer.',
    safetyWarnings: ['Accumulates nitrates in polluted soil — avoid roadside patches.', 'Cook for best digestion.'],
    ...wikiGallery(
      ['Chenopodium album.jpg', 'Chenopodium album leaves.jpg', 'Chenopodium album seeds.jpg'],
      'Wikimedia Commons — Chenopodium album',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Chenopodium_album' }],
  },
  {
    id: 'wild-amaranth',
    commonName: 'Wild Amaranth',
    scientificName: 'Amaranthus retroflexus',
    alsoKnownAs: ['Pigweed', 'Redroot amaranth'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-east', 'ca-sacramento', 'ca-sierra-foothills', 'both', 'eugene'],
    habitat: 'Disturbed ground, gardens, and agricultural fields.',
    identification:
      'Red taproot. Rough hairy stems. Large simple oval leaves. Tall green flower spikes maturing to black seeds.',
    lookalikes: [
      'Fat hen — mealy white tips, no red root.',
      'Spiny amaranth — has spines at leaf nodes.',
      'Prostrate pigweed — low spreading habit.',
    ],
    edibleNotes: 'Young leaves cooked like spinach. Seeds edible as grain (tiny but nutritious).',
    preparation: 'Cook leaves. Winnow seeds for grain or pop like miniature popcorn.',
    harvestSeason: 'Summer leaves; fall seeds.',
    safetyWarnings: ['Avoid oxalate-heavy older leaves in huge quantities.', 'Spiny species require more prep.'],
    ...wikiGallery(
      ['Amaranthus retroflexus.jpg', 'Amaranthus retroflexus seeds.jpg', 'Amaranthus retroflexus leaves.jpg'],
      'Wikimedia Commons — Amaranthus retroflexus',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Amaranthus_retroflexus' }],
  },
  {
    id: 'orache',
    commonName: 'Orache',
    scientificName: 'Atriplex hortensis',
    alsoKnownAs: ['Garden orache', 'Mountain spinach'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-east', 'ca-silver-lake', 'ca-shasta', 'ca-sierra-foothills'],
    habitat: 'Disturbed alkaline soils and dry open ground — east-side and Great Basin fringe.',
    identification:
      'Arrowhead to diamond-shaped leaves, often gray-green or reddish. Mealy texture on some species. Insignificant green flowers.',
    lookalikes: [
      'Lamb\'s quarters / fat hen — similar goosefoot family.',
      'Spinach — cultivated lookalike.',
    ],
    edibleNotes: 'Mild salty spinach substitute — leaves can be red, green, or purple.',
    preparation: 'Cook briefly or use young leaves raw in salad.',
    harvestSeason: 'Spring through summer.',
    safetyWarnings: ['Salt-tolerant — may accumulate minerals; moderate portions.'],
    ...wikiGallery(
      ['Atriplex hortensis.jpg', 'Atriplex hortensis leaves.jpg', 'Atriplex canescens.jpg'],
      'Wikimedia Commons — Atriplex',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Atriplex_hortensis' }],
  },
  {
    id: 'winter-cress',
    commonName: 'Winter Cress',
    scientificName: 'Barbarea vulgaris',
    alsoKnownAs: ['Yellow rocket', 'Bittercress (common name overlap)'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-portland', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Disturbed moist ground, ditches, and field margins.',
    identification:
      'Basal rosette of lobed dark green leaves. Tall spikes of bright yellow four-petaled mustard flowers. Peppery mustard family taste.',
    lookalikes: [
      'Other Barbarea and bittercress — mustard family; generally similar prep.',
      'Wild radish — similar flowers; hairier pods.',
    ],
    edibleNotes: 'Early spring green before bitterness intensifies — traditional "poor man\'s asparagus" for young shoots.',
    preparation: 'Boil young leaves and shoots; change water if too bitter.',
    harvestSeason: 'Early spring rosettes and flower shoots — March–April.',
    safetyWarnings: ['Becomes very bitter after flowering — harvest young.', 'Mustard family — goitrogens if eaten raw in huge amounts.'],
    ...wikiGallery(
      ['Barbarea vulgaris.jpg', 'Barbarea vulgaris flowers.jpg', 'Barbarea vulgaris rosette.jpg'],
      'Wikimedia Commons — Barbarea vulgaris',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Barbarea_vulgaris' }],
  },
  {
    id: 'bittercress',
    commonName: 'Bittercress',
    scientificName: 'Cardamine oligosperma',
    alsoKnownAs: ['Little Western bittercress', 'Small-flowered bittercress'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-coast', 'or-cascades', 'ca-north-coast', 'both', 'eugene', 'florence'],
    habitat: 'Moist shady forest and stream edges — early spring groundcover.',
    identification:
      'Small pinnate leaves. Tiny white four-petaled flowers. Slender exploding seed pods when mature. Mild peppery taste.',
    lookalikes: [
      'Other Cardamine species — generally edible mustard family.',
      'Winter cress — larger plant, yellow flowers.',
    ],
    edibleNotes: 'Delicate peppery microgreen — excellent in spring salads.',
    preparation: 'Eat rosettes and flowers raw.',
    harvestSeason: 'Early spring — February–April.',
    safetyWarnings: ['Tiny plant — harvest sustainably in patches.'],
    ...wikiGallery(
      ['Cardamine oligosperma.jpg', 'Cardamine hirsuta.jpg', 'Cardamine pratensis.jpg'],
      'Wikimedia Commons — Cardamine',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cardamine' }],
  },
  {
    id: 'wild-radish-greens',
    commonName: 'Wild Radish Greens',
    scientificName: 'Raphanus raphanistrum',
    alsoKnownAs: ['Jointed charlock'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-coast', 'or-willamette', 'ca-north-coast', 'ca-sacramento', 'both', 'florence'],
    habitat: 'Disturbed coastal and valley ground — fields, roadsides, and dunes.',
    identification:
      'Hairy leaves with lobed margins. Yellow or white four-petaled flowers (sometimes veined lavender). Jointed seed pods that do not split.',
    lookalikes: [
      'Wild mustard — smooth pods that split.',
      'Rape/canola — similar yellow flowers.',
    ],
    edibleNotes: 'Young leaves and flowers peppery like radish — good cooked green and salad garnish.',
    preparation: 'Cook older leaves; young leaves raw. Pickled seed pods ("poor man\'s capers").',
    harvestSeason: 'Spring greens and flowers; summer pods.',
    safetyWarnings: ['Hairy mature leaves are tough — use tender spring growth.'],
    ...wikiGallery(
      ['Raphanus raphanistrum.jpg', 'Raphanus raphanistrum flowers.jpg', 'Raphanus raphanistrum pods.jpg'],
      'Wikimedia Commons — Raphanus raphanistrum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Raphanus_raphanistrum' }],
  },

  // ——— Roots & tubers ———
  {
    id: 'camas',
    commonName: 'Camas',
    scientificName: 'Camassia quamash',
    alsoKnownAs: ['Common camas', 'Blue camas'],
    uses: 'both',
    category: 'herb',
    regions: ['or-willamette', 'or-rogue', 'or-klamath', 'ca-north-coast', 'both', 'eugene'],
    habitat: 'Wet meadows and prairies — historically managed by Indigenous fire ecology in Willamette Valley.',
    identification:
      'Grass-like leaves from bulb. Tall spike of blue-violet six-petaled star flowers in spring. Bulb white and onion-shaped but NO onion smell.',
    lookalikes: [
      'DEATH CAMAS (Toxicoscordion venenosum / Zigadenus) — WHITE or cream flowers, NO onion smell — FATAL.',
      'If flowers are white/cream and plant has NO onion odor — DO NOT HARVEST.',
      'Onion family (Allium) — HAS onion smell — edible but different food.',
    ],
    edibleNotes: 'Slow-roasted camas bulbs become sweet as pear — cornerstone Indigenous food of the Willamette Valley.',
    medicinalNotes: 'Traditional food medicine — prepared only through long slow cooking.',
    preparation: 'Pit-roast or slow bake 24–48 hours until brown and sweet. NEVER eat raw.',
    harvestSeason: 'Dig bulbs after seed set — late summer when flowers are gone.',
    safetyWarnings: [
      'DEATH CAMAS grows in the same meadows — FATAL misidentification risk.',
      'Camas has BLUE flowers; death camas has WHITE/CREAM flowers.',
      'No onion smell on either — flower color and expert ID required.',
      'Raw camas causes severe GI distress — always fully cook.',
      'Never harvest without experienced mentor on first outings.',
    ],
    ...wikiGallery(
      ['Camassia quamash.jpg', 'Camassia quamash flowers.jpg', 'Camassia quamash meadow.jpg'],
      'Wikimedia Commons — Camassia quamash',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Camassia_quamash' }],
  },
  {
    id: 'wapato',
    commonName: 'Wapato',
    scientificName: 'Sagittaria latifolia',
    alsoKnownAs: ['Broadleaf arrowhead', 'Indian potato', 'Duck potato'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-willamette', 'or-coast', 'ca-north-coast', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Shallow freshwater marshes, ponds, and slow sloughs — wade to harvest.',
    identification:
      'Arrowhead-shaped emergent leaves. Three-petaled white flowers. Round starchy tubers on underwater roots — pull or feel with toes.',
    lookalikes: [
      'Other Sagittaria — generally edible tubers.',
      'Water hemlock roots in same habitat — DEADLY; know leaf shape.',
      'Bur reed — different leaf and tuber.',
    ],
    edibleNotes: 'Starchy tubers like potatoes — historically traded extensively in the PNW.',
    preparation: 'Peel and boil or roast. Dried and ground as flour.',
    harvestSeason: 'Fall tuber harvest when tops die back.',
    safetyWarnings: ['Wade carefully — soft mud and deep holes.', 'Verify arrowhead leaf shape — not hemlock.'],
    ...wikiGallery(
      ['Sagittaria latifolia.jpg', 'Sagittaria latifolia tuber.jpg', 'Sagittaria latifolia flowers.jpg'],
      'Wikimedia Commons — Sagittaria latifolia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sagittaria_latifolia' }],
  },
  {
    id: 'balsamroot',
    commonName: 'Balsamroot',
    scientificName: 'Balsamorhiza sagittata',
    alsoKnownAs: ['Arrowleaf balsamroot'],
    uses: 'both',
    category: 'herb',
    regions: ['or-east', 'or-klamath', 'ca-silver-lake', 'ca-shasta', 'ca-sierra-foothills'],
    habitat: 'Dry open east-side hills and sagebrush — golden sunflower displays in spring.',
    identification:
      'Large arrow-shaped fuzzy basal leaves. Big yellow sunflower-like blooms on short stems. Deep taproot and large fleshy root crown.',
    lookalikes: [
      'Mule\'s ears (Wyethia) — similar flowers; roots also historically used.',
      'Sunflowers — different leaf and root.',
    ],
    edibleNotes: 'Roasted roots and seeds — piney-resinous flavor. Young leaf stems peeled and eaten.',
    medicinalNotes: 'Resinous root used in traditional salves and teas.',
    preparation: 'Slow-roast roots. Harvest seeds in summer. Peel young stems.',
    harvestSeason: 'Spring stems; fall roots; summer seeds.',
    safetyWarnings: ['Root harvest kills plant — take sparingly from large stands.', 'Resinous flavor is strong — start with small portions.'],
    ...wikiGallery(
      ['Balsamorhiza sagittata.jpg', 'Balsamorhiza sagittata flowers.jpg', 'Balsamorhiza sagittata leaves.jpg'],
      'Wikimedia Commons — Balsamorhiza sagittata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Balsamorhiza_sagittata' }],
  },
  {
    id: 'biscuitroot',
    commonName: 'Biscuitroot',
    scientificName: 'Lomatium californicum',
    alsoKnownAs: ['California biscuitroot', 'Pestle parsnip'],
    uses: 'both',
    category: 'herb',
    regions: ['or-rogue', 'or-klamath', 'ca-north-coast', 'ca-shasta'],
    habitat: 'Dry open woodland and rocky slopes — Klamath-Siskiyou and coast range.',
    identification:
      'Finely divided fern-like leaves. Yellow umbel flowers. Thick aromatic root smelling of celery/parsley when cut.',
    lookalikes: [
      'Poison hemlock and water hemlock — umbel family — DEADLY; no aromatic biscuitroot smell.',
      'Other Lomatium — many edible with similar prep; expert ID helps.',
      'Cow parsnip — much larger, different leaf.',
    ],
    edibleNotes: 'Root dried and ground into flour for bread — traditional "biscuitroot" of the West.',
    medicinalNotes: 'Lomatium species widely used in PNW herbalism — potent; consult qualified sources.',
    preparation: 'Dry and grind root. Cook flour into cakes or thicken soups.',
    harvestSeason: 'Fall root harvest after seeds set.',
    safetyWarnings: ['Umbel family — absolute certainty required vs. hemlock.', 'Some people report skin rash from handling — gloves recommended.'],
    ...wikiGallery(
      ['Lomatium californicum.jpg', 'Lomatium californicum root.jpg', 'Lomatium californicum flowers.jpg'],
      'Wikimedia Commons — Lomatium californicum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Lomatium' }],
  },
  {
    id: 'cow-parsnip',
    commonName: 'Cow Parsnip',
    scientificName: 'Heracleum maximum',
    alsoKnownAs: ['Indian celery', 'Pushki'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-cascades', 'or-coast', 'or-klamath', 'ca-north-coast', 'ca-shasta', 'both'],
    habitat: 'Moist meadows, stream banks, and forest openings — large leafy presence.',
    identification:
      'Huge maple-like compound leaves. Thick hollow stem with purple mottling. Flat white umbel flowers — can reach 6+ feet tall.',
    lookalikes: [
      'GIANT HOGWEED (Heracleum mantegazzianum) — invasive; causes severe photodermatitis — AVOID.',
      'Poison hemlock — purple blotched stem but fern-like leaves, not maple-like.',
      'Cow parsnip leaf is MAPLE-SHAPED and huge.',
    ],
    edibleNotes: 'Young peeled leaf stalks and flower buds — celery-like when cooked. Traditional spring food.',
    preparation: 'COOK ONLY — peel young stems, boil or steam. Never eat raw.',
    harvestSeason: 'Early spring young stems — before flowers open.',
    safetyWarnings: [
      'NEVER EAT RAW — causes nausea.',
      'Sap causes PHOTODERMATITIS (phytophotodermatitis) — wear gloves; avoid sun on skin contact.',
      'Do not confuse with giant hogweed.',
      'Only young spring growth — older plant becomes inedible and more toxic.',
    ],
    ...wikiGallery(
      ['Heracleum maximum.jpg', 'Heracleum maximum flowers.jpg', 'Heracleum maximum leaves.jpg'],
      'Wikimedia Commons — Heracleum maximum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Heracleum_maximum' }],
  },
  {
    id: 'silverweed',
    commonName: 'Silverweed',
    scientificName: 'Argentina pacifica',
    alsoKnownAs: ['Pacific silverweed', 'Wild strawberry relative'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-coast', 'or-willamette', 'ca-north-coast', 'both', 'florence', 'eugene'],
    habitat: 'Coastal estuaries, tidal flats, and moist meadows — silver-backed pinnate leaves.',
    identification:
      'Pinnate leaves with silvery white undersides. Yellow five-petaled buttercup-family flowers. Creeping red runners. Small edible roots.',
    lookalikes: [
      'Cinquefoil — similar flowers but no silver leaf backs.',
      'Strawberry — trifoliate, not pinnate.',
    ],
    edibleNotes: 'Roots sweet and starchy when slow-cooked — traditional coastal food. Leaves edible in moderation.',
    preparation: 'Slow-roast or steam roots until soft and sweet.',
    harvestSeason: 'Fall and winter roots when tops dormant.',
    safetyWarnings: ['Sustainable harvest — roots are small; take sparingly.', 'Buttercup family — always cook roots.'],
    ...wikiGallery(
      ['Argentina pacifica.jpg', 'Potentilla anserina ssp pacifica.jpg', 'Argentina pacifica flowers.jpg'],
      'Wikimedia Commons — Argentina pacifica',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Argentina_pacifica' }],
  },

  // ——— Ferns ———
  {
    id: 'lady-fern-fiddleheads',
    commonName: 'Lady Fern Fiddleheads',
    scientificName: 'Athyrium filix-femina',
    uses: 'edible',
    category: 'fern',
    regions: ['or-coast', 'or-cascades', 'or-willamette', 'ca-north-coast', 'ca-shasta', 'both'],
    habitat: 'Moist shady forest and stream banks — one of the most common ferns in the PNW.',
    identification:
      'Bright green lacy fronds. Fiddleheads emerge in spring as tightly coiled green crosiers with brown papery scales (not black like bracken).',
    lookalikes: [
      'Bracken fern — triangular fronds, black stem on fiddlehead; carcinogenic concerns.',
      'Ostrich fern (E. esculentum) — edible; deep U-shaped groove on stem.',
      'Unidentified fern fiddleheads — do not eat without species ID.',
    ],
    edibleNotes: 'Mild fiddleheads — popular spring green when properly cooked.',
    preparation: 'Remove brown scales. Boil 10+ minutes or steam, then sauté. Never raw.',
    harvestSeason: 'Spring crosiers — April–May.',
    safetyWarnings: ['Never eat raw — thiaminase and other compounds.', 'Confirm species — not all ferns are edible.'],
    ...wikiGallery(
      ['Athyrium filix-femina.jpg', 'Athyrium filix-femina fiddlehead.jpg', 'Athyrium filix-femina frond.jpg'],
      'Wikimedia Commons — Athyrium filix-femina',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Athyrium_filix-femina' }],
  },
  {
    id: 'deer-fern',
    commonName: 'Deer Fern',
    scientificName: 'Blechnum spicant',
    uses: 'both',
    category: 'fern',
    regions: ['or-coast', 'or-cascades', 'ca-north-coast', 'both', 'florence'],
    habitat: 'Moist conifer forest floor — two distinct frond types (fertile brownish upright, sterile flat green).',
    identification:
      'Sterile fronds flat rosette near ground. Fertile fronds taller, narrow, with rolled-under pinnae bearing spores. Leathery texture.',
    lookalikes: [
      'Other woodland ferns — deer fern has unique dual frond types.',
      'Sword fern — single frond type, larger.',
    ],
    edibleNotes: 'Rhizomes and young fronds historically eaten — minor food; more medicinal than staple.',
    medicinalNotes: 'Coastal peoples used rhizome chews for mouth sores and digestive support.',
    preparation: 'Cook rhizomes thoroughly if used. Young fronds cooked like greens.',
    harvestSeason: 'Spring fronds; fall rhizomes.',
    safetyWarnings: ['Not a beginner fern food — cook thoroughly.', 'Harvest rhizomes sustainably — slow-growing.'],
    ...wikiGallery(
      ['Blechnum spicant.jpg', 'Blechnum spicant fertile frond.jpg', 'Blechnum spicant habitat.jpg'],
      'Wikimedia Commons — Blechnum spicant',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Blechnum_spicant' }],
  },
  {
    id: 'bracken-fiddleheads',
    commonName: 'Bracken Fiddlehead',
    scientificName: 'Pteridium aquilinum',
    alsoKnownAs: ['Eagle fern', 'Bracken fern'],
    uses: 'edible',
    category: 'fern',
    regions: ['or-coast', 'or-cascades', 'or-east', 'ca-north-coast', 'ca-shasta', 'both'],
    habitat: 'Disturbed sunny slopes, roadsides, and forest openings — aggressive colonizer.',
    identification:
      'Triangular fronds on tall stems. Fiddleheads with black/brown stem base and woolly coating. Single type of frond (not deer fern\'s dual form).',
    lookalikes: [
      'Lady fern — lacy, not triangular; green stem on fiddlehead.',
      'Ostrich fern — U-groove on stem.',
    ],
    edibleNotes: 'Eaten in many cultures when heavily processed — controversial due to carcinogen (ptaquiloside) research.',
    preparation: 'Boil in multiple changes of water 15+ minutes. Traditional soaking and salt-curing in some cultures.',
    harvestSeason: 'Spring fiddleheads only — April.',
    safetyWarnings: [
      'CONTAINS PTAQUILOSIDE — linked to cancer in animal studies; epidemiological concerns in heavy consumers.',
      'Never eat raw. Extensive cooking required.',
      'Many foragers avoid entirely — eat at your own informed risk.',
      'Do not pickle without proper processing.',
    ],
    ...wikiGallery(
      ['Pteridium aquilinum.jpg', 'Pteridium aquilinum fiddlehead.jpg', 'Pteridium aquilinum frond.jpg'],
      'Wikimedia Commons — Pteridium aquilinum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Pteridium_aquilinum' }],
  },

  // ——— Nuts & seeds ———
  {
    id: 'wild-hazelnut',
    commonName: 'Wild Hazelnut',
    scientificName: 'Corylus cornuta',
    alsoKnownAs: ['Beaked hazelnut'],
    uses: 'edible',
    category: 'shrub',
    regions: ['or-coast', 'or-cascades', 'or-willamette', 'ca-north-coast', 'ca-shasta', 'both', 'florence'],
    habitat: 'Understory of moist forest — coast range and Cascades.',
    identification:
      'Double-toothed oval leaves. Long beaked husk enclosing small nut. Catkins in winter. Often multi-stemmed shrub.',
    lookalikes: [
      'Cultivated hazelnut — larger nuts, shorter husk.',
      'Other Corylus — all edible nuts in genus.',
    ],
    edibleNotes: 'Small but rich wild nuts — ripen before husks turn fully brown (jays compete for them).',
    preparation: 'Dry and crack. Roast for best flavor. Ground into meal.',
    harvestSeason: 'Late summer — August–September before jays take them all.',
    safetyWarnings: ['Harvest green-turning-brown before wildlife does.', 'Husk hairs can irritate skin.'],
    ...wikiGallery(
      ['Corylus cornuta.jpg', 'Corylus cornuta nut.jpg', 'Corylus cornuta leaves.jpg'],
      'Wikimedia Commons — Corylus cornuta',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Corylus_cornuta' }],
  },
  {
    id: 'garry-oak-acorn',
    commonName: 'Garry Oak Acorn',
    scientificName: 'Quercus garryana',
    alsoKnownAs: ['Oregon white oak acorn'],
    uses: 'edible',
    category: 'tree',
    regions: ['or-willamette', 'or-rogue', 'ca-north-coast', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Open oak savanna and woodland — Willamette Valley and Rogue oak country.',
    identification:
      'Deeply lobed oak leaves. Acorns short-stalked with shallow scaly cap. Large spreading oak of valley floors.',
    lookalikes: [
      'Other oak acorns — all require leaching; species vary in tannin.',
      'Horse chestnut/buckeye — NOT an oak; TOXIC without proper ID.',
    ],
    edibleNotes: 'Staple Indigenous carbohydrate — sweet after proper leaching compared to many oaks.',
    preparation: 'Shell, grind, and LEACH tannins in cold or hot water repeatedly until not bitter. Then bake into mush or flour.',
    harvestSeason: 'Fall acorn drop — September–October.',
    safetyWarnings: [
      'RAW ACORNS ARE INEDIBLE — high tannins cause nausea and kidney stress.',
      'Leaching is mandatory — cold water leaching (days) or hot (repeated boils).',
      'Never skip leaching step.',
    ],
    ...wikiGallery(
      ['Quercus garryana.jpg', 'Quercus garryana acorn.jpg', 'Quercus garryana leaves.jpg'],
      'Wikimedia Commons — Quercus garryana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Quercus_garryana' }],
  },
  {
    id: 'golden-chinquapin',
    commonName: 'Golden Chinquapin',
    scientificName: 'Chrysolepis chrysophylla',
    alsoKnownAs: ['Giant chinquapin', 'Bush chinquapin'],
    uses: 'edible',
    category: 'shrub',
    regions: ['or-coast', 'or-cascades', 'or-rogue', 'ca-north-coast', 'ca-shasta'],
    habitat: 'Dry open conifer forest — understory shrub to small tree on coast and Cascades.',
    identification:
      'Evergreen serrated leaves with golden fuzzy undersides. Spiny bur enclosing single sweet nut.',
    lookalikes: [
      'Chestnut burs — related; similar spiny husk.',
      'Tanoak — different leaf; acorn not single nut in spiny bur.',
    ],
    edibleNotes: 'Sweet nut edible raw or roasted — one of the best wild nuts in the PNW.',
    preparation: 'Roast in oven or open fire. Remove from spiny bur with gloves.',
    harvestSeason: 'Fall — September–November.',
    safetyWarnings: ['Spiny burs — wear gloves.', 'Competes with squirrels — harvest promptly.'],
    ...wikiGallery(
      ['Chrysolepis chrysophylla.jpg', 'Chrysolepis chrysophylla nut.jpg', 'Chrysolepis chrysophylla leaves.jpg'],
      'Wikimedia Commons — Chrysolepis chrysophylla',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Chrysolepis_chrysophylla' }],
  },
  {
    id: 'gray-pine-nut',
    commonName: 'Gray Pine Nut',
    scientificName: 'Pinus sabiniana',
    alsoKnownAs: ['Digger pine', 'Ghost pine'],
    uses: 'edible',
    category: 'tree',
    regions: ['ca-sierra-foothills', 'ca-sacramento', 'ca-shasta'],
    habitat: 'Hot dry foothill woodland — Sacramento Valley edges and Sierra west slope.',
    identification:
      'Large heavy cones with hooked spines. Long gray-green needles in bundles of three. Irregular open crown.',
    lookalikes: [
      'Other pine nuts — all require work to extract.',
      'Ponderosa pine — lighter cones, different range.',
    ],
    edibleNotes: 'Large nutritious pine nuts — traditional California Indigenous staple.',
    preparation: 'Roast cones to open, or hammer nuts from cones. Shell small nuts patiently.',
    harvestSeason: 'Fall cone drop.',
    safetyWarnings: ['Heavy spiny cones — watch your head under trees.', 'Labor-intensive shelling.'],
    ...wikiGallery(
      ['Pinus sabiniana.jpg', 'Pinus sabiniana cone.jpg', 'Pinus sabiniana habitat.jpg'],
      'Wikimedia Commons — Pinus sabiniana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Pinus_sabiniana' }],
  },
  {
    id: 'chia',
    commonName: 'Chia',
    scientificName: 'Salvia columbariae',
    alsoKnownAs: ['Golden chia', 'Desert chia'],
    uses: 'both',
    category: 'herb',
    regions: ['ca-sierra-foothills', 'ca-sacramento', 'ca-silver-lake', 'or-east'],
    habitat: 'Dry open grassland and sagebrush — east-side Oregon fringe and California foothills.',
    identification:
      'Square mint-family stem. Small blue flowers in spiky whorls. Tiny seeds in calyx cups — swell in water.',
    lookalikes: [
      'Other Salvia — mint smell on crushed leaves.',
      'Non-mint lookalikes — verify square stem and mint odor.',
    ],
    edibleNotes: 'Seeds form gel when soaked — protein and omega-3 rich. Traditional pemmican and beverage ingredient.',
    medicinalNotes: 'Cooling demulcent seed gel — traditional thirst quencher on hot trails.',
    preparation: 'Winnow seeds. Soak in water for gel drink, or grind into meal.',
    harvestSeason: 'Summer when seed heads dry — June–July.',
    safetyWarnings: ['Ensure fully dry seeds for storage — mold risk if damp.'],
    ...wikiGallery(
      ['Salvia columbariae.jpg', 'Salvia columbariae seeds.jpg', 'Salvia columbariae flowers.jpg'],
      'Wikimedia Commons — Salvia columbariae',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Salvia_columbariae' }],
  },

  // ——— Trees & shrubs (tips, sap, aromatics) ———
  {
    id: 'spruce-tips',
    commonName: 'Spruce Tips',
    scientificName: 'Picea sitchensis',
    alsoKnownAs: ['Sitka spruce tips', 'Blue spruce tips (P. pungens in east)'],
    uses: 'both',
    category: 'tree',
    regions: ['or-coast', 'or-cascades', 'ca-north-coast', 'both', 'florence'],
    habitat: 'Coastal and montane conifer forest — harvest from Sitka spruce on coast, Engelmann/blue spruce east-side.',
    identification:
      'Soft bright green new growth at branch tips in spring. Single sharp needles. Hanging cones. Citrus-resin scent when crushed.',
    lookalikes: [
      'Fir tips — flat friendly needles (not sharp), different cone upright on branch.',
      'Yew — flat dark needles, red cup berry — TOXIC.',
      'Douglas fir (in main library) — bracts on cones, different needle.',
    ],
    edibleNotes: 'Bright citrus-pine flavor — syrup, beer, salt, and tea. High vitamin C.',
    medicinalNotes: 'Resinous tea for respiratory support — similar to fir tips.',
    preparation: 'Infuse in syrup, honey, or vinegar. Dry for tea.',
    harvestSeason: 'Soft new tips only — April–May.',
    safetyWarnings: ['Take only tips from lower branches — never top trees.', 'Sharp needles — handle gently.'],
    ...wikiGallery(
      ['Picea sitchensis.jpg', 'Picea sitchensis cones.jpg', 'Spruce tips.jpg'],
      'Wikimedia Commons — Picea sitchensis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Picea_sitchensis' }],
  },
  {
    id: 'grand-fir-tips',
    commonName: 'Grand Fir Tips',
    scientificName: 'Abies grandis',
    uses: 'both',
    category: 'tree',
    regions: ['or-coast', 'or-willamette', 'or-cascades', 'ca-north-coast', 'both', 'eugene'],
    habitat: 'Low to mid-elevation moist forest — west-side valleys and coast range.',
    identification:
      'Flat needles with two white stomatal bands underneath — no prickles (friendly fir). Upright cones on branches. Balsam-scented blister resin on bark.',
    lookalikes: [
      'Douglas fir — not a true fir; single bracts on cones.',
      'Spruce — sharp square needles rolled in fingers.',
      'Hemlock — small cones, different needle arrangement.',
    ],
    edibleNotes: 'Grapefruit-balsam flavored tips — among the best conifer tips for syrup and tea.',
    medicinalNotes: 'Balsam resin traditionally used topically; tip tea for chest congestion.',
    preparation: 'Spring tip syrup, tea, or infused salt.',
    harvestSeason: 'April–May soft tips.',
    safetyWarnings: ['Sustainable harvest — few tips per branch.'],
    ...wikiGallery(
      ['Abies grandis.jpg', 'Abies grandis cones.jpg', 'Abies grandis needles.jpg'],
      'Wikimedia Commons — Abies grandis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Abies_grandis' }],
  },
  {
    id: 'bigleaf-maple-sap',
    commonName: 'Bigleaf Maple Sap',
    scientificName: 'Acer macrophyllum',
    uses: 'edible',
    category: 'tree',
    regions: ['or-coast', 'or-willamette', 'ca-north-coast', 'both', 'florence', 'eugene'],
    habitat: 'Moist lowland forest — dominant maple of west-side riparian zones.',
    identification:
      'Largest leaves of any maple — up to 12 inches across. Five lobes. Winged samaras in pairs. Moss-covered branches common.',
    lookalikes: [
      'Vine maple — smaller leaves, shrubbier.',
      'Other maples — all produce sap but bigleaf is the PNW species.',
    ],
    edibleNotes: 'Sap makes delicate syrup — lower sugar than sugar maple but unique flavor. Also sap drink fresh.',
    preparation: 'Tap in late winter. Boil sap down 40:1 or more for syrup.',
    harvestSeason: 'Late winter sap run — February–March during freeze-thaw cycles.',
    safetyWarnings: ['Tap only healthy large trees — small hole, proper spile.', 'Boil sap outdoors — heavy steam.'],
    ...wikiGallery(
      ['Acer macrophyllum.jpg', 'Acer macrophyllum leaves.jpg', 'Acer macrophyllum samaras.jpg'],
      'Wikimedia Commons — Acer macrophyllum',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Acer_macrophyllum' }],
  },
  {
    id: 'yerba-buena',
    commonName: 'Yerba Buena',
    scientificName: 'Clinopodium douglasii',
    alsoKnownAs: ['Oregon tea', 'Indian mint'],
    uses: 'both',
    category: 'herb',
    regions: ['or-coast', 'or-willamette', 'ca-north-coast', 'both', 'florence', 'eugene'],
    habitat: 'Shady forest floor trailing vine — coast range and lowland forest.',
    identification:
      'Trailing square-stemmed mint with tiny rounded leaves. Strong mint aroma when crushed. Small white flowers.',
    lookalikes: [
      'Wild mint (in main library) — upright, larger leaves.',
      'Other mints — mint smell confirms family.',
    ],
    edibleNotes: 'Classic PNW forest tea — mild mint flavor. Leaves for tea and garnish.',
    medicinalNotes: 'Cooling digestive tea — traditional stomach soother.',
    preparation: 'Fresh or dried leaf tea. Cold infusion preferred by some.',
    harvestSeason: 'Spring through fall — year-round in mild coast.',
    safetyWarnings: ['Trailing habit — harvest from clean forest floor.'],
    ...wikiGallery(
      ['Clinopodium douglasii.jpg', 'Clinopodium douglasii leaves.jpg', 'Clinopodium douglasii flowers.jpg'],
      'Wikimedia Commons — Clinopodium douglasii',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Clinopodium_douglasii' }],
  },
  {
    id: 'mugwort',
    commonName: 'Mugwort',
    scientificName: 'Artemisia douglasiana',
    alsoKnownAs: ['Douglas mugwort', 'Dream plant'],
    uses: 'both',
    category: 'herb',
    regions: ['or-coast', 'or-willamette', 'ca-north-coast', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Stream banks, open woodland, and disturbed moist ground.',
    identification:
      'Tall aromatic silvery-green leaves, white-woolly underneath. Pungent sage-camphor smell. Small greenish flower spikes.',
    lookalikes: [
      'Wormwood (A. absinthium) — more silvery, bitter.',
      'Other Artemisia — aromatic family; verify regional species.',
    ],
    edibleNotes: 'Used as bitter aromatic seasoning in small amounts — rice cakes and mochi wrapping in Asian traditions.',
    medicinalNotes: 'Dream pillow herb, moxibustion, and digestive bitter — powerful; not for pregnancy.',
    preparation: 'Small amounts as food seasoning. Dry for tea or dream sachets.',
    harvestSeason: 'Before flowering — summer.',
    safetyWarnings: ['AVOID IN PREGNANCY — stimulates uterus.', 'Strong herb — small culinary doses only.'],
    ...wikiGallery(
      ['Artemisia douglasiana.jpg', 'Artemisia douglasiana leaves.jpg', 'Artemisia douglasiana habitat.jpg'],
      'Wikimedia Commons — Artemisia douglasiana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Artemisia_douglasiana' }],
  },
  {
    id: 'sweet-cicely',
    commonName: 'Sweet Cicely',
    scientificName: 'Osmorhiza occidentalis',
    alsoKnownAs: ['Western sweet cicely', 'Western sweetroot'],
    uses: 'both',
    category: 'herb',
    regions: ['or-cascades', 'or-coast', 'ca-north-coast', 'ca-shasta', 'both'],
    habitat: 'Moist shady forest — understory of conifer and mixed woods.',
    identification:
      'Fern-like divided leaves with anise-licorice smell when crushed. Small white umbel flowers. Long slender aromatic roots.',
    lookalikes: [
      'Poison hemlock — NO anise smell — DEADLY.',
      'Other Osmorhiza — anise scent confirms edible group.',
      'Sweet cicely vs. hemlock: CRUSH AND SMELL — anise = sweet cicely.',
    ],
    edibleNotes: 'Anise-flavored roots, leaves, and green seeds — natural sweetener quality.',
    medicinalNotes: 'Soothing stomach herb — anise flavor aids digestion.',
    preparation: 'Use young leaves and seeds in salads. Cook roots or chew as trail nibble.',
    harvestSeason: 'Spring leaves; fall roots; early summer green seeds.',
    safetyWarnings: ['Anise smell is critical ID vs. hemlock.', 'Umbel family — never eat without smell test.'],
    ...wikiGallery(
      ['Osmorhiza occidentalis.jpg', 'Osmorhiza occidentalis flowers.jpg', 'Osmorhiza occidentalis root.jpg'],
      'Wikimedia Commons — Osmorhiza occidentalis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Osmorhiza' }],
  },
  {
    id: 'california-bay-laurel',
    commonName: 'California Bay Laurel',
    scientificName: 'Umbellularia californica',
    alsoKnownAs: ['Oregon myrtle', 'Pepperwood'],
    uses: 'both',
    category: 'tree',
    regions: ['or-coast', 'or-rogue', 'ca-north-coast', 'ca-shasta'],
    habitat: 'Moist canyon woodland — southwest Oregon and northern California.',
    identification:
      'Evergreen lance leaves with peppery bay aroma when crushed. Yellow-green four-petaled flowers. Green oval drupes.',
    lookalikes: [
      'Mediterranean bay laurel — similar smell but cultivated; smaller leaves.',
      'Madrona — different bark and berry.',
    ],
    edibleNotes: 'Leaves used SPARINGLY as spice — much stronger than Mediterranean bay. Nuts roasted (after leaching).',
    medicinalNotes: 'Headache remedy in some traditions — volatile oils are potent.',
    preparation: 'Use 1/4 the amount of regular bay leaves. Roast nuts after leaching like acorns.',
    harvestSeason: 'Leaves year-round; nuts fall — October.',
    safetyWarnings: [
      'Leaves are VERY strong — overuse causes headache and nausea.',
      'Use sparingly in cooking — start with tiny amounts.',
      'Headache tree nickname is literal.',
    ],
    ...wikiGallery(
      ['Umbellularia californica.jpg', 'Umbellularia californica leaves.jpg', 'Umbellularia californica fruit.jpg'],
      'Wikimedia Commons — Umbellularia californica',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Umbellularia_californica' }],
  },

  // ——— Seaweeds (coast) ———
  {
    id: 'bull-kelp',
    commonName: 'Bull Kelp',
    scientificName: 'Nereocystis luetkeana',
    uses: 'edible',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'both', 'florence'],
    habitat: 'Pacific sub-tidal and low intertidal — floating canopy with bulb and long stipe from rocky coast.',
    identification:
      'Large floating bulb at surface connected to long stipe. Broad blade fronds. Grows in kelp forests visible from shore.',
    lookalikes: [
      'Other kelp species — generally edible with similar prep.',
      'Detritus or drift — harvest fresh attached or recently washed up cold.',
    ],
    edibleNotes: 'Stipe pickles ("kelp pickles"), dried flakes for dashi, and fresh fronds in soups.',
    preparation: 'Pickle stipes, dry fronds for seasoning, or blanch before use.',
    harvestSeason: 'Year-round; best spring–summer growth.',
    safetyWarnings: ['Check local harvest rules and limits.', 'Only from clean cold ocean water.', 'Slippery on rocks — safety first.'],
    ...wikiGallery(
      ['Nereocystis luetkeana.jpg', 'Nereocystis luetkeana forest.jpg', 'Nereocystis luetkeana stipe.jpg'],
      'Wikimedia Commons — Nereocystis luetkeana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Nereocystis_luetkeana' }],
  },
  {
    id: 'sea-palm',
    commonName: 'Sea Palm',
    scientificName: 'Postelsia palmaeformis',
    alsoKnownAs: ['Palm kelp'],
    uses: 'edible',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'florence'],
    habitat: 'Surf-swept rocky headlands — only where waves crash. Iconic tufted kelp looks like tiny palm trees.',
    identification:
      'Short stipe with dense cluster of finger-like fronds. Only on exposed surf zones. Distinctive palm-tree silhouette.',
    lookalikes: [
      'Other small kelps — sea palm is uniquely surf-zone and palm-shaped.',
    ],
    edibleNotes: 'Prized crunchy texture — eaten raw or dried. Commercially popular PNW seaweed snack.',
    preparation: 'Rinse and eat raw, roast until crisp, or add to soups.',
    harvestSeason: 'Summer low tides on calm days.',
    safetyWarnings: [
      'HARVEST ONLY WITH EXTREME CAUTION — surf zone is dangerous.',
      'Protected in some areas — check regulations.',
      'Never turn back to the ocean on slippery rocks.',
    ],
    ...wikiGallery(
      ['Postelsia palmaeformis.jpg', 'Postelsia palmaeformis habitat.jpg', 'Postelsia palmaeformis closeup.jpg'],
      'Wikimedia Commons — Postelsia palmaeformis',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Postelsia_palmaeformis' }],
  },
  {
    id: 'sea-lettuce',
    commonName: 'Sea Lettuce',
    scientificName: 'Ulva lactuca',
    uses: 'edible',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'both', 'florence'],
    habitat: 'Intertidal rocks, tide pools, and sheltered bays — bright green sheets.',
    identification:
      'Bright green thin ruffled sheets resembling lettuce. No midrib. Soft texture when fresh.',
    lookalikes: [
      'Enteromorpha (Ulva) species — similar edible greens.',
      'Green algae films — verify sheet structure.',
    ],
    edibleNotes: 'Mild green salad seaweed — raw in salads or dried as flakes.',
    preparation: 'Rinse well. Raw in salads or brief blanch. Dry for seasoning.',
    harvestSeason: 'Spring through fall — bright green growth.',
    safetyWarnings: ['Do not harvest from polluted bays — absorbs nutrients/toxins.', 'Rinse sand thoroughly.'],
    ...wikiGallery(
      ['Ulva lactuca.jpg', 'Ulva lactuca habitat.jpg', 'Ulva lactuca closeup.jpg'],
      'Wikimedia Commons — Ulva lactuca',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ulva_lactuca' }],
  },
  {
    id: 'bladderwrack',
    commonName: 'Bladderwrack',
    scientificName: 'Fucus gardneri',
    alsoKnownAs: ['Rockweed', 'Popweed (when popping bladders)'],
    uses: 'both',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'florence'],
    habitat: 'Mid intertidal rocky shore — branched fronds with paired float bladders.',
    identification:
      'Olive-brown branched fronds with midrib and paired air bladders that pop when squeezed. Forked tips.',
    lookalikes: [
      'Other Fucus species — similar and edible.',
      'Sargassum — different range (more southern).',
    ],
    edibleNotes: 'Blanched fronds as vegetable. Bladders pop for fun trail snack. Rich in minerals.',
    medicinalNotes: 'Traditional iodine and thyroid support source — moderation essential.',
    preparation: 'Blanch or pickle. Use in broth. Dry for powder.',
    harvestSeason: 'Year-round at low tide.',
    safetyWarnings: ['Iodine content — avoid excess if thyroid sensitive.', 'Clean ocean only.'],
    ...wikiGallery(
      ['Fucus gardneri.jpg', 'Fucus vesiculosus bladders.jpg', 'Fucus gardneri habitat.jpg'],
      'Wikimedia Commons — Fucus gardneri',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Fucus' }],
  },
  {
    id: 'nori-laver',
    commonName: 'Nori / Laver',
    scientificName: 'Porphyra abbottiae',
    alsoKnownAs: ['Pacific nori', 'Laver seaweed'],
    uses: 'edible',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'florence'],
    habitat: 'High intertidal rocks — thin purple-red film to ruffled sheets.',
    identification:
      'Purple-red to greenish thin sheet algae on rocks. Nearly translucent when fresh. Same genus as sushi nori.',
    lookalikes: [
      'Other Porphyra/Pyropia — all generally edible laver types.',
      'Irish moss — different texture.',
    ],
    edibleNotes: 'Classic nori when dried — toast on skillet until crisp. Traditional "black butter" and sheets.',
    preparation: 'Dry and toast into nori sheets, or fry fresh in butter.',
    harvestSeason: 'Winter and spring growth — best after storms.',
    safetyWarnings: ['Rinse grit thoroughly.', 'Harvest from clean surf-exposed rocks.'],
    ...wikiGallery(
      ['Porphyra abbottiae.jpg', 'Porphyra umbilicalis.jpg', 'Pyropia perforata.jpg'],
      'Wikimedia Commons — Porphyra',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Porphyra' }],
  },
  {
    id: 'rockweed',
    commonName: 'Rockweed',
    scientificName: 'Pelvetiopsis limitata',
    alsoKnownAs: ['Little rockweed', 'False lily'],
    uses: 'edible',
    category: 'seaweed',
    regions: ['or-coast', 'ca-north-coast', 'florence'],
    habitat: 'High intertidal splash zone on rocks — small olive fronds with pointed tips, no bladders.',
    identification:
      'Small forked olive-brown fronds with distinctive pointed tips. No air bladders (unlike Fucus). Grows above barnacle zone.',
    lookalikes: [
      'Bladderwrack (Fucus) — has paired bladders.',
      'Other high-zone seaweeds — verify forked tips.',
    ],
    edibleNotes: 'Tender tips in spring — steamed or added to broth. Traditional coastal nibble.',
    preparation: 'Steam tips or dry for broth powder.',
    harvestSeason: 'Spring tender growth.',
    safetyWarnings: ['Small harvests — intertidal zone stewardship.', 'Clean water only.'],
    ...wikiGallery(
      ['Pelvetiopsis limitata.jpg', 'Pelvetiopsis limitata habitat.jpg', 'Pelvetiopsis limitata closeup.jpg'],
      'Wikimedia Commons — Pelvetiopsis limitata',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Pelvetiopsis' }],
  },

  // ——— Other PNW edibles ———
  {
    id: 'pickleweed',
    commonName: 'Pickleweed',
    scientificName: 'Salicornia pacifica',
    alsoKnownAs: ['Sea asparagus', 'Glasswort', 'Marsh samphire'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-coast', 'ca-north-coast', 'ca-sacramento', 'florence'],
    habitat: 'Salt marshes and tidal flats — jointed succulent stems in saline wetlands.',
    identification:
      'Jointed succulent green-to-red stems resembling tiny cactus without spines. No true leaves visible. Grows in salt marsh.',
    lookalikes: [
      'Other Salicornia — all generally edible salt marsh plants.',
      'Sea blite — different branching.',
    ],
    edibleNotes: 'Crisp salty "sea asparagus" — blanch or pickle. Trendy restaurant green from wild marshes.',
    preparation: 'Blanch 30 seconds, sauté in butter, or pickle in vinegar.',
    harvestSeason: 'Summer–fall when green and plump.',
    safetyWarnings: ['Salt marsh only — do not confuse with inland plants.', 'Check tidal access safety.'],
    ...wikiGallery(
      ['Salicornia pacifica.jpg', 'Salicornia europaea.jpg', 'Salicornia pacifica marsh.jpg'],
      'Wikimedia Commons — Salicornia',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Salicornia' }],
  },
  {
    id: 'sea-rocket',
    commonName: 'Sea Rocket',
    scientificName: 'Cakile edentula',
    alsoKnownAs: ['American sea rocket'],
    uses: 'edible',
    category: 'herb',
    regions: ['or-coast', 'ca-north-coast', 'florence'],
    habitat: 'Sandy beaches and dunes above high tide line.',
    identification:
      'Fleshy succulent leaves on sand. Four-petaled white to lavender flowers. Peppery mustard-family taste. Pod splits into two corky segments.',
    lookalikes: [
      'Beach mustard — similar habitat and family.',
      'Orach on dunes — different leaf shape.',
    ],
    edibleNotes: 'Peppery succulent leaves and young seed pods — beach salad green.',
    preparation: 'Raw in salads or quick pickle of pods.',
    harvestSeason: 'Spring through summer on dunes.',
    safetyWarnings: ['Dune habitat fragile — step carefully on established paths.', 'Rinse sand.'],
    ...wikiGallery(
      ['Cakile edentula.jpg', 'Cakile maritima flowers.jpg', 'Cakile edentula habitat.jpg'],
      'Wikimedia Commons — Cakile',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cakile' }],
  },
  {
    id: 'elderflower',
    commonName: 'Elderflower',
    scientificName: 'Sambucus cerulea',
    alsoKnownAs: ['Blue elderflower'],
    uses: 'both',
    category: 'shrub',
    regions: ['or-willamette', 'or-coast', 'or-cascades', 'ca-north-coast', 'ca-sacramento', 'both', 'eugene'],
    habitat: 'Same as blue elderberry — stream banks, open woods, sunny edges. Flower harvest is separate focus from berry entry in main library.',
    identification:
      'Large flat cream-white flower clusters (corymbs) in late spring. Compound opposite leaves. Reddish stems. Must confirm blue elder, NOT red elder.',
    lookalikes: [
      'Red elderberry (S. racemosa) — upright CONICAL red-fruited cluster later; flowers similar — TOXIC berries.',
      'Blue elder (S. cerulea) — flat flower cluster, blue berries later.',
      'Red elder flowers in conical cluster; blue elder flowers in flat broad corymb.',
    ],
    edibleNotes: 'Floral fritters, cordial, and champagne — classic spring delicacy. Remove most stems.',
    medicinalNotes: 'Cooling diaphoretic flower tea — traditional fever support.',
    preparation: 'Infuse flowers in syrup, cordial, or batter for fritters. Strain out insects and stems.',
    harvestSeason: 'Late spring flowers — May–June.',
    safetyWarnings: [
      'Confirm BLUE elder (S. cerulea) — flat flower cluster.',
      'RED elder (S. racemosa) has conical flower/berry cluster — berries TOXIC raw.',
      'Do not eat large amounts of stems or leaves — cyanogenic compounds.',
    ],
    ...wikiGallery(
      ['Sambucus cerulea flowers.jpg', 'Sambucus cerulea.jpg', 'Sambucus cerulea inflorescence.jpg'],
      'Wikimedia Commons — Sambucus cerulea',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sambucus_cerulea' }],
  },
  {
    id: 'nootka-rose-hips',
    commonName: 'Nootka Rose Hips',
    scientificName: 'Rosa nutkana',
    alsoKnownAs: ['Wild rose hips'],
    uses: 'both',
    category: 'berry',
    regions: ['or-coast', 'or-willamette', 'or-cascades', 'ca-north-coast', 'both', 'eugene', 'florence'],
    habitat: 'Focus on fall hip harvest from stream banks and sunny openings — complements the main library Nootka rose entry with hip-specific foraging detail.',
    identification:
      'Large red-orange rose hips with persistent sepals at tip. Thorny stems. Hips round to pear-shaped, 1–2 cm. Seeds and hairs inside.',
    lookalikes: [
      'Baldhip rose (R. gymnocarpa) — hips lose sepals early; same hair caution.',
      'Himalayan blackberry fruit — aggregate, not a hip.',
    ],
    edibleNotes: 'Among the highest vitamin C wild foods — tart apple-like flavor in tea, syrup, and jelly.',
    medicinalNotes: 'Astringent hip tea for digestive and winter immune support.',
    preparation: 'Halve and scrape out hairy seeds, or cook whole and strain through jelly bag. Never eat hairs.',
    harvestSeason: 'After first frost — October–November when fully colored.',
    safetyWarnings: [
      'IRRITATING HAIRS inside hips — always strain or scoop out seeds and hairs.',
      'Do not eat hips whole without processing.',
    ],
    ...wikiGallery(
      ['Rosa nutkana hips.jpg', 'Rosa nutkana fruit.jpg', 'Rosa nutkana hip closeup.jpg'],
      'Wikimedia Commons — Rosa nutkana',
    ),
    externalLinks: [{ label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rosa_nutkana' }],
  },
];
