import type { ErrorCode } from './types';

export const poolErrorCodes: ErrorCode[] = [
  {
    id: 'pentair-df',
    packId: 'pool',
    brand: 'Pentair IntelliFlo',
    code: 'df',
    meaning: 'Drive failure / fault',
    fix: ['Power cycle 1 minute', 'Check supply voltage', 'Inspect drive for heat damage', 'Replace drive if persistent'],
    severity: 'high',
  },
  {
    id: 'pentair-svrs',
    packId: 'pool',
    brand: 'Pentair',
    code: 'SVRS',
    meaning: 'Safety vacuum release / priming protection event',
    fix: ['Clear suction obstruction', 'Check for closed valves', 'Inspect drain covers', 'Reset per manual'],
    severity: 'critical',
  },
  {
    id: 'hayward-tri',
    packId: 'pool',
    brand: 'Hayward TriStar VS',
    code: 'TRIP',
    meaning: 'Drive tripped on fault',
    fix: ['Note subcode', 'Verify priming', 'Check voltage', 'Clear debris from impeller'],
    severity: 'high',
  },
  {
    id: 'hayward-salt-low',
    packId: 'pool',
    brand: 'Hayward AquaRite',
    code: 'LOW SALT',
    meaning: 'Salt below threshold or cell scaled/failing',
    fix: ['Verify salt with meter', 'Inspect/clean cell', 'Check water temp', 'Replace cell if weak'],
    severity: 'medium',
  },
  {
    id: 'jandy-flo',
    packId: 'pool',
    brand: 'Jandy/Zodiac',
    code: 'FLO',
    meaning: 'Flow fault at heater or SWG',
    fix: ['Clean filter', 'Open valves', 'Check pump speed', 'Verify flow switch'],
    severity: 'high',
  },
  {
    id: 'jandy-ign',
    packId: 'pool',
    brand: 'Jandy heater',
    code: 'IGN',
    meaning: 'Ignition failure',
    fix: ['Clean flame sensor', 'Check gas supply', 'Inspect igniter', 'Verify venting'],
    severity: 'high',
  },
  {
    id: 'pentair-heater-ag',
    packId: 'pool',
    brand: 'Pentair MasterTemp',
    code: 'AG',
    meaning: 'Airflow / vent related fault (verify exact legend for model)',
    fix: ['Clear intake/exhaust', 'Check blower', 'Inspect pressure switch tubing'],
    severity: 'high',
  },
  {
    id: 'generic-heater-hl',
    packId: 'pool',
    brand: 'Generic heater',
    code: 'HL / HIGH LIMIT',
    meaning: 'High limit opened',
    fix: ['Verify flow', 'Check bypass', 'Test high-limit switch', 'Look for scale in heat exchanger'],
    severity: 'high',
  },
];

export const electricalErrorCodes: ErrorCode[] = [
  {
    id: 'afci-arc',
    packId: 'electrical',
    brand: 'AFCI',
    code: 'ARC / AF',
    meaning: 'Arc fault detected',
    fix: ['Inspect damaged cords', 'Retorque connections', 'Check shared neutrals', 'Replace weak AFCI if wiring clean'],
    severity: 'high',
  },
  {
    id: 'gfci-trip',
    packId: 'electrical',
    brand: 'GFCI',
    code: 'TRIP',
    meaning: 'Ground fault current detected',
    fix: ['Unplug loads', 'Dry/replace wet devices', 'Megger cable', 'Fix neutral-ground bonds downstream'],
    severity: 'high',
  },
  {
    id: 'motor-ol',
    packId: 'electrical',
    brand: 'Motor starter',
    code: 'OL',
    meaning: 'Thermal overload',
    fix: ['Measure amps vs FLA', 'Check voltage', 'Allow cool-down', 'Inspect mechanical load'],
    severity: 'medium',
  },
  {
    id: 'vfd-oc',
    packId: 'electrical',
    brand: 'VFD',
    code: 'OC',
    meaning: 'Overcurrent',
    fix: ['Check mechanical bind', 'Verify motor data in drive', 'Inspect output cables', 'Ramp time adjust'],
    severity: 'high',
  },
  {
    id: 'vfd-ou',
    packId: 'electrical',
    brand: 'VFD',
    code: 'Ou / OV',
    meaning: 'Overvoltage (often decel/regen)',
    fix: ['Extend decel time', 'Check supply spikes', 'Brake resistor if equipped'],
    severity: 'medium',
  },
  {
    id: 'panel-surge',
    packId: 'electrical',
    brand: 'SPD',
    code: 'END OF LIFE',
    meaning: 'Surge protector spent',
    fix: ['Replace SPD module', 'Inspect after known surge event'],
    severity: 'medium',
  },
];

export const plumbingErrorCodes: ErrorCode[] = [
  {
    id: 'rinnai-10',
    packId: 'plumbing',
    brand: 'Rinnai tankless',
    code: '10',
    meaning: 'Air supply or exhaust blockage',
    fix: ['Check intake/exhaust for obstructions', 'Verify vent terminations', 'Inspect fan operation'],
    severity: 'high',
  },
  {
    id: 'rinnai-11',
    packId: 'plumbing',
    brand: 'Rinnai tankless',
    code: '11',
    meaning: 'Ignition failure',
    fix: ['Verify gas supply', 'Check igniter and flame rod', 'Confirm proper gas pressure'],
    severity: 'high',
  },
  {
    id: 'navien-e003',
    packId: 'plumbing',
    brand: 'Navien',
    code: 'E003',
    meaning: 'Ignition failure',
    fix: ['Check gas valve', 'Clean flame rod', 'Verify inlet gas pressure'],
    severity: 'high',
  },
  {
    id: 'navien-e012',
    packId: 'plumbing',
    brand: 'Navien',
    code: 'E012',
    meaning: 'Flame loss during operation',
    fix: ['Inspect venting', 'Clean flame rod', 'Check condensate blockage'],
    severity: 'high',
  },
  {
    id: 'moen-1222',
    packId: 'plumbing',
    brand: 'Moen Posi-Temp',
    code: 'No hot / scald',
    meaning: 'Cartridge balance spool stuck or failed',
    fix: ['Shut off stops', 'Remove handle and clip', 'Replace 1222 cartridge'],
    severity: 'medium',
  },
  {
    id: 'zoeller-epm',
    packId: 'plumbing',
    brand: 'Zoeller sump',
    code: 'EPM / no run',
    meaning: 'Pump not responding — float or power',
    fix: ['Check breaker and float switch', 'Test pump plug direct', 'Inspect impeller for jam'],
    severity: 'high',
  },
  {
    id: 'watts-rpz',
    packId: 'plumbing',
    brand: 'Watts RPZ',
    code: 'Relief dripping',
    meaning: 'Check valve #2 failure or high supply pressure',
    fix: ['Test per AWWA procedure', 'Rebuild or replace assembly', 'Verify supply pressure and PRV'],
    severity: 'medium',
  },
  {
    id: 'bradford-white-flash',
    packId: 'plumbing',
    brand: 'Bradford White',
    code: '4 flashes',
    meaning: 'Temperature sensor fault (verify model chart)',
    fix: ['Check sensor connections', 'Replace sensor per manual', 'Reset power'],
    severity: 'medium',
  },
];

export const hvacErrorCodes: ErrorCode[] = [
  {
    id: 'carrier-33',
    packId: 'hvac',
    brand: 'Carrier/Bryant',
    code: '33',
    meaning: 'Limit switch fault / high limit open',
    fix: ['Verify airflow and filter', 'Check blower operation', 'Inspect heat exchanger', 'Reset after cause fixed'],
    severity: 'high',
  },
  {
    id: 'carrier-13',
    packId: 'hvac',
    brand: 'Carrier/Bryant',
    code: '13',
    meaning: 'Ignition lockout',
    fix: ['Clean flame sensor', 'Check gas supply', 'Inspect ignitor', 'Verify inducer pressure switch'],
    severity: 'high',
  },
  {
    id: 'trane-126',
    packId: 'hvac',
    brand: 'Trane/American Standard',
    code: '126',
    meaning: 'Communication fault between modules',
    fix: ['Check comm wiring', 'Verify grounds', 'Power-cycle system', 'Replace board if persistent'],
    severity: 'high',
  },
  {
    id: 'lennox-e227',
    packId: 'hvac',
    brand: 'Lennox',
    code: 'E227',
    meaning: 'Low refrigerant / pressure switch',
    fix: ['Leak search before recharge', 'Verify indoor airflow', 'Check filter and coil'],
    severity: 'high',
  },
  {
    id: 'goodman-flash-6',
    packId: 'hvac',
    brand: 'Goodman/Amana',
    code: '6 flashes',
    meaning: 'Open roll-out switch / flame rollout',
    fix: ['Inspect heat exchanger', 'Check flue', 'Do not bypass safety', 'Call for combustion service'],
    severity: 'critical',
  },
  {
    id: 'nest-e195',
    packId: 'hvac',
    brand: 'Nest',
    code: 'E195',
    meaning: 'No power to thermostat (C wire / transformer)',
    fix: ['Check furnace door switch', 'Verify 24VAC R–C', 'Inspect fuse on board', 'Add common if battery-only'],
    severity: 'medium',
  },
  {
    id: 'ecobee-calibrating',
    packId: 'hvac',
    brand: 'Ecobee',
    code: 'Calibrating / blank',
    meaning: 'Boot or power dip during calibration',
    fix: ['Wait 5–10 min', 'Check C wire', 'Verify 24VAC at subbase'],
    severity: 'low',
  },
  {
    id: 'mitsubishi-6607',
    packId: 'hvac',
    brand: 'Mitsubishi mini-split',
    code: '6607',
    meaning: 'Outdoor communication error',
    fix: ['Check S1/S2/S3 wiring', 'Verify dip switches', 'Inspect outdoor board fuses'],
    severity: 'high',
  },
];
