import type { ErrorCode } from './types';

export const poolErrorCodes: ErrorCode[] = [
  {
    id: 'pentair-df',
    packId: 'pool',
    brand: 'Pentair IntelliFlo',
    code: 'df',
    meaning: 'Drive failure / fault',
    fix: ['Power cycle 1 minute', 'Check supply voltage', 'Inspect drive for heat damage', 'Replace drive if persistent'],
    severity: 'high',
  },
  {
    id: 'pentair-svrs',
    packId: 'pool',
    brand: 'Pentair',
    code: 'SVRS',
    meaning: 'Safety vacuum release / priming protection event',
    fix: ['Clear suction obstruction', 'Check for closed valves', 'Inspect drain covers', 'Reset per manual'],
    severity: 'critical',
  },
  {
    id: 'hayward-tri',
    packId: 'pool',
    brand: 'Hayward TriStar VS',
    code: 'TRIP',
    meaning: 'Drive tripped on fault',
    fix: ['Note subcode', 'Verify priming', 'Check voltage', 'Clear debris from impeller'],
    severity: 'high',
  },
  {
    id: 'hayward-salt-low',
    packId: 'pool',
    brand: 'Hayward AquaRite',
    code: 'LOW SALT',
    meaning: 'Salt below threshold or cell scaled/failing',
    fix: ['Verify salt with meter', 'Inspect/clean cell', 'Check water temp', 'Replace cell if weak'],
    severity: 'medium',
  },
  {
    id: 'jandy-flo',
    packId: 'pool',
    brand: 'Jandy/Zodiac',
    code: 'FLO',
    meaning: 'Flow fault at heater or SWG',
    fix: ['Clean filter', 'Open valves', 'Check pump speed', 'Verify flow switch'],
    severity: 'high',
  },
  {
    id: 'jandy-ign',
    packId: 'pool',
    brand: 'Jandy heater',
    code: 'IGN',
    meaning: 'Ignition failure',
    fix: ['Clean flame sensor', 'Check gas supply', 'Inspect igniter', 'Verify venting'],
    severity: 'high',
  },
  {
    id: 'pentair-heater-ag',
    packId: 'pool',
    brand: 'Pentair MasterTemp',
    code: 'AG',
    meaning: 'Airflow / vent related fault (verify exact legend for model)',
    fix: ['Clear intake/exhaust', 'Check blower', 'Inspect pressure switch tubing'],
    severity: 'high',
  },
  {
    id: 'generic-heater-hl',
    packId: 'pool',
    brand: 'Generic heater',
    code: 'HL / HIGH LIMIT',
    meaning: 'High limit opened',
    fix: ['Verify flow', 'Check bypass', 'Test high-limit switch', 'Look for scale in heat exchanger'],
    severity: 'high',
  },
];

export const electricalErrorCodes: ErrorCode[] = [
  {
    id: 'afci-arc',
    packId: 'electrical',
    brand: 'AFCI',
    code: 'ARC / AF',
    meaning: 'Arc fault detected',
    fix: ['Inspect damaged cords', 'Retorque connections', 'Check shared neutrals', 'Replace weak AFCI if wiring clean'],
    severity: 'high',
  },
  {
    id: 'gfci-trip',
    packId: 'electrical',
    brand: 'GFCI',
    code: 'TRIP',
    meaning: 'Ground fault current detected',
    fix: ['Unplug loads', 'Dry/replace wet devices', 'Megger cable', 'Fix neutral-ground bonds downstream'],
    severity: 'high',
  },
  {
    id: 'motor-ol',
    packId: 'electrical',
    brand: 'Motor starter',
    code: 'OL',
    meaning: 'Thermal overload',
    fix: ['Measure amps vs FLA', 'Check voltage', 'Allow cool-down', 'Inspect mechanical load'],
    severity: 'medium',
  },
  {
    id: 'vfd-oc',
    packId: 'electrical',
    brand: 'VFD',
    code: 'OC',
    meaning: 'Overcurrent',
    fix: ['Check mechanical bind', 'Verify motor data in drive', 'Inspect output cables', 'Ramp time adjust'],
    severity: 'high',
  },
  {
    id: 'vfd-ou',
    packId: 'electrical',
    brand: 'VFD',
    code: 'Ou / OV',
    meaning: 'Overvoltage (often decel/regen)',
    fix: ['Extend decel time', 'Check supply spikes', 'Brake resistor if equipped'],
    severity: 'medium',
  },
  {
    id: 'panel-surge',
    packId: 'electrical',
    brand: 'SPD',
    code: 'END OF LIFE',
    meaning: 'Surge protector spent',
    fix: ['Replace SPD module', 'Inspect after known surge event'],
    severity: 'medium',
  },
];
