import type { GuidedFlow } from './types';

export const guidedFlows: GuidedFlow[] = [
  {
    id: 'pool-no-flow',
    packId: 'pool',
    title: 'No flow / weak returns',
    description: 'Guided triage from pump basket to filter to returns.',
    startStepId: 'power',
    steps: {
      power: {
        id: 'power',
        prompt: 'Is the pump powered and trying to run (hum, display on, shaft attempting)?',
        yesNext: 'basket',
        noNext: 'result-power',
      },
      basket: {
        id: 'basket',
        prompt: 'Is the pump basket full of water with the lid sealed and minimal air bubbles?',
        yesNext: 'pressure',
        noNext: 'result-prime',
      },
      pressure: {
        id: 'pressure',
        prompt: 'Is filter pressure high vs the clean baseline?',
        yesNext: 'result-filter',
        noNext: 'result-suction',
      },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'pool-pump-hum-no-spin' },
      'result-prime': { id: 'result-prime', prompt: '', resultFaultId: 'pool-pump-no-prime' },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'pool-filter-high-pressure' },
      'result-suction': { id: 'result-suction', prompt: '', resultFaultId: 'pool-pump-no-prime' },
    },
  },
  {
    id: 'elec-trip',
    packId: 'electrical',
    title: 'Breaker keeps tripping',
    description: 'Separate overload, short, GFCI, and weak breaker paths.',
    startStepId: 'immediate',
    steps: {
      immediate: {
        id: 'immediate',
        prompt: 'Does it trip instantly with all loads unplugged/off?',
        yesNext: 'result-short',
        noNext: 'gfci',
      },
      gfci: {
        id: 'gfci',
        prompt: 'Is it a GFCI/AFCI device, or is there an upstream GFCI involved?',
        yesNext: 'result-gfci',
        noNext: 'onload',
      },
      onload: {
        id: 'onload',
        prompt: 'Does it only trip when a motor/compressor/heater starts?',
        yesNext: 'result-inrush',
        noNext: 'result-nuisance',
      },
      'result-short': { id: 'result-short', prompt: '', resultFaultId: 'elec-breaker-nuisance' },
      'result-gfci': { id: 'result-gfci', prompt: '', resultFaultId: 'elec-gfci-wont-reset' },
      'result-inrush': { id: 'result-inrush', prompt: '', resultFaultId: 'elec-motor-wont-start' },
      'result-nuisance': { id: 'result-nuisance', prompt: '', resultFaultId: 'elec-breaker-nuisance' },
    },
  },
  {
    id: 'prop-washer-drain',
    packId: 'property',
    title: 'Washer won’t drain',
    description: 'Coin trap → hose → pump → door lock.',
    startStepId: 'standing',
    steps: {
      standing: {
        id: 'standing',
        prompt: 'Is there standing water in the drum?',
        yesNext: 'filter',
        noNext: 'spin',
      },
      filter: {
        id: 'filter',
        prompt: 'After cleaning the pump filter / coin trap, does it drain?',
        yesNext: 'result-filter',
        noNext: 'hose',
      },
      hose: {
        id: 'hose',
        prompt: 'Is the drain hose kinked or pushed too far into a sealed standpipe?',
        yesNext: 'result-hose',
        noNext: 'result-pump',
      },
      spin: {
        id: 'spin',
        prompt: 'Does it drain but refuse to spin?',
        yesNext: 'result-spin',
        noNext: 'result-filter',
      },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-hose': { id: 'result-hose', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-pump': { id: 'result-pump', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-spin': { id: 'result-spin', prompt: '', resultFaultId: 'prop-washer-no-spin' },
    },
  },
  {
    id: 'prop-dryer-heat',
    packId: 'property',
    title: 'Dryer no heat',
    description: '240V → vent → fuse → element / gas path.',
    startStepId: 'power',
    steps: {
      power: {
        id: 'power',
        prompt: 'Does the drum tumble normally?',
        yesNext: 'fuel',
        noNext: 'result-power',
      },
      fuel: {
        id: 'fuel',
        prompt: 'Is this an electric dryer (240V) rather than gas?',
        yesNext: 'vent',
        noNext: 'result-gas',
      },
      vent: {
        id: 'vent',
        prompt: 'Is the exterior vent blowing strongly with little lint restriction?',
        yesNext: 'result-fuse',
        noNext: 'result-vent',
      },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
      'result-gas': { id: 'result-gas', prompt: '', resultFaultId: 'prop-dryer-gas-no-heat' },
      'result-vent': { id: 'result-vent', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
      'result-fuse': { id: 'result-fuse', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
    },
  },
  {
    id: 'pool-no-chlorine',
    packId: 'pool',
    title: 'No chlorine / salt cell',
    description: 'Separate low salt, dirty cell, cold water, and failed cell.',
    startStepId: 'test',
    steps: {
      test: {
        id: 'test',
        prompt: 'Is free chlorine reading near zero while the SWG says it’s generating?',
        yesNext: 'salt',
        noNext: 'result-cloudy',
      },
      salt: {
        id: 'salt',
        prompt: 'Is salt within the cell’s target range (often ~3200–3400 ppm)?',
        yesNext: 'cell',
        noNext: 'result-salt',
      },
      cell: {
        id: 'cell',
        prompt: 'After cleaning the cell, does output recover?',
        yesNext: 'result-dirty',
        noNext: 'result-cell',
      },
      'result-salt': { id: 'result-salt', prompt: '', resultFaultId: 'pool-salt-low-false' },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'pool-no-chlorine' },
      'result-cell': { id: 'result-cell', prompt: '', resultFaultId: 'pool-no-chlorine' },
      'result-cloudy': { id: 'result-cloudy', prompt: '', resultFaultId: 'pool-cloudy-water' },
    },
  },
  {
    id: 'pool-heater',
    packId: 'pool',
    title: 'Heater not firing',
    description: 'Flow → ignition → gas/electric path.',
    startStepId: 'flow',
    steps: {
      flow: {
        id: 'flow',
        prompt: 'Is filter pressure normal and flow switch / pressure switch satisfied?',
        yesNext: 'ignition',
        noNext: 'result-flow',
      },
      ignition: {
        id: 'ignition',
        prompt: 'Do you hear igniter / see trial for ignition then lockout?',
        yesNext: 'result-ignition',
        noNext: 'result-noheat',
      },
      'result-flow': { id: 'result-flow', prompt: '', resultFaultId: 'pool-heater-no-heat' },
      'result-ignition': { id: 'result-ignition', prompt: '', resultFaultId: 'pool-heater-ignition' },
      'result-noheat': { id: 'result-noheat', prompt: '', resultFaultId: 'pool-heater-no-heat' },
    },
  },
  {
    id: 'elec-no-power',
    packId: 'electrical',
    title: 'Dead circuit / no power',
    description: 'Breaker → GFCI → open neutral / lost leg.',
    startStepId: 'breaker',
    steps: {
      breaker: {
        id: 'breaker',
        prompt: 'Is the branch breaker ON and measuring voltage at the load side?',
        yesNext: 'gfci',
        noNext: 'result-breaker',
      },
      gfci: {
        id: 'gfci',
        prompt: 'Is there a tripped GFCI (device or upstream) on this circuit?',
        yesNext: 'result-gfci',
        noNext: 'neutral',
      },
      neutral: {
        id: 'neutral',
        prompt: 'Do L-N voltages look wild under load (open neutral / lost leg symptoms)?',
        yesNext: 'result-neutral',
        noNext: 'result-dead',
      },
      'result-breaker': { id: 'result-breaker', prompt: '', resultFaultId: 'elec-no-power-circuit' },
      'result-gfci': { id: 'result-gfci', prompt: '', resultFaultId: 'elec-gfci-wont-reset' },
      'result-neutral': { id: 'result-neutral', prompt: '', resultFaultId: 'elec-open-neutral' },
      'result-dead': { id: 'result-dead', prompt: '', resultFaultId: 'elec-no-power-circuit' },
    },
  },
  {
    id: 'elec-panel-hot',
    packId: 'electrical',
    title: 'Panel / lug running hot',
    description: 'Torque → double-tap → aluminum / corrosion.',
    startStepId: 'feel',
    steps: {
      feel: {
        id: 'feel',
        prompt: 'Is heat localized to a lug, breaker, or neutral bar (not the whole can)?',
        yesNext: 'torque',
        noNext: 'result-clearance',
      },
      torque: {
        id: 'torque',
        prompt: 'After de-energizing and retorquing to spec, does heat return under load?',
        yesNext: 'double',
        noNext: 'result-torque',
      },
      double: {
        id: 'double',
        prompt: 'Is more than one conductor under a lug that is not listed for it?',
        yesNext: 'result-double',
        noNext: 'result-hot',
      },
      'result-torque': { id: 'result-torque', prompt: '', resultFaultId: 'elec-panel-hot' },
      'result-double': { id: 'result-double', prompt: '', resultFaultId: 'elec-double-tap' },
      'result-hot': { id: 'result-hot', prompt: '', resultFaultId: 'elec-panel-hot' },
      'result-clearance': { id: 'result-clearance', prompt: '', resultFaultId: 'elec-working-clearance' },
    },
  },
  {
    id: 'prop-dishwasher-drain',
    packId: 'property',
    title: 'Dishwasher won’t drain',
    description: 'Filter → air gap / hose → disposal knockout.',
    startStepId: 'standing',
    steps: {
      standing: {
        id: 'standing',
        prompt: 'Is there standing water in the tub after the cycle?',
        yesNext: 'filter',
        noNext: 'result-leak',
      },
      filter: {
        id: 'filter',
        prompt: 'After cleaning the filter / sump screen, does it drain?',
        yesNext: 'result-filter',
        noNext: 'disposal',
      },
      disposal: {
        id: 'disposal',
        prompt: 'Is the disposal knockout still plugged or the drain hose kinked/high loop missing?',
        yesNext: 'result-hose',
        noNext: 'result-drain',
      },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-hose': { id: 'result-hose', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-drain': { id: 'result-drain', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-leak': { id: 'result-leak', prompt: '', resultFaultId: 'prop-dishwasher-leak' },
    },
  },
  {
    id: 'prop-disposal-jam',
    packId: 'property',
    title: 'Disposal hums / jammed',
    description: 'Hex key → reset → wiring.',
    startStepId: 'hum',
    steps: {
      hum: {
        id: 'hum',
        prompt: 'Does it hum without spinning when switched on?',
        yesNext: 'hex',
        noNext: 'result-dead',
      },
      hex: {
        id: 'hex',
        prompt: 'After turning the hex key under the unit and pressing reset, does it free up?',
        yesNext: 'result-jam',
        noNext: 'result-motor',
      },
      'result-jam': { id: 'result-jam', prompt: '', resultFaultId: 'prop-disposal-hum' },
      'result-motor': { id: 'result-motor', prompt: '', resultFaultId: 'prop-disposal-hum' },
      'result-dead': { id: 'result-dead', prompt: '', resultFaultId: 'prop-unit-gfci' },
    },
  },
  {
    id: 'prop-fridge-warm',
    packId: 'property',
    title: 'Fridge not cold enough',
    description: 'Airflow → condenser → sealed system triage.',
    startStepId: 'setpoint',
    steps: {
      setpoint: {
        id: 'setpoint',
        prompt: 'Are controls set cold enough and interior fans running?',
        yesNext: 'condenser',
        noNext: 'result-controls',
      },
      condenser: {
        id: 'condenser',
        prompt: 'Is the condenser coil clean and the condenser fan moving air?',
        yesNext: 'result-sealed',
        noNext: 'result-dirty',
      },
      'result-controls': { id: 'result-controls', prompt: '', resultFaultId: 'prop-fridge-warm' },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'prop-fridge-warm' },
      'result-sealed': { id: 'result-sealed', prompt: '', resultFaultId: 'prop-fridge-not-cold' },
    },
  },
  {
    id: 'plumb-main-backup',
    packId: 'plumbing',
    title: 'Main line backing up',
    description: 'Confirm main vs branch, cleanout, camera path.',
    startStepId: 'multiple',
    steps: {
      multiple: {
        id: 'multiple',
        prompt: 'Are multiple fixtures backing up (especially lowest drains)?',
        yesNext: 'cleanout',
        noNext: 'result-branch',
      },
      cleanout: {
        id: 'cleanout',
        prompt: 'Is there a cleanout with standing sewage when opened carefully?',
        yesNext: 'result-main',
        noNext: 'result-vent',
      },
      'result-main': { id: 'result-main', prompt: '', resultFaultId: 'plumb-main-sewer-backup' },
      'result-branch': { id: 'result-branch', prompt: '', resultFaultId: 'plumb-kitchen-grease-clog' },
      'result-vent': { id: 'result-vent', prompt: '', resultFaultId: 'plumb-shower-tub-slow-drain' },
    },
  },
  {
    id: 'plumb-no-hot',
    packId: 'plumbing',
    title: 'No hot water',
    description: 'Tank vs tankless triage.',
    startStepId: 'type',
    steps: {
      type: {
        id: 'type',
        prompt: 'Is this a tankless unit with a digital error code?',
        yesNext: 'result-tankless',
        noNext: 'breaker',
      },
      breaker: {
        id: 'breaker',
        prompt: 'For tank electric — is breaker on and upper element getting power?',
        yesNext: 'result-tank',
        noNext: 'result-power',
      },
      'result-tankless': { id: 'result-tankless', prompt: '', resultFaultId: 'plumb-tankless-flame-failure' },
      'result-tank': { id: 'result-tank', prompt: '', resultFaultId: 'plumb-tank-wh-no-hot' },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'plumb-tank-wh-no-hot' },
    },
  },
  {
    id: 'plumb-toilet-run',
    packId: 'plumbing',
    title: 'Toilet won’t stop running',
    description: 'Flapper → fill valve → overflow.',
    startStepId: 'overflow',
    steps: {
      overflow: {
        id: 'overflow',
        prompt: 'Is water flowing into the overflow tube?',
        yesNext: 'result-fill',
        noNext: 'flapper',
      },
      flapper: {
        id: 'flapper',
        prompt: 'Does the flapper seal when you press it — or is it warped/crudded?',
        yesNext: 'result-flapper',
        noNext: 'result-fill',
      },
      'result-fill': { id: 'result-fill', prompt: '', resultFaultId: 'plumb-toilet-running-phantom' },
      'result-flapper': { id: 'result-flapper', prompt: '', resultFaultId: 'plumb-toilet-running-phantom' },
    },
  },
  {
    id: 'hvac-no-cool',
    packId: 'hvac',
    title: 'AC not cooling',
    description: 'Thermostat call → airflow → refrigeration.',
    startStepId: 'call',
    steps: {
      call: {
        id: 'call',
        prompt: 'Is outdoor unit running with Y call present at contactor?',
        yesNext: 'split',
        noNext: 'result-controls',
      },
      split: {
        id: 'split',
        prompt: 'Is return-to-supply temperature split under 10°F?',
        yesNext: 'result-warm',
        noNext: 'result-airflow',
      },
      'result-controls': { id: 'result-controls', prompt: '', resultFaultId: 'hvac-thermostat-blank' },
      'result-warm': { id: 'result-warm', prompt: '', resultFaultId: 'hvac-ac-warm-air' },
      'result-airflow': { id: 'result-airflow', prompt: '', resultFaultId: 'hvac-dirty-filter-high-delta-t' },
    },
  },
  {
    id: 'hvac-furnace-heat',
    packId: 'hvac',
    title: 'Furnace no heat',
    description: 'Power → inducer → ignition chain.',
    startStepId: 'power',
    steps: {
      power: {
        id: 'power',
        prompt: 'Is 24VAC present at the board and door switch closed?',
        yesNext: 'inducer',
        noNext: 'result-power',
      },
      inducer: {
        id: 'inducer',
        prompt: 'Does inducer start and pressure switch close?',
        yesNext: 'ignition',
        noNext: 'result-inducer',
      },
      ignition: {
        id: 'ignition',
        prompt: 'Does ignitor glow and flame establish for more than 3 seconds?',
        yesNext: 'result-flame',
        noNext: 'result-ignitor',
      },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'hvac-thermostat-blank' },
      'result-inducer': { id: 'result-inducer', prompt: '', resultFaultId: 'hvac-furnace-no-heat' },
      'result-ignitor': { id: 'result-ignitor', prompt: '', resultFaultId: 'hvac-ignitor-failure' },
      'result-flame': { id: 'result-flame', prompt: '', resultFaultId: 'hvac-flame-sensor-fault' },
    },
  },
  {
    id: 'hvac-frozen-coil',
    packId: 'hvac',
    title: 'Frozen evaporator coil',
    description: 'Thaw → airflow → charge.',
    startStepId: 'ice',
    steps: {
      ice: {
        id: 'ice',
        prompt: 'Is ice visible on suction line or indoor coil?',
        yesNext: 'filter',
        noNext: 'result-other',
      },
      filter: {
        id: 'filter',
        prompt: 'Is filter clean and blower moving strong airflow?',
        yesNext: 'result-charge',
        noNext: 'result-airflow',
      },
      'result-airflow': { id: 'result-airflow', prompt: '', resultFaultId: 'hvac-frozen-evaporator-coil' },
      'result-charge': { id: 'result-charge', prompt: '', resultFaultId: 'hvac-low-suction-undercharge-signs' },
      'result-other': { id: 'result-other', prompt: '', resultFaultId: 'hvac-ac-warm-air' },
    },
  },
  {
    id: 'fiber-ont-los',
    packId: 'fiber',
    title: 'ONT LOS — no light',
    description: 'Optical power → drop → splitter path.',
    startStepId: 'rx',
    steps: {
      rx: {
        id: 'rx',
        prompt: 'Is optical power at the ONT within vendor RX range (roughly -8 to -27 dBm GPON)?',
        yesNext: 'provision',
        noNext: 'vfl',
      },
      vfl: {
        id: 'vfl',
        prompt: 'Does VFL from FDH show light reaching the customer pedestal/NID?',
        yesNext: 'result-dirty',
        noNext: 'result-cut',
      },
      provision: {
        id: 'provision',
        prompt: 'Is ONT serial and PON type correct in EMS?',
        yesNext: 'result-register',
        noNext: 'result-register',
      },
      'result-cut': { id: 'result-cut', prompt: '', resultFaultId: 'fiber-vfl-no-light-customer' },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'fiber-dirty-sc-apc' },
      'result-register': { id: 'result-register', prompt: '', resultFaultId: 'fiber-ont-not-registering' },
    },
  },
  {
    id: 'fiber-high-splice-loss',
    packId: 'fiber',
    title: 'High fusion splice loss',
    description: 'Cleave → clean → program → re-fuse.',
    startStepId: 'cleave',
    steps: {
      cleave: {
        id: 'cleave',
        prompt: 'Do both fiber endfaces look clean under scope with good cleave angle?',
        yesNext: 'program',
        noNext: 'result-cleave',
      },
      program: {
        id: 'program',
        prompt: 'Is the fusion program correct for this fiber type (G.652 vs G.657)?',
        yesNext: 'result-fusion',
        noNext: 'result-fusion',
      },
      'result-cleave': { id: 'result-cleave', prompt: '', resultFaultId: 'fiber-cleave-angle-bad' },
      'result-fusion': { id: 'result-fusion', prompt: '', resultFaultId: 'fiber-fusion-high-loss' },
    },
  },
  {
    id: 'fiber-span-loss',
    packId: 'fiber',
    title: 'High span loss / power budget fail',
    description: 'Segment test from OLT to ONT.',
    startStepId: 'clean',
    steps: {
      clean: {
        id: 'clean',
        prompt: 'Are all patch connectors cleaned and inspected before measuring?',
        yesNext: 'segment',
        noNext: 'result-dirty',
      },
      segment: {
        id: 'segment',
        prompt: 'Can you isolate loss to one leg (splitter port vs drop vs splice case)?',
        yesNext: 'result-budget',
        noNext: 'result-budget',
      },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'fiber-dirty-sc-apc' },
      'result-budget': { id: 'result-budget', prompt: '', resultFaultId: 'fiber-power-meter-high-loss' },
    },
  },
];

export function getGuidedFlows(packId?: import('../packs/types').TradePackId) {
  return packId ? guidedFlows.filter((f) => f.packId === packId) : guidedFlows;
}

export function getGuidedFlow(id: string) {
  return guidedFlows.find((f) => f.id === id);
}
