import type { GuidedFlow } from './types';

export const guidedFlows: GuidedFlow[] = [
  {
    id: 'pool-no-flow',
    packId: 'pool',
    title: 'No flow / weak returns',
    description: 'Guided triage from pump basket to filter to returns.',
    startStepId: 'power',
    steps: {
      power: {
        id: 'power',
        prompt: 'Is the pump powered and trying to run (hum, display on, shaft attempting)?',
        yesNext: 'basket',
        noNext: 'result-power',
      },
      basket: {
        id: 'basket',
        prompt: 'Is the pump basket full of water with the lid sealed and minimal air bubbles?',
        yesNext: 'pressure',
        noNext: 'result-prime',
      },
      pressure: {
        id: 'pressure',
        prompt: 'Is filter pressure high vs the clean baseline?',
        yesNext: 'result-filter',
        noNext: 'result-suction',
      },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'pool-pump-hum-no-spin' },
      'result-prime': { id: 'result-prime', prompt: '', resultFaultId: 'pool-pump-no-prime' },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'pool-filter-high-pressure' },
      'result-suction': { id: 'result-suction', prompt: '', resultFaultId: 'pool-pump-no-prime' },
    },
  },
  {
    id: 'elec-trip',
    packId: 'electrical',
    title: 'Breaker keeps tripping',
    description: 'Separate overload, short, GFCI, and weak breaker paths.',
    startStepId: 'immediate',
    steps: {
      immediate: {
        id: 'immediate',
        prompt: 'Does it trip instantly with all loads unplugged/off?',
        yesNext: 'result-short',
        noNext: 'gfci',
      },
      gfci: {
        id: 'gfci',
        prompt: 'Is it a GFCI/AFCI device, or is there an upstream GFCI involved?',
        yesNext: 'result-gfci',
        noNext: 'onload',
      },
      onload: {
        id: 'onload',
        prompt: 'Does it only trip when a motor/compressor/heater starts?',
        yesNext: 'result-inrush',
        noNext: 'result-nuisance',
      },
      'result-short': { id: 'result-short', prompt: '', resultFaultId: 'elec-breaker-nuisance' },
      'result-gfci': { id: 'result-gfci', prompt: '', resultFaultId: 'elec-gfci-wont-reset' },
      'result-inrush': { id: 'result-inrush', prompt: '', resultFaultId: 'elec-motor-wont-start' },
      'result-nuisance': { id: 'result-nuisance', prompt: '', resultFaultId: 'elec-breaker-nuisance' },
    },
  },
  {
    id: 'prop-washer-drain',
    packId: 'property',
    title: 'Washer won’t drain',
    description: 'Coin trap → hose → pump → door lock.',
    startStepId: 'standing',
    steps: {
      standing: {
        id: 'standing',
        prompt: 'Is there standing water in the drum?',
        yesNext: 'filter',
        noNext: 'spin',
      },
      filter: {
        id: 'filter',
        prompt: 'After cleaning the pump filter / coin trap, does it drain?',
        yesNext: 'result-filter',
        noNext: 'hose',
      },
      hose: {
        id: 'hose',
        prompt: 'Is the drain hose kinked or pushed too far into a sealed standpipe?',
        yesNext: 'result-hose',
        noNext: 'result-pump',
      },
      spin: {
        id: 'spin',
        prompt: 'Does it drain but refuse to spin?',
        yesNext: 'result-spin',
        noNext: 'result-filter',
      },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-hose': { id: 'result-hose', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-pump': { id: 'result-pump', prompt: '', resultFaultId: 'prop-washer-no-drain' },
      'result-spin': { id: 'result-spin', prompt: '', resultFaultId: 'prop-washer-no-spin' },
    },
  },
  {
    id: 'prop-dryer-heat',
    packId: 'property',
    title: 'Dryer no heat',
    description: '240V → vent → fuse → element / gas path.',
    startStepId: 'power',
    steps: {
      power: {
        id: 'power',
        prompt: 'Does the drum tumble normally?',
        yesNext: 'fuel',
        noNext: 'result-power',
      },
      fuel: {
        id: 'fuel',
        prompt: 'Is this an electric dryer (240V) rather than gas?',
        yesNext: 'vent',
        noNext: 'result-gas',
      },
      vent: {
        id: 'vent',
        prompt: 'Is the exterior vent blowing strongly with little lint restriction?',
        yesNext: 'result-fuse',
        noNext: 'result-vent',
      },
      'result-power': { id: 'result-power', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
      'result-gas': { id: 'result-gas', prompt: '', resultFaultId: 'prop-dryer-gas-no-heat' },
      'result-vent': { id: 'result-vent', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
      'result-fuse': { id: 'result-fuse', prompt: '', resultFaultId: 'prop-dryer-no-heat' },
    },
  },
  {
    id: 'pool-no-chlorine',
    packId: 'pool',
    title: 'No chlorine / salt cell',
    description: 'Separate low salt, dirty cell, cold water, and failed cell.',
    startStepId: 'test',
    steps: {
      test: {
        id: 'test',
        prompt: 'Is free chlorine reading near zero while the SWG says it’s generating?',
        yesNext: 'salt',
        noNext: 'result-cloudy',
      },
      salt: {
        id: 'salt',
        prompt: 'Is salt within the cell’s target range (often ~3200–3400 ppm)?',
        yesNext: 'cell',
        noNext: 'result-salt',
      },
      cell: {
        id: 'cell',
        prompt: 'After cleaning the cell, does output recover?',
        yesNext: 'result-dirty',
        noNext: 'result-cell',
      },
      'result-salt': { id: 'result-salt', prompt: '', resultFaultId: 'pool-salt-low-false' },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'pool-no-chlorine' },
      'result-cell': { id: 'result-cell', prompt: '', resultFaultId: 'pool-no-chlorine' },
      'result-cloudy': { id: 'result-cloudy', prompt: '', resultFaultId: 'pool-cloudy-water' },
    },
  },
  {
    id: 'pool-heater',
    packId: 'pool',
    title: 'Heater not firing',
    description: 'Flow → ignition → gas/electric path.',
    startStepId: 'flow',
    steps: {
      flow: {
        id: 'flow',
        prompt: 'Is filter pressure normal and flow switch / pressure switch satisfied?',
        yesNext: 'ignition',
        noNext: 'result-flow',
      },
      ignition: {
        id: 'ignition',
        prompt: 'Do you hear igniter / see trial for ignition then lockout?',
        yesNext: 'result-ignition',
        noNext: 'result-noheat',
      },
      'result-flow': { id: 'result-flow', prompt: '', resultFaultId: 'pool-heater-no-heat' },
      'result-ignition': { id: 'result-ignition', prompt: '', resultFaultId: 'pool-heater-ignition' },
      'result-noheat': { id: 'result-noheat', prompt: '', resultFaultId: 'pool-heater-no-heat' },
    },
  },
  {
    id: 'elec-no-power',
    packId: 'electrical',
    title: 'Dead circuit / no power',
    description: 'Breaker → GFCI → open neutral / lost leg.',
    startStepId: 'breaker',
    steps: {
      breaker: {
        id: 'breaker',
        prompt: 'Is the branch breaker ON and measuring voltage at the load side?',
        yesNext: 'gfci',
        noNext: 'result-breaker',
      },
      gfci: {
        id: 'gfci',
        prompt: 'Is there a tripped GFCI (device or upstream) on this circuit?',
        yesNext: 'result-gfci',
        noNext: 'neutral',
      },
      neutral: {
        id: 'neutral',
        prompt: 'Do L-N voltages look wild under load (open neutral / lost leg symptoms)?',
        yesNext: 'result-neutral',
        noNext: 'result-dead',
      },
      'result-breaker': { id: 'result-breaker', prompt: '', resultFaultId: 'elec-no-power-circuit' },
      'result-gfci': { id: 'result-gfci', prompt: '', resultFaultId: 'elec-gfci-wont-reset' },
      'result-neutral': { id: 'result-neutral', prompt: '', resultFaultId: 'elec-open-neutral' },
      'result-dead': { id: 'result-dead', prompt: '', resultFaultId: 'elec-no-power-circuit' },
    },
  },
  {
    id: 'elec-panel-hot',
    packId: 'electrical',
    title: 'Panel / lug running hot',
    description: 'Torque → double-tap → aluminum / corrosion.',
    startStepId: 'feel',
    steps: {
      feel: {
        id: 'feel',
        prompt: 'Is heat localized to a lug, breaker, or neutral bar (not the whole can)?',
        yesNext: 'torque',
        noNext: 'result-clearance',
      },
      torque: {
        id: 'torque',
        prompt: 'After de-energizing and retorquing to spec, does heat return under load?',
        yesNext: 'double',
        noNext: 'result-torque',
      },
      double: {
        id: 'double',
        prompt: 'Is more than one conductor under a lug that is not listed for it?',
        yesNext: 'result-double',
        noNext: 'result-hot',
      },
      'result-torque': { id: 'result-torque', prompt: '', resultFaultId: 'elec-panel-hot' },
      'result-double': { id: 'result-double', prompt: '', resultFaultId: 'elec-double-tap' },
      'result-hot': { id: 'result-hot', prompt: '', resultFaultId: 'elec-panel-hot' },
      'result-clearance': { id: 'result-clearance', prompt: '', resultFaultId: 'elec-working-clearance' },
    },
  },
  {
    id: 'prop-dishwasher-drain',
    packId: 'property',
    title: 'Dishwasher won’t drain',
    description: 'Filter → air gap / hose → disposal knockout.',
    startStepId: 'standing',
    steps: {
      standing: {
        id: 'standing',
        prompt: 'Is there standing water in the tub after the cycle?',
        yesNext: 'filter',
        noNext: 'result-leak',
      },
      filter: {
        id: 'filter',
        prompt: 'After cleaning the filter / sump screen, does it drain?',
        yesNext: 'result-filter',
        noNext: 'disposal',
      },
      disposal: {
        id: 'disposal',
        prompt: 'Is the disposal knockout still plugged or the drain hose kinked/high loop missing?',
        yesNext: 'result-hose',
        noNext: 'result-drain',
      },
      'result-filter': { id: 'result-filter', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-hose': { id: 'result-hose', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-drain': { id: 'result-drain', prompt: '', resultFaultId: 'prop-dishwasher-no-drain' },
      'result-leak': { id: 'result-leak', prompt: '', resultFaultId: 'prop-dishwasher-leak' },
    },
  },
  {
    id: 'prop-disposal-jam',
    packId: 'property',
    title: 'Disposal hums / jammed',
    description: 'Hex key → reset → wiring.',
    startStepId: 'hum',
    steps: {
      hum: {
        id: 'hum',
        prompt: 'Does it hum without spinning when switched on?',
        yesNext: 'hex',
        noNext: 'result-dead',
      },
      hex: {
        id: 'hex',
        prompt: 'After turning the hex key under the unit and pressing reset, does it free up?',
        yesNext: 'result-jam',
        noNext: 'result-motor',
      },
      'result-jam': { id: 'result-jam', prompt: '', resultFaultId: 'prop-disposal-hum' },
      'result-motor': { id: 'result-motor', prompt: '', resultFaultId: 'prop-disposal-hum' },
      'result-dead': { id: 'result-dead', prompt: '', resultFaultId: 'prop-unit-gfci' },
    },
  },
  {
    id: 'prop-fridge-warm',
    packId: 'property',
    title: 'Fridge not cold enough',
    description: 'Airflow → condenser → sealed system triage.',
    startStepId: 'setpoint',
    steps: {
      setpoint: {
        id: 'setpoint',
        prompt: 'Are controls set cold enough and interior fans running?',
        yesNext: 'condenser',
        noNext: 'result-controls',
      },
      condenser: {
        id: 'condenser',
        prompt: 'Is the condenser coil clean and the condenser fan moving air?',
        yesNext: 'result-sealed',
        noNext: 'result-dirty',
      },
      'result-controls': { id: 'result-controls', prompt: '', resultFaultId: 'prop-fridge-warm' },
      'result-dirty': { id: 'result-dirty', prompt: '', resultFaultId: 'prop-fridge-warm' },
      'result-sealed': { id: 'result-sealed', prompt: '', resultFaultId: 'prop-fridge-not-cold' },
    },
  },
];

export function getGuidedFlows(packId?: import('../packs/types').TradePackId) {
  return packId ? guidedFlows.filter((f) => f.packId === packId) : guidedFlows;
}

export function getGuidedFlow(id: string) {
  return guidedFlows.find((f) => f.id === id);
}
