/** Light Pros HQ shell — matches /pros marketing (#fafbfc) and the Diagnose app. */
export const prosAdmin = {
  page: 'min-h-screen bg-[#fafbfc] text-slate-900',
  pageCenter: 'min-h-screen bg-[#fafbfc] flex items-center justify-center text-slate-500',
  pageCenterAuth: 'min-h-screen bg-[#fafbfc] text-slate-900 flex items-center justify-center px-4',
  pageOnboard: 'min-h-screen bg-[#fafbfc] text-slate-900 px-4 py-16',
  header: 'border-b border-slate-200 bg-white/90 backdrop-blur-xl sticky top-0 z-40',
  card: 'rounded-2xl border border-slate-200 bg-white shadow-sm',
  cardSubtle: 'rounded-xl border border-slate-200 bg-white',
  cardInset: 'rounded-xl border border-slate-200 bg-slate-50',
  input:
    'rounded-xl bg-white border border-slate-200 px-3 py-2.5 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:border-amber-500/60',
  textarea:
    'rounded-xl bg-white border border-slate-200 px-3 py-2.5 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:border-amber-500/60 resize-y',
  signInCard: 'max-w-md w-full rounded-2xl border border-slate-200 bg-white shadow-lg p-8',
  tabActive: 'bg-[#F5A623] text-slate-900',
  tabInactive: 'text-slate-600 hover:text-slate-900 hover:bg-slate-100',
  filterActive: 'bg-[#F5A623] text-slate-900',
  filterInactive: 'bg-slate-100 text-slate-600',
  iconBtn: 'p-2 rounded-lg hover:bg-slate-100 text-slate-500',
  roleBadge: 'text-[10px] uppercase font-bold px-2 py-1 rounded-full bg-slate-100 text-slate-600',
  btnPrimary: 'rounded-xl bg-[#F5A623] hover:bg-[#e09510] text-slate-900 font-bold',
  btnSecondary: 'rounded-xl border border-slate-200 text-slate-700 hover:border-amber-500/50 font-bold',
  btnGhost: 'rounded-xl border border-slate-200 px-4 py-2 text-sm text-slate-700 hover:border-amber-500/50',
  error: 'rounded-xl bg-red-50 text-red-700 px-4 py-3 text-sm',
  errorInline: 'text-sm text-red-600',
  success: 'rounded-xl bg-emerald-50 text-emerald-800 px-4 py-3 text-sm',
  muted: 'text-slate-500',
  bodyMuted: 'text-slate-600',
  link: 'text-xs text-[#1E3A8A] hover:underline font-semibold',
  linkAmber: 'text-xs text-amber-700 hover:underline font-semibold',
  highlightBanner: 'rounded-2xl border border-[#1E3A8A]/25 bg-[#1E3A8A]/5',
  featuredTip: 'rounded-2xl border border-amber-500/30 bg-amber-50',
  jobExpand: 'border-t border-slate-200 px-4 py-4 space-y-4 bg-slate-50',
  jobRowHover: 'hover:bg-slate-50',
  checkboxRow: 'flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 cursor-pointer',
  avatar: 'w-11 h-11 rounded-full bg-amber-100 overflow-hidden flex items-center justify-center text-amber-700 font-bold',
  avatarSm: 'w-10 h-10 rounded-xl bg-amber-100 flex items-center justify-center',
  status: {
    queued: 'bg-slate-100 text-slate-700',
    in_progress: 'bg-sky-100 text-sky-800',
    needs_parts: 'bg-amber-100 text-amber-800',
    done: 'bg-emerald-100 text-emerald-800',
  } as Record<string, string>,
  partStatus: {
    pending_approval: 'bg-amber-100 text-amber-800',
    approved: 'bg-sky-100 text-sky-800',
    ordered: 'bg-emerald-100 text-emerald-800',
    declined: 'bg-red-100 text-red-800',
  } as Record<string, string>,
  notifyPriority: {
    urgent: 'bg-red-100 text-red-800',
    high: 'bg-amber-100 text-amber-800',
    normal: 'bg-slate-100 text-slate-600',
  } as Record<string, string>,
  calloutSky: 'rounded-2xl border border-sky-200 bg-sky-50',
  calloutAmber: 'rounded-2xl border border-amber-200 bg-amber-50',
  demoBanner: 'mb-6 rounded-xl border border-sky-200 bg-gradient-to-r from-sky-50 to-amber-50 px-4 py-3',
  demoBadge: 'text-[9px] font-bold uppercase px-1.5 py-0.5 rounded bg-sky-100 text-sky-800 tracking-wider',
  assistantPanel: 'fixed bottom-24 right-6 z-50 w-[min(420px,calc(100vw-2rem))] h-[min(560px,calc(100vh-8rem))] rounded-2xl border border-slate-200 bg-white shadow-2xl flex flex-col overflow-hidden',
} as const;
