/**
 * Illustrative Pros HQ data — merged at read time for sparse companies.
 * All ids are prefixed with `demo-`; never written to Firestore.
 */

const DAY = 86_400_000;
const now = Date.now();
const ago = (days) => now - days * DAY;

export function isDemoId(id) {
  return String(id || '').startsWith('demo-');
}

export function demoPreviewEnabled(settings = {}) {
  return settings.demoPreviewEnabled !== false;
}

/** Show sample data until the shop has meaningful real activity. */
export function shouldShowDemoPreview(settings, counts = {}) {
  if (!demoPreviewEnabled(settings)) return false;
  const score =
    (counts.jobs || 0) +
    (counts.tips || 0) +
    (counts.feedback || 0) +
    (counts.parts || 0) +
    (counts.notifications || 0);
  return score < 20;
}

export const DEMO_DISCLAIMER =
  'Sample data previews what a thriving shop looks like. It disappears as you add real jobs, tips, and parts.';

export function getDemoKnowledgeGrowth() {
  return [
    { month: '2026-02', label: 'Feb', tips: 18, feedback: 14, jobsDone: 9, activity: 22 },
    { month: '2026-03', label: 'Mar', tips: 31, feedback: 24, jobsDone: 17, activity: 38 },
    { month: '2026-04', label: 'Apr', tips: 44, feedback: 36, jobsDone: 26, activity: 51 },
    { month: '2026-05', label: 'May', tips: 62, feedback: 49, jobsDone: 34, activity: 68 },
    { month: '2026-06', label: 'Jun', tips: 81, feedback: 67, jobsDone: 45, activity: 89 },
    { month: '2026-07', label: 'Jul', tips: 97, feedback: 78, jobsDone: 52, activity: 104 },
  ];
}

export function getDemoFeaturedTip() {
  return {
    id: 'demo-tip-1',
    text: 'IntelliFlo VSF showing "Priming" loop — check skimmer/weir for air leak before replacing the pump.',
    fixSummary: 'Tightened union at pump inlet; cleared debris from weir door. Saved a $680 pump swap.',
    packId: 'pool',
    helpfulCount: 14,
  };
}

export function getDemoAnalyticsTotals() {
  return {
    tips: 97,
    feedback: 78,
    manualChunks: 24,
    jobsTotal: 28,
    jobsDone: 18,
    fieldNotes: 46,
    openJobs: 8,
  };
}

export function getDemoJobsByStatus() {
  return { queued: 3, in_progress: 3, needs_parts: 2, done: 4 };
}

export function getDemoJobs() {
  return [
    {
      id: 'demo-job-1',
      title: 'IntelliFlo VSF — priming loop / low flow',
      address: '1842 Lakeshore Dr, Austin TX',
      customerName: 'Rebecca Holt',
      customerPhone: '(512) 555-0142',
      notes: 'Pump runs but flow meter stuck at 12 GPM. Customer reports air in basket.',
      adminNotes: 'Bring union wrench; check weir door.',
      packId: 'pool',
      status: 'in_progress',
      priority: 'high',
      assigneeUid: 'demo-tech-1',
      assigneeName: 'Marcus Rivera',
      scheduledFor: 'Today 9:00 AM',
      fieldNotes: [
        {
          id: 'demo-fn-1',
          text: 'Nameplate: Pentair 011028. Basket has fine debris; union at pump inlet slightly loose.',
          authorUid: 'demo-tech-1',
          createdAt: ago(0.1),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(2),
      updatedAt: ago(0.1),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-2',
      title: 'Carrier heat pump — no cool, outdoor unit humming',
      address: '902 Ridgeview Ln, Round Rock TX',
      customerName: 'David & Ana Kim',
      customerPhone: '(512) 555-0198',
      notes: 'No cooling since yesterday. Outdoor fan spins, no cold air.',
      adminNotes: '',
      packId: 'hvac',
      status: 'needs_parts',
      priority: 'emergency',
      assigneeUid: 'demo-tech-2',
      assigneeName: 'Jordan Lee',
      scheduledFor: 'Today 11:30 AM',
      fieldNotes: [
        {
          id: 'demo-fn-2',
          text: 'Low suction, 45° split. Contactor pitted — ordered replacement via Parts tab.',
          authorUid: 'demo-tech-2',
          createdAt: ago(0.3),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(1),
      updatedAt: ago(0.3),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-3',
      title: '200A panel upgrade — rough inspection prep',
      address: '4401 Elm Creek Blvd, Cedar Park TX',
      customerName: 'Westlake Property Mgmt',
      customerPhone: '(512) 555-0221',
      notes: 'Subpanel labels missing; AFCI breakers for kitchen renovation.',
      adminNotes: 'Permit #EL-2026-1847 on file.',
      packId: 'electrical',
      status: 'queued',
      priority: 'normal',
      assigneeUid: 'demo-tech-3',
      assigneeName: 'Sam Chen',
      scheduledFor: 'Wed 8:00 AM',
      fieldNotes: [],
      photos: [],
      faultIds: [],
      createdAt: ago(3),
      updatedAt: ago(3),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-4',
      title: 'Sta-Rite heater — ignition failure',
      address: '77 Palm Court, Lakeway TX',
      customerName: 'Chris Navarro',
      customerPhone: '(512) 555-0167',
      notes: 'Heater fires then faults IF code. Gas pressure OK at meter.',
      adminNotes: '',
      packId: 'pool',
      status: 'done',
      priority: 'normal',
      assigneeUid: 'demo-tech-1',
      assigneeName: 'Marcus Rivera',
      scheduledFor: 'Fri 2:00 PM',
      fieldNotes: [
        {
          id: 'demo-fn-3',
          text: 'Flame sensor cleaned; heat exchanger OK. Tip logged to knowledge base.',
          authorUid: 'demo-tech-1',
          createdAt: ago(4),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(5),
      updatedAt: ago(4),
      completedAt: ago(4),
      isDemo: true,
    },
    {
      id: 'demo-job-5',
      title: 'Kitchen GFCI tripping — dishwasher circuit',
      address: '2100 Barton Springs Rd, Austin TX',
      customerName: 'Priya Shah',
      customerPhone: '(512) 555-0133',
      notes: 'Trips when dishwasher and disposal run together.',
      adminNotes: '',
      packId: 'electrical',
      status: 'in_progress',
      priority: 'normal',
      assigneeUid: 'demo-tech-3',
      assigneeName: 'Sam Chen',
      scheduledFor: 'Today 3:00 PM',
      fieldNotes: [],
      photos: [],
      faultIds: [],
      createdAt: ago(1),
      updatedAt: ago(0.5),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-6',
      title: 'Annual pool open — salt cell & chemistry balance',
      address: '3300 Scenic Dr, Austin TX',
      customerName: 'Greenfield HOA',
      customerPhone: '(512) 555-0200',
      notes: 'Open 3 community pools. Bring test kit refills.',
      adminNotes: 'Gate code 4421#',
      packId: 'pool',
      status: 'queued',
      priority: 'normal',
      assigneeUid: 'demo-tech-1',
      assigneeName: 'Marcus Rivera',
      scheduledFor: 'Mon 7:00 AM',
      fieldNotes: [],
      photos: [],
      faultIds: [],
      createdAt: ago(0.5),
      updatedAt: ago(0.5),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-7',
      title: 'Water heater — no hot water, pilot out',
      address: '5512 Burnet Rd, Austin TX',
      customerName: 'Linda Martinez',
      customerPhone: '(512) 555-0188',
      notes: '40 gal gas WH, pilot will not stay lit. Smell of gas when relighting.',
      adminNotes: 'Verify gas valve open at meter.',
      packId: 'plumbing',
      status: 'done',
      priority: 'high',
      assigneeUid: 'demo-tech-4',
      assigneeName: 'Alex Torres',
      scheduledFor: 'Sat 10:00 AM',
      fieldNotes: [
        {
          id: 'demo-fn-4',
          text: 'Thermocouple replaced. Diagnose walkthrough matched TCO fault pattern.',
          authorUid: 'demo-tech-4',
          createdAt: ago(1.2),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(2),
      updatedAt: ago(1.2),
      completedAt: ago(1.2),
      isDemo: true,
    },
    {
      id: 'demo-job-8',
      title: 'Trane XR14 — frozen coil, no airflow upstairs',
      address: '12008 Tech Ridge Blvd, Austin TX',
      customerName: 'North Austin Medical Plaza',
      customerPhone: '(512) 555-0244',
      notes: 'Filter overdue; tenant reports ice on lineset.',
      adminNotes: 'After-hours access — call security 512-555-0100.',
      packId: 'hvac',
      status: 'in_progress',
      priority: 'emergency',
      assigneeUid: 'demo-tech-2',
      assigneeName: 'Jordan Lee',
      scheduledFor: 'Today 6:30 PM',
      fieldNotes: [
        {
          id: 'demo-fn-5',
          text: 'Coil thawing. Filter 20x25x1 plugged solid — replaced from truck stock.',
          authorUid: 'demo-tech-2',
          createdAt: ago(0.08),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(0.15),
      updatedAt: ago(0.08),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-9',
      title: 'Main line backup — kitchen sink + laundry',
      address: '8901 Brodie Ln, Austin TX',
      customerName: 'James & Nora Webb',
      customerPhone: '(512) 555-0155',
      notes: 'Gurgling in both drains. Cleanout in garage.',
      adminNotes: '',
      packId: 'plumbing',
      status: 'done',
      priority: 'normal',
      assigneeUid: 'demo-tech-4',
      assigneeName: 'Alex Torres',
      scheduledFor: 'Thu 1:00 PM',
      fieldNotes: [
        {
          id: 'demo-fn-6',
          text: 'Snaked 75 ft, pulled grease plug. Recommended enzyme treatment.',
          authorUid: 'demo-tech-4',
          createdAt: ago(3),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(4),
      updatedAt: ago(3),
      completedAt: ago(3),
      isDemo: true,
    },
    {
      id: 'demo-job-10',
      title: 'EV charger install — 50A circuit + NEMA 14-50',
      address: '2200 Westlake Dr, West Lake Hills TX',
      customerName: 'Robert Finch',
      customerPhone: '(512) 555-0210',
      notes: 'Tesla Wall Connector. Panel has spare breaker slot.',
      adminNotes: 'Permit pulled — inspector Fri AM.',
      packId: 'electrical',
      status: 'queued',
      priority: 'normal',
      assigneeUid: 'demo-tech-3',
      assigneeName: 'Sam Chen',
      scheduledFor: 'Thu 8:00 AM',
      fieldNotes: [],
      photos: [],
      faultIds: [],
      createdAt: ago(2),
      updatedAt: ago(2),
      completedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-job-11',
      title: 'Jandy AquaLink — pump not responding on app',
      address: '4500 Spicewood Springs Rd, Austin TX',
      customerName: 'Helen & Paul Grant',
      customerPhone: '(512) 555-0177',
      notes: 'RS485 comm fault after storm. Breakers OK.',
      adminNotes: '',
      packId: 'pool',
      status: 'done',
      priority: 'normal',
      assigneeUid: 'demo-tech-1',
      assigneeName: 'Marcus Rivera',
      scheduledFor: 'Tue 4:00 PM',
      fieldNotes: [
        {
          id: 'demo-fn-7',
          text: 'Re-seated RS485 terminator; updated firmware via Diagnose checklist.',
          authorUid: 'demo-tech-1',
          createdAt: ago(5),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(6),
      updatedAt: ago(5),
      completedAt: ago(5),
      isDemo: true,
    },
    {
      id: 'demo-job-12',
      title: 'Rheem heat pump — aux heat stuck on',
      address: '1801 E 51st St, Austin TX',
      customerName: 'Eastside Co-op Housing',
      customerPhone: '(512) 555-0266',
      notes: 'Electric bill spike. Outdoor stat reads 58°F, aux running constantly.',
      adminNotes: 'Multi-unit — master key in lockbox.',
      packId: 'hvac',
      status: 'needs_parts',
      priority: 'high',
      assigneeUid: 'demo-tech-2',
      assigneeName: 'Jordan Lee',
      scheduledFor: 'Tomorrow 7:30 AM',
      fieldNotes: [
        {
          id: 'demo-fn-8',
          text: 'Outdoor temp sensor reading 28°F — ordered replacement sensor.',
          authorUid: 'demo-tech-2',
          createdAt: ago(0.6),
        },
      ],
      photos: [],
      faultIds: [],
      createdAt: ago(1),
      updatedAt: ago(0.6),
      completedAt: null,
      isDemo: true,
    },
  ];
}

export function getDemoTeamMembers() {
  return [
    {
      uid: 'demo-tech-1',
      email: 'marcus.rivera@demo.aibhive.com',
      displayName: 'Marcus Rivera',
      photoUrl: null,
      role: 'tech',
      status: 'active',
      tradePack: 'pool',
      joinedAt: ago(120),
      isDemo: true,
    },
    {
      uid: 'demo-tech-2',
      email: 'jordan.lee@demo.aibhive.com',
      displayName: 'Jordan Lee',
      photoUrl: null,
      role: 'tech',
      status: 'active',
      tradePack: 'hvac',
      joinedAt: ago(90),
      isDemo: true,
    },
    {
      uid: 'demo-tech-3',
      email: 'sam.chen@demo.aibhive.com',
      displayName: 'Sam Chen',
      photoUrl: null,
      role: 'tech',
      status: 'active',
      tradePack: 'electrical',
      joinedAt: ago(60),
      isDemo: true,
    },
    {
      uid: 'demo-tech-4',
      email: 'alex.torres@demo.aibhive.com',
      displayName: 'Alex Torres',
      photoUrl: null,
      role: 'tech',
      status: 'active',
      tradePack: 'plumbing',
      joinedAt: ago(45),
      isDemo: true,
    },
    {
      uid: 'demo-manager',
      email: 'hq@demo.aibhive.com',
      displayName: 'Jamie Okonkwo',
      photoUrl: null,
      role: 'admin',
      status: 'active',
      tradePack: 'multi',
      joinedAt: ago(200),
      isDemo: true,
    },
  ];
}

export function getDemoPartRequests() {
  return [
    {
      id: 'demo-part-1',
      status: 'pending_approval',
      partName: 'Hayward Super Pump impeller & seal kit',
      partNumber: 'SPX1600Z2',
      quantity: 1,
      brand: 'Hayward',
      equipmentModel: 'SP2607X10',
      notes: 'Customer pool down — need by Thursday.',
      partUrl: 'https://www.hayward.com/products/pumps/super-pump',
      jobId: 'demo-job-1',
      jobTitle: 'IntelliFlo VSF — priming loop / low flow',
      packId: 'pool',
      diagnoseQuery: 'Low flow on Pentair pump, impeller noise',
      requestedByUid: 'demo-tech-1',
      requestedByName: 'Marcus Rivera',
      requestedByEmail: 'marcus.rivera@demo.aibhive.com',
      approvedByName: null,
      orderedByName: null,
      declineReason: null,
      supplierNote: null,
      createdAt: ago(0.2),
      updatedAt: ago(0.2),
      approvedAt: null,
      orderedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-part-2',
      status: 'pending_approval',
      partName: 'Carrier contactor 2-pole 40A',
      partNumber: 'HC43GE230',
      quantity: 1,
      brand: 'Carrier',
      equipmentModel: '25HCC524A003',
      notes: 'Pitted contacts — outdoor unit not starting compressor.',
      jobId: 'demo-job-2',
      jobTitle: 'Carrier heat pump — no cool',
      packId: 'hvac',
      diagnoseQuery: 'Heat pump outdoor humming no cool',
      requestedByUid: 'demo-tech-2',
      requestedByName: 'Jordan Lee',
      requestedByEmail: 'jordan.lee@demo.aibhive.com',
      approvedByName: null,
      orderedByName: null,
      declineReason: null,
      supplierNote: null,
      createdAt: ago(0.35),
      updatedAt: ago(0.35),
      approvedAt: null,
      orderedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-part-3',
      status: 'approved',
      partName: 'Pentair IntelliChlor salt cell',
      partNumber: '520555',
      quantity: 1,
      brand: 'Pentair',
      equipmentModel: 'IC40',
      notes: 'Cell reading 0% — confirmed failed flow switch OK.',
      jobId: null,
      jobTitle: null,
      packId: 'pool',
      diagnoseQuery: 'Salt cell not producing chlorine',
      requestedByUid: 'demo-tech-1',
      requestedByName: 'Marcus Rivera',
      requestedByEmail: 'marcus.rivera@demo.aibhive.com',
      approvedByName: 'Office Manager',
      orderedByName: null,
      declineReason: null,
      supplierNote: null,
      createdAt: ago(1.5),
      updatedAt: ago(0.8),
      approvedAt: ago(0.8),
      orderedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-part-4',
      status: 'ordered',
      partName: 'Sta-Rite Max-E-Pro pump seal plate o-ring',
      partNumber: 'U006-906S',
      quantity: 2,
      brand: 'Sta-Rite',
      equipmentModel: 'MPE-5',
      notes: 'Stock spare for route truck.',
      jobId: 'demo-job-4',
      jobTitle: 'Sta-Rite heater — ignition failure',
      packId: 'pool',
      diagnoseQuery: 'Pump leaking at seal plate',
      requestedByUid: 'demo-tech-1',
      requestedByName: 'Marcus Rivera',
      requestedByEmail: 'marcus.rivera@demo.aibhive.com',
      approvedByName: 'Office Manager',
      orderedByName: 'Accounting',
      declineReason: null,
      supplierNote: 'PO #4821 — Pool Supply World, ETA Fri',
      createdAt: ago(3),
      updatedAt: ago(2),
      approvedAt: ago(2.5),
      orderedAt: ago(2),
      isDemo: true,
    },
    {
      id: 'demo-part-5',
      status: 'pending_approval',
      partName: 'Trane outdoor temp sensor',
      partNumber: 'SEN02037',
      quantity: 1,
      brand: 'Trane',
      equipmentModel: 'XR14',
      notes: 'Reading 28°F when ambient is 58°F — aux heat stuck.',
      jobId: 'demo-job-12',
      jobTitle: 'Rheem heat pump — aux heat stuck on',
      packId: 'hvac',
      diagnoseQuery: "Heat pump aux heat won't shut off outdoor sensor",
      requestedByUid: 'demo-tech-2',
      requestedByName: 'Jordan Lee',
      requestedByEmail: 'jordan.lee@demo.aibhive.com',
      approvedByName: null,
      orderedByName: null,
      declineReason: null,
      supplierNote: null,
      createdAt: ago(0.55),
      updatedAt: ago(0.55),
      approvedAt: null,
      orderedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-part-6',
      status: 'approved',
      partName: 'Rheem thermocouple universal',
      partNumber: 'SP20172',
      quantity: 2,
      brand: 'Rheem',
      equipmentModel: 'XR40T06',
      notes: 'Stock for water heater route.',
      jobId: 'demo-job-7',
      jobTitle: 'Water heater — no hot water',
      packId: 'plumbing',
      diagnoseQuery: "Gas water heater pilot won't stay lit",
      requestedByUid: 'demo-tech-4',
      requestedByName: 'Alex Torres',
      requestedByEmail: 'alex.torres@demo.aibhive.com',
      approvedByName: 'Jamie Okonkwo',
      orderedByName: null,
      declineReason: null,
      supplierNote: null,
      createdAt: ago(2),
      updatedAt: ago(1.5),
      approvedAt: ago(1.5),
      orderedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-part-7',
      status: 'ordered',
      partName: 'Square D 50A GFCI breaker',
      partNumber: 'QO250GFI',
      quantity: 1,
      brand: 'Square D',
      equipmentModel: 'QO panel',
      notes: 'EV charger install — permit inspection Fri.',
      jobId: 'demo-job-10',
      jobTitle: 'EV charger install — 50A circuit',
      packId: 'electrical',
      diagnoseQuery: 'EV charger GFCI requirements NEC 625',
      requestedByUid: 'demo-tech-3',
      requestedByName: 'Sam Chen',
      requestedByEmail: 'sam.chen@demo.aibhive.com',
      approvedByName: 'Jamie Okonkwo',
      orderedByName: 'Jamie Okonkwo',
      declineReason: null,
      supplierNote: 'Graybar pickup Wed AM',
      createdAt: ago(1.8),
      updatedAt: ago(1.2),
      approvedAt: ago(1.6),
      orderedAt: ago(1.2),
      isDemo: true,
    },
    {
      id: 'demo-part-8',
      status: 'declined',
      partName: 'Full heat pump condenser unit',
      partNumber: '25HCC524A003',
      quantity: 1,
      brand: 'Carrier',
      equipmentModel: '25HCC524A003',
      notes: 'Customer wanted whole unit — contactor fix sufficient.',
      jobId: 'demo-job-2',
      jobTitle: 'Carrier heat pump — no cool',
      packId: 'hvac',
      diagnoseQuery: null,
      requestedByUid: 'demo-tech-2',
      requestedByName: 'Jordan Lee',
      requestedByEmail: 'jordan.lee@demo.aibhive.com',
      approvedByName: 'Jamie Okonkwo',
      orderedByName: null,
      declineReason: 'Contactor repair approved instead — no full unit needed.',
      supplierNote: null,
      createdAt: ago(0.9),
      updatedAt: ago(0.7),
      approvedAt: null,
      orderedAt: null,
      isDemo: true,
    },
  ];
}

export function getDemoNotifications() {
  return [
    {
      id: 'demo-notif-1',
      title: 'New job assigned',
      body: 'IntelliFlo VSF — priming loop. 1842 Lakeshore Dr, 9:00 AM.',
      type: 'job_update',
      priority: 'high',
      jobId: 'demo-job-1',
      jobTitle: 'IntelliFlo VSF — priming loop / low flow',
      assigneeUid: 'demo-tech-1',
      assigneeName: 'Marcus Rivera',
      status: 'completed',
      response: {
        completed: true,
        fixSummary: 'En route — ETA 15 min',
        tipText: null,
        respondedByUid: 'demo-tech-1',
      },
      createdAt: ago(2),
      respondedAt: ago(1.9),
      isDemo: true,
    },
    {
      id: 'demo-notif-2',
      title: 'Part request submitted',
      body: 'Jordan Lee requested Carrier contactor HC43GE230 for heat pump job.',
      type: 'announcement',
      priority: 'normal',
      jobId: 'demo-job-2',
      jobTitle: 'Carrier heat pump — no cool',
      assigneeUid: null,
      assigneeName: null,
      status: 'pending',
      response: null,
      createdAt: ago(0.35),
      respondedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-notif-3',
      title: 'Fix of the week',
      body: 'Marcus logged a tip: IntelliFlo priming loop — check weir before replacing pump.',
      type: 'announcement',
      priority: 'normal',
      jobId: null,
      jobTitle: null,
      assigneeUid: null,
      assigneeName: null,
      status: 'pending',
      response: null,
      createdAt: ago(1),
      respondedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-notif-4',
      title: 'After-hours dispatch',
      body: 'North Austin Medical — frozen coil. Jordan en route (ETA 25 min).',
      type: 'job_update',
      priority: 'emergency',
      jobId: 'demo-job-8',
      jobTitle: 'Trane XR14 — frozen coil',
      assigneeUid: 'demo-tech-2',
      assigneeName: 'Jordan Lee',
      status: 'completed',
      response: {
        completed: true,
        fixSummary: 'On site — thawing coil',
        tipText: null,
        respondedByUid: 'demo-tech-2',
      },
      createdAt: ago(0.12),
      respondedAt: ago(0.1),
      isDemo: true,
    },
    {
      id: 'demo-notif-5',
      title: 'Part approved',
      body: 'Square D 50A GFCI approved for EV charger job — ordered from Graybar.',
      type: 'announcement',
      priority: 'normal',
      jobId: 'demo-job-10',
      jobTitle: 'EV charger install',
      assigneeUid: 'demo-tech-3',
      assigneeName: 'Sam Chen',
      status: 'pending',
      response: null,
      createdAt: ago(1.2),
      respondedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-notif-6',
      title: 'Voice agent — new lead',
      body: 'Pros voice captured: main line backup at 8901 Brodie Ln. Callback scheduled.',
      type: 'announcement',
      priority: 'high',
      jobId: null,
      jobTitle: null,
      assigneeUid: null,
      assigneeName: null,
      status: 'pending',
      response: null,
      createdAt: ago(3.5),
      respondedAt: null,
      isDemo: true,
    },
    {
      id: 'demo-notif-7',
      title: 'Diagnose sync',
      body: 'Alex marked water heater fix as helpful — tip promoted to team knowledge.',
      type: 'announcement',
      priority: 'normal',
      jobId: 'demo-job-7',
      jobTitle: 'Water heater — no hot water',
      assigneeUid: 'demo-tech-4',
      assigneeName: 'Alex Torres',
      status: 'completed',
      response: {
        completed: true,
        fixSummary: 'Thermocouple pattern saved to knowledge base',
        tipText: 'Check thermocouple before replacing gas valve',
        respondedByUid: 'demo-tech-4',
      },
      createdAt: ago(1.1),
      respondedAt: ago(1.0),
      isDemo: true,
    },
    {
      id: 'demo-notif-8',
      title: 'Weekly route digest',
      body: '12 open jobs, 3 pending parts, 4 techs in field. Pool route Mon AM.',
      type: 'announcement',
      priority: 'normal',
      jobId: null,
      jobTitle: null,
      assigneeUid: null,
      assigneeName: null,
      status: 'pending',
      response: null,
      createdAt: ago(0.02),
      respondedAt: null,
      isDemo: true,
    },
  ];
}

export function getDemoActivity() {
  return [
    {
      id: 'demo-act-1',
      type: 'knowledge_tip',
      message: 'Field tip added: IntelliFlo priming — check skimmer weir for air leak',
      actorUid: 'demo-tech-1',
      actorEmail: 'marcus.rivera@demo.aibhive.com',
      createdAt: ago(0.5),
      isDemo: true,
    },
    {
      id: 'demo-act-2',
      type: 'part_request',
      message: 'Part request: Carrier contactor HC43GE230',
      actorUid: 'demo-tech-2',
      actorEmail: 'jordan.lee@demo.aibhive.com',
      createdAt: ago(0.35),
      isDemo: true,
    },
    {
      id: 'demo-act-3',
      type: 'job_complete',
      message: 'Job completed: Sta-Rite heater — ignition failure',
      actorUid: 'demo-tech-1',
      actorEmail: 'marcus.rivera@demo.aibhive.com',
      jobId: 'demo-job-4',
      createdAt: ago(4),
      isDemo: true,
    },
    {
      id: 'demo-act-4',
      type: 'manual_ingest',
      message: 'Manual ingested: Pentair IntelliFlo VSF installation guide (14 chunks)',
      actorUid: 'demo-manager',
      actorEmail: 'hq@demo.aibhive.com',
      createdAt: ago(7),
      isDemo: true,
    },
    {
      id: 'demo-act-5',
      type: 'diagnose_feedback',
      message: 'Diagnose feedback: "That worked" on salt cell flow troubleshooting',
      actorUid: 'demo-tech-1',
      actorEmail: 'marcus.rivera@demo.aibhive.com',
      createdAt: ago(2),
      isDemo: true,
    },
    {
      id: 'demo-act-6',
      type: 'part_request_update',
      message: 'Part request ordered: Sta-Rite seal plate o-ring (PO #4821)',
      actorUid: 'demo-manager',
      actorEmail: 'hq@demo.aibhive.com',
      createdAt: ago(2),
      isDemo: true,
    },
    {
      id: 'demo-act-7',
      type: 'job_assigned',
      message: 'Job assigned: Trane XR14 frozen coil — after-hours dispatch',
      actorUid: 'demo-manager',
      actorEmail: 'hq@demo.aibhive.com',
      jobId: 'demo-job-8',
      createdAt: ago(0.15),
      isDemo: true,
    },
    {
      id: 'demo-act-8',
      type: 'knowledge_tip',
      message: 'Field tip added: Rheem aux heat — verify outdoor temp sensor before board swap',
      actorUid: 'demo-tech-2',
      actorEmail: 'jordan.lee@demo.aibhive.com',
      createdAt: ago(0.6),
      isDemo: true,
    },
    {
      id: 'demo-act-9',
      type: 'part_request',
      message: 'Part request: Trane outdoor temp sensor SEN02037',
      actorUid: 'demo-tech-2',
      actorEmail: 'jordan.lee@demo.aibhive.com',
      createdAt: ago(0.55),
      isDemo: true,
    },
    {
      id: 'demo-act-10',
      type: 'job_complete',
      message: 'Job completed: Water heater — thermocouple replaced',
      actorUid: 'demo-tech-4',
      actorEmail: 'alex.torres@demo.aibhive.com',
      jobId: 'demo-job-7',
      createdAt: ago(1.2),
      isDemo: true,
    },
    {
      id: 'demo-act-11',
      type: 'diagnose_feedback',
      message: 'Diagnose feedback: "That worked" on Jandy RS485 comm reset steps',
      actorUid: 'demo-tech-1',
      actorEmail: 'marcus.rivera@demo.aibhive.com',
      createdAt: ago(5),
      isDemo: true,
    },
    {
      id: 'demo-act-12',
      type: 'voice_lead',
      message: 'Voice agent logged lead: pool heater IF code — scheduled Tue PM',
      actorUid: 'demo-manager',
      actorEmail: 'hq@demo.aibhive.com',
      createdAt: ago(0.25),
      isDemo: true,
    },
    {
      id: 'demo-act-13',
      type: 'part_request_update',
      message: 'Part request declined: full condenser unit — contactor repair instead',
      actorUid: 'demo-manager',
      actorEmail: 'hq@demo.aibhive.com',
      createdAt: ago(0.7),
      isDemo: true,
    },
    {
      id: 'demo-act-14',
      type: 'job_complete',
      message: 'Job completed: Main line backup — grease plug cleared',
      actorUid: 'demo-tech-4',
      actorEmail: 'alex.torres@demo.aibhive.com',
      jobId: 'demo-job-9',
      createdAt: ago(3),
      isDemo: true,
    },
  ];
}

/** Austin-area sample pins for Where is everybody? */
export function getDemoLocations() {
  return [
    {
      uid: 'demo-tech-1',
      displayName: 'Marcus Rivera',
      email: 'marcus.rivera@demo.aibhive.com',
      lat: 30.2672,
      lng: -97.7431,
      accuracyM: 18,
      updatedAt: ago(0.02),
      stale: false,
      onJobId: 'demo-job-1',
      isDemo: true,
    },
    {
      uid: 'demo-tech-2',
      displayName: 'Jordan Lee',
      email: 'jordan.lee@demo.aibhive.com',
      lat: 30.5083,
      lng: -97.6789,
      accuracyM: 22,
      updatedAt: ago(0.04),
      stale: false,
      onJobId: 'demo-job-2',
      isDemo: true,
    },
    {
      uid: 'demo-tech-3',
      displayName: 'Sam Chen',
      email: 'sam.chen@demo.aibhive.com',
      lat: 30.505,
      lng: -97.82,
      accuracyM: 15,
      updatedAt: ago(0.08),
      stale: false,
      onJobId: 'demo-job-5',
      isDemo: true,
    },
    {
      uid: 'demo-tech-4',
      displayName: 'Alex Torres',
      email: 'alex.torres@demo.aibhive.com',
      lat: 30.35,
      lng: -97.72,
      accuracyM: 20,
      updatedAt: ago(0.03),
      stale: false,
      onJobId: 'demo-job-7',
      isDemo: true,
    },
  ];
}

export async function getCompanyDemoContext(db, companyId) {
  const snap = await db.collection('pros_companies').doc(companyId).get();
  const data = snap.data() || {};
  return {
    settings: data.settings || {},
    tradeType: data.tradeType || 'multi',
    name: data.name || 'Your company',
  };
}

export async function getSparseCounts(db, companyId) {
  const ref = db.collection('pros_companies').doc(companyId);
  const [jobsSnap, tipsSnap, feedbackSnap, partsSnap, notifSnap] = await Promise.all([
    ref.collection('jobs').limit(20).get(),
    ref.collection('knowledge_tips').limit(20).get(),
    ref.collection('knowledge_feedback').limit(20).get(),
    ref.collection('part_requests').limit(20).get(),
    ref.collection('notifications').limit(20).get(),
  ]);
  return {
    jobs: jobsSnap.size,
    tips: tipsSnap.size,
    feedback: feedbackSnap.size,
    parts: partsSnap.size,
    notifications: notifSnap.size,
  };
}
