import type { EquipmentManual } from './types';

/**
 * Offline manual index — metadata + links to OEM documentation.
 * Full PDF text can be ingested server-side later (Pros RAG); this ships URLs
 * so techs can open the right manual in one tap from the field.
 */
export const MANUAL_CORPUS: EquipmentManual[] = [
  // —— Pool ——
  {
    id: 'manual-pentair-intelliflo-vsf',
    packId: 'pool',
    brand: 'Pentair',
    modelPrefixes: ['011057', 'INTELLIFLO', 'VSF', 'VS+', 'INTELLIFLO3'],
    title: 'IntelliFlo VSF / VS+ variable-speed pump',
    category: 'pumps',
    manualUrl: 'https://www.pentair.com/en-us/products/residential/pool-spa-equipment/pool-pumps/intelliflo-vsf-variable-speed-pump.html',
    summary: 'Programming speeds, wiring, fault codes, and wet-end service for IntelliFlo VSF platforms.',
    relatedFaultIds: ['pool-vs-error', 'pool-pump-hum-no-spin'],
  },
  {
    id: 'manual-hayward-tristar-vs',
    packId: 'pool',
    brand: 'Hayward',
    modelPrefixes: ['TRISTAR', 'SP3202', 'SP3206', 'VS900', 'W3SP3202'],
    title: 'TriStar VS variable-speed pump',
    category: 'pumps',
    manualUrl: 'https://www.hayward.com/en-us/products/pumps/variable-speed-pumps/tristar-vs.html',
    summary: 'Drive menu, TRIP faults, priming, and union/wet-end exploded views.',
    relatedFaultIds: ['pool-vs-error', 'pool-pump-no-prime'],
  },
  {
    id: 'manual-hayward-aquarite',
    packId: 'pool',
    brand: 'Hayward',
    modelPrefixes: ['AQUARITE', 'T-CELL', 'T15', 'T9', 'GLX-CELL'],
    title: 'AquaRite salt chlorine generator',
    category: 'salt',
    manualUrl: 'https://www.hayward.com/en-us/products/sanitization/salt-chlorination/aquarite.html',
    summary: 'Cell cleaning, salt calibration, flow switch, and diagnostic LED patterns.',
    relatedFaultIds: ['pool-salt-low-false', 'pool-no-chlorine'],
  },
  {
    id: 'manual-jandy-iaqualink',
    packId: 'pool',
    brand: 'Jandy / Zodiac',
    modelPrefixes: ['IAQUALINK', 'RS', 'PS', 'PDA'],
    title: 'iAqualink automation',
    category: 'automation',
    manualUrl: 'https://www.jandy.com/en/products/automation/iaqualink',
    summary: 'RS board wiring, relay mapping, app pairing, and heater enable logic.',
    relatedFaultIds: ['pool-automation-relay'],
  },
  {
    id: 'manual-pentair-mastertemp',
    packId: 'pool',
    brand: 'Pentair',
    modelPrefixes: ['MASTERTEMP', '460736', '460737', 'SR333'],
    title: 'MasterTemp gas pool heater',
    category: 'heaters',
    manualUrl: 'https://www.pentair.com/en-us/products/residential/pool-spa-equipment/pool-heaters/mastertemp-pool-and-spa-heater.html',
    summary: 'Ignition sequence, AG/AF fault legends, water pressure switch, and venting.',
    relatedFaultIds: ['pool-heater-ignition'],
  },
  {
    id: 'manual-pentair-clean-clear',
    packId: 'pool',
    brand: 'Pentair',
    modelPrefixes: ['CLEAN', 'CLEAR', 'CC100', 'CC150', 'CC200'],
    title: 'Clean & Clear cartridge filter',
    category: 'filters',
    manualUrl: 'https://www.pentair.com/en-us/products/residential/pool-spa-equipment/pool-filters/cartridge-filters/clean-clear-cartridge-filter.html',
    summary: 'Band clamp, cartridge spec, pressure gauge baseline, and drain procedures.',
    relatedFaultIds: ['pool-filter-high-pressure'],
  },
  // —— Electrical ——
  {
    id: 'manual-sqd-qo-panel',
    packId: 'electrical',
    brand: 'Square D / Schneider',
    modelPrefixes: ['QO', 'QO130', 'QO220', 'HOM', 'HOM24L70'],
    title: 'QO / Homeline load centers',
    category: 'panels',
    manualUrl: 'https://www.se.com/us/en/product-range-presentation/62050-square-d-qo-and-homeline-load-centers/',
    summary: 'Breaker compatibility, torque specs, bonding bar, and labeling.',
    relatedFaultIds: ['elec-breaker-nuisance', 'elec-panel-hot'],
  },
  {
    id: 'manual-eaton-ch',
    packId: 'electrical',
    brand: 'Eaton',
    modelPrefixes: ['CH', 'BR', 'CH130', 'CH220', 'BR2020'],
    title: 'CH / BR load centers',
    category: 'panels',
    manualUrl: 'https://www.eaton.com/us/en-us/catalog/low-voltage-power-distribution-controls-systems/residential-loadcenters.html',
    summary: 'CH vs BR breaker families, neutral bar, and ground bonding.',
    relatedFaultIds: ['elec-breaker-nuisance'],
  },
  {
    id: 'manual-sqd-homeline-gfci-afci',
    packId: 'electrical',
    brand: 'Square D',
    modelPrefixes: ['QO120CAFI', 'QO120GFI', 'HOM120CAFI', 'HOM120GFI'],
    title: 'QO / Homeline AFCI & GFCI breakers',
    category: 'breakers',
    manualUrl: 'https://www.se.com/us/en/product-range-presentation/62050-square-d-qo-and-homeline-load-centers/',
    summary: 'Trip diagnostics, pigtail neutrals, shared neutral limitations.',
    relatedFaultIds: ['elec-gfci-wont-reset', 'elec-afci-trip'],
  },
  {
    id: 'manual-generac-standby',
    packId: 'electrical',
    brand: 'Generac',
    modelPrefixes: ['GUARDIAN', '22KW', '24KW', '7043', '7210'],
    title: 'Guardian home standby generator',
    category: 'panels',
    manualUrl: 'https://www.generac.com/residential-products/standby-generators/',
    summary: 'Transfer switch, exercise cycle, fault codes, and service intervals.',
    relatedFaultIds: ['elec-motor-wont-start'],
  },
  // —— Plumbing ——
  {
    id: 'manual-rinnai-tankless',
    packId: 'plumbing',
    brand: 'Rinnai',
    modelPrefixes: ['RU199', 'RU160', 'RUCS', 'RUIN', 'V53', 'RL75'],
    title: 'Rinnai tankless water heaters',
    category: 'water-heaters',
    manualUrl: 'https://www.rinnai.us/tankless-water-heater',
    summary: 'Error code 10/11, descale procedure, venting, and gas pressure specs.',
    relatedFaultIds: ['plumb-tankless-flame-failure'],
  },
  {
    id: 'manual-navien-npe',
    packId: 'plumbing',
    brand: 'Navien',
    modelPrefixes: ['NPE', 'NPE-180', 'NPE-210', 'NPE-240', 'NPN'],
    title: 'Navien NPE condensing tankless',
    category: 'water-heaters',
    manualUrl: 'https://www.navieninc.com/residential/tankless-water-heaters',
    summary: 'E003/E012 ignition faults, cascade setup, and condensate neutralizer.',
    relatedFaultIds: ['plumb-tankless-flame-failure'],
  },
  {
    id: 'manual-bradford-white-gas',
    packId: 'plumbing',
    brand: 'Bradford White',
    modelPrefixes: ['RG', 'MI', 'RE', 'UR', 'M440'],
    title: 'Bradford White gas water heaters',
    category: 'water-heaters',
    manualUrl: 'https://www.bradfordwhite.com/products/residential-water-heaters/gas/',
    summary: 'Pilot/ignitor systems, T&P specs, anode, and LED flash codes.',
    relatedFaultIds: ['plumb-tank-wh-no-hot', 'plumb-tp-valve-dripping'],
  },
  {
    id: 'manual-zoeller-sump',
    packId: 'plumbing',
    brand: 'Zoeller',
    modelPrefixes: ['M53', 'M98', 'M267', 'M264', '50', 'EPM'],
    title: 'Zoeller submersible sump pumps',
    category: 'gas-backflow',
    manualUrl: 'https://www.zoeller.com/products/residential-sump-pumps/',
    summary: 'Float switch adjustment, impeller clearance, and vertical switch replacement.',
    relatedFaultIds: ['plumb-sump-pump-not-running'],
  },
  {
    id: 'manual-watts-rpz',
    packId: 'plumbing',
    brand: 'Watts',
    modelPrefixes: ['009', 'RPZ', 'LF009', '775', '957'],
    title: 'Watts RPZ backflow assemblies',
    category: 'gas-backflow',
    manualUrl: 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers',
    summary: 'Annual test procedure, relief discharge causes, and rebuild kits.',
    relatedFaultIds: ['plumb-backflow-preventer-drip'],
  },
  {
    id: 'manual-moen-positemp',
    packId: 'plumbing',
    brand: 'Moen',
    modelPrefixes: ['1222', '1225', '2520', 'T215', 'POSI-TEMP'],
    title: 'Moen Posi-Temp shower valves',
    category: 'fixtures',
    manualUrl: 'https://www.moen.com/support',
    summary: '1222 cartridge replacement, scald guard adjustment, and stop removal.',
    relatedFaultIds: ['plumb-shower-valve-temp-fault', 'plumb-faucet-drip-cartridge'],
  },
  // —— HVAC ——
  {
    id: 'manual-carrier-infinity',
    packId: 'hvac',
    brand: 'Carrier / Bryant',
    modelPrefixes: ['24ACC', '24ANB', '58MCA', 'FE4ANF', 'Infinity'],
    title: 'Carrier Infinity / Performance split systems',
    category: 'cooling',
    manualUrl: 'https://www.carrier.com/residential/en/us/products/',
    summary: 'Communicating fault codes, charge charts, and thermostat pairing.',
    relatedFaultIds: ['hvac-ac-warm-air', 'hvac-communicating-stat-fault'],
  },
  {
    id: 'manual-trane-xr',
    packId: 'hvac',
    brand: 'Trane / American Standard',
    modelPrefixes: ['XR', '4TTR', 'TEM6', 'TAM9', 'S9V2'],
    title: 'Trane XR / XV heat pumps & furnaces',
    category: 'heating',
    manualUrl: 'https://www.trane.com/residential/en/products/',
    summary: 'Blinking LED fault codes, defrost board, and filter sizing.',
    relatedFaultIds: ['hvac-furnace-no-heat', 'hvac-heat-pump-wont-heat'],
  },
  {
    id: 'manual-lennox-elite',
    packId: 'hvac',
    brand: 'Lennox',
    modelPrefixes: ['EL', 'XC', 'ML', 'CBK', 'ELO'],
    title: 'Lennox Elite / Merit series',
    category: 'cooling',
    manualUrl: 'https://www.lennox.com/products/',
    summary: 'E227 and related diagnostics, blower tables, and warranty registration.',
    relatedFaultIds: ['hvac-ac-warm-air'],
  },
  {
    id: 'manual-goodman-gmec',
    packId: 'hvac',
    brand: 'Goodman / Amana',
    modelPrefixes: ['GMEC', 'GMSS', 'ARUF', 'ASPT', 'CAPF'],
    title: 'Goodman gas furnaces & air handlers',
    category: 'heating',
    manualUrl: 'https://www.goodmanmfg.com/products',
    summary: 'LED flash codes, ignitor replacement, and door switch interlock.',
    relatedFaultIds: ['hvac-ignitor-failure', 'hvac-flame-sensor-fault'],
  },
  {
    id: 'manual-nest-thermostat',
    packId: 'hvac',
    brand: 'Google Nest',
    modelPrefixes: ['T3007', 'T3016', 'G4CVZ', 'LEARNING', 'NEST'],
    title: 'Nest Learning / Thermostat',
    category: 'controls',
    manualUrl: 'https://support.google.com/googlenest/answer/9248268',
    summary: 'C-wire requirements, E195 power errors, and heat pump O/B wiring.',
    relatedFaultIds: ['hvac-thermostat-blank'],
  },
  {
    id: 'manual-ecobee',
    packId: 'hvac',
    brand: 'Ecobee',
    modelPrefixes: ['EB-', 'EB-STATE', 'SMARTTHERMOSTAT', 'ECOBEE'],
    title: 'Ecobee smart thermostats',
    category: 'controls',
    manualUrl: 'https://www.ecobee.com/en-us/support/',
    summary: 'PEK adapter, equipment configuration, and auxiliary heat lockout.',
    relatedFaultIds: ['hvac-thermostat-blank', 'hvac-aux-heat-stuck-on'],
  },
  {
    id: 'manual-mitsubishi-mz',
    packId: 'hvac',
    brand: 'Mitsubishi Electric',
    modelPrefixes: ['MSZ', 'MXZ', 'SUZ', 'MUZ', '6607'],
    title: 'Mitsubishi mini-split / multi-zone',
    category: 'cooling',
    manualUrl: 'https://www.mitsubishicomfort.com/products',
    summary: '6607 comm errors, dip switch addressing, and line-set length limits.',
    relatedFaultIds: ['hvac-communicating-stat-fault', 'hvac-ac-warm-air'],
  },
  // —— Property / appliances ——
  {
    id: 'manual-whirlpool-cabrio',
    packId: 'property',
    brand: 'Whirlpool / Maytag',
    modelPrefixes: ['WTW', 'MVWB', 'CABRIO', 'BRAVOS', 'WED'],
    title: 'Whirlpool Cabrio / Bravos washer & dryer',
    category: 'appliances',
    manualUrl: 'https://www.whirlpool.com/support.html',
    summary: 'Tech sheet location, F21 drain, and lid lock service mode.',
    relatedFaultIds: ['prop-washer-no-drain'],
  },
  {
    id: 'manual-lg-washer',
    packId: 'property',
    brand: 'LG',
    modelPrefixes: ['WM', 'WT', 'DLEX', 'DLG'],
    title: 'LG front-load washers & dryers',
    category: 'appliances',
    manualUrl: 'https://www.lg.com/us/support',
    summary: 'OE/UE codes, pump filter access, and inverter motor tests.',
    relatedFaultIds: ['prop-washer-no-drain', 'prop-dryer-no-heat'],
  },
  {
    id: 'manual-samsung-appliance',
    packId: 'property',
    brand: 'Samsung',
    modelPrefixes: ['WF', 'WA', 'RF', 'DW', 'NE63'],
    title: 'Samsung laundry & kitchen',
    category: 'appliances',
    manualUrl: 'https://www.samsung.com/us/support/',
    summary: 'Model-specific tech bulletins, 4C/5C, and ice maker fill tube fixes.',
    relatedFaultIds: ['prop-washer-no-drain', 'prop-dishwasher-no-drain'],
  },
  {
    id: 'manual-ge-appliance',
    packId: 'property',
    brand: 'GE / Profile',
    modelPrefixes: ['GFE', 'GDT', 'JB', 'GTW', 'PFE'],
    title: 'GE Profile appliances',
    category: 'appliances',
    manualUrl: 'https://www.geappliances.com/ge/service-and-support/',
    summary: 'Service manuals, TCO boards, and dishwasher drain paths.',
    relatedFaultIds: ['prop-fridge-warm', 'prop-dishwasher-no-drain'],
  },
  {
    id: 'manual-insinkerator',
    packId: 'property',
    brand: 'InSinkErator',
    modelPrefixes: ['BADGER', 'EVOLUTION', 'PRO', 'ESSENTIAL'],
    title: 'InSinkErator disposals',
    category: 'appliances',
    manualUrl: 'https://www.insinkerator.com/support',
    summary: 'Reset button, hex wrench unjam, and dishwasher knockout.',
    relatedFaultIds: ['prop-disposal-hum'],
  },
];
