import type { FaultEntry } from '../types';

export const fiberFaults: FaultEntry[] = [
  {
    id: 'fiber-fusion-high-loss',
    packId: 'fiber',
    category: 'splicing',
    title: 'Fusion splice loss too high',
    aliases: ['high loss splice', 'splice fail', '0.5 dB splice', 'fusion loss high'],
    symptoms: ['OTDR event > 0.1 dB on single-mode', 'Power meter delta exceeds splice spec', 'Splicer estimates high loss before protector'],
    likelyCauses: ['Contaminated or scratched fiber endface', 'Misaligned cores / offset', 'Wrong cleave angle or bad cleave', 'Wrong fusion program for fiber type', 'Bubble or inclusion in splice'],
    steps: [
      'Strip, clean, and re-cleave both fibers; inspect endfaces at 200× before re-splicing.',
      'Verify fusion program matches fiber (G.652.D vs G.657.A1 bend-insensitive).',
      'Check electrode wear and run arc calibration per splicer manual.',
      'Re-splice and measure with inline power meter or OTDR through launch cable.',
      'If loss persists on good cleaves, inspect V-groove contamination and replace electrodes.',
    ],
    safety: ['Never look into live fiber — use power meter or VFL only.', 'Dispose cleave scraps in sharps container.'],
    tools: ['Fusion splicer', 'High-precision cleaver', 'IPA wipes', 'Fiber inspection scope', 'OTDR or power meter'],
    parts: ['Splice protectors', 'Replacement fiber stub', 'Electrode kit'],
    severity: 'high',
    proTips: ['Most high-loss splices are dirty or bad cleaves — rework ends before blaming the splicer.'],
  },
  {
    id: 'fiber-fusion-bubble',
    packId: 'fiber',
    category: 'splicing',
    title: 'Bubble or void visible in fusion splice',
    aliases: ['bubble in splice', 'void splice', 'splice inclusion', 'cloudy splice'],
    symptoms: ['Visible bubble in splice microscope view', 'Elevated loss and back-reflection', 'Splicer may flag estimate warning'],
    likelyCauses: ['Moisture on fiber', 'Contamination in V-groove', 'Arc power too low', 'Damaged fiber coating in strip zone'],
    steps: [
      'Cut out splice and re-strip with longer buffer strip if coating entered arc zone.',
      'Clean V-grooves with manufacturer-approved tool; dry with lint-free wipes.',
      'Re-cleave and fuse with verified dry fiber ends.',
      'Run arc test / calibration if bubbles repeat on clean fiber.',
      'Document splice loss and photo for QA if on backbone span.',
    ],
    safety: ['Hot splice protectors — allow cool before handling.'],
    tools: ['Fusion splicer', 'Fiber scope', 'V-groove cleaner', 'Cleaver'],
    parts: ['Splice protectors', 'Electrodes'],
    severity: 'medium',
    proTips: ['A single bubble often means moisture — always dry after alcohol wipe before cleaving.'],
  },
  {
    id: 'fiber-cleave-angle-bad',
    packId: 'fiber',
    category: 'splicing',
    title: 'Bad cleave angle causing splice loss',
    aliases: ['cleave angle off', 'bad cleave', 'chipped cleave', 'cleaver blade worn'],
    symptoms: ['Endface scope shows angle > 1°', 'Uneven ferrule contact on mechanical splice', 'Fusion splicer rejects or warns on estimate'],
    likelyCauses: ['Worn cleaver blade', 'Fiber not seated in cleaver', 'Tension on fiber during cleave', 'Wrong cleaver for fiber diameter'],
    steps: [
      'Inspect cleave angle on scope — rotate fiber 90° and re-check.',
      'Replace cleaver blade per cut count schedule.',
      'Ensure fiber is perpendicular and fully seated in cleaver clamp.',
      'Cleve again and verify mirror endface before splicing.',
      'Log blade serial / cut count for maintenance tracking.',
    ],
    safety: ['Handle cleaved fiber ends carefully — glass shards are sharp.'],
    tools: ['Precision cleaver', 'Fiber inspection scope', 'IPA wipes'],
    parts: ['Cleaver blade', 'Replacement cleaver'],
    severity: 'medium',
    proTips: ['If one side cleaves well and the other does not, suspect blade wear or clamp damage.'],
  },
  {
    id: 'fiber-mechanical-splice-loss',
    packId: 'fiber',
    category: 'splicing',
    title: 'Mechanical splice high loss or intermittent',
    aliases: ['mechanical splice fail', 'cam lock splice loss', 'quick splice bad'],
    symptoms: ['Loss > 0.3 dB on SM mechanical splice', 'Link flaps when cable moved', 'Visible gap in index-matching gel'],
    likelyCauses: ['Fiber not fully inserted to stop', 'Gel expired or contaminated', 'Fiber diameter mismatch (250 µm vs 900 µm)', 'Lock cam not fully closed'],
    steps: [
      'Open mechanical splice and inspect fiber insertion depth marks.',
      'Re-strip, clean, cleave, and re-insert both fibers to full stop.',
      'Verify gel is fresh and splice body is rated for SM fiber.',
      'Close cam lock fully and tug-test gently per manufacturer spec.',
      'Measure loss with power meter; replace splice body if gel is cloudy.',
    ],
    safety: ['Temporary mechanical splices on drops — plan fusion for permanent restore.'],
    tools: ['Mechanical splice kit', 'Cleaver', 'Power meter', 'VFL'],
    parts: ['Mechanical splice bodies', 'Index-matching gel'],
    severity: 'medium',
    proTips: ['Mechanical splices are for emergency restore — fusion the span when traffic allows.'],
  },
  {
    id: 'fiber-splice-protector-shift',
    packId: 'fiber',
    category: 'splicing',
    title: 'Splice protector shifted / micro-bend at splice tray',
    aliases: ['protector too tight', 'fiber pinched in tray', 'splice tray bend'],
    symptoms: ['Loss spikes when tray lid closed', 'OTDR shows event at splice rack', 'Fiber paint stripe cracked at protector'],
    likelyCauses: ['Protector crimped too tight', 'Fiber radius too tight in tray', 'Protector length wrong for tray slot', 'Multiple fibers stacked under splice'],
    steps: [
      'Open tray and relieve tension on fiber path to splice.',
      'Re-seat protector in tray channel without pinching.',
      'Verify minimum bend radius (typically 30 mm SM) leaving splice.',
      'Re-test with OTDR or power meter before closing tray.',
      'Re-route slack so splice is not under mechanical stress.',
    ],
    safety: ['Do not force tray lid if fiber binds — rework routing first.'],
    tools: ['Splice tray', 'OTDR', 'Radius gauge'],
    parts: ['Splice protectors', 'Tray organizers'],
    severity: 'medium',
    proTips: ['A loss that appears only when the tray closes is almost always routing, not the splice itself.'],
  },
  {
    id: 'fiber-otdr-ghost-event',
    packId: 'fiber',
    category: 'testing',
    title: 'OTDR ghost / false event on trace',
    aliases: ['ghost event', 'false reflection', 'double peak otdr', 'phantom event'],
    symptoms: ['Duplicate events at multiples of distance', 'Event does not match physical plant', 'Loss values unrealistic on ghost'],
    likelyCauses: ['Poor launch cable connection', 'Reflective connector at near end', 'OTDR pulse width too wide', 'Dead zone masking real event'],
    steps: [
      'Clean and inspect launch cable connector; re-test with known good launch.',
      'Use shorter pulse width and increase averaging for near-end resolution.',
      'Try testing from opposite direction to confirm real vs ghost event.',
      'Apply index of refraction (IOR) matching fiber spec — wrong IOR shifts all events.',
      'Mark real events on as-built and correlate with vault/handhole map.',
    ],
    safety: ['OTDR lasers are Class 1M/3R — never view fiber output directly.'],
    tools: ['OTDR', 'Launch cable', 'Known-good reference patch', 'Inspection scope'],
    parts: ['Launch cable', 'SC/APC reference'],
    severity: 'medium',
    proTips: ['Bidirectional OTDR averaging separates real splices from ghosts every time.'],
  },
  {
    id: 'fiber-otdr-no-backscatter',
    packId: 'fiber',
    category: 'testing',
    title: 'OTDR shows no backscatter / flat line after event',
    aliases: ['otdr flat line', 'no trace after break', 'fiber break otdr', 'end of fiber event'],
    symptoms: ['Trace drops to noise floor after sharp event', 'VFL shows red light escaping at one location', 'No return from remote end'],
    likelyCauses: ['Complete fiber break or severe bend', 'Cut cable', 'Crushed duct', 'Open connector (fiber not seated)'],
    steps: [
      'Shoot VFL from near end — bright leak pinpoints break for field locate.',
      'Walk span / review as-built for recent construction or aerial damage.',
      'Open nearest handhole and inspect for cut or pulled buffer tubes.',
      'If break confirmed, plan fusion restore with sufficient slack both sides.',
      'After repair, OTDR both directions and store trace for records.',
    ],
    safety: ['Traffic control if locating break along roadway; bucket safety for aerial.'],
    tools: ['OTDR', 'VFL', 'Tone locator', 'Fusion splicer'],
    parts: ['Fiber cable', 'Splice protectors', 'Closure kit'],
    severity: 'critical',
    proTips: ['VFL from both ends can distinguish mid-span break vs open far-end connector.'],
  },
  {
    id: 'fiber-power-meter-high-loss',
    packId: 'fiber',
    category: 'testing',
    title: 'Optical power budget failure / high span loss',
    aliases: ['high db loss', 'power budget fail', 'low rx power', 'link margin negative'],
    symptoms: ['RX power below ONT threshold', 'OLT reports high loss on PON branch', 'Measured loss exceeds design budget'],
    likelyCauses: ['Dirty connectors at patch panel', 'Excess splices or poor splices', 'Macro-bends in slack storage', 'Wrong wavelength test', 'Splitter tap too many times'],
    steps: [
      'Reference power meter at known good port; zero calibration with meter set.',
      'Measure at 1490/1577 nm for GPON/XGS-PON per SFP spec — match wavelength.',
      'Clean all connectors with proper stick cleaner; inspect before mate.',
      'Segment test: OLT → splitter → mid-span → ONT to isolate loss segment.',
      'Compare measured loss to design budget (splices + connectors + splitter + fiber/km).',
    ],
    safety: ['Confirm you are on correct live PON port before opening at OLT — use proper filters.'],
    tools: ['Calibrated power meter', 'OLTS', 'Inspection scope', 'Connector cleaners'],
    parts: ['Patch cords', 'Splitters (if failed)'],
    severity: 'high',
    proTips: ['Segment isolation beats guessing — measure each leg of a branched PON.'],
  },
  {
    id: 'fiber-vfl-no-light-customer',
    packId: 'fiber',
    category: 'testing',
    title: 'VFL shows no light at customer premises',
    aliases: ['no red light', 'vfl dark', 'no light at ont', 'dark fiber drop'],
    symptoms: ['VFL injected at FDH shows no glow at customer end', 'ONT LOS alarm', 'Drop continuity fails'],
    likelyCauses: ['Cut drop cable', 'Open mechanical splice in pedestal', 'APC connector open at NID', 'Splitter port dead or mis-patched'],
    steps: [
      'Confirm VFL is on correct splitter port at FDH — verify patch record.',
      'VFL from FDH toward customer; locate last bright point before dark section.',
      'Open pedestal/NID and inspect for broken drop or loose connector.',
      'OTDR from FDH if distance to fault is uncertain on long drop.',
      'Repair cut or re-terminate; verify RX within ONT range before closing ticket.',
    ],
    safety: ['Pedestal traffic cones; assume drop may be aerial — hard hat and gloves.'],
    tools: ['VFL', 'OTDR', 'Power meter', 'Fusion splicer or field termination kit'],
    parts: ['Drop cable', 'SC/APC pigtail', 'Weather enclosure'],
    severity: 'critical',
    proTips: ['Always verify splitter port labeling before blaming the drop — wrong port wastes hours.'],
  },
  {
    id: 'fiber-olts-fail-report',
    packId: 'fiber',
    category: 'testing',
    title: 'OLTS / tier-1 test fail on new install',
    aliases: ['olts fail', 'tier 1 fail', 'insertion loss fail', 'link not certified'],
    symptoms: ['OLTS reports FAIL on length or loss', 'One fiber in pair fails polarity', 'Margin below threshold on PDF report'],
    likelyCauses: ['Transposed TX/RX', 'Dirty reference cord on OLTS', 'Wrong test standard selected', 'Connector not fully seated'],
    steps: [
      'Clean OLTS reference cords and DUT connectors; re-run auto test.',
      'Verify correct fiber mapping (1→1, 2→2) on duplex LC.',
      'Check test limit (OM3 vs OM4, SM vs MM) matches installed cable.',
      'Re-terminate failing end if loss isolated to one connector.',
      'Export PDF report for customer sign-off and file in job packet.',
    ],
    safety: ['Cap unused ports during testing to prevent contamination.'],
    tools: ['OLTS', 'Inspection scope', 'Connector cleaners'],
    parts: ['LC connectors', 'Patch cords'],
    severity: 'medium',
    proTips: ['90% of OLTS fails on new build are dirty refs or swapped TX/RX — check those first.'],
  },
  {
    id: 'fiber-ont-los-alarm',
    packId: 'fiber',
    category: 'distribution',
    title: 'ONT LOS (loss of signal) alarm',
    aliases: ['ont los', 'red los light', 'ont no light', 'customer offline los'],
    symptoms: ['ONT LOS LED solid red', 'No service at premises', 'OLT shows last gasp or offline'],
    likelyCauses: ['No optical power at ONT', 'Broken drop or open connector', 'OLT PON port down', 'Splitter failure', 'ONT optical port failed'],
    steps: [
      'Measure optical power at ONT feed with meter — compare to ONT sensitivity spec.',
      'If no power, trace upstream: NID → drop → splitter → FDH patch.',
      'Check OLT for PON port alarm; verify VLAN/provisioning only after optical OK.',
      'Swap ONT with known-good unit if power is present but LOS persists.',
      'Document RX level and close with carrier threshold screenshot.',
    ],
    safety: ['Do not stare into live PON fiber — power levels can exceed eye-safe in distribution.'],
    tools: ['Optical power meter', 'VFL', 'Known-good ONT'],
    parts: ['ONT', 'SC/APC pigtail', 'Drop cable'],
    severity: 'critical',
    proTips: ['LOS is always optics first — provisioning tickets come after you have measurable RX.'],
  },
  {
    id: 'fiber-ont-not-registering',
    packId: 'fiber',
    category: 'distribution',
    title: 'ONT not registering on OLT (optical OK)',
    aliases: ['ont wont register', 'gpon serial not found', 'ont auth fail', 'omci fail'],
    symptoms: ['RX power within range but ONT stays offline', 'OLT shows discovery but auth fails', 'Wrong serial in EMS'],
    likelyCauses: ['Serial/GPON SN mismatch in OLT provisioning', 'Wrong PON technology (GPON vs XGS-PON)', 'ONT profile not assigned', 'VLAN/line profile mismatch'],
    steps: [
      'Confirm measured RX at ONT within vendor range (typically -8 to -27 dBm GPON).',
      'Read ONT serial from label or local GUI; compare to OLT provisioning exactly.',
      'Verify OLT port is correct technology and not mixed XGS/GPON on same port.',
      'Push correct line profile / service profile from EMS; reboot ONT.',
      'If still failing, factory-reset ONT and re-provision per carrier workflow.',
    ],
    safety: ['Document EMS changes — mis-provisioning can affect other subscribers on PON.'],
    tools: ['Power meter', 'Laptop for ONT GUI', 'EMS access'],
    parts: ['ONT'],
    severity: 'high',
    proTips: ['Copy-paste serial numbers — one wrong character blocks registration for hours.'],
  },
  {
    id: 'fiber-olt-pon-port-down',
    packId: 'fiber',
    category: 'distribution',
    title: 'OLT PON port down / all customers on leg offline',
    aliases: ['whole pon down', 'olt port alarm', 'all ont offline', 'pon leg out'],
    symptoms: ['All ONTs on splitter leg offline', 'OLT LOS or PON failed alarm', 'No optical from port'],
    likelyCauses: ['OLT SFP failed', 'Fiber cut upstream of splitter', 'Patch cord pulled at headend', 'OLT card reboot / software fault'],
    steps: [
      'Check OLT alarms and correlate with NOC ticket.',
      'Verify patch at OLT frame — reseat SFP if permitted by carrier procedure.',
      'OTDR or VFL from OLT toward field to locate cut.',
      'If SFP optical out is dead with good patch, replace SFP per sparing policy.',
      'Restore traffic and confirm ONT mass re-register before clearing alarm.',
    ],
    safety: ['Headend work may require escort and change control — follow carrier process.'],
    tools: ['OTDR', 'Power meter', 'Spare SFP'],
    parts: ['PON SFP', 'Patch cord'],
    severity: 'critical',
    proTips: ['If every customer on one PON is out, think upstream of the splitter first.'],
  },
  {
    id: 'fiber-splitter-failure',
    packId: 'fiber',
    category: 'distribution',
    title: 'Splitter high loss or dead output port',
    aliases: ['splitter bad port', 'splitter loss high', '1x32 port dead', 'fdh splitter fail'],
    symptoms: ['One branch has high loss vs siblings', 'No power on splitter output port', 'Water in splitter enclosure'],
    likelyCauses: ['Cracked splitter chip', 'Water ingress in FDH', 'Over-tight bend on splitter pigtail', 'Factory defect on one leg'],
    steps: [
      'Measure all splitter outputs from same input — compare loss uniformity.',
      'Inspect FDH for water, cracked housing, or damaged pigtails.',
      'Move customer to spare splitter port if available; document port map update.',
      'Replace splitter module if leg is dead or > 1 dB over spec.',
      'Update as-built and EMS port assignment after swap.',
    ],
    safety: ['FDH may have live PON on other ports — use dust caps and avoid cross-connects.'],
    tools: ['Power meter', 'VFL', 'Splitter spares'],
    parts: ['1×N splitter', 'FDH gasket kit'],
    severity: 'high',
    proTips: ['Compare all legs — one hot leg and one dead leg screams splitter not drop.'],
  },
  {
    id: 'fiber-gpon-xgs-mismatch',
    packId: 'fiber',
    category: 'distribution',
    title: 'GPON / XGS-PON technology mismatch',
    aliases: ['wrong pon type', 'xgs ont on gpon port', 'ont incompatible', 'symmetric pon mismatch'],
    symptoms: ['ONT never discovers despite good power', 'OLT rejects wrong optics', 'SFP wavelength mismatch'],
    likelyCauses: ['XGS-PON ONT on GPON port', 'Wrong SFP in OLT', 'Field swap mixed generations', 'Customer CPE upgrade not coordinated'],
    steps: [
      'Read ONT and OLT port technology from labels and EMS.',
      'Verify SFP part number matches port designation (GPON Class B+ vs XGS).',
      'Replace ONT or move to correct port per carrier design.',
      'Re-provision with correct profile after hardware match.',
      'Label customer NID with technology to prevent repeat truck roll.',
    ],
    safety: ['Never mix optics types on same PON without engineered plan.'],
    tools: ['EMS', 'Power meter', 'Correct ONT/SFP'],
    parts: ['GPON or XGS-PON ONT', 'Matching SFP'],
    severity: 'high',
    proTips: ['When optics look fine but nothing registers, check technology match before re-splicing.'],
  },
  {
    id: 'fiber-dirty-sc-apc',
    packId: 'fiber',
    category: 'premises',
    title: 'Dirty or damaged SC/APC connector',
    aliases: ['dirty apc', 'sc apc high loss', 'green connector dirty', 'scratch on ferrule'],
    symptoms: ['Intermittent loss when wiggling connector', 'Visible dirt on scope', 'Loss > 0.5 dB on pair'],
    likelyCauses: ['Finger oil on ferrule', 'Using wet wipes on APC', 'Scratched ceramic ferrule', 'Cap missing — dust on endface'],
    steps: [
      'Inspect endface at 200× — look for dirt, pits, scratches.',
      'Clean with dry stick cleaner only (no alcohol on APC unless vendor allows).',
      'Re-inspect; if scratch crosses core, re-terminate connector.',
      'Mate carefully — listen for single click, do not spin APC connectors.',
      'Measure loss; replace patch if still above 0.3 dB mated pair.',
    ],
    safety: ['APC angle is precise — never mate UPC into APC port.'],
    tools: ['Inspection scope', 'Stick cleaners', 'Reference patch'],
    parts: ['SC/APC pigtail', 'Field connector kit'],
    severity: 'medium',
    proTips: ['One dirty connector at the patch panel can look like a bad span — clean before OTDR panic.'],
  },
  {
    id: 'fiber-lc-duplex-polarity',
    packId: 'fiber',
    category: 'premises',
    title: 'LC duplex polarity / TX-RX swap',
    aliases: ['polarity swap', 'tx rx reversed', 'flipped fibers', 'no link wrong pair'],
    symptoms: ['OLTS fails polarity', 'No link but power on wrong fiber', 'One direction works only'],
    likelyCauses: ['Incorrect duplex latch orientation', 'MPO polarity Type A vs B confusion', 'Field termination swapped fibers'],
    steps: [
      'Use VFL or continuity checker to identify TX/RX pair mapping.',
      'Verify patch cord polarity (A-to-A vs A-to-B) against rack diagram.',
      'For MPO, confirm trunk polarity label matches switch and panel.',
      'Swap TX/RX at one end only if both fibers reach correct ports.',
      'Re-certify with OLTS after correction.',
    ],
    safety: ['Powered optics — disable port before re-patching if hot-swap not supported.'],
    tools: ['VFL', 'OLTS', 'Polarity tester'],
    parts: ['Correct polarity patch cord', 'MPO cassette'],
    severity: 'medium',
    proTips: ['Duplex polarity issues often show up as “works one way” on bi-di testing — always check pair mapping.'],
  },
  {
    id: 'fiber-mpo-polarity',
    packId: 'fiber',
    category: 'premises',
    title: 'MPO trunk polarity / cassette mismatch',
    aliases: ['mpo wrong type', 'mpo 12f polarity', 'cassette swap', 'data center mpo fail'],
    symptoms: ['Multiple channels fail OLTS', 'Transceiver link down on half strands', 'Correct loss on wrong ports'],
    likelyCauses: ['Type A vs Type B trunk mix-up', 'Cassette flipped in module', 'Wrong key-up/key-down orientation'],
    steps: [
      'Identify MPO polarity standard on both ends (Method A/B/C per TIA-568).',
      'Trace strand mapping with VFL from switch to patch panel.',
      'Replace or re-key cassette to match engineered polarity.',
      'Re-test all strands on OLTS — do not assume one good strand means all good.',
      'Label cassettes and trunks per site standard.',
    ],
    safety: ['High-density ports — cap unused MPO to block dust.'],
    tools: ['MPO tester', 'VFL', 'Polarity documentation'],
    parts: ['MPO cassette', 'Correct polarity trunk'],
    severity: 'high',
    proTips: ['Method B trunks are common — verify before re-terminating every LC leg.'],
  },
  {
    id: 'fiber-macro-bend-rack',
    packId: 'fiber',
    category: 'premises',
    title: 'Macro-bend loss in rack / slack management',
    aliases: ['macro bend', 'tight bend in rack', 'fiber pinched', 'bend radius violation'],
    symptoms: ['Loss increases when cable dressed', 'OTDR shows bend event not splice', 'G.657 fiber still lossy at tight radius'],
    likelyCauses: ['Violating minimum bend radius', 'Zip ties too tight', 'Fiber stuffed behind equipment', 'Door pinching cable'],
    steps: [
      'Identify bend location — OTDR or VFL from nearest access point.',
      'Re-dress slack using proper guides; maintain ≥ 30 mm radius SM (check cable spec).',
      'Replace zip ties with hook-and-loop; no hard clamps on buffer tube.',
      'Re-test loss after dress — compare before/after readings.',
      'Leave service loop per rack design for future work.',
    ],
    safety: ['De-energize adjacent power when dressing fiber near busbars.'],
    tools: ['OTDR', 'VFL', 'Radius guides', 'Velcro straps'],
    parts: ['Fiber guides', 'Cable management'],
    severity: 'medium',
    proTips: ['Bend loss often moves when you push on the cable — wiggle test confirms macro-bend.'],
  },
  {
    id: 'fiber-patch-panel-wrong-port',
    packId: 'fiber',
    category: 'premises',
    title: 'Patch panel cross-connect / wrong port',
    aliases: ['wrong patch', 'cross connect error', 'labeled wrong port', 'swapped customer'],
    symptoms: ['Customer gets someone else service', 'OTDR distance does not match record', 'Good light wrong VLAN'],
    likelyCauses: ['Human labeling error', 'Documentation not updated after change', 'Similar port numbers on adjacent panels'],
    steps: [
      'Tone or VFL trace from customer to FDH with partner confirming port flashes.',
      'Compare field trace to as-built and EMS ONT assignment.',
      'Move patch to correct port; update labels and records immediately.',
      'Verify customer service and optical levels after move.',
      'Photo panel labels for ticket closure.',
    ],
    safety: ['Changing live PON patches can disturb other customers — coordinate brief outage if needed.'],
    tools: ['VFL', 'Tone tracer', 'Label printer'],
    parts: ['Patch cords', 'Labels'],
    severity: 'high',
    proTips: ['When optics are perfect but the wrong customer lights up, it is always a patch record problem.'],
  },
  {
    id: 'fiber-drop-cut-aerial',
    packId: 'fiber',
    category: 'troubleshooting',
    title: 'Aerial drop cable cut or storm damage',
    aliases: ['drop cut', 'aerial fiber cut', 'storm damage drop', 'tree fell on fiber'],
    symptoms: ['VFL bright at cut location', 'Customer and neighbors on same strand out', 'Cable hanging low'],
    likelyCauses: ['Vehicle strike', 'Tree limb', 'Improper strand support', 'Rodent chew at lashed drop'],
    steps: [
      'Make safe — traffic cones, bucket if aerial, de-energize if near power lines per policy.',
      'Locate cut with VFL; gather sufficient slack for fusion or mechanical temp splice.',
      'Strip and fusion splice drop; protect in weather enclosure or splice case.',
      'Verify optical level at ONT; secure cable with proper lash and sag.',
      'Update damage report and photo for insurance/carrier.',
    ],
    safety: ['Stay clear of downed power lines — call utility if fiber on power equipment.'],
    tools: ['Fusion splicer', 'VFL', 'Aerial lashing tools', 'Bucket truck'],
    parts: ['Drop cable', 'Splice closure', 'Support hardware'],
    severity: 'critical',
    proTips: ['Temp mechanical splice gets customer back — schedule fusion when weather clears.'],
  },
  {
    id: 'fiber-handhole-water',
    packId: 'fiber',
    category: 'troubleshooting',
    title: 'Handhole flooding / wet splice closure',
    aliases: ['water in handhole', 'wet closure', 'flooded vault', 'corrosion splice case'],
    symptoms: ['High loss after rain event', 'Water inside closure', 'Corroded mechanical splices'],
    likelyCauses: ['Failed gasket on closure', 'Handhole below water table', 'Cracked conduit entry', 'Poor sealing of cable entries'],
    steps: [
      'Pump or vacuum water per safety procedure; ventilate confined space per OSHA.',
      'Open closure, dry splices, inspect for corrosion or water damage.',
      'Re-splice damaged fibers; replace heat-shrink or gel closure if compromised.',
      'Re-seal cable entries with proper kits; test watertightness.',
      'Elevate or relocate closure if chronic flooding.',
    ],
    safety: ['Confined space entry requires training and gas monitor — follow company policy.'],
    tools: ['Closure kit', 'Fusion splicer', 'Pump', 'Desiccant'],
    parts: ['Splice closure', 'Gasket kit', 'Entry seals'],
    severity: 'high',
    proTips: ['After any water event, assume every mechanical splice in that closure is suspect.'],
  },
  {
    id: 'fiber-intermittent-link',
    packId: 'fiber',
    category: 'troubleshooting',
    title: 'Intermittent fiber link / flapping ONT',
    aliases: ['flapping ont', 'intermittent fiber', 'link up down', 'random los'],
    symptoms: ['ONT drops and recovers', 'Loss changes when cable touched', 'Errors correlate with wind or vibration'],
    likelyCauses: ['Loose connector', 'Fractured fiber near tight bend', 'Bad mechanical splice', 'Damaged pigtail at strain relief'],
    steps: [
      'Inspect all connectors for looseness; reseat and clean.',
      'Gently flex cable along path while monitoring power meter for loss change.',
      'OTDR for hidden fracture or tight bend events.',
      'Re-terminate or re-splice suspect section.',
      'Monitor ONT for 30+ minutes before closing intermittent ticket.',
    ],
    safety: ['Intermittent PON can affect alarm thresholds — document min/max RX.'],
    tools: ['Power meter', 'OTDR', 'Inspection scope'],
    parts: ['Connectors', 'Pigtails', 'Splice protectors'],
    severity: 'high',
    proTips: ['Wiggle-test while watching dBm — intermittent almost always mechanical.'],
  },
  {
    id: 'fiber-sm-mm-mismatch',
    packId: 'fiber',
    category: 'troubleshooting',
    title: 'Single-mode / multimode fiber mismatch',
    aliases: ['sm mm mismatch', 'wrong fiber type', 'mode mismatch', 'gig over mm too far'],
    symptoms: ['High loss despite short distance', 'Link works on MM only with short patch', 'OTDR shows wrong event spacing'],
    likelyCauses: ['SM transceiver on MM fiber', 'MM patch in SM span', 'Field tech mixed cable reels'],
    steps: [
      'Read cable jacket marking (OS2 vs OM3/OM4).',
      'Verify SFP/SFP+ spec matches fiber type and distance.',
      'Replace patch or span segment with correct fiber type.',
      'Re-test loss and distance limits per IEEE/application.',
      'Label ends to prevent future mix-ups.',
    ],
    safety: ['SM launch power into MM can blind receivers — check before live mate.'],
    tools: ['Cable ID labels', 'Power meter', 'OTDR'],
    parts: ['Correct fiber patch', 'Media converters if transition required'],
    severity: 'high',
    proTips: ['Orange jacket vs yellow jacket — teach apprentices before they fusion the wrong reel.'],
  },
  {
    id: 'fiber-fdh-pedestal-vandalism',
    packId: 'fiber',
    category: 'troubleshooting',
    title: 'FDH / pedestal tampering or vandalism',
    aliases: ['pedestal opened', 'fdh tamper', 'fiber stolen', 'vandal cut'],
    symptoms: ['Enclosure open', 'Fibers pulled out', 'Multiple customers out in neighborhood'],
    likelyCauses: ['Theft of copper confused with fiber', 'Kids opened pedestal', 'Contractor damage'],
    steps: [
      'Secure scene; photo damage for police/carrier report if theft.',
      'Identify all cut or pulled fibers; tag pairs before restoration.',
      'Fusion restore each fiber; update splitter port map.',
      'Lock enclosure with carrier-approved lock; repair hinge/gasket.',
      'Notify NOC of mass restore and re-provision if SNs changed.',
    ],
    safety: ['Assume enclosure may have live PON — eye safety and dust caps.'],
    tools: ['Fusion splicer', 'OTDR', 'Lock kit', 'Label set'],
    parts: ['Splitter pigtails', 'Closure parts', 'Pedestal lid'],
    severity: 'critical',
    proTips: ['Tag every fiber before splicing a vandal mess — port map errors take longer than the cuts.'],
  },
  {
    id: 'fiber-bend-insensitive-g657',
    packId: 'fiber',
    category: 'premises',
    title: 'G.657 bend-insensitive fiber still high loss',
    aliases: ['g657 bend loss', 'bend insensitive fail', 'tight coiled drop', 'mini bend loss'],
    symptoms: ['Loss at small coil in customer premises', 'OTDR bend signature at CPE', 'Drop coiled behind ONT'],
    likelyCauses: ['Coil radius below G.657.A1 spec', 'Fiber kinked during install', 'ONT fiber pigtail pinched', 'Using G.652 in tight bend location'],
    steps: [
      'Uncoil drop to generous loop behind ONT; maintain manufacturer minimum radius.',
      'Inspect for kink — kinked fiber must be cut and re-terminated.',
      'If premises routing is tight, replace with G.657.A2 or proper indoor cable.',
      'Measure RX before and after dress at ONT.',
      'Educate customer not to pinch fiber with furniture.',
    ],
    safety: ['Customer premises — boot covers and respect for home.'],
    tools: ['Power meter', 'Coil guide', 'Field termination kit'],
    parts: ['G.657 drop cable', 'ONT pigtail'],
    severity: 'medium',
    proTips: ['Bend-insensitive does not mean tie-wrap tight — still needs a real loop.'],
  },
  {
    id: 'fiber-connector-endface-scratch',
    packId: 'fiber',
    category: 'premises',
    title: 'Connector endface scratch / pit requiring re-terminate',
    aliases: ['scratched ferrule', 'pitted connector', 'bad polish', 'connector fail scope'],
    symptoms: ['Scope shows scratch through core', 'Loss > 1 dB on good mate', 'Repeat fail after cleaning'],
    likelyCauses: ['Dirty mate damaged ferrule', 'Dropped connector', 'Bad field polish', 'Manufacturing defect'],
    steps: [
      'Document scope image for QA.',
      'Cut connector and re-terminate or replace factory pigtail.',
      'Polish per kit instructions if field LC — check under scope before mate.',
      'Verify loss < 0.3 dB on reference test.',
      'Cap connector until final mate.',
    ],
    safety: ['Dispose ceramic ferrule shards safely.'],
    tools: ['Inspection scope', 'Field polish kit', 'Cleaver'],
    parts: ['Connectors', 'Pigtails'],
    severity: 'medium',
    proTips: ['Do not polish through a deep scratch — re-terminate saves another truck roll.'],
  },
  {
    id: 'fiber-otdr-wrong-ior',
    packId: 'fiber',
    category: 'testing',
    title: 'OTDR distance error / wrong index of refraction',
    aliases: ['wrong ior', 'otdr distance off', 'event location wrong', 'cant find break distance'],
    symptoms: ['OTDR distance does not match map', 'Crew digs wrong handhole', 'Event table miles off'],
    likelyCauses: ['IOR left at default 1.465', 'Mixed fiber types on span', 'Not using cable-specific IOR'],
    steps: [
      'Set IOR from cable datasheet (often 1.467–1.468 for G.652 at 1310 nm).',
      'Re-shoot trace and compare known vault distances.',
      'For mixed plant, segment OTDR per cable type.',
      'Mark corrected distances on printout for locate crew.',
      'Store IOR in OTDR cable library for site.',
    ],
    safety: ['Wrong locate wastes crew time in roadway — verify IOR before mark-out.'],
    tools: ['OTDR with cable library', 'As-built map'],
    parts: [],
    severity: 'medium',
    proTips: ['Always correlate OTDR distance to two known physical landmarks before digging.'],
  },
  {
    id: 'fiber-pon-olt-high-ont-count',
    packId: 'fiber',
    category: 'distribution',
    title: 'PON oversubscription / optical budget exhausted',
    aliases: ['too many onts', 'pon overloaded', 'rx too low many splits', 'cascade splitter loss'],
    symptoms: ['ONTs at edge of spec RX', 'New ONT install knocks others offline', 'OLT reports optical budget warning'],
    likelyCauses: ['Too many splitter stages', 'High-split ratio on long distance', 'No headroom for aging plant', 'Bad splice adding loss across whole PON'],
    steps: [
      'Calculate budget: OLT launch + splits + splices + fiber loss vs ONT sensitivity.',
      'Measure worst-case ONT RX on leg; compare to spec margin.',
      'Reduce split ratio, move leg to new PON, or shorten cascade.',
      'Fix plant loss if one bad splice affects entire branch.',
      'Coordinate with engineering before adding ONTs on marginal PON.',
    ],
    safety: ['Split changes may require overnight outage — schedule with NOC.'],
    tools: ['Power meter', 'Budget calculator', 'EMS'],
    parts: ['Splitter', 'SFP'],
    severity: 'high',
    proTips: ['When the last ONT on a PON barely registers, the PON is full — engineer before adding one more.'],
  },
];
