import type { FaultEntry } from '../types';

export const plumbingFaults: FaultEntry[] = [
  {
    id: 'plumb-main-sewer-backup',
    packId: 'plumbing',
    category: 'drains',
    title: 'Main sewer line backup / multiple fixtures backing up',
    aliases: ['main line clog', 'sewage backup', 'multiple drains clogged', 'whole house backup'],
    symptoms: [
      'Lowest fixtures back up first (basement shower or floor drain).',
      'Toilet bubbles when sink or tub drains.',
      'Sewage odor and dirty water at floor drains.',
      'Multiple fixtures drain slowly at the same time.',
    ],
    likelyCauses: [
      'Main building drain blockage from wipes, paper, or grease buildup.',
      'Root intrusion at clay or older sewer joints.',
      'Bellied or broken sewer line holding solids.',
      'City main surcharge during heavy rain events.',
      'Failed backwater valve stuck partially closed.',
    ],
    steps: [
      '1) Stop all water use immediately to prevent additional overflow.',
      '2) Confirm this is a main-line issue by testing one high fixture and one low fixture.',
      '3) Pull a downstream cleanout carefully and check for standing sewage in the line.',
      '4) Cable or hydro-jet from the correct cleanout toward the street and then back toward the house.',
      '5) Camera-inspect the line after flow is restored to document roots, offsets, or collapse.',
      '6) Recommend root treatment, spot repair, or full replacement based on camera findings.',
    ],
    safety: [
      'Raw sewage is a biohazard - use gloves, eye protection, and disposable boot covers.',
      'Do not run fixtures while cleanout is open indoors.',
      'Use respirator protection in poorly ventilated crawlspaces or pits.',
    ],
    tools: ['Drain machine with cutter heads', 'Sewer camera', 'Hydro-jetter', 'PPE kit', 'Disinfectant'],
    parts: ['Cleanout cap and plug', 'Backwater valve flapper', 'Repair coupling', 'Root inhibitor treatment'],
    severity: 'critical',
    proTips: ['If more than one fixture is involved, always start diagnosis at the main cleanout before opening interior traps.'],
  },
  {
    id: 'plumb-kitchen-grease-clog',
    packId: 'plumbing',
    category: 'drains',
    title: 'Kitchen drain slow / grease clog',
    aliases: ['slow kitchen sink', 'grease blockage', 'food disposal clog', 'double bowl backflow'],
    symptoms: [
      'Water pools in one or both kitchen sink bowls.',
      'Drain improves briefly after plunging then slows again.',
      'Gurgling at kitchen line when dishwasher drains.',
      'Greasy odor from sink or disposal.',
    ],
    likelyCauses: [
      'Grease and soap solids narrowed branch drain.',
      'Partial blockage at trap arm or sanitary tee.',
      'Disposal discharge baffle jammed with food solids.',
      'Improper slope causing recurring sludge settlement.',
      'Air admittance valve failure causing poor venting.',
    ],
    steps: [
      '1) Remove and inspect P-trap for grease mat and food solids.',
      '2) Verify disposal spins freely and knockout plug is removed if recently installed.',
      '3) Cable branch line through trap arm toward stack until resistance clears.',
      '4) Flush with hot water plus detergent to break remaining grease film.',
      '5) If recurring, inspect line grade/venting and consider access for periodic jetting.',
    ],
    safety: [
      'Shut disposal power before reaching near grind chamber.',
      'Avoid chemical drain openers before cabling - chemicals can splash during service.',
    ],
    tools: ['Hand auger', 'Sink machine cable', 'Trap wrench', 'Bucket', 'Inspection camera'],
    parts: ['Tubular trap kit', 'Slip-joint washers', 'Air admittance valve', 'Disposal baffle'],
    severity: 'medium',
    proTips: ['Grease clogs hide just past the trap arm bend, so a short cable run with the right head is often enough.'],
  },
  {
    id: 'plumb-shower-tub-slow-drain',
    packId: 'plumbing',
    category: 'drains',
    title: 'Shower or tub drain slow',
    aliases: [
      'slow tub drain',
      'hair clog',
      'standing shower water',
      'bath drain clog',
      'bathtub not draining',
      'tub not draining',
      'tub wont drain',
      'bathtub wont drain',
      'shower not draining',
      'bath not draining',
    ],
    symptoms: [
      'Water rises around feet while shower is running.',
      'Tub takes several minutes to drain after use.',
      'Drain emits gurgle after flow stops.',
      'Occasional sewer smell near tub shoe.',
    ],
    likelyCauses: [
      'Hair and soap scum accumulation at strainer and trap.',
      'Pop-up stopper linkage not fully opening.',
      'Branch drain partially blocked downstream of trap.',
      'Vent restriction causing sluggish flow.',
      'Old cast iron scaling reduced pipe diameter.',
    ],
    steps: [
      '1) Remove stopper and extract visible hair/debris at drain opening.',
      '2) Fill and release tub to observe flow rate and confirm partial vs full blockage.',
      '3) Run a small cable through overflow or drain body to clear trap and trap arm.',
      '4) Flush with hot water while monitoring for backing at nearby fixtures.',
      '5) If issue repeats quickly, camera the branch line for scale or sagging.',
    ],
    safety: [
      'Use non-slip protection in wet tub surfaces while servicing.',
      'Do not mix drain chemicals with mechanical cleaning tools.',
    ],
    tools: ['Zip tool', 'Hand auger', 'Screwdriver set', 'Wet vac', 'Mini inspection camera'],
    parts: ['Tub stopper assembly', 'Overflow gasket', 'Trap adapter washers'],
    severity: 'low',
    proTips: ['Pulling the overflow plate often gives better cable access than forcing through the drain shoe.'],
  },
  {
    id: 'plumb-toilet-weak-flush',
    packId: 'plumbing',
    category: 'fixtures',
    title: 'Toilet weak flush / partial clog',
    aliases: ['lazy flush', 'toilet not clearing bowl', 'partial blockage', 'double flush'],
    symptoms: [
      'Bowl rises high then drains slowly.',
      'Paper remains after one flush.',
      'Toilet may clear then clog again on next use.',
      'Other nearby fixtures generally drain normally.',
    ],
    likelyCauses: [
      'Partial obstruction in trapway or closet bend.',
      'Low tank water level reducing flush volume.',
      'Blocked rim jets limiting bowl wash and siphon action.',
      'Vent issue affecting siphon performance.',
      'Aging low-flow toilet with worn flush valve components.',
    ],
    steps: [
      '1) Check tank level and adjust fill valve to manufacturer waterline.',
      '2) Use closet auger to clear trapway and retrieve trapped objects if present.',
      '3) Verify flapper opens fully and chain has slight slack.',
      '4) Clean rim jet ports if mineral scale is restricting flow.',
      '5) If recurring, run mainline check to rule out downstream branch restrictions.',
    ],
    safety: ['Sanitize tools after toilet service.', 'Shut angle stop if bowl threatens to overflow.'],
    tools: ['Closet auger', 'Mirror', 'Bucket', 'Nylon brush', 'Adjustable pliers'],
    parts: ['Flapper', 'Fill valve', 'Flush valve seal', 'Wax ring if reset required'],
    severity: 'medium',
    proTips: ['A strong swirl with weak siphon usually means trapway restriction, not just a tank adjustment issue.'],
  },
  {
    id: 'plumb-toilet-running-phantom',
    packId: 'plumbing',
    category: 'fixtures',
    title: 'Toilet running / phantom flush / flapper issues',
    aliases: ['ghost flush', 'toilet keeps refilling', 'leaking flapper', 'running fill valve'],
    symptoms: [
      'Tank refills periodically without use.',
      'Audible hiss from fill valve.',
      'Water trickle visible into bowl.',
      'Higher water bill with no obvious leak points.',
    ],
    likelyCauses: [
      'Worn flapper not sealing flush valve seat.',
      'Chain too tight preventing complete flapper closure.',
      'Fill valve overfilling into overflow tube.',
      'Pitted flush valve seat surface.',
      'Tank-to-bowl bolt gasket leak lowering tank level.',
    ],
    steps: [
      '1) Add dye to tank and confirm color transfer into bowl without flushing.',
      '2) Replace flapper and set chain slack to about 1/2 inch.',
      '3) Adjust fill valve so waterline sits below overflow top.',
      '4) Clean or replace flush valve seat if new flapper still leaks.',
      '5) Recheck after 15 minutes for silent, stable tank level.',
    ],
    safety: ['Close angle stop before disassembling fill or flush components.', 'Hand-tighten plastic nuts to avoid cracking tank.'],
    tools: ['Dye tablets', 'Channel-lock pliers', 'Sponge', 'Small brush'],
    parts: ['Flapper', 'Fill valve', 'Flush valve seal', 'Tank bolt kit'],
    severity: 'low',
    proTips: ['Dye test first - it prevents replacing fill valves when the real culprit is a leaking flapper seat.'],
  },
  {
    id: 'plumb-toilet-wax-ring-leak',
    packId: 'plumbing',
    category: 'fixtures',
    title: 'Wax ring leak / toilet rocking',
    aliases: ['toilet base leak', 'wax seal failure', 'rocking toilet', 'closet flange issue'],
    symptoms: [
      'Water appears at toilet base after flush.',
      'Toilet shifts side-to-side when seated.',
      'Musty subfloor smell around toilet footprint.',
      'Ceiling stain below bathroom in multi-story homes.',
    ],
    likelyCauses: [
      'Compressed or misaligned wax ring.',
      'Broken or low closet flange height.',
      'Loose or corroded closet bolts.',
      'Uneven floor without proper shimming.',
      'Hidden crack in toilet bowl or horn.',
    ],
    steps: [
      '1) Shut water, drain tank and bowl, then remove toilet completely.',
      '2) Inspect flange condition and height relative to finished floor.',
      '3) Replace broken flange components and install correct seal type for height.',
      '4) Reset toilet with solid shims and tighten bolts evenly without overtorque.',
      '5) Caulk base perimeter (leave rear gap) and test several full flushes.',
    ],
    safety: [
      'Use proper lifting technique - toilets are heavy and awkward.',
      'Inspect subfloor for rot before reinstalling.',
    ],
    tools: ['Closet bolt wrench', 'Scraper', 'Level', 'Shims', 'Caulk gun'],
    parts: ['Wax ring or waxless seal', 'Closet bolt kit', 'Flange repair ring', 'Toilet shims'],
    severity: 'high',
    proTips: ['If toilet rocks even slightly, correct the floor support and shimming before trusting any new seal.'],
  },
  {
    id: 'plumb-under-sink-supply-leak',
    packId: 'plumbing',
    category: 'supply',
    title: 'Under-sink supply leak',
    aliases: ['angle stop leak', 'faucet supply line leak', 'cabinet water leak', 'compression leak'],
    symptoms: [
      'Cabinet floor wet near supply valves.',
      'Water drip at braided connector or valve stem.',
      'Staining on cabinet wall under faucet tailpiece.',
      'Leak worsens when faucet is opened or closed.',
    ],
    likelyCauses: [
      'Worn braided supply hose gasket.',
      'Loose compression nut or ferrule seep.',
      'Valve stem packing leak on older stops.',
      'Corroded copper stub-out or pinhole.',
      'Cross-threaded connector at faucet shank.',
    ],
    steps: [
      '1) Isolate leak point with dry towel and staged pressure test.',
      '2) Shut local angle stop; if stop fails, shut branch/main water.',
      '3) Replace suspect braided line and hand-start threads to avoid cross-threading.',
      '4) Rebuild or replace leaking stop valve if stem or body seeps.',
      '5) Pressurize and observe for several minutes at all joints.',
    ],
    safety: ['Keep electrical devices out of wet cabinet areas.', 'Do not overtighten plastic faucet shanks.'],
    tools: ['Basin wrench', 'Mini tubing cutter', 'Adjustable wrenches', 'Towels', 'Flashlight'],
    parts: ['Braided supply line', 'Quarter-turn angle stop', 'Compression sleeve/nut', 'Escutcheon'],
    severity: 'medium',
    proTips: ['If one old braided line failed, replace both hot and cold while the cabinet is already open.'],
  },
  {
    id: 'plumb-whole-house-low-pressure',
    packId: 'plumbing',
    category: 'supply',
    title: 'Whole-house low water pressure',
    aliases: ['low pressure everywhere', 'weak fixtures whole home', 'poor flow all taps'],
    symptoms: [
      'Multiple fixtures show weak flow at the same time.',
      'Shower pressure drops drastically when another fixture runs.',
      'Irrigation and hose bib flow are also reduced.',
      'No recent fixture-specific repairs explain issue.',
    ],
    likelyCauses: [
      'Partially closed main shutoff or meter valve.',
      'Failed pressure reducing valve (PRV) stuck low.',
      'Supply-side leak reducing available pressure.',
      'Mineral scaling in older galvanized piping.',
      'Municipal supply pressure drop or maintenance event.',
    ],
    steps: [
      '1) Verify complaint at several fixtures including exterior hose bib.',
      '2) Measure static and residual pressure with gauge at hose bib.',
      '3) Confirm main and meter valves are fully open.',
      '4) Test and adjust PRV; replace if no response or unstable reading.',
      '5) If pressure remains low, coordinate utility-side pressure verification and check for hidden leaks.',
    ],
    safety: ['Depressurize line before replacing PRV.', 'Use caution around older brittle piping when adjusting valves.'],
    tools: ['Pressure gauge with hose thread', 'PRV adjustment wrench', 'Leak detection meter', 'Stethoscope'],
    parts: ['Pressure reducing valve', 'Main shutoff valve', 'Union gaskets'],
    severity: 'high',
    proTips: ['Always compare static vs flowing pressure - static alone can hide severe supply restrictions.'],
  },
  {
    id: 'plumb-prv-high-pressure',
    packId: 'plumbing',
    category: 'supply',
    title: 'PRV failed / high pressure',
    aliases: ['high house pressure', 'blowing supply lines', 'pressure spikes', 'failed regulator'],
    symptoms: [
      'Fixture hoses or icemaker lines fail repeatedly.',
      'Banging pipes and noisy fill valves.',
      'T&P valve drips intermittently after heat cycles.',
      'Pressure gauge reads above recommended residential range.',
    ],
    likelyCauses: [
      'PRV internal spring/seat failure allowing high street pressure through.',
      'Thermal expansion in closed system without working expansion tank.',
      'Incorrect PRV sizing or installation orientation.',
      'Debris fouling PRV seat causing creep.',
      'Municipal pressure surges.',
    ],
    steps: [
      '1) Measure and document static pressure at hose bib after no-flow period.',
      '2) Confirm pressure creep by monitoring gauge for 10-15 minutes.',
      '3) Adjust PRV setpoint and verify whether pressure responds.',
      '4) Replace PRV if pressure remains high or fluctuates uncontrollably.',
      '5) Add or service thermal expansion tank when system is closed.',
    ],
    safety: ['High pressure can trigger sudden line failures - isolate vulnerable appliances first.', 'Depressurize before regulator replacement.'],
    tools: ['Pressure gauge', 'Pipe wrenches', 'Expansion tank pressure gauge', 'Thread sealant'],
    parts: ['PRV', 'Thermal expansion tank', 'Isolation ball valves', 'Dielectric unions'],
    severity: 'critical',
    proTips: ['If pressure rises only after heater recovery, suspect expansion control before blaming street pressure alone.'],
  },
  {
    id: 'plumb-water-hammer',
    packId: 'plumbing',
    category: 'supply',
    title: 'Water hammer / failed arrestor',
    aliases: ['pipe banging', 'hammer noise', 'quick-closing valve noise', 'arrestor failure'],
    symptoms: [
      'Loud bang in walls when washer, dishwasher, or solenoid valve closes.',
      'Pipe movement or vibration after faucet shutoff.',
      'Intermittent banging at night from automatic fixtures.',
      'New noise after recent valve or appliance replacement.',
    ],
    likelyCauses: [
      'Failed or waterlogged hammer arrestor.',
      'Loose pipe supports allowing movement.',
      'Excessive house pressure amplifying shock wave.',
      'Fast-closing fixture cartridges or solenoids.',
      'Long unbraced horizontal runs.',
    ],
    steps: [
      '1) Identify exact fixture trigger and reproduce noise on command.',
      '2) Check system pressure and correct if above target range.',
      '3) Inspect and secure accessible piping with proper clamps/isolators.',
      '4) Install or replace hammer arrestors at offending quick-closing fixture branches.',
      '5) Retest multiple on/off cycles to confirm noise elimination.',
    ],
    safety: ['Secure ladder and wall access points before opening finishes.', 'Shut water before adding arrestors.'],
    tools: ['Pressure gauge', 'Pipe straps', 'Arrestor sizing chart', 'Tubing tools'],
    parts: ['Water hammer arrestor', 'Pipe clamps with isolators', 'PRV if overpressure'],
    severity: 'medium',
    proTips: ['Hammer gets much worse above 80 psi, so pressure correction should come before chasing every clamp.'],
  },
  {
    id: 'plumb-frozen-pipe-thaw',
    packId: 'plumbing',
    category: 'supply',
    title: 'Frozen pipe thaw protocol',
    aliases: ['frozen water line', 'no water in winter', 'pipe freeze', 'thaw procedure'],
    symptoms: [
      'No flow or weak trickle at one or more fixtures during freezing weather.',
      'Visible frost on exposed piping.',
      'Localized cold spot in wall or crawlspace line.',
      'Possible split at fittings after thaw starts.',
    ],
    likelyCauses: [
      'Uninsulated piping in exterior walls or crawlspaces.',
      'Open vents or air leaks exposing lines to freezing air.',
      'Heat loss from power outage or failed space heating.',
      'Low or no trickle flow during severe freeze.',
      'Improperly winterized seasonal lines.',
    ],
    steps: [
      '1) Shut off water to affected branch if possible and open fixture to relieve pressure.',
      '2) Locate likely frozen section by temperature and exposure points.',
      '3) Apply gentle heat (heat tape, warm air) moving from faucet side toward supply side.',
      '4) Keep faucet open and monitor for restored flow and any leaks as ice melts.',
      '5) Once thawed, inspect entire run for cracks and add insulation plus air-sealing measures.',
    ],
    safety: [
      'Never use open flame torches on frozen pipes.',
      'Treat thawed lines as leak-prone until fully inspected.',
      'Use GFCI-protected power for heat tape and thaw equipment.',
    ],
    tools: ['IR thermometer', 'Heat gun on low', 'Heat tape', 'Insulation', 'Moisture meter'],
    parts: ['Pipe insulation', 'Heat cable', 'Pipe repair couplings', 'Shutoff valve'],
    severity: 'high',
    proTips: ['Open fixture first - moving water and pressure relief reduce the chance of burst during thaw.'],
  },
  {
    id: 'plumb-burst-pipe-emergency',
    packId: 'plumbing',
    category: 'supply',
    title: 'Burst pipe emergency shutoff',
    aliases: ['active water leak', 'pipe burst', 'flooding emergency', 'main shutoff procedure'],
    symptoms: [
      'Rapid uncontrolled water discharge from wall, ceiling, or crawlspace.',
      'Pressure collapse at fixtures after rupture.',
      'Water damage spreading across floors and electrical areas.',
      'Meter spins continuously when all fixtures are off.',
    ],
    likelyCauses: [
      'Freeze-thaw rupture.',
      'Corroded or pitted copper/galvanized failure.',
      'Mechanical damage from fasteners or renovation cuts.',
      'Overpressure event from failed PRV.',
      'Aging flexible connector burst.',
    ],
    steps: [
      '1) Shut main water immediately and confirm flow has stopped.',
      '2) Shut water heater fuel/power to prevent dry-fire damage.',
      '3) Drain affected lines and begin extraction/drying to limit secondary damage.',
      '4) Isolate damaged section and install temporary repair or full section replacement.',
      '5) Restore pressure slowly while monitoring all repaired joints and nearby weak points.',
      '6) Document moisture impact and recommend remediation if structural materials are saturated.',
    ],
    safety: [
      'If water reached electrical equipment, isolate power before entering flooded area.',
      'Slip hazard is severe on wet finished floors.',
      'Use respiratory protection in contaminated or mold-prone environments.',
    ],
    tools: ['Main shutoff key', 'Pipe cutters', 'Press/crimp tools', 'Extraction vacuum', 'Moisture meter'],
    parts: ['Repair couplings', 'Replacement pipe', 'Ball valves', 'Flexible supply connectors'],
    severity: 'critical',
    proTips: ['Train occupants on main shutoff location before emergencies - response time is the biggest damage factor.'],
  },
  {
    id: 'plumb-tank-wh-no-hot',
    packId: 'plumbing',
    category: 'water-heaters',
    title: 'Tank water heater no hot water / failed element',
    aliases: ['electric heater cold', 'upper element', 'lower element', 'ECO tripped'],
    symptoms: [
      'No hot water at all or only brief lukewarm output.',
      'Breaker may be on but heater remains cold.',
      'Reset button on upper thermostat may trip repeatedly.',
      'Long recovery times after small draws.',
    ],
    likelyCauses: [
      'Open upper or lower heating element.',
      'Failed thermostat pair not sequencing elements.',
      'Tripped high-limit (ECO) from overheating event.',
      'No 240V supply due to one dropped leg.',
      'Heavy sediment reducing heat transfer.',
    ],
    steps: [
      '1) Verify 240V supply at heater junction and both poles of breaker.',
      '2) Reset ECO once and observe whether it holds.',
      '3) Ohm-test upper and lower elements after isolating power and wires.',
      '4) Replace failed element(s) and thermostats as needed with correct wattage.',
      '5) Flush sediment and confirm normal amp draw and recovery time.',
    ],
    safety: [
      'Lock out breaker before removing access covers.',
      'Drain below element level before extraction to avoid scalding.',
      'Confirm tank is full before restoring power.',
    ],
    tools: ['Multimeter', 'Element wrench', 'Hose', 'Clamp meter'],
    parts: ['Heating element', 'Thermostat kit', 'Element gasket', 'Anode rod'],
    severity: 'high',
    proTips: ['Stone-cold tank usually points to upper circuit failure; short hot water usually points to lower element issues.'],
  },
  {
    id: 'plumb-tankless-flame-failure',
    packId: 'plumbing',
    category: 'water-heaters',
    title: 'Tankless error code / flame failure',
    aliases: ['tankless ignition failure', 'flame loss', 'code 11', 'code 12'],
    symptoms: [
      'Unit displays ignition or flame failure code.',
      'Burner starts then drops out quickly.',
      'Water temperature fluctuates during draw.',
      'Unit lockout until reset.',
    ],
    likelyCauses: [
      'Low gas pressure or undersized gas piping.',
      'Dirty flame rod or burner assembly.',
      'Vent blockage or intake restriction.',
      'Condensate trap or neutralizer blockage on condensing units.',
      'Scale buildup causing overheating and protective shutdown.',
    ],
    steps: [
      '1) Record exact error code and model-specific definition.',
      '2) Verify inlet gas pressure at idle and during full fire demand.',
      '3) Clean flame sensor and inspect burner/igniter condition.',
      '4) Check venting, intake screen, and condensate path for blockage.',
      '5) Descale heat exchanger and verify required service interval was followed.',
      '6) Re-test at multiple flow rates and confirm stable flame signal.',
    ],
    safety: [
      'Gas adjustments require qualified personnel and calibrated instruments.',
      'Do not bypass combustion safety circuits.',
      'Verify vent integrity to prevent carbon monoxide hazards.',
    ],
    tools: ['Manometer', 'Combustion analyzer', 'Service manual', 'Descale pump kit'],
    parts: ['Flame rod', 'Igniter', 'Gas valve', 'Condensate trap kit', 'Isolation valves'],
    severity: 'high',
    proTips: ['Always capture both error code and live gas pressure under load - most misdiagnoses happen when pressure is checked only at idle.'],
  },
  {
    id: 'plumb-tp-valve-dripping',
    packId: 'plumbing',
    category: 'water-heaters',
    title: 'T&P relief valve dripping',
    aliases: ['temperature pressure valve leak', 'heater relief dripping', 'discharge pipe dripping'],
    symptoms: [
      'Periodic hot water discharge from T&P drain line.',
      'Relief outlet drips after heating cycles.',
      'Moisture or staining around heater drain pan.',
      'Pressure spikes observed elsewhere in house.',
    ],
    likelyCauses: [
      'Thermal expansion in closed system without proper expansion tank.',
      'Overheated water due to thermostat set too high.',
      'System pressure above safe operating range.',
      'Debris preventing T&P valve from reseating.',
      'Aged T&P valve spring/seat fatigue.',
    ],
    steps: [
      '1) Measure incoming pressure and verify temperature setting at heater.',
      '2) Test expansion tank precharge and replace if waterlogged or flat.',
      '3) Flush/replace T&P valve if debris or age is suspected.',
      '4) Correct overpressure source (PRV adjustment or replacement) and retest.',
      '5) Confirm discharge pipe is full-size, unobstructed, and terminated safely.',
    ],
    safety: [
      'T&P discharge can be scalding - keep body clear of outlet.',
      'Never cap or plug a T&P discharge line.',
      'Use approved discharge piping materials only.',
    ],
    tools: ['Pressure gauge', 'Tire gauge for expansion tank', 'Pipe wrench', 'Thermometer'],
    parts: ['T&P relief valve', 'Expansion tank', 'PRV', 'Discharge pipe fittings'],
    severity: 'high',
    proTips: ['A new relief valve will still drip if thermal expansion is not corrected, so fix root pressure cause first.'],
  },
  {
    id: 'plumb-backflow-preventer-drip',
    packId: 'plumbing',
    category: 'gas-backflow',
    title: 'Backflow preventer dripping / failing test',
    aliases: ['RPZ discharge', 'backflow failure', 'check valve leak', 'test failure'],
    symptoms: [
      'Relief port on RPZ discharges water.',
      'Annual certification test fails differential requirements.',
      'Visible seepage at test cocks or body seams.',
      'Downstream pressure instability during demand changes.',
    ],
    likelyCauses: [
      'Debris on check seats preventing tight closure.',
      'Worn check rubbers or relief valve diaphragm.',
      'Freeze damage to body or internals.',
      'Incorrect installation orientation or missing strainers where required.',
      'Normal protective discharge due to upstream pressure spikes.',
    ],
    steps: [
      '1) Confirm device type, orientation, and current isolation valve positions.',
      '2) Perform calibrated backflow test and record zone/check differentials.',
      '3) Clean or rebuild internal check modules and relief assembly as needed.',
      '4) Re-test after rebuild and document passing values for compliance records.',
      '5) If body is cracked or heavily corroded, replace full assembly and retest.',
    ],
    safety: [
      'Backflow assemblies protect potable water quality - treat failures as priority.',
      'Use only certified testers for official compliance documentation.',
      'Depressurize safely before opening check covers.',
    ],
    tools: ['Certified backflow test kit', 'Torque wrench', 'Service kit tools', 'Inspection mirror'],
    parts: ['Backflow rebuild kit', 'Check modules', 'Relief valve assembly', 'Isolation valve kit'],
    severity: 'critical',
    proTips: ['Photograph gauge readings and serial plate during testing to prevent paperwork disputes later.'],
  },
  {
    id: 'plumb-slab-leak-signs',
    packId: 'plumbing',
    category: 'supply',
    title: 'Slab leak indicators and confirmation',
    aliases: ['hot slab leak', 'underground supply leak', 'foundation leak', 'hidden water loss'],
    symptoms: [
      'Unexplained high water bills.',
      'Warm floor spot or damp flooring without surface spill.',
      'Continuous meter movement when fixtures are off.',
      'Low pressure or intermittent air at fixtures.',
    ],
    likelyCauses: [
      'Copper pinhole from corrosion/abrasion under slab.',
      'Failed joint in buried supply line.',
      'Ground movement stressing embedded piping.',
      'Recirculation line leak under concrete.',
      'Poor dielectric isolation causing galvanic deterioration.',
    ],
    steps: [
      '1) Perform meter test with all fixtures isolated to confirm continuous flow.',
      '2) Isolate hot vs cold branches to narrow leak location.',
      '3) Use acoustic listening and thermal imaging to map probable leak zone.',
      '4) Pressure-test suspect line segment to verify loss rate.',
      '5) Recommend least-invasive repair path (reroute overhead, epoxy, or spot break) based on structure and pipe condition.',
    ],
    safety: [
      'Hidden moisture can compromise flooring and electrical systems.',
      'Mark utility routes before any slab cutting.',
      'Use dust and silica controls if concrete access is required.',
    ],
    tools: ['Leak correlator', 'Thermal camera', 'Pressure test pump', 'Moisture meter'],
    parts: ['Reroute piping', 'Repair couplings', 'Isolation valves', 'Sleeving materials'],
    severity: 'critical',
    proTips: ['Long-term reliability is usually better with reroute than repeated spot repairs on aging slab copper.'],
  },
  {
    id: 'plumb-faucet-drip-cartridge',
    packId: 'plumbing',
    category: 'fixtures',
    title: 'Faucet drip / worn cartridge',
    aliases: ['leaking faucet', 'dripping spout', 'cartridge failure', 'stem leak'],
    symptoms: [
      'Steady drip from spout when handle is off.',
      'Handle stiff or rough operation.',
      'Leak at handle bonnet during use.',
      'Mineral buildup around aerator and spout base.',
    ],
    likelyCauses: [
      'Worn ceramic cartridge or stem seals.',
      'Damaged seat/spring in compression style faucet.',
      'Debris scored cartridge sealing surfaces.',
      'Excessive pressure accelerating seal wear.',
      'Improperly tightened retaining nut after prior repair.',
    ],
    steps: [
      '1) Shut stops and verify faucet is depressurized.',
      '2) Disassemble handle carefully and identify exact cartridge part number.',
      '3) Inspect and clean valve body bore and seats before installing new cartridge.',
      '4) Reassemble with proper lubricant and torque, then flush debris at full flow.',
      '5) Check for both hot and cold seal-off with no drip after several cycles.',
    ],
    safety: ['Protect sink finish while using tools.', 'Do not force stuck cartridges without puller support to avoid body damage.'],
    tools: ['Cartridge puller', 'Allen keys', 'Silicone plumber grease', 'Needle-nose pliers'],
    parts: ['Cartridge', 'Seat and spring kit', 'O-rings', 'Aerator'],
    severity: 'low',
    proTips: ['Take a photo of cartridge orientation before removal - many callbacks are caused by reversed reassembly.'],
  },
  {
    id: 'plumb-shower-valve-temp-fault',
    packId: 'plumbing',
    category: 'fixtures',
    title: 'Shower valve no hot water or scald swings',
    aliases: ['no hot at shower', 'scalding shower', 'pressure balance valve', 'mixing valve issue'],
    symptoms: [
      'Shower stays lukewarm while sinks have hot water.',
      'Temperature swings when nearby fixture runs.',
      'Handle rotation does not change temperature smoothly.',
      'Anti-scald limit stop may be mis-set.',
    ],
    likelyCauses: [
      'Failed pressure-balance spool or thermostatic cartridge.',
      'Debris in hot inlet port of shower valve.',
      'Cross-connection from single-handle fixture elsewhere.',
      'Water heater setpoint too low or recovery issue.',
      'Incorrect limit-stop setting after previous service.',
    ],
    steps: [
      '1) Verify true hot supply at nearby lavatory to isolate shower valve fault.',
      '2) Remove trim and check anti-scald limit stop adjustment.',
      '3) Pull and inspect cartridge; clean debris and replace if movement is sticky.',
      '4) Flush valve body with cartridge removed to clear inlet sediment.',
      '5) Recalibrate maximum temperature to safe target and retest under varying flow conditions.',
    ],
    safety: [
      'Prevent scald exposure during testing - verify outlet temp with thermometer.',
      'Shut off water before cartridge extraction.',
    ],
    tools: ['Thermometer', 'Cartridge puller', 'Hex key set', 'Trim tools'],
    parts: ['Shower cartridge', 'Limit stop kit', 'Balancing spool', 'Valve body seals'],
    severity: 'high',
    proTips: ['If only one shower is affected but sinks are hot, replace cartridge before chasing water-heater controls.'],
  },
  {
    id: 'plumb-sump-pump-not-running',
    packId: 'plumbing',
    category: 'drains',
    title: 'Sump pump not running',
    aliases: ['basement sump failure', 'pit overflowing', 'float switch stuck', 'pump hum no discharge'],
    symptoms: [
      'Pit water level rises without pump activation.',
      'Pump hums but little or no discharge flow.',
      'Frequent breaker trips on sump circuit.',
      'Basement seepage during rain events.',
    ],
    likelyCauses: [
      'Failed float switch or jammed tether.',
      'Clogged impeller or blocked discharge/check valve.',
      'Power loss, tripped GFCI, or failed receptacle.',
      'Frozen or blocked exterior discharge line.',
      'Pump motor end-of-life from continuous duty.',
    ],
    steps: [
      '1) Verify power at receptacle and check GFCI/breaker status.',
      '2) Lift float manually to test switch and motor response.',
      '3) Inspect pit for debris binding float or impeller inlet.',
      '4) Check discharge pipe and check valve orientation for blockage or backflow.',
      '5) Replace switch or pump assembly if amperage/performance is out of spec.',
      '6) Test full fill-and-pump cycle and confirm backup system operation if installed.',
    ],
    safety: [
      'Use GFCI protection and dry footing around sump pits.',
      'Disconnect power before reaching into pit.',
      'Treat floodwater as potentially contaminated.',
    ],
    tools: ['Multimeter', 'Pump test cord', 'Pipe wrench', 'Shop vac', 'Bucket for cycle test'],
    parts: ['Sump pump', 'Float switch', 'Check valve', 'Discharge piping', 'Battery backup pump'],
    severity: 'critical',
    proTips: ['Always test the system with actual water volume after repair - bench-running a pump does not prove field reliability.'],
  },
];
