export type CommunalTopic = {
  id: string;
  label: string;
  docs: number;
  blurb: string;
  /** Position on unit sphere-ish layout (will be scaled) */
  position: [number, number, number];
  links: string[];
  hue: number;
};

/** Seed topics for the Communal Library knowledge map (illustrative corpus counts). */
export const COMMUNAL_TOPICS: CommunalTopic[] = [
  {
    id: 'hieroglyphics',
    label: 'Hieroglyphics',
    docs: 1842,
    blurb: 'Glyph plates, temple inscriptions, and bilingual gloss packs from community OCR.',
    position: [2.2, 1.1, 0.4],
    links: ['cuneiform', 'ancient-maps', 'translation'],
    hue: 42,
  },
  {
    id: 'cuneiform',
    label: 'Cuneiform',
    docs: 1267,
    blurb: 'Tablet transliterations and wedge-script comparative notes shared by researchers.',
    position: [1.6, -0.8, 1.8],
    links: ['hieroglyphics', 'tartarian', 'academia'],
    hue: 28,
  },
  {
    id: 'mud-flood',
    label: 'Mud Flood',
    docs: 934,
    blurb: 'Street-level photo archives, window-line studies, and excavation timelines.',
    position: [-0.4, 2.0, 1.2],
    links: ['tartarian', 'world-fairs', 'orphan-trains'],
    hue: 18,
  },
  {
    id: 'tartarian',
    label: 'Tartarian',
    docs: 2104,
    blurb: 'Architecture plates, empire maps, and community-sourced anomaly dossiers.',
    position: [0.2, 0.6, 2.4],
    links: ['mud-flood', 'world-fairs', 'ancient-maps', 'star-forts'],
    hue: 38,
  },
  {
    id: 'orphan-trains',
    label: 'Orphan Trains',
    docs: 611,
    blurb: 'Passenger lists, placement records, and oral-history transcripts.',
    position: [-2.0, 0.9, 0.8],
    links: ['mud-flood', 'legal-research', 'academia'],
    hue: 200,
  },
  {
    id: 'legal-research',
    label: 'Legal Research',
    docs: 1588,
    blurb: 'Public-domain finding packs, exhibit OCR, and citation-ready outlines.',
    position: [-2.4, -0.6, -0.5],
    links: ['orphan-trains', 'academia', 'quantum'],
    hue: 210,
  },
  {
    id: 'homeopathic',
    label: 'Homeopathic Cures',
    docs: 742,
    blurb: 'Materia medica scans, remedy monographs, and de-identified literature packs.',
    position: [-1.2, -1.8, 1.0],
    links: ['mycology', 'botanicals', 'medical-holistic'],
    hue: 140,
  },
  {
    id: 'mycology',
    label: 'Mycology',
    docs: 891,
    blurb: 'Spore prints, field guides, and fungal pharmacology notes from the hive.',
    position: [-0.2, -2.2, -0.6],
    links: ['homeopathic', 'botanicals', 'quantum'],
    hue: 120,
  },
  {
    id: 'quantum',
    label: 'Quantum Physics',
    docs: 1320,
    blurb: 'Paper OCR, figure extractions, and cross-linked theory maps.',
    position: [1.4, -1.4, -1.6],
    links: ['academia', 'legal-research', 'mycology'],
    hue: 265,
  },
  {
    id: 'world-fairs',
    label: 'World Fairs',
    docs: 1055,
    blurb: 'Exposition plates, pavilion plans, and captioned photograph corpora.',
    position: [2.0, 1.8, -0.8],
    links: ['tartarian', 'mud-flood', 'star-forts'],
    hue: 48,
  },
  {
    id: 'star-forts',
    label: 'Star Forts',
    docs: 478,
    blurb: 'Bastion geometry surveys and comparative fortification atlases.',
    position: [0.8, 2.2, -1.6],
    links: ['tartarian', 'world-fairs', 'ancient-maps'],
    hue: 55,
  },
  {
    id: 'ancient-maps',
    label: 'Ancient Maps',
    docs: 967,
    blurb: 'Sanborn sheets, portolan charts, and georeferenced legend packs.',
    position: [2.6, -0.2, -1.0],
    links: ['hieroglyphics', 'tartarian', 'star-forts'],
    hue: 32,
  },
  {
    id: 'botanicals',
    label: 'Botanicals',
    docs: 823,
    blurb: 'Herbarium plates, ethnobotany translations, and constituent tables.',
    position: [-2.2, -1.4, 1.6],
    links: ['homeopathic', 'mycology', 'medical-holistic'],
    hue: 100,
  },
  {
    id: 'medical-holistic',
    label: 'Holistic Medicine',
    docs: 1102,
    blurb: 'Integrative protocol reviews and bilingual clinical literature maps.',
    position: [-1.6, 0.2, 2.2],
    links: ['homeopathic', 'botanicals', 'academia'],
    hue: 160,
  },
  {
    id: 'academia',
    label: 'Academia',
    docs: 1744,
    blurb: 'Shared corpora, lit-review memos, and open scholarly datasets.',
    position: [0.0, -0.4, -2.4],
    links: ['quantum', 'legal-research', 'cuneiform', 'translation'],
    hue: 220,
  },
  {
    id: 'translation',
    label: 'Ancient Translation',
    docs: 1490,
    blurb: 'Modern ↔ historical script pipelines with community-corrected glossaries.',
    position: [1.0, 0.2, 0.0],
    links: ['hieroglyphics', 'cuneiform', 'academia', 'nag-hammadi'],
    hue: 35,
  },
  {
    id: 'cathedral',
    label: 'Cathedral Plans',
    docs: 392,
    blurb: 'Floor plates, Latin notes, and architectural measurement extracts.',
    position: [-0.8, 1.6, -1.8],
    links: ['star-forts', 'tartarian', 'ancient-maps'],
    hue: 25,
  },
  {
    id: 'free-energy',
    label: 'Free Energy Archives',
    docs: 556,
    blurb: 'Patent plates, suppressed-tech dossiers, and schematic OCR packs.',
    position: [1.8, -2.0, 0.6],
    links: ['quantum', 'tartarian', 'world-fairs'],
    hue: 195,
  },
  {
    id: 'giants',
    label: 'Giant Skeletons',
    docs: 318,
    blurb: 'Newspaper clippings, mound surveys, and contested osteology notes.',
    position: [-1.8, 1.8, -0.4],
    links: ['mud-flood', 'orphan-trains', 'tartarian'],
    hue: 15,
  },
  {
    id: 'sound-healing',
    label: 'Sound & Frequency',
    docs: 447,
    blurb: 'Resonance studies, temple acoustics, and frequency therapy literature.',
    position: [0.6, -1.0, 2.0],
    links: ['homeopathic', 'quantum', 'cathedral'],
    hue: 280,
  },
  {
    id: 'alchemy',
    label: 'Alchemy Texts',
    docs: 529,
    blurb: 'Emblem books, laboratory notes, and symbolic lexicon translations.',
    position: [-2.6, 0.4, -1.4],
    links: ['botanicals', 'translation', 'academia', 'nag-hammadi'],
    hue: 50,
  },
  {
    id: 'ley-lines',
    label: 'Ley Lines',
    docs: 401,
    blurb: 'Geomantic overlays, surveyor notebooks, and site-alignment corpora.',
    position: [2.4, 0.8, 1.6],
    links: ['star-forts', 'ancient-maps', 'cathedral'],
    hue: 70,
  },
  {
    id: 'nag-hammadi',
    label: 'Nag Hammadi & Gnostic',
    docs: 52,
    blurb:
      'Complete Nag Hammadi tractate catalog — Coptic plates, English editions, and word-indexed Gnostic scriptures.',
    position: [-0.6, -0.2, 1.4],
    links: ['translation', 'alchemy', 'academia', 'hieroglyphics'],
    hue: 45,
  },
];

export function getCommunalTopic(id: string) {
  return COMMUNAL_TOPICS.find((t) => t.id === id);
}
