/**
 * Seed archive findings for Communal Library topic pages.
 * Images are public-domain / Wikimedia Commons (or LOC) thumbnails for layout demos.
 * Live published entries merge on top when available.
 */

export type SeedFinding = {
  id: string;
  topicId: string;
  title: string;
  creator: string;
  date: string;
  catalogId: string;
  imageUrl: string;
  sourceUrl: string;
  excerpt: string;
  relatedCount?: number;
};

const W = 'https://upload.wikimedia.org/wikipedia/commons';

/** Two curated findings per lattice topic (22 topics). */
export const ARCHIVE_SEED_FINDINGS: SeedFinding[] = [
  // —— Hieroglyphics ——
  {
    id: 'hieroglyphics-1',
    topicId: 'hieroglyphics',
    title: 'Rosetta Stone (trilingual decree)',
    creator: 'British Museum / Wikimedia',
    date: '196 BCE',
    catalogId: 'EA24',
    imageUrl: `${W}/thumb/2/23/Rosetta_Stone.JPG/640px-Rosetta_Stone.JPG`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG',
    excerpt:
      'Egyptian decree in hieroglyphic, Demotic, and Greek — the key bilingual plate for modern decipherment work.',
    relatedCount: 12,
  },
  {
    id: 'hieroglyphics-2',
    topicId: 'hieroglyphics',
    title: 'Papyrus of Ani — weighing of the heart',
    creator: 'British Museum',
    date: 'c. 1250 BCE',
    catalogId: 'EA10470',
    imageUrl: `${W}/thumb/6/6f/Book_of_the_Dead_of_Hunefer_sheet_5.jpg/640px-Book_of_the_Dead_of_Hunefer_sheet_5.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Book_of_the_Dead_of_Hunefer_sheet_5.jpg',
    excerpt: 'Funerary vignette with captioned hieroglyphic columns — strong OCR target for gloss packs.',
    relatedCount: 8,
  },
  // —— Cuneiform ——
  {
    id: 'cuneiform-1',
    topicId: 'cuneiform',
    title: 'Code of Hammurabi stele (detail)',
    creator: 'Louvre',
    date: 'c. 1755 BCE',
    catalogId: 'Sb 8',
    imageUrl: `${W}/thumb/4/4b/Code_of_Hammurabi%2C_King_of_Babylon%2C_front_view.jpg/480px-Code_of_Hammurabi%2C_King_of_Babylon%2C_front_view.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Code_of_Hammurabi,_King_of_Babylon,_front_view.jpg',
    excerpt: 'Basalt law code with continuous Akkadian wedges — classic comparative transliteration plate.',
    relatedCount: 15,
  },
  {
    id: 'cuneiform-2',
    topicId: 'cuneiform',
    title: 'Cuneiform tablet (administrative)',
    creator: 'Metropolitan Museum',
    date: 'c. 2040 BCE',
    catalogId: '86.11.268',
    imageUrl: `${W}/thumb/9/9c/Cuneiform_tablet_-_administrative_account_of_barley_distribution_with_cylinder_seal_impression_of_a_man_and_two_goats_-_MET_DT848.jpg/640px-Cuneiform_tablet_-_administrative_account_of_barley_distribution_with_cylinder_seal_impression_of_a_man_and_two_goats_-_MET_DT848.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Cuneiform_tablet_-_administrative_account_of_barley_distribution_with_cylinder_seal_impression_of_a_man_and_two_goats_-_MET_DT848.jpg',
    excerpt: 'Barley distribution account with seal impression — typical hive OCR → translate pipeline input.',
    relatedCount: 6,
  },
  // —— Mud Flood ——
  {
    id: 'mud-flood-1',
    topicId: 'mud-flood',
    title: 'Seattle regrade — Denny Hill excavation',
    creator: 'University of Washington Libraries',
    date: '1909',
    catalogId: 'SEA-regrade',
    imageUrl: `${W}/thumb/8/8a/Denny_Hill_regrade%2C_Seattle%2C_1909_%28CURTIS_160%29.jpg/640px-Denny_Hill_regrade%2C_Seattle%2C_1909_%28CURTIS_160%29.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Denny_Hill_regrade,_Seattle,_1909_(CURTIS_160).jpg',
    excerpt: 'Street-grade change with buildings mid-cut — window-line / buried-story study plate.',
    relatedCount: 9,
  },
  {
    id: 'mud-flood-2',
    topicId: 'mud-flood',
    title: 'Chicago after the fire — street ruins',
    creator: 'George N. Barnard',
    date: '1871',
    catalogId: 'CHI-1871',
    imageUrl: `${W}/thumb/e/e3/Chicago_Fire_-_Corner_of_Dearborn_and_Monroe_Streets%2C_1871.jpg/640px-Chicago_Fire_-_Corner_of_Dearborn_and_Monroe_Streets%2C_1871.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Chicago_Fire_-_Corner_of_Dearborn_and_Monroe_Streets,_1871.jpg',
    excerpt: 'Post-disaster street elevation and rubble lines used in mud-flood comparative dossiers.',
    relatedCount: 11,
  },
  // —— Tartarian ——
  {
    id: 'tartarian-1',
    topicId: 'tartarian',
    title: 'A Newe Mape of Tartary (John Speed)',
    creator: 'John Speed',
    date: '1626',
    catalogId: 'Speed-Tartary',
    imageUrl: `${W}/thumb/3/3a/1626_Speed_Map_of_Tartary_%28Central_Asia%2C_Siberia%2C_China%29_-_Geographicus_-_Tartary-speed-1626.jpg/640px-1626_Speed_Map_of_Tartary_%28Central_Asia%2C_Siberia%2C_China%29_-_Geographicus_-_Tartary-speed-1626.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:1626_Speed_Map_of_Tartary_(Central_Asia,_Siberia,_China)_-_Geographicus_-_Tartary-speed-1626.jpg',
    excerpt: 'Early modern “Tartary” atlas plate — primary map lead for empire / place-name trails.',
    relatedCount: 18,
  },
  {
    id: 'tartarian-2',
    topicId: 'tartarian',
    title: 'World’s Columbian Exposition — Court of Honor',
    creator: 'C. D. Arnold',
    date: '1893',
    catalogId: 'WCE-1893',
    imageUrl: `${W}/thumb/1/14/Court_of_Honor_and_Grand_Basin%2C_World%27s_Columbian_Exposition%2C_Chicago%2C_1893.jpg/640px-Court_of_Honor_and_Grand_Basin%2C_World%27s_Columbian_Exposition%2C_Chicago%2C_1893.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Court_of_Honor_and_Grand_Basin,_World%27s_Columbian_Exposition,_Chicago,_1893.jpg',
    excerpt: 'White City architecture plate often cross-linked with Tartarian / fair rebuild narratives.',
    relatedCount: 22,
  },
  // —— Orphan Trains ——
  {
    id: 'orphan-trains-1',
    topicId: 'orphan-trains',
    title: 'Orphan train children, Kansas City',
    creator: 'Public domain press photo',
    date: '1900s',
    catalogId: 'OT-KC',
    imageUrl: `${W}/thumb/4/4e/Orphan_Train.jpg/640px-Orphan_Train.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Orphan_Train.jpg',
    excerpt: 'Group portrait of placed children — pair with Chron Am “orphan train” state digs.',
    relatedCount: 7,
  },
  {
    id: 'orphan-trains-2',
    topicId: 'orphan-trains',
    title: 'Children’s Aid Society — New York',
    creator: 'Unknown photographer',
    date: 'c. 1890',
    catalogId: 'CAS-NY',
    imageUrl: `${W}/thumb/d/d9/Children%27s_Aid_Society%2C_New_York_City.jpg/640px-Children%27s_Aid_Society%2C_New_York_City.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Children%27s_Aid_Society,_New_York_City.jpg',
    excerpt: 'Institutional campus photo for orphan-asylum / placement-record cross-checks.',
    relatedCount: 5,
  },
  // —— Legal Research ——
  {
    id: 'legal-research-1',
    topicId: 'legal-research',
    title: 'Magna Carta (1297 inspeximus)',
    creator: 'National Archives UK',
    date: '1297',
    catalogId: 'C_52_1',
    imageUrl: `${W}/thumb/b/b6/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/640px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Magna_Carta_(British_Library_Cotton_MS_Augustus_II.106).jpg',
    excerpt: 'Foundational legal manuscript plate — exhibit OCR / citation brief sample.',
    relatedCount: 10,
  },
  {
    id: 'legal-research-2',
    topicId: 'legal-research',
    title: 'U.S. Supreme Court building (historical)',
    creator: 'Library of Congress',
    date: '1935',
    catalogId: 'LOC-SC',
    imageUrl: `${W}/thumb/f/f3/Supreme_Court_Building.jpg/640px-Supreme_Court_Building.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Supreme_Court_Building.jpg',
    excerpt: 'Institutional architecture plate used in public-domain finding-pack demos.',
    relatedCount: 4,
  },
  // —— Homeopathic ——
  {
    id: 'homeopathic-1',
    topicId: 'homeopathic',
    title: 'Samuel Hahnemann portrait plate',
    creator: 'Public domain engraving',
    date: '1841',
    catalogId: 'Hahnemann',
    imageUrl: `${W}/thumb/8/8e/Samuel_Hahnemann.jpg/480px-Samuel_Hahnemann.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Samuel_Hahnemann.jpg',
    excerpt: 'Founder plate commonly paired with materia medica monograph OCR.',
    relatedCount: 6,
  },
  {
    id: 'homeopathic-2',
    topicId: 'homeopathic',
    title: 'Homeopathic pharmacopoeia title page',
    creator: 'Archive.org / public domain',
    date: '1878',
    catalogId: 'HP-1878',
    imageUrl: `${W}/thumb/a/a8/The_American_homeopathic_pharmacopoeia_%28IA_americanhomeopat00boer%29.pdf/page1-640px-The_American_homeopathic_pharmacopoeia_%28IA_americanhomeopat00boer%29.pdf.jpg`,
    sourceUrl: 'https://archive.org/details/americanhomeopat00boer',
    excerpt: 'Remedy monograph scan — dosage tables are high-value OCR targets.',
    relatedCount: 9,
  },
  // —— Mycology ——
  {
    id: 'mycology-1',
    topicId: 'mycology',
    title: 'Amanita muscaria botanical plate',
    creator: 'Public domain illustration',
    date: '1892',
    catalogId: 'Amanita',
    imageUrl: `${W}/thumb/3/32/Amanita_muscaria_%28fly_agaric%29.JPG/480px-Amanita_muscaria_%28fly_agaric%29.JPG`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Amanita_muscaria_(fly_agaric).JPG',
    excerpt: 'Field-guide style plate for spore/pharmacology note packs.',
    relatedCount: 8,
  },
  {
    id: 'mycology-2',
    topicId: 'mycology',
    title: 'Morchella — morel illustration',
    creator: 'Public domain',
    date: '1890s',
    catalogId: 'Morchella',
    imageUrl: `${W}/thumb/4/4a/Morchella_esculenta_Sturm50.jpg/480px-Morchella_esculenta_Sturm50.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morchella_esculenta_Sturm50.jpg',
    excerpt: 'Classic mycological engraving — caption OCR + ethnobotany cross-links.',
    relatedCount: 5,
  },
  // —— Quantum ——
  {
    id: 'quantum-1',
    topicId: 'quantum',
    title: 'Niels Bohr atomic model diagram (historical)',
    creator: 'Public domain textbook',
    date: '1913',
    catalogId: 'Bohr-1913',
    imageUrl: `${W}/thumb/5/5e/Bohr_atom_model.svg/480px-Bohr_atom_model.svg.png`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bohr_atom_model.svg',
    excerpt: 'Early quantum model figure for paper-OCR / theory-map demos.',
    relatedCount: 7,
  },
  {
    id: 'quantum-2',
    topicId: 'quantum',
    title: 'Einstein–Szilard letter (first page facsimile context)',
    creator: 'U.S. National Archives',
    date: '1939',
    catalogId: 'Einstein-1939',
    imageUrl: `${W}/thumb/b/b4/Einstein-Szilard-letter.png/640px-Einstein-Szilard-letter.png`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Einstein-Szilard-letter.png',
    excerpt: 'Typed scientific-policy document — clean OCR → citation brief sample.',
    relatedCount: 4,
  },
  // —— World Fairs ——
  {
    id: 'world-fairs-1',
    topicId: 'world-fairs',
    title: 'Paris Exposition Universelle — Eiffel Tower',
    creator: 'Public domain photograph',
    date: '1889',
    catalogId: 'Paris-1889',
    imageUrl: `${W}/thumb/a/a8/Tour_Eiffel_Wunderlich.jpg/480px-Tour_Eiffel_Wunderlich.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wunderlich.jpg',
    excerpt: 'Exposition landmark plate — pavilion / fairground corpus seed.',
    relatedCount: 14,
  },
  {
    id: 'world-fairs-2',
    topicId: 'world-fairs',
    title: 'Panama–Pacific International Exposition',
    creator: 'Cardinell-Vincent Co.',
    date: '1915',
    catalogId: 'PPIE-1915',
    imageUrl: `${W}/thumb/0/0c/Palace_of_Fine_Arts%2C_Panama-Pacific_International_Exposition.jpg/640px-Palace_of_Fine_Arts%2C_Panama-Pacific_International_Exposition.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Palace_of_Fine_Arts,_Panama-Pacific_International_Exposition.jpg',
    excerpt: 'SF 1915 fair architecture — rebuild / quake-context trails.',
    relatedCount: 11,
  },
  // —— Star Forts ——
  {
    id: 'star-forts-1',
    topicId: 'star-forts',
    title: 'Bourtange star fort plan',
    creator: 'Public domain map',
    date: '18th c.',
    catalogId: 'Bourtange',
    imageUrl: `${W}/thumb/4/4e/Vesting_Bourtange.jpg/640px-Vesting_Bourtange.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vesting_Bourtange.jpg',
    excerpt: 'Classic bastion geometry — Rumsey/LOC star-fort dig companion.',
    relatedCount: 13,
  },
  {
    id: 'star-forts-2',
    topicId: 'star-forts',
    title: 'Fort McHenry aerial / plan context',
    creator: 'U.S. National Park Service',
    date: 'historical',
    catalogId: 'McHenry',
    imageUrl: `${W}/thumb/7/7a/Fort_McHenry_aerial.jpg/640px-Fort_McHenry_aerial.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fort_McHenry_aerial.jpg',
    excerpt: 'Trace italienne outline visible from above — fortification atlas seed.',
    relatedCount: 6,
  },
  // —— Ancient Maps ——
  {
    id: 'ancient-maps-1',
    topicId: 'ancient-maps',
    title: 'Tabula Rogeriana (al-Idrisi)',
    creator: 'Muhammad al-Idrisi',
    date: '1154',
    catalogId: 'Idrisi',
    imageUrl: `${W}/thumb/2/2c/TabulaRogeriana.jpg/640px-TabulaRogeriana.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:TabulaRogeriana.jpg',
    excerpt: 'Medieval world chart — legend / place-name OCR target.',
    relatedCount: 16,
  },
  {
    id: 'ancient-maps-2',
    topicId: 'ancient-maps',
    title: 'Ptolemy world map (15th-c. print)',
    creator: 'After Ptolemy',
    date: '1482',
    catalogId: 'Ptolemy',
    imageUrl: `${W}/thumb/2/23/PtolemyCosmographia.jpg/640px-PtolemyCosmographia.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:PtolemyCosmographia.jpg',
    excerpt: 'Printed cosmographia plate for comparative ancient-map corpora.',
    relatedCount: 12,
  },
  // —— Botanicals ——
  {
    id: 'botanicals-1',
    topicId: 'botanicals',
    title: 'Digitalis purpurea — herbarium plate',
    creator: 'Public domain botanical',
    date: '1885',
    catalogId: 'Digitalis',
    imageUrl: `${W}/thumb/4/49/Digitalis_purpurea_Sturm24.jpg/480px-Digitalis_purpurea_Sturm24.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Digitalis_purpurea_Sturm24.jpg',
    excerpt: 'Foxglove plate — ethnobotany / constituent-table pipeline sample.',
    relatedCount: 9,
  },
  {
    id: 'botanicals-2',
    topicId: 'botanicals',
    title: 'Mandragora officinarum illustration',
    creator: 'Public domain',
    date: '1887',
    catalogId: 'Mandrake',
    imageUrl: `${W}/thumb/3/3c/Mandragora_officinarum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-090.jpg/480px-Mandragora_officinarum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-090.jpg`,
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Mandragora_officinarum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-090.jpg',
    excerpt: 'Medicinal plant engraving with labeled parts — OCR caption gold.',
    relatedCount: 7,
  },
  // —— Medical Holistic ——
  {
    id: 'medical-holistic-1',
    topicId: 'medical-holistic',
    title: 'Acupuncture chart (historical)',
    creator: 'Public domain Chinese medical print',
    date: '17th–19th c.',
    catalogId: 'Acu-chart',
    imageUrl: `${W}/thumb/7/75/Acupuncture_chart%2C_Ming_Dynasty.jpg/480px-Acupuncture_chart%2C_Ming_Dynasty.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Acupuncture_chart,_Ming_Dynasty.jpg',
    excerpt: 'Channel diagram for bilingual clinical literature map demos.',
    relatedCount: 8,
  },
  {
    id: 'medical-holistic-2',
    topicId: 'medical-holistic',
    title: 'Gray’s Anatomy — musculature plate',
    creator: 'Henry Vandyke Carter',
    date: '1918',
    catalogId: 'Gray-122',
    imageUrl: `${W}/thumb/0/0b/Gray122.png/480px-Gray122.png`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gray122.png',
    excerpt: 'Public-domain anatomical plate often reused in integrative protocol reviews.',
    relatedCount: 5,
  },
  // —— Academia ——
  {
    id: 'academia-1',
    topicId: 'academia',
    title: 'Newton’s Principia title page',
    creator: 'Isaac Newton',
    date: '1687',
    catalogId: 'Principia',
    imageUrl: `${W}/thumb/3/3e/NewtonsPrincipia.jpg/480px-NewtonsPrincipia.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:NewtonsPrincipia.jpg',
    excerpt: 'Canonical scholarly title page — lit-review / open-dataset seed.',
    relatedCount: 10,
  },
  {
    id: 'academia-2',
    topicId: 'academia',
    title: 'Library of Alexandria artistic reconstruction',
    creator: 'O. Von Corven',
    date: '19th c.',
    catalogId: 'Alexandria',
    imageUrl: `${W}/thumb/6/63/Ancientlibraryalex.jpg/640px-Ancientlibraryalex.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ancientlibraryalex.jpg',
    excerpt: 'Iconic “library as commons” plate for academia topic branding.',
    relatedCount: 6,
  },
  // —— Translation ——
  {
    id: 'translation-1',
    topicId: 'translation',
    title: 'Behistun Inscription (trilingual)',
    creator: 'Achaemenid Persia',
    date: 'c. 520 BCE',
    catalogId: 'Behistun',
    imageUrl: `${W}/thumb/0/0f/Behistun_Inscription_Darius_the_Great.jpg/640px-Behistun_Inscription_Darius_the_Great.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Behistun_Inscription_Darius_the_Great.jpg',
    excerpt: 'Trilingual cliff inscription — ancient↔modern translation pipeline exemplar.',
    relatedCount: 11,
  },
  {
    id: 'translation-2',
    topicId: 'translation',
    title: 'Linear B tablet (Pylos)',
    creator: 'Mycenaean archive',
    date: 'c. 1200 BCE',
    catalogId: 'PY-Tn',
    imageUrl: `${W}/thumb/5/54/Linear_B_tablet.jpg/640px-Linear_B_tablet.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Linear_B_tablet.jpg',
    excerpt: 'Syllabic tablet for script pipeline + glossary correction demos.',
    relatedCount: 7,
  },
  // —— Cathedral ——
  {
    id: 'cathedral-1',
    topicId: 'cathedral',
    title: 'Notre-Dame de Paris — plan / elevation context',
    creator: 'Public domain photograph',
    date: '19th c.',
    catalogId: 'ND-Paris',
    imageUrl: `${W}/thumb/1/1d/NotreDameDeParis.jpg/480px-NotreDameDeParis.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:NotreDameDeParis.jpg',
    excerpt: 'Gothic fabric plate for floor-plan / Latin-notes extract trails.',
    relatedCount: 9,
  },
  {
    id: 'cathedral-2',
    topicId: 'cathedral',
    title: 'Chartres Cathedral labyrinth',
    creator: 'Public domain',
    date: 'medieval / photo',
    catalogId: 'Chartres-lab',
    imageUrl: `${W}/thumb/8/8d/Chartres_Labyrinth.jpg/640px-Chartres_Labyrinth.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chartres_Labyrinth.jpg',
    excerpt: 'Measured pavement geometry — architectural measurement extract sample.',
    relatedCount: 5,
  },
  // —— Free Energy ——
  {
    id: 'free-energy-1',
    topicId: 'free-energy',
    title: 'Nikola Tesla — Wardenclyffe / lab context',
    creator: 'Public domain photograph',
    date: 'c. 1890s',
    catalogId: 'Tesla-lab',
    imageUrl: `${W}/thumb/7/79/Tesla_colorado.jpg/640px-Tesla_colorado.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tesla_colorado.jpg',
    excerpt: 'High-voltage experiment plate — patent / schematic OCR companion.',
    relatedCount: 8,
  },
  {
    id: 'free-energy-2',
    topicId: 'free-energy',
    title: 'Faraday electromagnetic apparatus engraving',
    creator: 'Public domain',
    date: '19th c.',
    catalogId: 'Faraday',
    imageUrl: `${W}/thumb/4/4e/Faraday_electromagnetic_experiment.png/640px-Faraday_electromagnetic_experiment.png`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Faraday_electromagnetic_experiment.png',
    excerpt: 'Laboratory schematic engraving for free-energy archive dossiers.',
    relatedCount: 4,
  },
  // —— Giants ——
  {
    id: 'giants-1',
    topicId: 'giants',
    title: 'Cardiff Giant exhibition photograph',
    creator: 'Public domain press',
    date: '1869',
    catalogId: 'Cardiff',
    imageUrl: `${W}/thumb/7/75/Cardiff_Giant.jpg/640px-Cardiff_Giant.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cardiff_Giant.jpg',
    excerpt: 'Famous “petrified giant” exhibit — newspaper clipping corpus seed.',
    relatedCount: 6,
  },
  {
    id: 'giants-2',
    topicId: 'giants',
    title: 'Mound City / Hopewell earthworks context',
    creator: 'NPS / public domain',
    date: 'historical',
    catalogId: 'Hopewell',
    imageUrl: `${W}/thumb/4/4a/Mound_City_Group.jpg/640px-Mound_City_Group.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mound_City_Group.jpg',
    excerpt: 'Mound survey landscape for contested osteology / mound-dossier trails.',
    relatedCount: 5,
  },
  // —— Sound Healing ——
  {
    id: 'sound-healing-1',
    topicId: 'sound-healing',
    title: 'Pythagorean monochord diagram',
    creator: 'Public domain engraving',
    date: 'historical',
    catalogId: 'Monochord',
    imageUrl: `${W}/thumb/6/6e/Monochord.jpg/640px-Monochord.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Monochord.jpg',
    excerpt: 'Interval diagram for resonance / frequency therapy literature packs.',
    relatedCount: 4,
  },
  {
    id: 'sound-healing-2',
    topicId: 'sound-healing',
    title: 'Tibetan singing bowls',
    creator: 'Public domain photograph',
    date: 'modern archival',
    catalogId: 'Singing-bowls',
    imageUrl: `${W}/thumb/3/3e/Singing_bowls.jpg/640px-Singing_bowls.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Singing_bowls.jpg',
    excerpt: 'Instrument plate for temple acoustics / sound-healing corpora.',
    relatedCount: 3,
  },
  // —— Alchemy ——
  {
    id: 'alchemy-1',
    topicId: 'alchemy',
    title: 'Splendor Solis — alchemical emblem',
    creator: 'Attributed workshop of Splendor Solis',
    date: '1582',
    catalogId: 'Splendor',
    imageUrl: `${W}/thumb/2/2e/Splendor_Solis_22_sun.jpg/480px-Splendor_Solis_22_sun.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Splendor_Solis_22_sun.jpg',
    excerpt: 'Emblem book plate — symbolic lexicon translation sample.',
    relatedCount: 10,
  },
  {
    id: 'alchemy-2',
    topicId: 'alchemy',
    title: 'Ripley Scroll detail (alchemical)',
    creator: 'George Ripley tradition',
    date: '15th–16th c.',
    catalogId: 'Ripley',
    imageUrl: `${W}/thumb/8/8a/Ripley_Scroll.jpg/480px-Ripley_Scroll.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ripley_Scroll.jpg',
    excerpt: 'Laboratory-symbolic scroll for alchemy text OCR packs.',
    relatedCount: 7,
  },
  // —— Ley Lines ——
  {
    id: 'ley-lines-1',
    topicId: 'ley-lines',
    title: 'Stonehenge plan / survey context',
    creator: 'Public domain',
    date: 'historical survey',
    catalogId: 'Stonehenge',
    imageUrl: `${W}/thumb/3/3c/Stonehenge2007_07_30.jpg/640px-Stonehenge2007_07_30.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Stonehenge2007_07_30.jpg',
    excerpt: 'Alignment landmark plate for geomantic overlay dossiers.',
    relatedCount: 8,
  },
  {
    id: 'ley-lines-2',
    topicId: 'ley-lines',
    title: 'Avebury stone circle',
    creator: 'Public domain photograph',
    date: 'historical',
    catalogId: 'Avebury',
    imageUrl: `${W}/thumb/1/1a/Avebury_Stone_Circle.jpg/640px-Avebury_Stone_Circle.jpg`,
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Avebury_Stone_Circle.jpg',
    excerpt: 'Site-alignment corpus seed for surveyor notebook trails.',
    relatedCount: 5,
  },
];

export function getSeedFindingsForTopic(topicId: string): SeedFinding[] {
  return ARCHIVE_SEED_FINDINGS.filter((f) => f.topicId === topicId);
}

export function countSeedFindings(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const f of ARCHIVE_SEED_FINDINGS) {
    out[f.topicId] = (out[f.topicId] || 0) + 1;
  }
  return out;
}
