/**
 * Seed archive findings for Communal Library topic pages.
 * Images are cached under /public/communal-archive (public-domain Commons plates).
 * Live published entries merge on top when available.
 */

export type SeedFinding = {
  id: string;
  topicId: string;
  title: string;
  creator: string;
  date: string;
  catalogId: string;
  imageUrl: string;
  sourceUrl: string;
  excerpt: string;
  relatedCount?: number;
};

const img = (topicId: string, n: 1 | 2) => `/communal-archive/${topicId}/${n}.jpg`;

/** Two curated findings per lattice topic (22 topics). */
export const ARCHIVE_SEED_FINDINGS: SeedFinding[] = [
  {
    id: 'hieroglyphics-1',
    topicId: 'hieroglyphics',
    title: 'Rosetta Stone (trilingual decree)',
    creator: 'Ptolemaic Egypt · British Museum',
    date: '196 BCE',
    catalogId: 'EA24',
    imageUrl: img('hieroglyphics', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG',
    excerpt:
      'Egyptian decree in hieroglyphic, Demotic, and Greek — the key bilingual plate for modern decipherment work.',
    relatedCount: 12,
  },
  {
    id: 'hieroglyphics-2',
    topicId: 'hieroglyphics',
    title: 'Book of the Dead of Hunefer — weighing of the heart',
    creator: 'New Kingdom Egypt · British Museum',
    date: 'c. 1275 BCE',
    catalogId: 'EA9901',
    imageUrl: img('hieroglyphics', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Book_of_the_Dead_of_Hunefer_sheet_5.jpg',
    excerpt: 'Funerary vignette with captioned hieroglyphic columns — strong OCR target for gloss packs.',
    relatedCount: 8,
  },
  {
    id: 'cuneiform-1',
    topicId: 'cuneiform',
    title: 'Code of Hammurabi stele',
    creator: 'Babylon · Louvre',
    date: 'c. 1755 BCE',
    catalogId: 'Sb 8',
    imageUrl: img('cuneiform', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Code_of_Hammurabi.jpg',
    excerpt: 'Basalt law code with continuous Akkadian wedges — classic comparative transliteration plate.',
    relatedCount: 15,
  },
  {
    id: 'cuneiform-2',
    topicId: 'cuneiform',
    title: 'Cuneiform tablet case with stamp seal',
    creator: 'Mesopotamia · public domain photograph',
    date: '2nd millennium BCE',
    catalogId: 'Tablet-case',
    imageUrl: img('cuneiform', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Cuneiform',
    excerpt: 'Administrative tablet envelope with seal impression — typical hive OCR → translate pipeline input.',
    relatedCount: 6,
  },
  {
    id: 'mud-flood-1',
    topicId: 'mud-flood',
    title: 'Denny Hill regrade — Seattle',
    creator: 'University of Washington / public domain',
    date: '1909–1910',
    catalogId: 'SEA-regrade',
    imageUrl: img('mud-flood', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Denny_Regrade,_Seattle',
    excerpt: 'Street-grade change with buildings mid-cut — window-line / buried-story study plate.',
    relatedCount: 9,
  },
  {
    id: 'mud-flood-2',
    topicId: 'mud-flood',
    title: 'Chicago in Flames (Currier & Ives)',
    creator: 'Currier & Ives',
    date: '1871',
    catalogId: 'CHI-1871',
    imageUrl: img('mud-flood', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Great_Chicago_Fire',
    excerpt: 'Post-disaster street elevation narrative used in mud-flood comparative dossiers.',
    relatedCount: 11,
  },
  {
    id: 'tartarian-1',
    topicId: 'tartarian',
    title: '1626 map of Tartary by John Speed',
    creator: 'John Speed',
    date: '1626',
    catalogId: 'Speed-Tartary',
    imageUrl: img('tartarian', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:1626_map_of_Tartary_by_John_Speed.jpg',
    excerpt: 'Early modern “Tartary” atlas plate — primary map lead for empire / place-name trails.',
    relatedCount: 18,
  },
  {
    id: 'tartarian-2',
    topicId: 'tartarian',
    title: 'World’s Columbian Exposition — official views',
    creator: 'Exposition publishers · Internet Archive',
    date: '1893',
    catalogId: 'WCE-1893',
    imageUrl: img('tartarian', 2),
    sourceUrl: 'https://archive.org/details/worldscolumbiane00worl',
    excerpt: 'White City architecture plates often cross-linked with Tartarian / fair rebuild narratives.',
    relatedCount: 22,
  },
  {
    id: 'orphan-trains-1',
    topicId: 'orphan-trains',
    title: 'Orphan Home Festival Day trains',
    creator: 'Public domain press photograph',
    date: 'c. 1900',
    catalogId: 'OT-fest',
    imageUrl: img('orphan-trains', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Orphan_trains',
    excerpt: 'Group portrait of placed children — pair with Chron Am “orphan train” state digs.',
    relatedCount: 7,
  },
  {
    id: 'orphan-trains-2',
    topicId: 'orphan-trains',
    title: 'Children’s Aid Society, New York City',
    creator: 'Valentine’s Manual / public domain',
    date: 'c. 1890',
    catalogId: 'CAS-NY',
    imageUrl: img('orphan-trains', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Children%27s_Aid_Society',
    excerpt: 'Institutional campus plate for orphan-asylum / placement-record cross-checks.',
    relatedCount: 5,
  },
  {
    id: 'legal-research-1',
    topicId: 'legal-research',
    title: 'Magna Carta (Cotton MS Augustus II.106)',
    creator: 'British Library',
    date: '1215 / later inspeximus',
    catalogId: 'Cotton MS Aug II.106',
    imageUrl: img('legal-research', 1),
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Magna_Carta_(British_Library_Cotton_MS_Augustus_II.106).jpg',
    excerpt: 'Foundational legal manuscript plate — exhibit OCR / citation brief sample.',
    relatedCount: 10,
  },
  {
    id: 'legal-research-2',
    topicId: 'legal-research',
    title: 'United States Supreme Court Building',
    creator: 'Public domain architectural photograph',
    date: '1935',
    catalogId: 'LOC-SC',
    imageUrl: img('legal-research', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:US_Supreme_Court_Building.jpg',
    excerpt: 'Institutional architecture plate used in public-domain finding-pack demos.',
    relatedCount: 4,
  },
  {
    id: 'homeopathic-1',
    topicId: 'homeopathic',
    title: 'Portrait of Dr. Samuel Hahnemann',
    creator: 'Wellcome Collection',
    date: '19th c.',
    catalogId: 'Hahnemann',
    imageUrl: img('homeopathic', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Samuel_Hahnemann',
    excerpt: 'Founder plate commonly paired with materia medica monograph OCR.',
    relatedCount: 6,
  },
  {
    id: 'homeopathic-2',
    topicId: 'homeopathic',
    title: 'Homeopathic globules',
    creator: 'Public domain photograph',
    date: 'historical',
    catalogId: 'Globules',
    imageUrl: img('homeopathic', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Homeopathic_Globules.jpg',
    excerpt: 'Remedy form plate — dosage tables are high-value OCR targets in companion texts.',
    relatedCount: 9,
  },
  {
    id: 'mycology-1',
    topicId: 'mycology',
    title: 'Amanita muscaria (fly agaric)',
    creator: 'Field photograph · public domain / Commons',
    date: 'modern archival',
    catalogId: 'Amanita',
    imageUrl: img('mycology', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Amanita_muscaria',
    excerpt: 'Field-guide style plate for spore/pharmacology note packs.',
    relatedCount: 8,
  },
  {
    id: 'mycology-2',
    topicId: 'mycology',
    title: 'Common morel (Morchella esculenta)',
    creator: 'Historical botanical illustration',
    date: '19th c.',
    catalogId: 'Morchella',
    imageUrl: img('mycology', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Morchella_esculenta',
    excerpt: 'Classic mycological engraving — caption OCR + ethnobotany cross-links.',
    relatedCount: 5,
  },
  {
    id: 'quantum-1',
    topicId: 'quantum',
    title: 'Niels Bohr',
    creator: 'Public domain portrait',
    date: 'early 20th c.',
    catalogId: 'Bohr',
    imageUrl: img('quantum', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Niels_Bohr.jpg',
    excerpt: 'Portrait plate for paper-OCR / early quantum theory-map demos.',
    relatedCount: 7,
  },
  {
    id: 'quantum-2',
    topicId: 'quantum',
    title: 'Albert Einstein (1921)',
    creator: 'F. Schmutzer · restoration',
    date: '1921',
    catalogId: 'Einstein-1921',
    imageUrl: img('quantum', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Albert_Einstein',
    excerpt: 'Canonical scientific portrait for relativity / citation-brief corpora.',
    relatedCount: 4,
  },
  {
    id: 'world-fairs-1',
    topicId: 'world-fairs',
    title: 'World’s Columbian Exposition album',
    creator: 'Exposition publishers · Internet Archive',
    date: '1893',
    catalogId: 'WCE-views',
    imageUrl: img('world-fairs', 1),
    sourceUrl: 'https://archive.org/details/worldscolumbiane00worl',
    excerpt: 'Exposition landmark plates — pavilion / fairground corpus seed.',
    relatedCount: 14,
  },
  {
    id: 'world-fairs-2',
    topicId: 'world-fairs',
    title: 'Panama–Pacific International Exposition',
    creator: 'Official fair publications · Internet Archive',
    date: '1915',
    catalogId: 'PPIE-1915',
    imageUrl: img('world-fairs', 2),
    sourceUrl: 'https://archive.org/details/panamapacificint00pana',
    excerpt: 'SF 1915 fair architecture — rebuild / quake-context trails.',
    relatedCount: 11,
  },
  {
    id: 'star-forts-1',
    topicId: 'star-forts',
    title: 'Palmanova star-fort plan (historical print)',
    creator: 'Italian fortification print',
    date: '16th–17th c.',
    catalogId: 'Palmanova',
    imageUrl: img('star-forts', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Palmanova',
    excerpt: 'Classic bastion geometry — Rumsey/LOC star-fort dig companion.',
    relatedCount: 13,
  },
  {
    id: 'star-forts-2',
    topicId: 'star-forts',
    title: 'Bourtange fortress ditches & bridges',
    creator: 'Public domain photograph',
    date: 'modern archival of historic fort',
    catalogId: 'Bourtange',
    imageUrl: img('star-forts', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Vesting_Bourtange',
    excerpt: 'Trace italienne outline — fortification atlas seed.',
    relatedCount: 6,
  },
  {
    id: 'ancient-maps-1',
    topicId: 'ancient-maps',
    title: 'Tabula Rogeriana (al-Idrisi)',
    creator: 'Muhammad al-Idrisi',
    date: '1154',
    catalogId: 'Idrisi',
    imageUrl: img('ancient-maps', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:TabulaRogeriana.jpg',
    excerpt: 'Medieval world chart — legend / place-name OCR target.',
    relatedCount: 16,
  },
  {
    id: 'ancient-maps-2',
    topicId: 'ancient-maps',
    title: 'Ptolemy world map (printed cosmographia)',
    creator: 'After Claudius Ptolemy',
    date: '15th c. print',
    catalogId: 'Ptolemy',
    imageUrl: img('ancient-maps', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Claudius_Ptolemy-_The_World.jpg',
    excerpt: 'Printed cosmographia plate for comparative ancient-map corpora.',
    relatedCount: 12,
  },
  {
    id: 'botanicals-1',
    topicId: 'botanicals',
    title: 'Illustrated flora plate',
    creator: 'Historical botanical atlas · Internet Archive',
    date: '19th c.',
    catalogId: 'Flora',
    imageUrl: img('botanicals', 1),
    sourceUrl: 'https://archive.org/details/illustratedflora00brit',
    excerpt: 'Herbarium-style plate — ethnobotany / constituent-table pipeline sample.',
    relatedCount: 9,
  },
  {
    id: 'botanicals-2',
    topicId: 'botanicals',
    title: 'Mandragora officinalis botanical illustration',
    creator: 'Public domain botanical engraving',
    date: '19th c.',
    catalogId: 'Mandrake',
    imageUrl: img('botanicals', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Mandragora',
    excerpt: 'Medicinal plant engraving with labeled parts — OCR caption gold.',
    relatedCount: 7,
  },
  {
    id: 'medical-holistic-1',
    topicId: 'medical-holistic',
    title: 'Gray’s Anatomy — title page (20th ed.)',
    creator: 'Henry Gray / H. V. Carter',
    date: '1918',
    catalogId: 'Gray-1918',
    imageUrl: img('medical-holistic', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Gray%27s_Anatomy_plates',
    excerpt: 'Public-domain anatomical title plate for integrative protocol reviews.',
    relatedCount: 5,
  },
  {
    id: 'medical-holistic-2',
    topicId: 'medical-holistic',
    title: 'Ming bronze acupuncture statue',
    creator: 'Ming Dynasty medical model',
    date: 'Ming period',
    catalogId: 'Acu-bronze',
    imageUrl: img('medical-holistic', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Acupuncture',
    excerpt: 'Channel model for bilingual clinical literature map demos.',
    relatedCount: 8,
  },
  {
    id: 'academia-1',
    topicId: 'academia',
    title: 'Newton’s Principia title page',
    creator: 'Isaac Newton',
    date: '1687',
    catalogId: 'Principia',
    imageUrl: img('academia', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:NewtonsPrincipia.jpg',
    excerpt: 'Canonical scholarly title page — lit-review / open-dataset seed.',
    relatedCount: 10,
  },
  {
    id: 'academia-2',
    topicId: 'academia',
    title: 'Serapeum of Alexandria (artistic reconstruction)',
    creator: 'Historical reconstruction plate',
    date: '19th c. tradition',
    catalogId: 'Alexandria',
    imageUrl: img('academia', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Library_of_Alexandria',
    excerpt: 'Iconic “library as commons” plate for academia topic branding.',
    relatedCount: 6,
  },
  {
    id: 'translation-1',
    topicId: 'translation',
    title: 'Behistun Inscription reliefs',
    creator: 'Achaemenid Persia',
    date: 'c. 520 BCE',
    catalogId: 'Behistun',
    imageUrl: img('translation', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Behistun_Inscription',
    excerpt: 'Trilingual cliff inscription — ancient↔modern translation pipeline exemplar.',
    relatedCount: 11,
  },
  {
    id: 'translation-2',
    topicId: 'translation',
    title: 'Linear B tablet (Pylos vase inventory)',
    creator: 'Mycenaean archive',
    date: 'c. 1200 BCE',
    catalogId: 'PY-Ta-641',
    imageUrl: img('translation', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Linear_B',
    excerpt: 'Syllabic tablet drawing for script pipeline + glossary correction demos.',
    relatedCount: 7,
  },
  {
    id: 'cathedral-1',
    topicId: 'cathedral',
    title: 'Notre-Dame de Paris',
    creator: 'Public domain architectural photograph',
    date: 'historical / restored fabric',
    catalogId: 'ND-Paris',
    imageUrl: img('cathedral', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Notre-Dame_de_Paris',
    excerpt: 'Gothic fabric plate for floor-plan / Latin-notes extract trails.',
    relatedCount: 9,
  },
  {
    id: 'cathedral-2',
    topicId: 'cathedral',
    title: 'Labyrinth at Chartres Cathedral',
    creator: 'Public domain photograph',
    date: 'medieval pavement / photo',
    catalogId: 'Chartres-lab',
    imageUrl: img('cathedral', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Labyrinth_at_Chartres_Cathedral.JPG',
    excerpt: 'Measured pavement geometry — architectural measurement extract sample.',
    relatedCount: 5,
  },
  {
    id: 'free-energy-1',
    topicId: 'free-energy',
    title: 'Nikola Tesla with laboratory equipment',
    creator: 'Public domain photograph',
    date: 'c. 1899',
    catalogId: 'Tesla-lab',
    imageUrl: img('free-energy', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Nikola_Tesla',
    excerpt: 'High-voltage experiment plate — patent / schematic OCR companion.',
    relatedCount: 8,
  },
  {
    id: 'free-energy-2',
    topicId: 'free-energy',
    title: 'Faraday electromagnetic rotations diagram',
    creator: 'Michael Faraday tradition · engraving',
    date: '19th c.',
    catalogId: 'Faraday',
    imageUrl: img('free-energy', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Faraday-electromagnetic-rotations.png',
    excerpt: 'Laboratory schematic engraving for free-energy archive dossiers.',
    relatedCount: 4,
  },
  {
    id: 'giants-1',
    topicId: 'giants',
    title: 'Cardiff Giant exhibition',
    creator: 'Public domain press photograph',
    date: '1869+',
    catalogId: 'Cardiff',
    imageUrl: img('giants', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Cardiff_Giant',
    excerpt: 'Famous “petrified giant” exhibit — newspaper clipping corpus seed.',
    relatedCount: 6,
  },
  {
    id: 'giants-2',
    topicId: 'giants',
    title: 'Serpent Mound plaque / site context',
    creator: 'Public domain / NPS tradition',
    date: 'historical',
    catalogId: 'Serpent',
    imageUrl: img('giants', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Serpent_Mound',
    excerpt: 'Mound survey landscape for contested osteology / mound-dossier trails.',
    relatedCount: 5,
  },
  {
    id: 'sound-healing-1',
    topicId: 'sound-healing',
    title: 'Archimedean solids — harmonic geometry plate',
    creator: 'Public domain mathematical diagram',
    date: 'historical',
    catalogId: 'Archimedean',
    imageUrl: img('sound-healing', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Archimedean_solids',
    excerpt: 'Geometric harmony diagram for resonance / frequency literature packs.',
    relatedCount: 4,
  },
  {
    id: 'sound-healing-2',
    topicId: 'sound-healing',
    title: 'Singing bowl',
    creator: 'Public domain photograph',
    date: 'modern archival',
    catalogId: 'Singing-bowl',
    imageUrl: img('sound-healing', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Singing_bowls',
    excerpt: 'Instrument plate for temple acoustics / sound-healing corpora.',
    relatedCount: 3,
  },
  {
    id: 'alchemy-1',
    topicId: 'alchemy',
    title: 'Splendor Solis — hermaphrodite with egg',
    creator: 'Splendor Solis tradition',
    date: '1582',
    catalogId: 'Splendor-09',
    imageUrl: img('alchemy', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Splendor_Solis',
    excerpt: 'Emblem book plate — symbolic lexicon translation sample.',
    relatedCount: 10,
  },
  {
    id: 'alchemy-2',
    topicId: 'alchemy',
    title: 'Alchemical emblem with three suns',
    creator: 'Public domain emblem engraving',
    date: 'early modern',
    catalogId: 'Three-suns',
    imageUrl: img('alchemy', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Alchemical_symbols',
    excerpt: 'Laboratory-symbolic emblem for alchemy text OCR packs.',
    relatedCount: 7,
  },
  {
    id: 'ley-lines-1',
    topicId: 'ley-lines',
    title: 'Stonehenge Heel Stone',
    creator: 'Public domain photograph',
    date: 'historical site',
    catalogId: 'Heel-Stone',
    imageUrl: img('ley-lines', 1),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Stonehenge',
    excerpt: 'Alignment landmark plate for geomantic overlay dossiers.',
    relatedCount: 8,
  },
  {
    id: 'ley-lines-2',
    topicId: 'ley-lines',
    title: 'Avebury stone circles',
    creator: 'Public domain photograph',
    date: 'historical site',
    catalogId: 'Avebury',
    imageUrl: img('ley-lines', 2),
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Avebury',
    excerpt: 'Site-alignment corpus seed for surveyor notebook trails.',
    relatedCount: 5,
  },
];

export function getSeedFindingsForTopic(topicId: string): SeedFinding[] {
  return ARCHIVE_SEED_FINDINGS.filter((f) => f.topicId === topicId);
}

export function countSeedFindings(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const f of ARCHIVE_SEED_FINDINGS) {
    out[f.topicId] = (out[f.topicId] || 0) + 1;
  }
  return out;
}
