/**
 * Complete Nag Hammadi Library tractate catalog for Communal Library search/indexing.
 * Codex I–XIII (+ related Bindings). Titles follow standard NHL nomenclature.
 * Harvest URLs prefer Internet Archive / public scholarly mirrors for OCR → word index.
 */
export type NagHammadiTractate = {
  id: string;
  /** NHC citation e.g. II,2 */
  nhc: string;
  codex: number;
  title: string;
  altTitles?: string[];
  /** Short public description for archive cards / search */
  excerpt: string;
  /** Primary dig URL (Archive.org search or known item) */
  sourceUrl: string;
  /** Extra Archive.org / gnosis.org digs for full-text harvest */
  harvestUrls?: string[];
  date: string;
  creator: string;
};

const IA = (q: string) =>
  `https://archive.org/search?query=${encodeURIComponent(q)}&and[]=mediatype%3A%22texts%22`;

/** All unique tractates (duplicates across codices listed once with primary NHC). */
export const NAG_HAMMADI_TRACTATES: NagHammadiTractate[] = [
  {
    id: 'nhc-i-1',
    nhc: 'I,1',
    codex: 1,
    title: 'The Prayer of the Apostle Paul',
    altTitles: ['Prayer of Paul'],
    excerpt: 'Jung Codex opening prayer — short invocation attached to Codex I.',
    sourceUrl: IA('Prayer of the Apostle Paul Nag Hammadi'),
    harvestUrls: [IA('Nag Hammadi Library Robinson'), 'http://gnosis.org/naghamm/prp.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex I (Jung Codex)',
  },
  {
    id: 'nhc-i-2',
    nhc: 'I,2',
    codex: 1,
    title: 'The Apocryphon of James',
    altTitles: ['Secret Book of James', 'Apocryphon of James'],
    excerpt: 'Secret dialogue of Jesus with James and Peter after the resurrection.',
    sourceUrl: IA('Apocryphon of James Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/jam.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex I',
  },
  {
    id: 'nhc-i-3',
    nhc: 'I,3',
    codex: 1,
    title: 'The Gospel of Truth',
    altTitles: ['Evangelium Veritatis'],
    excerpt: 'Valentinian meditation on ignorance, error, and the Father — also in Codex XII.',
    sourceUrl: IA('Gospel of Truth Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/got.html', IA('Gospel of Truth Valentinian')],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex I (also XII)',
  },
  {
    id: 'nhc-i-4',
    nhc: 'I,4',
    codex: 1,
    title: 'The Treatise on the Resurrection',
    altTitles: ['Rheginos', 'Letter to Rheginos'],
    excerpt: 'Letter teaching spiritual resurrection to Rheginos.',
    sourceUrl: IA('Treatise on the Resurrection Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/res.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex I',
  },
  {
    id: 'nhc-i-5',
    nhc: 'I,5',
    codex: 1,
    title: 'The Tripartite Tractate',
    excerpt: 'Long Valentinian systematic theology of the pleroma, creation, and salvation.',
    sourceUrl: IA('Tripartite Tractate Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/tripart.htm'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex I',
  },
  {
    id: 'nhc-ii-1',
    nhc: 'II,1',
    codex: 2,
    title: 'The Apocryphon of John',
    altTitles: ['Secret Book of John', 'Apocryphon of John'],
    excerpt:
      'Foundational Sethian cosmology — long version in II & IV; short versions in III & BG 8502.',
    sourceUrl: IA('Apocryphon of John Nag Hammadi'),
    harvestUrls: [
      'http://gnosis.org/naghamm/apocjn.html',
      IA('Secret Book of John Coptic'),
    ],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II (also III, IV)',
  },
  {
    id: 'nhc-ii-2',
    nhc: 'II,2',
    codex: 2,
    title: 'The Gospel of Thomas',
    excerpt: '114 sayings of Jesus — the most widely studied Nag Hammadi tractate.',
    sourceUrl: IA('Gospel of Thomas Coptic Nag Hammadi'),
    harvestUrls: [
      'http://gnosis.org/naghamm/gosthom.html',
      'https://archive.org/details/TheGospelOfThomas',
      IA('Gospel of Thomas Lambdin'),
    ],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II',
  },
  {
    id: 'nhc-ii-3',
    nhc: 'II,3',
    codex: 2,
    title: 'The Gospel of Philip',
    excerpt: 'Valentinian sacramental sayings — bridal chamber, names, and mysteries.',
    sourceUrl: IA('Gospel of Philip Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/gop.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II',
  },
  {
    id: 'nhc-ii-4',
    nhc: 'II,4',
    codex: 2,
    title: 'The Hypostasis of the Archons',
    altTitles: ['Reality of the Rulers'],
    excerpt: 'Sethian myth of the archons, Norea, and the rape of Eve’s image.',
    sourceUrl: IA('Hypostasis of the Archons Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/hypostas.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II',
  },
  {
    id: 'nhc-ii-5',
    nhc: 'II,5',
    codex: 2,
    title: 'On the Origin of the World',
    excerpt: 'Cosmogony of chaos, Sophia, and the rulers — also preserved in Codex XIII.',
    sourceUrl: IA('On the Origin of the World Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/origin.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II (also XIII)',
  },
  {
    id: 'nhc-ii-6',
    nhc: 'II,6',
    codex: 2,
    title: 'The Exegesis on the Soul',
    excerpt: 'Allegory of the soul’s fall into body and restoration through repentance.',
    sourceUrl: IA('Exegesis on the Soul Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/exe.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II',
  },
  {
    id: 'nhc-ii-7',
    nhc: 'II,7',
    codex: 2,
    title: 'The Book of Thomas the Contender',
    altTitles: ['Thomas the Contender'],
    excerpt: 'Ascetic dialogue of Jesus with Judas Thomas on the body and salvation.',
    sourceUrl: IA('Book of Thomas the Contender Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/bookth.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex II',
  },
  {
    id: 'nhc-iii-2',
    nhc: 'III,2',
    codex: 3,
    title: 'The Gospel of the Egyptians',
    altTitles: ['Holy Book of the Great Invisible Spirit'],
    excerpt: 'Sethian baptismal liturgy of the Great Invisible Spirit — also Codex IV.',
    sourceUrl: IA('Gospel of the Egyptians Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/goseqypt.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex III (also IV)',
  },
  {
    id: 'nhc-iii-3',
    nhc: 'III,3',
    codex: 3,
    title: 'Eugnostos the Blessed',
    excerpt: 'Philosophical revelation of the divine realms — parallel to Sophia of Jesus Christ.',
    sourceUrl: IA('Eugnostos the Blessed Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/eugn.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex III (also V)',
  },
  {
    id: 'nhc-iii-4',
    nhc: 'III,4',
    codex: 3,
    title: 'The Sophia of Jesus Christ',
    altTitles: ['Wisdom of Jesus Christ'],
    excerpt: 'Christianized dialogue version of Eugnostos — also Berlin Codex BG 8502.',
    sourceUrl: IA('Sophia of Jesus Christ Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/sjc.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex III (also BG 8502)',
  },
  {
    id: 'nhc-iii-5',
    nhc: 'III,5',
    codex: 3,
    title: 'The Dialogue of the Saviour',
    excerpt: 'Sayings dialogue of Jesus with disciples on rest, light, and the garments.',
    sourceUrl: IA('Dialogue of the Saviour Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/dialog.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex III',
  },
  {
    id: 'nhc-v-2',
    nhc: 'V,2',
    codex: 5,
    title: 'The Apocalypse of Paul',
    altTitles: ['Revelation of Paul'],
    excerpt: 'Heavenly ascent of Paul through the spheres — distinct from NT 2 Corinthians vision.',
    sourceUrl: IA('Apocalypse of Paul Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/apocpl.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex V',
  },
  {
    id: 'nhc-v-3',
    nhc: 'V,3',
    codex: 5,
    title: 'The (First) Apocalypse of James',
    altTitles: ['1 Apocalypse of James'],
    excerpt: 'Revelation to James on the archons and the path of ascent.',
    sourceUrl: IA('First Apocalypse of James Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/1ja.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex V',
  },
  {
    id: 'nhc-v-4',
    nhc: 'V,4',
    codex: 5,
    title: 'The (Second) Apocalypse of James',
    altTitles: ['2 Apocalypse of James'],
    excerpt: 'Martyrdom and farewell discourse of James the Just.',
    sourceUrl: IA('Second Apocalypse of James Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/2ja.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex V',
  },
  {
    id: 'nhc-v-5',
    nhc: 'V,5',
    codex: 5,
    title: 'The Apocalypse of Adam',
    excerpt: 'Sethian revelation from Adam to Seth on flood, fire, and illuminators.',
    sourceUrl: IA('Apocalypse of Adam Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/ad.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex V',
  },
  {
    id: 'nhc-vi-1',
    nhc: 'VI,1',
    codex: 6,
    title: 'The Acts of Peter and the Twelve Apostles',
    excerpt: 'Allegorical journey to Lithargoel — pearl merchant and healing city.',
    sourceUrl: IA('Acts of Peter and the Twelve Apostles Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/actp.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-2',
    nhc: 'VI,2',
    codex: 6,
    title: 'The Thunder, Perfect Mind',
    altTitles: ['Thunder Perfect Mind'],
    excerpt: 'First-person paradoxical revelation of the divine feminine voice.',
    sourceUrl: IA('Thunder Perfect Mind Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/thunder.html', IA('Thunder Perfect Mind')],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-3',
    nhc: 'VI,3',
    codex: 6,
    title: 'Authoritative Teaching',
    altTitles: ['Authentikos Logos'],
    excerpt: 'Soul’s contest with matter and the bridal chamber of rest.',
    sourceUrl: IA('Authoritative Teaching Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/auth.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-4',
    nhc: 'VI,4',
    codex: 6,
    title: 'The Concept of Our Great Power',
    excerpt: 'Apocalyptic history of aeons, flood, fire, and the end of the archons.',
    sourceUrl: IA('Concept of Our Great Power Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/greatpow.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-5',
    nhc: 'VI,5',
    codex: 6,
    title: 'Plato, Republic 588A–589B',
    altTitles: ['Republic excerpt'],
    excerpt: 'Coptic excerpt of Plato’s Republic (beast-man image) included in Codex VI.',
    sourceUrl: IA('Nag Hammadi Plato Republic Coptic'),
    harvestUrls: ['http://gnosis.org/naghamm/plato.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-6',
    nhc: 'VI,6',
    codex: 6,
    title: 'The Discourse on the Eighth and Ninth',
    altTitles: ['Ogdoad and Ennead'],
    excerpt: 'Hermetic ascent dialogue — Hermes and the pupil on the eighth and ninth spheres.',
    sourceUrl: IA('Discourse on the Eighth and Ninth Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/disc8-9.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-7',
    nhc: 'VI,7',
    codex: 6,
    title: 'The Prayer of Thanksgiving',
    excerpt: 'Hermetic eucharistic prayer — also known from Latin Asclepius tradition.',
    sourceUrl: IA('Prayer of Thanksgiving Nag Hammadi Hermetic'),
    harvestUrls: ['http://gnosis.org/naghamm/prat.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vi-8',
    nhc: 'VI,8',
    codex: 6,
    title: 'Asclepius 21–29',
    altTitles: ['Perfect Discourse excerpt'],
    excerpt: 'Coptic Hermetic Asclepius excerpt on idols, Egypt, and apocalypse.',
    sourceUrl: IA('Asclepius Nag Hammadi Hermetica'),
    harvestUrls: ['http://gnosis.org/naghamm/asclep.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VI',
  },
  {
    id: 'nhc-vii-1',
    nhc: 'VII,1',
    codex: 7,
    title: 'The Paraphrase of Shem',
    excerpt: 'Sethian cosmogony of Light, Darkness, and Spirit through Derdekeas.',
    sourceUrl: IA('Paraphrase of Shem Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/para.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VII',
  },
  {
    id: 'nhc-vii-2',
    nhc: 'VII,2',
    codex: 7,
    title: 'The Second Treatise of the Great Seth',
    excerpt: 'Christ’s laughter at the archons and the passion as cosmic drama.',
    sourceUrl: IA('Second Treatise of the Great Seth Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/2seth.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VII',
  },
  {
    id: 'nhc-vii-3',
    nhc: 'VII,3',
    codex: 7,
    title: 'The Apocalypse of Peter',
    altTitles: ['Revelation of Peter'],
    excerpt: 'Vision of the crucified substitute — distinct from Ethiopic Apocalypse of Peter.',
    sourceUrl: IA('Apocalypse of Peter Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/apopet.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VII',
  },
  {
    id: 'nhc-vii-4',
    nhc: 'VII,4',
    codex: 7,
    title: 'The Teachings of Silvanus',
    excerpt: 'Wisdom instruction blending biblical and philosophical paraenesis.',
    sourceUrl: IA('Teachings of Silvanus Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/silvanus.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VII',
  },
  {
    id: 'nhc-vii-5',
    nhc: 'VII,5',
    codex: 7,
    title: 'The Three Steles of Seth',
    excerpt: 'Liturgical hymns of Sethian ascent — Autogenes, Barbelo, Invisible Spirit.',
    sourceUrl: IA('Three Steles of Seth Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/steles.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VII',
  },
  {
    id: 'nhc-viii-1',
    nhc: 'VIII,1',
    codex: 8,
    title: 'Zostrianos',
    excerpt: 'Long Sethian ascent apocalypse — baptismal seals through the aeons.',
    sourceUrl: IA('Zostrianos Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/zostr.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VIII',
  },
  {
    id: 'nhc-viii-2',
    nhc: 'VIII,2',
    codex: 8,
    title: 'The Letter of Peter to Philip',
    excerpt: 'Post-resurrection gathering — pleroma teaching and mission charge.',
    sourceUrl: IA('Letter of Peter to Philip Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/petphil.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex VIII',
  },
  {
    id: 'nhc-ix-1',
    nhc: 'IX,1',
    codex: 9,
    title: 'Melchizedek',
    excerpt: 'Revelations to Melchizedek — Jesus as priest and eschatological warrior.',
    sourceUrl: IA('Melchizedek Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/melchiz.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex IX',
  },
  {
    id: 'nhc-ix-2',
    nhc: 'IX,2',
    codex: 9,
    title: 'The Thought of Norea',
    excerpt: 'Short hymn of Norea to the Four Luminaries.',
    sourceUrl: IA('Thought of Norea Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/nore.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex IX',
  },
  {
    id: 'nhc-ix-3',
    nhc: 'IX,3',
    codex: 9,
    title: 'The Testimony of Truth',
    excerpt: 'Polemic against Law, baptism, and martyrdom; praise of true gnosis.',
    sourceUrl: IA('Testimony of Truth Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/testruth.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex IX',
  },
  {
    id: 'nhc-x-1',
    nhc: 'X,1',
    codex: 10,
    title: 'Marsanes',
    excerpt: 'Sethian ascent and letter mysticism — badly damaged single tractate of Codex X.',
    sourceUrl: IA('Marsanes Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/marsanes.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex X',
  },
  {
    id: 'nhc-xi-1',
    nhc: 'XI,1',
    codex: 11,
    title: 'The Interpretation of Knowledge',
    excerpt: 'Valentinian homily on church members as body of the Word.',
    sourceUrl: IA('Interpretation of Knowledge Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/intpr.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XI',
  },
  {
    id: 'nhc-xi-2',
    nhc: 'XI,2',
    codex: 11,
    title: 'A Valentinian Exposition',
    altTitles: ['On Baptism', 'On the Eucharist'],
    excerpt: 'Valentinian cosmogony plus baptism and eucharist liturgical notes.',
    sourceUrl: IA('Valentinian Exposition Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/valex.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XI',
  },
  {
    id: 'nhc-xi-3',
    nhc: 'XI,3',
    codex: 11,
    title: 'Allogenes',
    altTitles: ['The Foreigner'],
    excerpt: 'Sethian visionary ascent of Allogenes to the Unknowable One.',
    sourceUrl: IA('Allogenes Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/allogene.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XI',
  },
  {
    id: 'nhc-xi-4',
    nhc: 'XI,4',
    codex: 11,
    title: 'Hypsiphrone',
    excerpt: 'Fragmentary revelation of Hypsiphrone descending into the world.',
    sourceUrl: IA('Hypsiphrone Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/hypsiph.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XI',
  },
  {
    id: 'nhc-xii-1',
    nhc: 'XII,1',
    codex: 12,
    title: 'The Sentences of Sextus',
    excerpt: 'Coptic sayings collection (pagan-Christian wisdom) — partial in Codex XII.',
    sourceUrl: IA('Sentences of Sextus Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/sex.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XII',
  },
  {
    id: 'nhc-xiii-1',
    nhc: 'XIII,1',
    codex: 13,
    title: 'Trimorphic Protennoia',
    altTitles: ['Three Forms of First Thought'],
    excerpt: 'Barbelo’s triple descent as Voice, Speech, and Word — Sethian revelatory hymn.',
    sourceUrl: IA('Trimorphic Protennoia Nag Hammadi'),
    harvestUrls: ['http://gnosis.org/naghamm/trimorph.html'],
    date: '4th c. Coptic',
    creator: 'Nag Hammadi Codex XIII',
  },
];

/** Major published editions useful for full-text harvest / word indexing. */
export const NAG_HAMMADI_PUBLISHED_EDITIONS = [
  {
    id: 'robinson-nhl-english',
    title: 'The Nag Hammadi Library in English (James M. Robinson, ed.)',
    creator: 'Coptic Gnostic Library Project / Harper & Row',
    date: '1977–1990 eds.',
    sourceUrl: IA('Nag Hammadi Library in English Robinson'),
    excerpt: 'Standard one-volume English translation set — primary harvest target for indexing.',
  },
  {
    id: 'meyer-nhl-scriptures',
    title: 'The Nag Hammadi Scriptures (Marvin Meyer, ed.)',
    creator: 'HarperOne',
    date: '2007',
    sourceUrl: IA('Nag Hammadi Scriptures Meyer'),
    excerpt: 'International edition translations with introductions — check borrowing rights before OCR.',
  },
  {
    id: 'barnstone-meyer-gnostic-bible',
    title: 'The Gnostic Bible (Barnstone & Meyer)',
    creator: 'Shambhala',
    date: '2003',
    sourceUrl: IA('Gnostic Bible Barnstone Meyer'),
    excerpt: 'Selected Nag Hammadi + related Gnostic scriptures in literary English.',
  },
  {
    id: 'brill-cgl',
    title: 'The Coptic Gnostic Library (Brill / NHS series)',
    creator: 'Brill Academic',
    date: '1975–',
    sourceUrl: IA('Coptic Gnostic Library Nag Hammadi Studies'),
    excerpt: 'Critical Coptic text + translation volumes — scholarly baseline for collation.',
  },
  {
    id: 'layton-gnostic-scriptures',
    title: 'The Gnostic Scriptures (Bentley Layton)',
    creator: 'Doubleday / Anchor',
    date: '1987',
    sourceUrl: IA('Gnostic Scriptures Layton'),
    excerpt: 'Annotated translations of major Nag Hammadi and related works.',
  },
  {
    id: 'gnosis-org-nhl',
    title: 'Gnostic Society Library — Nag Hammadi collection',
    creator: 'The Gnostic Society / Ecclesia Gnostica',
    date: 'web corpus',
    sourceUrl: 'http://gnosis.org/naghamm/nhl.html',
    excerpt: 'Online tractate index with multiple public English translations for search harvest.',
  },
  {
    id: 'ia-nhl-pdfy',
    title: 'The Nag Hammadi Library (PDFy / IA text mirrors)',
    creator: 'Internet Archive mirrors',
    date: 'various',
    sourceUrl: 'https://archive.org/search?query=nag+hammadi+library&and[]=mediatype%3A%22texts%22',
    excerpt: 'Borrowable and open text scans — best starting crawl for word indexing.',
  },
  {
    id: 'berlin-codex-bg8502',
    title: 'Berlin Codex BG 8502 (related Gnostic codex)',
    creator: 'Papyrus Berolinensis 8502',
    date: '5th c.',
    sourceUrl: IA('Berlin Codex Apocryphon of John Sophia Jesus Christ'),
    excerpt: 'Related codex with Apocryphon of John, Sophia of Jesus Christ, Act of Peter, Gospel of Mary.',
  },
  {
    id: 'gospel-of-mary',
    title: 'The Gospel of Mary (BG 8502 — companion text)',
    creator: 'Berlin Codex',
    date: '5th c.',
    sourceUrl: IA('Gospel of Mary Magdalene Coptic'),
    excerpt: 'Not from Nag Hammadi jars but essential companion Gnostic gospel for the corpus.',
  },
  {
    id: 'pistis-sophia',
    title: 'Pistis Sophia (Askew Codex — related Gnostic book)',
    creator: 'Askew Codex / British Library',
    date: 'pub. 1851–1921 tr.',
    sourceUrl: IA('Pistis Sophia Mead'),
    excerpt: 'Pre-NHL Gnostic dialogue book — public-domain Mead translation is OCR-friendly.',
  },
];

export function getNagHammadiTractates() {
  return NAG_HAMMADI_TRACTATES;
}

export function searchNagHammadiCatalog(query: string) {
  const needle = query.trim().toLowerCase();
  if (!needle) return NAG_HAMMADI_TRACTATES;
  return NAG_HAMMADI_TRACTATES.filter((t) => {
    const hay = [t.title, t.nhc, t.excerpt, t.creator, ...(t.altTitles || [])]
      .join(' ')
      .toLowerCase();
    return hay.includes(needle);
  });
}
