import type { FaultEntry } from '../types';

export const electricalFaults: FaultEntry[] = [
  {
    id: 'elec-breaker-nuisance',
    packId: 'electrical',
    category: 'breakers',
    title: 'Breaker nuisance trips',
    aliases: ['keeps tripping', 'breaker trips', 'nuisance trip'],
    symptoms: ['Trips under load or randomly', 'Resets then trips again'],
    likelyCauses: ['Overloaded circuit', 'Short/ground fault', 'Weak breaker', 'Motor inrush', 'Shared neutral issues'],
    steps: [
      'Identify exact breaker and connected loads.',
      'Reset once; if immediate trip with nothing on → short/ground.',
      'If trips when load starts → measure inrush / consider dedicated circuit.',
      'Check for double-taps, loose lugs, heat discoloration.',
      'Swap with known-good same-amp breaker to isolate weak breaker.',
    ],
    safety: ['LOTO. Verify de-energized.', 'Don’t upsize breaker to “fix” trips.'],
    tools: ['Clamp meter', 'IR thermometer', 'Insulated tools'],
    parts: ['Correct amp breaker', 'Pigtails', 'Torque-rated lugs'],
    severity: 'high',
    proTips: ['Heat at the breaker body is a confession — retorque or replace.'],
  },
  {
    id: 'elec-gfci-wont-reset',
    packId: 'electrical',
    category: 'breakers',
    title: 'GFCI won’t reset',
    aliases: ['gfci', 'gfi won’t reset', 'ground fault'],
    symptoms: ['Won’t stay reset', 'Trips immediately', 'Downstream dead'],
    likelyCauses: ['Active ground fault', 'Wet device', 'Miswired LINE/LOAD', 'Failed GFCI', 'Neutral-ground bootleg'],
    steps: [
      'Unplug all downstream loads; try reset.',
      'Open device; verify LINE vs LOAD orientation.',
      'Megger / insulation check on cable if outdoor/wet.',
      'Replace GFCI if no fault found and still dead.',
      'Check for neutral-ground bonds downstream of GFCI.',
    ],
    safety: ['Outdoor wet locations — treat as energized until proven otherwise.'],
    tools: ['GFCI tester', 'Multimeter', 'Outlet tester'],
    parts: ['WR/TR GFCI receptacle', 'GFCI breaker'],
    severity: 'high',
    proTips: ['LINE/LOAD swap is the #1 “new GFCI still won’t work” call.'],
  },
  {
    id: 'elec-afci-trip',
    packId: 'electrical',
    category: 'breakers',
    title: 'AFCI breaker trips',
    aliases: ['afci', 'arc fault', 'afci trip'],
    symptoms: ['Trips with certain loads', 'LED dimmers / vacuums trigger'],
    likelyCauses: ['Series arc (loose connection)', 'Damaged cord', 'Incompatible device', 'Weak AFCI', 'Shared neutrals'],
    steps: [
      'Note what load causes the trip.',
      'Inspect devices/cords on circuit for damage.',
      'Check for shared neutrals on multi-wire branch circuits.',
      'Retorque terminations; look for backstabbed devices.',
      'Replace AFCI if nuisance confirmed after wiring OK.',
    ],
    safety: ['Don’t bypass AFCI protection.'],
    tools: ['Torque screwdriver', 'Circuit tracer'],
    parts: ['AFCI breaker', 'AFCI receptacle', 'Pigtails'],
    severity: 'high',
    proTips: ['Loose neutrals create arcs AFCI is designed to catch — hunt connections first.'],
  },
  {
    id: 'elec-panel-hot',
    packId: 'electrical',
    category: 'panels',
    title: 'Panel or lugs running hot',
    aliases: ['hot panel', 'warm breaker', 'hot lugs', 'burning smell'],
    symptoms: ['Warm deadfront', 'Discoloration', 'Buzzing', 'Smell of hot insulation'],
    likelyCauses: ['Loose lugs', 'Overloaded service', 'Failing breaker', 'Aluminum oxidation', 'Poor torque'],
    steps: [
      'IR scan or careful temp check — document hot spots.',
      'De-energize if safe/required; retorque to manufacturer inch-lbs.',
      'Inspect for arcing damage; replace damaged breakers/lugs.',
      'Evaluate load vs service rating.',
      'Apply antioxidant on AL conductors per practice.',
    ],
    safety: ['Critical fire hazard. If actively smoking/arcing — utility / emergency.', 'Live panel work only if qualified.'],
    tools: ['IR camera', 'Torque wrench', 'No-Ox'],
    parts: ['Breakers', 'Lug kits', 'Panel if damaged'],
    severity: 'critical',
    proTips: ['Torque specs beat “tight enough.” Carry the chart.'],
  },
  {
    id: 'elec-open-neutral',
    packId: 'electrical',
    category: 'wiring',
    title: 'Open neutral symptoms',
    aliases: ['open neutral', 'lights bright dim', 'lost neutral'],
    symptoms: ['Lights brighten/dim with loads', 'Odd voltages 150/90', 'Tingles on appliances'],
    likelyCauses: ['Loose neutral lug', 'Failed utility neutral', 'Bad splice', 'Corroded meter neutral'],
    steps: [
      'Measure L1-N, L2-N, L1-L2 under changing loads.',
      'If voltages swing wildly, suspect open neutral — treat as urgent.',
      'Check panel neutral bar torque and feeder neutral.',
      'Coordinate with utility if service neutral suspected.',
    ],
    safety: ['Open neutrals can destroy equipment and shock. Prioritize.', 'Metal parts may be energized oddly.'],
    tools: ['True-RMS meter', 'Recording meter'],
    parts: ['Neutral lugs', 'Service cable (utility)'],
    severity: 'critical',
    proTips: ['If L1-N + L2-N still ≈ 240 but each leg wanders, you’re looking at a classic open neutral.'],
  },
  {
    id: 'elec-double-tap',
    packId: 'electrical',
    category: 'panels',
    title: 'Double-tapped breaker',
    aliases: ['double tap', 'two wires one breaker'],
    symptoms: ['Two conductors under one lug', 'Heat at breaker'],
    likelyCauses: ['Improper install', 'Added circuit without space'],
    steps: [
      'Confirm breaker listing — most allow one conductor only.',
      'Install listed handle-tied twin or add pigtail to wire connector.',
      'Move circuit to spare slot if available.',
      'Retorque all touched lugs.',
    ],
    safety: ['De-energize circuit before rearranging.'],
    tools: ['Wire connectors', 'Torque tool'],
    parts: ['Listed breaker', 'Polarias / wire nuts'],
    severity: 'medium',
    proTips: ['Photo the panel schedule before you move anything.'],
  },
  {
    id: 'elec-no-power-circuit',
    packId: 'electrical',
    category: 'wiring',
    title: 'Dead circuit / no power',
    aliases: ['no power', 'dead outlet', 'half the house dark'],
    symptoms: ['Outlets dead', 'Breaker on but no voltage'],
    likelyCauses: ['Tripped GFCI upstream', 'Open hot', 'Backstab failure', 'Bad breaker', 'Loose splice'],
    steps: [
      'Verify breaker position; check panel voltage.',
      'Hunt upstream GFCI (garage, bath, exterior, kitchen).',
      'Test first device on circuit; open and inspect.',
      'Wiggle test backstabs; pigtail to screws.',
      'Trace opens with toner if needed.',
    ],
    safety: ['Assume wires live until tested.'],
    tools: ['Outlet tester', 'Toner/probe', 'Non-contact tester'],
    parts: ['Receptacles', 'Wire nuts', 'Breaker'],
    severity: 'medium',
    proTips: ['Dead kitchen counter often hides a tripped GFCI in the garage.'],
  },
  {
    id: 'elec-bonding-pool',
    packId: 'electrical',
    category: 'bonding',
    title: 'Pool equipment bonding / shock tingle',
    aliases: ['tingle', 'pool shock', 'bonding', 'equipotential'],
    symptoms: ['Tingle at ladder/handrail', 'Voltage to water', 'Stray voltage'],
    likelyCauses: ['Missing bond wire', 'Broken bond clamp', 'Utility neutral issue', 'Faulty equipment ground'],
    steps: [
      'Stop use if tingling — safety first.',
      'Measure voltage water-to-deck / water-to-equipment.',
      'Inspect #8 solid bond loop to pump, heater, metal, water bond.',
      'Repair open bonds; verify equipment grounding conductors.',
      'Escalate to utility if primary neutral suspected.',
    ],
    safety: ['Shock hazard — keep people out of water until resolved.'],
    tools: ['Low-voltage meter', 'Bonding clamps'],
    parts: ['#8 solid copper', 'Listed bond clamps', 'Water bond fitting'],
    severity: 'critical',
    proTips: ['A complete equipotential bond is non-negotiable around pools.'],
  },
  {
    id: 'elec-motor-wont-start',
    packId: 'electrical',
    category: 'motors',
    title: 'Motor won’t start (pump/AC/compressor)',
    aliases: ['contactor', 'motor start', 'humming motor'],
    symptoms: ['Contactor chatters', 'Overload trips', 'No start'],
    likelyCauses: ['Low voltage', 'Bad capacitor', 'Failed contactor', 'Thermal overload', 'Seized motor'],
    steps: [
      'Measure voltage at motor under attempted start.',
      'Check caps (start/run) for rating and ESR.',
      'Inspect contactor pads for pitting.',
      'Verify overload/reset and amp draw.',
    ],
    safety: ['Capacitors store energy.', 'Rotating equipment guards.'],
    tools: ['Clamp meter', 'Cap tester'],
    parts: ['Capacitor', 'Contactor', 'Motor'],
    severity: 'high',
    proTips: ['Chattering contactor + low volts often means undersized conductors or bad connections upstream.'],
  },
  {
    id: 'elec-aluminum-branch',
    packId: 'electrical',
    category: 'wiring',
    title: 'Aluminum branch circuit concerns',
    aliases: ['aluminum wiring', 'al wire', 'CO/ALR'],
    symptoms: ['Warm devices', 'Flicker', 'Old AL branch'],
    likelyCauses: ['Oxidation', 'Wrong devices', 'Improper connectors'],
    steps: [
      'Identify AL conductors; don’t mix casually with CU under one lug.',
      'Use listed COPALUM/AlumiConn style repairs or CO/ALR devices as appropriate.',
      'Antioxidant + proper torque.',
      'Advise full remediation options for whole-home AL.',
    ],
    safety: ['Fire risk if ignored. Document recommendations.'],
    tools: ['Torque screwdriver', 'No-Ox'],
    parts: ['AlumiConn', 'CO/ALR receptacles'],
    severity: 'high',
    proTips: ['Never “just put a Cu pigtail under a wire nut” unless the connector is listed for AL/CU.'],
  },
  {
    id: 'elec-subpanel-neutral',
    packId: 'electrical',
    category: 'panels',
    title: 'Subpanel neutral-ground bonded incorrectly',
    aliases: ['subpanel bond', 'floating neutral', 'bootleg ground'],
    symptoms: ['Neutral bar bonded in sub', 'Objectionable current on ground'],
    likelyCauses: ['Installer left bond screw', 'Missing isolated neutral', '4th wire missing'],
    steps: [
      'Confirm feeder: 4-wire (hot hot neutral ground) for modern subpanels.',
      'Neutral isolated from can; grounds to can/bar.',
      'Remove incorrect bond screw/strap in sub.',
      'Add equipment ground if only 3-wire feeder (per applicable code path).',
    ],
    safety: ['Misbonding creates parallel neutral paths — shock risk.'],
    tools: ['Multimeter', 'Panel schedule'],
    parts: ['Ground bar kit', 'Ser / SE cable as needed'],
    severity: 'high',
    proTips: ['Main = bonded. Sub = isolated neutral. Say it every time.'],
  },
  {
    id: 'elec-working-clearance',
    packId: 'electrical',
    category: 'code',
    title: 'Panel working clearance / access issues',
    aliases: ['clearance', '30 inches', 'dedicated space'],
    symptoms: ['Storage in front of panel', 'Door can’t open', 'Low headroom'],
    likelyCauses: ['Homeowner storage', 'Poor original install'],
    steps: [
      'Recall: typically 30" wide, 36" deep, 6.5" headroom working space (verify current code).',
      'Remove storage; educate customer.',
      'Document if panel location is noncompliant for AHJ.',
    ],
    safety: ['Blocked panels delay emergency shutoff.'],
    tools: ['Tape measure', 'Camera for documentation'],
    parts: [],
    severity: 'medium',
    proTips: ['Photo the blockage — CYA for you and leverage for the customer.'],
  },
  {
    id: 'elec-lost-leg',
    packId: 'electrical',
    category: 'panels',
    title: 'Lost leg / single-phase brownout symptoms',
    aliases: ['lost leg', 'half power', '120 only', 'brownout'],
    symptoms: ['Half the 240V loads dead', 'Dim lights on one side', 'HVAC won’t start'],
    likelyCauses: ['Utility lost phase', 'Failed meter/socket', 'Loose service lug', 'Failed breaker feeding multiwire'],
    steps: [
      'Measure L1-L2, L1-N, L2-N at panel.',
      'If one hot is dead/low at main lugs, contact utility.',
      'If present at main but missing downstream, isolate feeder/breaker.',
      'Do not keep resetting 240V equipment into a lost leg.',
    ],
    safety: ['Can destroy motors/compressors quickly.', 'Utility coordination often required.'],
    tools: ['True-RMS meter'],
    parts: ['Service equipment (utility)', 'Main breaker'],
    severity: 'critical',
    proTips: ['If L1-L2 collapses while L-N looks weird, stop and call the utility.'],
  },
  {
    id: 'elec-shared-neutral',
    packId: 'electrical',
    category: 'wiring',
    title: 'Shared neutral / MWBC problems',
    aliases: ['shared neutral', 'mwbc', 'multiwire'],
    symptoms: ['AFCI trips', 'Overloaded neutral', 'Odd voltages'],
    likelyCauses: ['Unhandle-tied breakers', 'Neutrals landed wrong', 'Renovations broke pairing'],
    steps: [
      'Identify paired hots on opposite phases.',
      'Ensure handle tie / 2-pole breaker as required.',
      'Verify neutral continuity and landing.',
      'Correct miswired devices that borrowed neutrals.',
    ],
    safety: ['Opening neutral on MWBC can shock.'],
    tools: ['Circuit tracer', 'Clamp on neutral'],
    parts: ['2-pole breaker', 'Handle tie'],
    severity: 'high',
    proTips: ['Clamp the neutral — if amps ≈ difference of legs, pairing is healthy.'],
  },
  {
    id: 'elec-corroded-panel',
    packId: 'electrical',
    category: 'panels',
    title: 'Corroded outdoor panel / water intrusion',
    aliases: ['rusty panel', 'water in panel', 'corrosion'],
    symptoms: ['Rust streaks', 'Wet bus', 'Intermittent breakers'],
    likelyCauses: ['Failed weather seal', 'Conduit water entry', 'Missing drip loops', 'Flooding'],
    steps: [
      'Photograph and assess severity — may need full replacement.',
      'De-energize with utility if unsafe.',
      'Fix water path (hubs, myers hubs, drip loops).',
      'Replace damaged breakers/bus; never ignore green copper dust.',
    ],
    safety: ['Corrosion + moisture = shock/fire. Err on replacement.'],
    tools: ['Camera', 'Torque tools'],
    parts: ['NEMA 3R panel', 'Breakers', 'Hubs'],
    severity: 'critical',
    proTips: ['If the bus is pitted, don’t nickel-and-dime it — replace the gear.'],
  },
];

