import type { FaultEntry } from '../types';

/** Property Maintenance fault library — appliances + unit systems. */
export const propertyFaults: FaultEntry[] = [
  {
    id: 'prop-washer-no-drain',
    packId: 'property',
    category: 'appliances',
    title: 'Washer fills but won’t drain / spin',
    aliases: ['washer clogged', 'washer standing water', 'E21 drain', 'F21'],
    symptoms: ['Cycle stuck at drain', 'Standing water in drum', 'Humming pump'],
    likelyCauses: ['Clogged drain pump filter', 'Kinked drain hose', 'Failed drain pump', 'Lid/door lock open'],
    steps: [
      'Unplug washer. Bail standing water if needed.',
      'Locate and clean pump filter / coin trap (front-load kickplate or rear access).',
      'Check drain hose for kink and standpipe height (typically 30–96").',
      'Listen for pump hum with filter clear — replace pump if humming with no flow.',
      'Verify door/lid lock engages before spin.',
    ],
    safety: ['Unplug before opening pump cover.', 'Catch residual water — bleach residue irritates skin.'],
    tools: ['Towel', 'Flat screwdriver', 'Bucket', 'Needle-nose'],
    parts: ['Drain pump', 'Pump filter / coin trap', 'Door lock'],
    severity: 'medium',
    proTips: ['Photo the filter debris for the resident — coins and socks are the usual suspects.'],
  },
  {
    id: 'prop-washer-no-spin',
    packId: 'property',
    category: 'appliances',
    title: 'Washer drains but won’t spin',
    aliases: ['unbalanced load', 'washer shake', 'UB error'],
    symptoms: ['Clothes soaking wet', 'Drum rocks then stops', 'Unbalance code'],
    likelyCauses: ['Unbalanced load', 'Failed shock absorbers', 'Bad lid switch', 'Mode shifter (top-load)'],
    steps: [
      'Redistribute load and retry spin on a small towel load.',
      'Check leveling feet and shipping bolts removed.',
      'Inspect shocks / suspension rods for oil leaks or collapse.',
      'Test lid switch continuity if spin never starts.',
    ],
    safety: ['Unplug before tipping or removing panels.'],
    tools: ['Level', 'Multimeter', 'Socket set'],
    parts: ['Shock absorbers', 'Suspension rods', 'Lid switch'],
    severity: 'medium',
    proTips: ['One wet jeans load often trips “unbalance” — educate residents before parts.'],
  },
  {
    id: 'prop-dryer-no-heat',
    packId: 'property',
    category: 'appliances',
    title: 'Electric dryer tumbles but no heat',
    aliases: ['dryer cold', 'heating element', 'thermal fuse'],
    symptoms: ['Clothes damp after long cycle', 'Drum turns', 'No warmth at exhaust'],
    likelyCauses: ['Open thermal fuse', 'Failed heating element', 'Broken high-limit thermostat', 'L1 only on 240V'],
    steps: [
      'Confirm 240V at terminal block (both legs). One dead leg = no heat but motor runs.',
      'Check / clear lint path and exterior vent — restricted vent cooks fuses.',
      'Continuity-test thermal fuse (usually on blower housing) — open = replace + clear vent.',
      'Ohm heating element; replace if open.',
    ],
    safety: ['Kill breaker before opening cabinet.', 'Never bypass thermal fuse.'],
    tools: ['Multimeter', 'Nut driver', 'Vent brush'],
    parts: ['Thermal fuse', 'Heating element', 'High-limit thermostat'],
    severity: 'high',
    proTips: ['Always replace fuse and clean vent together — otherwise callback in weeks.'],
  },
  {
    id: 'prop-dryer-gas-no-heat',
    packId: 'property',
    category: 'appliances',
    title: 'Gas dryer no heat / no ignition',
    aliases: ['ignitor', 'gas valve coils', 'click no flame'],
    symptoms: ['Ignitor glows then nothing', 'No glow', 'Gas smell brief then off'],
    likelyCauses: ['Weak ignitor', 'Failed gas valve coils', 'Thermal fuse', 'Flame sensor'],
    steps: [
      'Confirm gas shutoff open and other gas appliances work.',
      'Watch ignitor: glow then click — if no flame, suspect coils.',
      'No glow → test ignitor continuity / thermal fuse.',
      'Replace coils as a pair when ignitor is healthy but valve won’t open.',
    ],
    safety: ['If you smell sustained gas, evacuate and shut supply — no sparks.'],
    tools: ['Multimeter', 'Nut driver'],
    parts: ['Ignitor', 'Gas valve coil kit', 'Thermal fuse'],
    severity: 'high',
    proTips: ['Glow-then-no-flame is classic dual-coil failure on Whirlpool platforms.'],
  },
  {
    id: 'prop-fridge-warm',
    packId: 'property',
    category: 'appliances',
    title: 'Fridge warm, freezer still cold',
    aliases: ['defrost failure', 'evaporator iced', 'airflow damper'],
    symptoms: ['Fresh food 50°F+', 'Freezer OK or too cold', 'Frost on freezer back wall'],
    likelyCauses: ['Failed defrost (heater/timer/thermistor)', 'Blocked evaporator', 'Damper stuck closed'],
    steps: [
      'Check vents between freezer and fridge — feel for air.',
      'Pull freezer panel; if iced solid, force-defrost (unplug 24h or carefully melt) then test defrost heater.',
      'Replace failed defrost component; don’t just melt and leave.',
      'Verify condenser coils clean and condenser fan runs.',
    ],
    safety: ['Unplug before removing liners.', 'Avoid puncturing evaporator with sharp tools.'],
    tools: ['Multimeter', 'Nut driver', 'Hair dryer (careful)'],
    parts: ['Defrost heater', 'Defrost thermostat / bi-metal', 'Adaptive defrost board'],
    severity: 'high',
    proTips: ['Warm fridge + icy freezer = defrost until proven otherwise.'],
  },
  {
    id: 'prop-fridge-not-cold',
    packId: 'property',
    category: 'appliances',
    title: 'Fridge and freezer both warm',
    aliases: ['compressor not running', 'start relay', 'sealed system'],
    symptoms: ['Both compartments warm', 'Compressor silent or click-click'],
    likelyCauses: ['Start relay / overload', 'Failed compressor', 'Dirty condenser', 'Control board'],
    steps: [
      'Clean condenser coils and confirm condenser fan.',
      'Listen for compressor attempt — rapid click → start relay.',
      'Swap start relay/overload (cheap) before condemning compressor.',
      'If compressor runs but no cooling, sealed-system — escalate / replace unit per property policy.',
    ],
    safety: ['Capacitors can hold charge on inverter boards.'],
    tools: ['Coil brush', 'Multimeter'],
    parts: ['Start relay', 'Overload', 'Condenser fan motor'],
    severity: 'high',
    proTips: ['Photo model/serial before ordering — start relays are model-specific.'],
  },
  {
    id: 'prop-ice-maker-dead',
    packId: 'property',
    category: 'appliances',
    title: 'Ice maker not producing',
    aliases: ['no ice', 'fill tube frozen', 'water filter'],
    symptoms: ['Empty bin', 'Harvest arm stuck', 'Filter overdue'],
    likelyCauses: ['Frozen fill tube', 'Clogged filter', 'Failed water inlet valve', 'Ice maker module'],
    steps: [
      'Confirm freezer ≤ 5°F and ice maker switch/arm ON.',
      'Replace water filter if >6 months or low flow at dispenser.',
      'Thaw fill tube with warm air; check for recurring freeze (bad fill valve dribble).',
      'Listen for fill buzz during harvest — no buzz → inlet valve or harness.',
    ],
    safety: ['Shut water before valve swap.'],
    tools: ['Filter wrench', 'Multimeter'],
    parts: ['Water filter', 'Inlet valve', 'Ice maker assembly'],
    severity: 'low',
    proTips: ['Samsung / LG filter resets matter — scan for model-specific reset.'],
  },
  {
    id: 'prop-dishwasher-leak',
    packId: 'property',
    category: 'appliances',
    title: 'Dishwasher leaking under door',
    aliases: ['door leak', 'foam overflow', 'door gasket'],
    symptoms: ['Puddle at kickplate', 'Float switch trip', 'Suds'],
    likelyCauses: ['Wrong detergent / too much soap', 'Torn door gasket', 'Clogged air gap / high drain loop', 'Loose circulation hose'],
    steps: [
      'Run empty rinse — if suds, flush with rinse-aid vinegar cycle; educate resident.',
      'Inspect door gasket for tears and food debris.',
      'Confirm drain hose high loop / air gap clear.',
      'Pull unit and check sump hose clamps if leak is under tub.',
    ],
    safety: ['Kill power and water before pulling unit.'],
    tools: ['Towels', 'Nut driver', 'Pliers'],
    parts: ['Door gasket', 'Drain hose', 'Hose clamps'],
    severity: 'medium',
    proTips: ['Hand dish soap in a dishwasher = flood. Always ask what soap they used.'],
  },
  {
    id: 'prop-dishwasher-no-drain',
    packId: 'property',
    category: 'appliances',
    title: 'Dishwasher won’t drain',
    aliases: ['standing water dishwasher', 'drain pump hum'],
    symptoms: ['Water left after cycle', 'Dirty smell'],
    likelyCauses: ['Clogged filter / chopper', 'Blocked disposal knockout', 'Failed drain pump', 'Air gap clog'],
    steps: [
      'Clean tub filter and check chopper area under spray arm.',
      'If tied to disposal, confirm knockout plug removed and disposal clear.',
      'Clear air gap on sink deck.',
      'Listen for drain pump — replace if humming with no flow.',
    ],
    safety: ['Unplug or kill dishwasher breaker.'],
    tools: ['Screwdriver', 'Wet vac'],
    parts: ['Drain pump', 'Filter', 'Air gap'],
    severity: 'medium',
    proTips: ['New disposal install without knocking out the plug is a classic callback.'],
  },
  {
    id: 'prop-range-burner-dead',
    packId: 'property',
    category: 'appliances',
    title: 'Electric range surface element dead',
    aliases: ['burner out', 'infinite switch', 'surface element'],
    symptoms: ['One burner cold', 'Others work'],
    likelyCauses: ['Failed element', 'Bad infinite switch', 'Loose terminal block'],
    steps: [
      'Swap element with a working burner of same size if plug-in style.',
      'Inspect receptacle for burn marks.',
      'Test continuity of element; replace if open.',
      'If element good, replace infinite switch for that burner.',
    ],
    safety: ['Kill range breaker — 240V.'],
    tools: ['Multimeter', 'Nut driver'],
    parts: ['Surface element', 'Infinite switch', 'Block kit'],
    severity: 'medium',
    proTips: ['Scorched terminals mean replace block + element together.'],
  },
  {
    id: 'prop-oven-no-heat',
    packId: 'property',
    category: 'appliances',
    title: 'Oven won’t heat',
    aliases: ['bake element', 'ignitor oven', 'F2 error'],
    symptoms: ['Broil works bake doesn’t', 'No glow on gas ignitor'],
    likelyCauses: ['Open bake element', 'Weak gas ignitor', 'Temp sensor', 'Control'],
    steps: [
      'Electric: ohm bake element; inspect for blister/break.',
      'Gas: ignitor should glow bright and draw ~3+ amps — weak glow won’t open valve.',
      'Check oven sensor ~1080Ω at room temp (most brands).',
      'Replace failed part; verify door lock not stuck on self-clean models.',
    ],
    safety: ['240V / gas — shut appropriate energy source.'],
    tools: ['Multimeter', 'Clamp meter (gas ignitor)'],
    parts: ['Bake element', 'Oven ignitor', 'Temp sensor'],
    severity: 'medium',
    proTips: ['Glow-but-no-flame on gas ovens is almost always a weak ignitor.'],
  },
  {
    id: 'prop-microwave-dead',
    packId: 'property',
    category: 'appliances',
    title: 'Microwave dead / no heat',
    aliases: ['magnetron', 'door switch', 'fuse microwave'],
    symptoms: ['Blank display', 'Runs but no heat', 'Trips breaker'],
    likelyCauses: ['Door switch', 'Internal fuse', 'Magnetron / diode', 'Control'],
    steps: [
      'Confirm outlet and dedicated circuit.',
      'Interlock switches fail often — test before magnetron.',
      'No heat but runs: diode/magnetron — many properties replace unit vs repair.',
      'Tripping: inspect for shorted magnetron or wiring damage.',
    ],
    safety: ['HIGH VOLTAGE capacitor — only trained techs open HV section. Prefer unit swap if policy allows.'],
    tools: ['Multimeter'],
    parts: ['Door switch kit', 'Ceramic fuse', 'Unit replacement'],
    severity: 'high',
    proTips: ['Document: many PM contracts are replace-not-repair on microwaves.'],
  },
  {
    id: 'prop-disposal-hum',
    packId: 'property',
    category: 'appliances',
    title: 'Garbage disposal hums / jammed',
    aliases: ['disposal stuck', 'allen wrench disposal', 'reset button'],
    symptoms: ['Hum no grind', 'Tripped reset', 'Dead'],
    likelyCauses: ['Jam under flywheel', 'Overload trip', 'Failed motor'],
    steps: [
      'Kill switch / unplug. Never reach in with power available.',
      'Hex wrench in bottom center — rock both directions to free jam.',
      'Press red reset on bottom. Restore power and test with water running.',
      'If reset won’t hold or still hums free, replace disposal.',
    ],
    safety: ['Power off. No hands in chamber with power on.'],
    tools: ['1/4" hex key', 'Tongs for debris'],
    parts: ['Disposal unit', 'Dishwasher knockout plug check'],
    severity: 'medium',
    proTips: ['Carry the hex key — residents lose it every time.'],
  },
  {
    id: 'prop-wh-no-hot',
    packId: 'property',
    category: 'water-heaters',
    title: 'No hot water — tank electric',
    aliases: ['upper thermostat', 'element open', 'ECO trip'],
    symptoms: ['Cold only', 'Some hot then cold'],
    likelyCauses: ['Tripped ECO', 'Failed upper/lower element', 'Bad thermostat', 'Breaker'],
    steps: [
      'Verify 240V at heater disconnect / breaker.',
      'Reset ECO on upper thermostat (red button).',
      'Ohm both elements (~10–16Ω typical); replace open element + gasket.',
      'If upper element good but no power sequencing, replace thermostat pair.',
    ],
    safety: ['Kill breaker. Drain below element before removal.', 'Scald risk when restoring.'],
    tools: ['Multimeter', 'Element wrench', 'Hose'],
    parts: ['Heating element', 'Thermostat', 'Gasket'],
    severity: 'high',
    proTips: ['Partial hot usually = lower element; stone cold often = upper/ECO.'],
  },
  {
    id: 'prop-wh-pilot',
    packId: 'property',
    category: 'water-heaters',
    title: 'Gas water heater pilot won’t stay lit',
    aliases: ['thermocouple', 'thermopile', 'pilot outage'],
    symptoms: ['Pilot lights then dies', 'No pilot'],
    likelyCauses: ['Bad thermocouple', 'Draft / dirty pilot', 'Gas control valve', 'Thermopile (FVIR)'],
    steps: [
      'Follow lighting instructions on tank — hold pilot timed correctly.',
      'Clean pilot orifice; check for soot.',
      'Replace thermocouple / thermopile as applicable.',
      'If new sensor still drops out, gas valve may be failing.',
    ],
    safety: ['Ventilate. No smoking. If gas odor persists, shut supply.'],
    tools: ['Thermocouple wrench', 'Brush'],
    parts: ['Thermocouple', 'Thermopile', 'Gas control'],
    severity: 'high',
    proTips: ['FVIR tanks are picky about dust lids — reseat combustion door gaskets.'],
  },
  {
    id: 'prop-hvac-filter',
    packId: 'property',
    category: 'hvac-basics',
    title: 'Weak airflow / icing — dirty filter',
    aliases: ['dirty filter', 'frozen coil', 'low airflow'],
    symptoms: ['Rooms not cooling', 'Ice on lines', 'Filter dark'],
    likelyCauses: ['Clogged filter', 'Blocked return', 'Failing blower'],
    steps: [
      'Replace filter with correct size and MERV per property standard.',
      'If iced, shut cooling / set fan-only to thaw before restarting.',
      'Check return grille and supply registers open.',
      'If airflow still poor after new filter, escalate to HVAC tech (blower / duct).',
    ],
    safety: ['Don’t chip ice off coils.'],
    tools: ['Filter', 'Flashlight'],
    parts: ['Air filter'],
    severity: 'medium',
    proTips: ['Photo dirty filter for the work order — reduces arguments.'],
  },
  {
    id: 'prop-thermostat-blank',
    packId: 'property',
    category: 'hvac-basics',
    title: 'Thermostat blank / dead',
    aliases: ['no display thermostat', 'C wire', 'batteries'],
    symptoms: ['Blank screen', 'Wi-Fi thermo offline'],
    likelyCauses: ['Dead batteries', 'No common (C) wire power', 'Tripped furnace door switch', 'Transformer'],
    steps: [
      'Replace batteries if applicable.',
      'Check air handler / furnace power and door interlock.',
      'Measure 24VAC R to C at thermostat.',
      'If no 24V, check transformer and low-voltage fuse on board.',
    ],
    safety: ['Low voltage is safer but still isolate before board work.'],
    tools: ['Multimeter', 'Batteries'],
    parts: ['Thermostat', '24V transformer', '3A fuse'],
    severity: 'medium',
    proTips: ['Many “dead Wi-Fi thermos” are missing C-wire — not the thermostat.'],
  },
  {
    id: 'prop-toilet-running',
    packId: 'property',
    category: 'plumbing-basics',
    title: 'Toilet running / phantom flush',
    aliases: ['flapper', 'fill valve', 'ghost flush'],
    symptoms: ['Constant refill sound', 'Periodic phantom cycle'],
    likelyCauses: ['Bad flapper', 'Chain too tight', 'Fill valve overflow height', 'Flush valve seat'],
    steps: [
      'Drop dye tablet / food color in tank — if bowl colors without flush, flapper leak.',
      'Replace flapper; adjust chain slack.',
      'Set water level ½" below overflow tube.',
      'Replace fill valve if noisy or won’t shut off.',
    ],
    safety: ['Shut angle stop before valve swap.'],
    tools: ['Channel locks', 'Sponge'],
    parts: ['Flapper', 'Fill valve', 'Supply line'],
    severity: 'low',
    proTips: ['Carry universal flappers — highest PM win-rate part.'],
  },
  {
    id: 'prop-unit-gfci',
    packId: 'property',
    category: 'unit-turns',
    title: 'Kitchen / bath outlets dead — GFCI',
    aliases: ['GFCI trip', 'dead kitchen plugs'],
    symptoms: ['No power at counter', 'GFCI won’t reset'],
    likelyCauses: ['Tripped GFCI upstream', 'LINE/LOAD swap', 'Failed GFCI', 'Open neutral'],
    steps: [
      'Find and reset all GFCIs (kitchen, bath, garage, exterior).',
      'If won’t reset, open and verify LINE vs LOAD — swap is #1 callback.',
      'Replace failed GFCI; test with tester.',
      'Cross-check Electrical pack for panel issues if multiple rooms dark.',
    ],
    safety: ['Kill breaker before rewiring GFCI.'],
    tools: ['Outlet tester', 'Screwdriver'],
    parts: ['GFCI receptacle'],
    severity: 'medium',
    proTips: ['Property Maintenance + Electrical pack: always mention upstream GFCI locations.'],
  },
  {
    id: 'prop-smoke-chirp',
    packId: 'property',
    category: 'unit-turns',
    title: 'Smoke detector chirping',
    aliases: ['low battery smoke', 'end of life detector'],
    symptoms: ['Chirp every 30–60s', 'Won’t silence'],
    likelyCauses: ['Low battery', 'End-of-life (10yr)', 'Dust', 'Interconnect signal'],
    steps: [
      'Replace battery with correct type; vacuum vents.',
      'Check manufacture date — replace unit if ≥10 years.',
      'For hardwired interconnect, replace with matching interconnect type.',
      'Never leave a disabled detector.',
    ],
    safety: ['Ladder safety. Don’t leave resident without detection overnight.'],
    tools: ['Ladder', 'Battery', 'Screwdriver'],
    parts: ['9V / lithium battery', 'Smoke alarm'],
    severity: 'medium',
    proTips: ['Photo the date stamp for the work order.'],
  },
];
